### ISSUE TITLE
[Bug] Behaviour of GridModule

### ISSUE THREAD

**Issue by stevenpawley** [OSGeo/grass#1000]
**Describe the bug**
The grass.pygrass.modules.grid.grid.GridModule appears to exhibit some strange issues.

**To Reproduce**
This works (from the manual) using r.slope.aspect:

```
    import grass.script as gs
    from grass.pygrass.modules.grid.grid import GridModule
    from grass.pygrass.modules.shortcuts import general as gg

    gg.region(raster="elevation", flags="a")
    grd = GridModule(
        cmd='r.slope.aspect',
        width=500,
        height=500,
        overlap=2,
        processes=16,
        split=False,
        elevation='elevation',
        slope='slope',
        aspect='aspect',
        overwrite=True
    )
    grd.run()
```

But using r.neighbors throws an error:

```
    grd = GridModule(
        cmd='r.neighbors',
        width=500,
        height=500,
        overlap=2,
        processes=16,
        split=False,
        input='elevation',
        output='smoothed',
        size=11,
        method="average",
        overwrite=True
    )
    grd.run()
```

The error is:

```
    grd.run()
  File "/usr/local/grass79/etc/python/grass/pygrass/modules/
grid/grid.py", line 572, in run
    self.patch()
  File "/usr/local/grass79/etc/python/grass/pygrass/modules/
grid/grid.py", line 611, in patch
    rpatch_map(otm.value,
  File "/usr/local/grass79/etc/python/grass/pygrass/modules/
grid/patch.py", line 77, in rpatch_map
    rast = RasterRow(prefix + raster, mapset)
TypeError: can only concatenate str (not "list") to str
```

I think that the issue is related to r.neighbors being able to produce multiple outputs, which is causing the output parameter attribute to contain a list rather than a string.

**System description (please complete the following information):**

- MacOS 10.16.6 and Ubuntu 20.04
- GRASS GIS development version

**Comment by petrasovaa** [comment]
> I think that the issue is related to r.neighbors being able to produce multiple outputs, which is causing the output parameter attribute to contain a list rather than a string.

Yes, it's related to that. I was workarounding this issue using r.mfilter instead but it's more work.

**Comment by stevenpawley** [comment]
So, this isn't a bug per se - GridModule cannot handle multiple outputs. Perhaps just a note in the manual/docstring is required to make it clear that GridModule only works with modules that produce a single output. I'm happy to make a small PR, but I'll close this.

My hacky workaround for using r.neighbors in parallel is to modify the GridModule.module so that `outputs.output.multiple` is set to False.
