### ISSUE TITLE
How to improve r.water.outlet  and r.to.vect performance

### ISSUE THREAD

**Issue by chakravarthi-vl** [OSGeo/grass#1039]
Hi Team,

Currently, I am using r.water.outlet and r.to.vect in my project, both are taking 5 to 10 seconds, Is there any way can I reduce execution time?

**Comment by neteler** [comment]
To better judge this, please post the settings of your current region:

`g.region -p`

**Comment by chakravarthi-vl** [comment]
> To better judge this, please post the settings of your current region:
> 
> `g.region -p`

projection: 3 (Latitude-Longitude)
zone:       0
datum:      wgs84
ellipsoid:  wgs84
north:      16:06:50.361545N
south:      16:03:59.906423N
west:       79:40:51.417411E
east:       79:44:05.387188E
nsres:      0:00:00.017418
ewres:      0:00:00.017418
rows:       9786
cols:       11136
cells:      108976896

**Comment by neteler** [comment]
You are computing  ~109 million cells which is something. A lot will depend on the hardware you use (esp. which CPU, SDD drive or not, etc.). The desired resolution is indeed 0:00:00.017418 degree?

Some hints have been collected here: https://grasswiki.osgeo.org/wiki/Large_raster_data_processing

**Comment by neteler** [comment]
I suppose this has been clarified. Closing
