### ISSUE TITLE
[Bug] r.pack of VRT (r.buildvrt) only packs metadata and misses tiles 

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1073]
**Describe the bug**
Using `r.pack `of a VRT (created with `r.buildvrt`) rather of a regular map only packs the metadata and misses the related tiles.

**To Reproduce**

(modified from [manual](https://grass.osgeo.org/grass78/manuals/r.buildvrt.html#examples))

1. Generate VRT from a DEM in the North Carolina sample dataset

```
grass79 ~/grassdata/nc_spm_08_grass7/user1/
# set the region
g.region raster=elev_state_500m -p
# higher resolution
g.region res=250 -p
# resample the DEM to 50 meter
r.resamp.interp input=elev_state_500m output=elev_state_250m method=bilinear
# create tiles
r.tile input=elev_state_250m output=elev_state_250m_tile_ width=500 height=500 overlap=0
# dump list of tiles to a file
g.list type="raster pattern=elev_state_250m_tile_*" output=tilelist.csv
# build a vrt
r.buildvrt file=tilelist.csv output=elev_state_250m_vrt
# verify
r.univar elev_state_250m
r.univar elev_state_250m_vrt
```

2. Pack map

```
r.pack elev_state_250m_vrt
```

3. Cleanup original tiles and VRT, then unpack map

```
for i in $(cat tilelist.csv) ; do g.remove raster name=$i -f ; done
g.remove raster name=elev_state_250m_vrt -f

r.unpack elev_state_250m_vrt.pack
```

4. Run r.info on imported package

```
# metadata are ok
r.info elev_state_250m_vrt
# data are not
r.univar elev_state_250m_vrt
ERROR: Tile raster map <elev_state_250m_tile_-000-000@user1> not found
```

**Expected behavior**
In case of a VRT `r.pack` should pack the related raster tiles.

**Comment by neteler** [comment]
I took liberty to reopen this PR as I have found a related bug.
The updated `r.pack` crashes when one or several VRT tiles lack the color table (which is acceptable).

To reproduce:

- if needed, run again "Step 1" of above example
- delete the color table of one tile:

```
r.colors -r elev_state_250m_tile_-001-001
```

- be sure tthat all is fine, statistically

```
r.univar elev_state_250m_vrt
```

- pack and see error:

```
r.pack elev_state_250m_vrt
Packing <elev_state_250m_vrt@user1> to
</home/mneteler/software/grass_master/elev_state_250m_vrt.pack>...
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/r.pack", line 173, in <module>
    sys.exit(main())
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/r.pack", line 132, in main
    shutil.copytree(
  File "/usr/lib64/python3.8/shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mneteler/grassdata/nc_spm_08_grass7/user1/colr/elev_state_250m_tile_-001-001'
```

The `copytree` step doesn't allow for missing color tables yet.

**Comment by neteler** [comment]
I have also an issue with unpacking this "pack" file which is based in 3x3 tiles:
https://data.neteler.org/tmp/bonn_innenstadt_nDOM50.pack (100 MB, sorry, but cool open data from openNRW)

The content are normalized digital surface model tiles with names
- ndom50_32366_5621_1_nw_2019
- ndom50_32364_5621_1_nw_2019
- ...

I suspect that the regex doesn't match in
https://github.com/OSGeo/grass/blob/4957d896e9b62c487a4e76bd19843e6a12e5edde/scripts/r.unpack/r.unpack.py#L169

**Comment by tmszi** [comment]
Another bug:

1. `r.unpack -p input=/home/tomas/Downloads/bonn_innenstadt_nDOM50.pack `

**Error message:**

```
Traceback (most recent call last):
  File "/usr/lib64/grass79/scripts/r.unpack", line 232, in
<module>
    sys.exit(main())
  File "/usr/lib64/grass79/scripts/r.unpack", line 88, in
main
    f = tar.extractfile('{}/{}'.format(data_name, fname))
NameError: name 'data_name' is not defined
```

**Comment by tmszi** [comment]
> I have also an issue with unpacking this "pack" file which is based in 3x3 tiles:
> https://data.neteler.org/tmp/bonn_innenstadt_nDOM50.pack (100 MB, sorry, but cool open data from openNRW)
> 
> The content are normalized digital surface model tiles with names
> 
>     * ndom50_32366_5621_1_nw_2019
> 
>     * ndom50_32364_5621_1_nw_2019
> 
>     * ...
> 
> 
> I suspect that the regex doesn't match in
> 
> https://github.com/OSGeo/grass/blob/4957d896e9b62c487a4e76bd19843e6a12e5edde/scripts/r.unpack/r.unpack.py#L169

Yes, you are right. 

Currently logic, If input vrt file name is:

`dem_vrt`

and individual rasters of vrt
```
map-000-001
map-000-002
....
```
During unpacking individual rasters of vrt, get new name according vrt name (better visual orientation of which individual rasters belongs to the virtual raster).
```
dem_vrt
dem_vrt-000-001
dem_vrt-000-002
...
```

Maybe you could guide me on how to do it right if it possible?

**Comment by neteler** [comment]
I'd lean towards keeping the original names. In my case, I have ~ 35.000 DSM files with names standardized by the publishing authority (hence, to be kept). For my case cited above, I build a VRT out of a subset and assigned an output name meaningful to me.

Now I wanted to transfer the VRT (with convenient name) and the associated DSM files (following the official naming scheme) to another computer where I'd prefer to see the same naming.

**Comment by tmszi** [comment]
> I'd lean towards keeping the original names. In my case, I have ~ 35.000 DSM files with names standardized by the publishing authority (hence, to be kept). For my case cited above, I build a VRT out of a subset and assigned an output name meaningful to me.
> 
> Now I wanted to transfer the VRT (with convenient name) and the associated DSM files (following the official naming scheme) to another computer where I'd prefer to see the same naming.

Thanks for explanation, I fixed it in this [PR](https://github.com/OSGeo/grass/pull/1116).

**Comment by neteler** [comment]
Thanks for the updated version: now both use cases work for me (same name and different names in the VRT).
