### ISSUE TITLE
[segmentation fault] r.sim.sediment with dynamic allocation of walkers

### ISSUE THREAD

**Issue by PiotrKopysc** [OSGeo/grass#1091]
**Describe the bug**
r.sim.sediment module does not produce intended output. Terminal prints "segmentation fault" message.

**To Reproduce**
On North Carolina Data set
1) I have used  elev_lid792_1m, dx, dy, depth (from r.sim.water), as an input data detachment and transport capacity with critical shear stress were filled with a map of the error derived from r.sim.water since I was missing this data for North Carolina. Other input data such as manning's n stayed as default. The number of walkers was set to 10000. 
2) In GRASS UI it did not create all the output raster, and none were added to a layer manager. The simulation ended up very quickly (0 seconds). When I used the terminal and copy-paste the command for r.sim.sediment It printed the "segmentation fault" message. 
3) First two maps that were created were Transport Capacity and Transport Limited Erosion to Deposition, The one that was missing are Sediment Concentration, Sediment Flux, Erosion to Deposition, and Vector file of the walkers. 

Command: 
r.sim.sediment --overwrite elevation=elev_lid792_1m@PERMANENT water_depth=NC_Depth@PERMANENT dx=NC_Dx@PERMANENT dy=NC_Dy@PERMANENT detachment_coeff=NC_Error@PERMANENT transport_coeff=NC_Error@PERMANENT shear_stress=NC_Error@PERMANENT transport_capacity=NC_TransportCapacity tlimit_erosion_deposition=NC_TransportLimitedErotoDepo sediment_concentration=NC_SedimentConcentration sediment_flux=NC_SedimentFlux erosion_deposition=NC_ErosiontoDeposition logfile=NC_Sample walkers_output=NC_Walkers_Sediment nwalkers=10000 nproces=4

**Expected behavior**
Creation of entire output including rasters of sediment concentration, sediment flux, erosion to deposition, and vector file of the walkers. 

**Screenshots**
![NC_Dataset_Depth](https://user-images.githubusercontent.com/73067317/99305651-58604480-2854-11eb-96aa-efc082758200.png)
![NC_Dataset_Sediment1](https://user-images.githubusercontent.com/73067317/99305657-5a2a0800-2854-11eb-99ca-4e510e1d6e2f.png)
![NC_Dataset_Sediment2](https://user-images.githubusercontent.com/73067317/99305659-5ac29e80-2854-11eb-8426-c4b0537c9df2.png)
![NC_Dataset_Sediment3](https://user-images.githubusercontent.com/73067317/99305661-5ac29e80-2854-11eb-9d06-8563fe4bb376.png)
![NC_Dataset_Sediment4](https://user-images.githubusercontent.com/73067317/99305664-5b5b3500-2854-11eb-9341-2e559a80878a.png)

**System description (please complete the following information):**

- Operating System: Ubuntu 20.04
- GRASS GIS version: Master build compilation -with OpenMP (7.9-devel)

**Additional context**

**Comment by neteler** [comment]
Would you be willing to run the process in the debugger? That's not complicated [1], something like this (note the `r` to actually run it inside `gdb` which you may need to install first):

```
gdb r.sim.sediment
...
(gdb) r --overwrite elevation=elev_lid792_1m@PERMANENT water_depth=NC_Depth@PERMANENT dx=NC_Dx@PERMANENT dy=NC_Dy@PERMANENT detachment_coeff=NC_Error@PERMANENT transport_coeff=NC_Error@PERMANENT shear_stress=NC_Error@PERMANENT transport_capacity=NC_TransportCapacity tlimit_erosion_deposition=NC_TransportLimitedErotoDepo sediment_concentration=NC_SedimentConcentration sediment_flux=NC_SedimentFlux erosion_deposition=NC_ErosiontoDeposition logfile=NC_Sample walkers_output=NC_Walkers_Sediment nwalkers=10000 nproces=4

... crash ...
bt full
```

For better debugging, it is needed to compile GRASS GIS with CFLAG `-g`:

```
CFLAGS="-g" ./configure ...
make
...
```

but you could give it a try without first.

[1] https://grasswiki.osgeo.org/wiki/GRASS_Debugging#Using_GDB

**Comment by PiotrKopysc** [comment]
Dear Mr. Neteler,

Thank you for taking interest in this problem. Today I will try to run the
process in the debugger. However, the results should be available tomorrow.
It is much appreciated for giving me these instructions as well. With that,
I should be able to do this much quicker.
Thank you for your time and help.

Best Regards,
Piotr Kopyść

wt., 17 lis 2020 o 23:25 Markus Neteler <notifications@github.com>
napisał(a):

**Comment by petrasovaa** [comment]
> Dear Mr. Neteler, Thank you for taking interest in this problem. Today I will try to run the process in the debugger. However, the results should be available tomorrow. It is much appreciated for giving me these instructions as well. With that, I should be able to do this much quicker. Thank you for your time and help. Best Regards, Piotr Kopyść 

No need to do that, I already fixed the problem, see the linked PR, I will merge it soon.

**Comment by neteler** [comment]
The fix has also been backported, to be published in the upcoming GRASS GIS 7.8.5.

**Comment by PiotrKopysc** [comment]
Dear All,

I have recompiled Grass GIS from the current master build and tested the behavior of the r.sim.sediment. Now it works flawlessly, no segmentation fault error has been spotted, and all of the output (raster maps) have been produced in the map set. Thank you for all the help and support.

Best regards,
Piotr Kopyść

**Comment by wenzeslaus** [comment]
> ```
> gdb r.sim.sediment
> ...
> (gdb) r --overwrite elevation=elev_lid792_1m@PERMANENT ...
> 
> ... crash ...
> bt full
> ```

Not needed here anymore, but for the record, you can also use `gdb -ex run --args ...` (I added that to the the wiki):

```
gdb -ex run --args r.sim.sediment --overwrite elevation=elev_lid792_1m@PERMANENT ...
```
