### ISSUE TITLE
[Bug] GUI doesn't start when watchdog library is not installed

### ISSUE THREAD

**Issue by landam** [OSGeo/grass#1097]
**Describe the bug**

GUI doesn't start when `watchdog` library is not installed. This issue has been introduced by 32bb3de1aa6488dc56fe070977f0b08103f87e28

**To Reproduce**

1. Start GRASS in GUI mode / g.gui

```
Traceback (most recent call last):
  File "/opt/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/wxgui.py", line 104, in OnInit
    from lmgr.frame import GMFrame
  File "/opt/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/lmgr/frame.py", line 69, in <module>
    from datacatalog.catalog import DataCatalog
  File "/opt/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/datacatalog/catalog.py", line 22, in <module>
    from datacatalog.tree import DataCatalogTree
  File "/opt/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/datacatalog/tree.py", line 189, in <module>
    class MapWatch(PatternMatchingEventHandler):
NameError: name 'PatternMatchingEventHandler' is not defined
```

**Expected behavior**

Watchdog is not a core dependency, GUI should work when watchdog is not installed.

**System description:**

- Operating System: Linux
- GRASS GIS version master

**Comment by petrasovaa** [comment]
Since watchdog is not part of the standard Python installation, would it be worth it to add it as a dependency? Alternatively, maybe on Linux (where it would be most relevant for users and easiest to install) we could use the infobars to pop up a suggestion to install watchdog to automatically update. The infobar could be triggered when you reload manually using the toolbar button.

**Comment by ninsbl** [comment]
> would it be worth it to add it as a dependency

Sounds reasonable to me to add "watchddog" as an optional requirement as the gain in functionality sounds pretty useful.

BTW. is the optional packages list:
https://github.com/OSGeo/grass/blob/master/REQUIREMENTS.html
complete? I did not find OpenMP for example....

**Comment by mlennert** [comment]
It is only necessary for the GUI, or ? So it should only be a dependency for the GUI not for grass-core (to use Debian-speak).

So a pop up sounds better in my eyes, with a hint for packagers to make it a dependency of grass-gui or equivalent.

Am 19. November 2020 04:55:35 MEZ schrieb Anna Petrasova <notifications@github.com>:

**Comment by ninsbl** [comment]
In the requrements list, there are plenty of libs and modules that only benefit a specific component of GRASS (GUI, TGRASS, PyGRASS, ...) and each list element comes with an explanation what it is good for.

Do packagers use that requirements list or do they package based on experience? Just asking how to pass that information best.
