### ISSUE TITLE
[Bug] g.extension: update to also accept "main" branch in addition to "master" default branch

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1128]
**Describe the bug**
New GitHub (and other) repositories today use the name `main` instead of `master` for the default branch ([background](https://github.com/github/renaming)).

Yet `g.extension` needs to be updated accordingly to accept both, as it currently only searches for

```
https://github.com/SOME_ORG/MODULE/archive/master.zip
```

**Example**

```
# this fails, since the repo was generated today with `main` instead of `master`:
g.extension extension=t.sentinel url=https://github.com/mundialis/t.sentinel
Fetching <t.sentinel> from
<https://github.com/mundialis/t.sentinel/archive/master.zip> (be
patient)...
ERROR: Extension <t.sentinel> not found

# However:
wget https://github.com/mundialis/t.sentinel/archive/main.zip
...
2020-11-29 12:30:52 (1.02 MB/s) - ‘main.zip’ saved [18228]
 ```

**Proposed solution:**

If `master.zip` isn't found, try `main.zip`.

**Comment by ninsbl** [comment]
See also: #625 
@neteler are you currently working on this? If not, I may have a look at it...

**Comment by neteler** [comment]
No, I am not - please go ahead!

**Comment by ninsbl** [comment]
Could not backport 1ed8b2c unfortunately.
Please see also the related comment in #1130

**Comment by neteler** [comment]
Backport done.
