### ISSUE TITLE
[Bug] Narrow toolbar shows IDs instead of labels

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#1133]
**Describe the bug**
Making windows with a toolbar, such as Layer Manager or Map Display, narrow causes a small arrow to show on the right. Clicking it shows a menu with tools which had to be hidden to make the window smaller. These tools are now represented by text, not by image. All that is fine. However, this text is not a label, but something which looks like some internal ID. The issue is even bigger for translations.

**To Reproduce**

1. Go to Layer Manager (or Map Display or other windows with a toolbar).
2. Make it as narrow as possible (minimal horizontal size).
3. Click the triangle/arrow at the right side of the toolbar.
4. See the "IDs" in the menu.

**Expected behavior**

Some readable text describing the tool/action should appear.

Some programs have short text associated with toolbar buttons such as Save, Open, Zoom (usually these programs allow text to appear with or instead the toolbar icons). There are already tooltips for (hopefully) all items in the toolbar present in GRASS. These could be used too, although they seem little too long for a menu entry.

**Screenshot**

![Screenshot from 2020-12-03 21-57-30](https://user-images.githubusercontent.com/5449060/101116261-c033c080-35b2-11eb-9613-ddc0697edf0e.png)

**System description (please complete the following information):**

- Operating System: Linux (likely all/most OS)
- GRASS GIS 7.9 (likely all, not a new issue)
- Python: 3.8.5                                                                   
- wxPython: 4.0.7                                                                 

**Additional context**
Seems like API misunderstanding - user visible string is sourced from something which was not meant to be visible.

**Comment by wenzeslaus** [comment]
Added screenshot to clarify what the issue is.

**Comment by tmszi** [comment]
> ![Screenshot from 2020-12-03 21-57-30](https://user-images.githubusercontent.com/5449060/101116261-c033c080-35b2-11eb-9613-ddc0697edf0e.png)

The toolbar menu is missing icons, could it be a bug in the gtk+ theme?

**Comment by wenzeslaus** [comment]
> The toolbar menu is missing icons, could it be a bug in the gtk+ theme?

I don't have them in context menus either. Same for other programs. It is like this for some time in different Ubuntu versions. I actually though it is an intention: perhaps cleanness of the interface and/or using them only when it has some additional meaning (while is not the best example as it using its own library, Gimp shows some graphics such as image thumbnails in recent or check boxes, but nothing else).
