### ISSUE TITLE
[Feat] New startup/GUI - change location/mapset with right click 

### ISSUE THREAD

**Issue by CarlosGrohmann** [OSGeo/grass#1144]
Now with the new startup procedure, in which we don't need to selec the location/mapset anymore, I just found myself in the last mapset I used (ok), but this time I wanted to use another one, so I went to "change location/mapet" (also ok), but what if I could just go to the Data tab, right-click a raster/vector in another location and select "change to this location/mapste" (or something in those lines...)
I think this would be simple to implement and very handy.

**Comment by veroandreo** [comment]
That's already there, IIUC your request, only not in maps but it's a menu that appears when you right click over the mapset you want to switch to:

![Screenshot_2020-12-02_22-44-22](https://user-images.githubusercontent.com/20075188/100935305-36bbba00-34f0-11eb-9058-5d38178d14f9.png)

Cool, ah?!

**Comment by CarlosGrohmann** [comment]
Fantastic! You developers always one step ahead...
