### ISSUE TITLE
[Bug] GUI crashes silently when mouse pointer moves over Map Display

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass#1169]
**Describe the bug**
The GUI crashes completely without any error message in the terminal whenever I move the mouse pointer above the Map Display window.

**To Reproduce**

1. Launch GUI
2. Move mouse pointer so that it is positioned over the Map Display
3. GUI crashes

**Expected behavior**

No crash ;-)

**System description (please complete the following information):**

- Debian testing
- GRASS GIS version 7.8.4 - (Debian Package 7.8.4-3)

```
$ g.version -breg
version=7.8.4
date=2020
revision=exported
build_date=2020-12-02
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8

 ./configure  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr/lib --enable-largefile --enable-socket --enable-shared --with-blas --with-bzlib --with-cairo --with-cxx --with-freetype --with-freetype-includes=/usr/include/freetype2 --with-gdal --with-geos --with-lapack --with-motif --with-mysql '--with-mysql-includes=/usr/include/mariadb /usr/include/mariadb/mysql' --with-netcdf --with-nls --with-odbc --with-openmp --with-pdal --with-postgres --with-postgres-includes=/usr/include/postgresql --with-proj-share=/usr/share/proj --with-python --with-readline --with-sqlite --with-wxwidgets=/usr/bin/wx-config --with-x --with-zstd
libgis_revision=2020-12-02T12:12:52+00:00
libgis_date=2020-12-02T12:12:52+00:00
proj=7.2.0
gdal=3.1.4
geos=3.8.1
sqlite=3.33.0

$ python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.1rc1 (default, Nov 27 2020, 19:38:39) 
[GCC 10.2.0]
4.0.7 gtk3 (phoenix) wxWidgets 3.0.5
```

**Additional context**
I tried with an older compiled version of trunk and had the same crash. I'm currently recompiling current trunk to test.

Any hints on how to debug this would be welcome. g.gisenv set=DEBUG=3 does not provide any additional information.

**Comment by nilason** [comment]
Sound very similar to https://github.com/OSGeo/grass/issues/1123.

**Comment by mlennert** [comment]
> Sound very similar to #1123.

Yes, absolutely. Don't know how I missed that. Closing this one as duplicate.
