### ISSUE TITLE
[Feat] Make Display related toolbars part of Display tab

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#1189]
## Suggestion

Move the two toolbars which are related to Display (added map layers, and/or Map Display) from the Layer Manager window main tool bar to the Display tab (panel). This:

* makes it consistent with Data tab which has its own toolbar which operates on the things in the tab,
* makes the main toolbar smaller which possibly highlights its content,
* groups adding layers with the operations on the added layers together,
* avoids the new issue created by Data tab _re-using_ the "pencil" icon to allow editing of other mapsets (now user sees two of these icons above each other which is strange), and
* avoids the confusion when Data tab is active and a user clicks the _Show attribute..._ button which is associated with selected layer in Displays, not selected vector map in Data tab.

However, unfortunately this makes the main toolbar longer by little less than one tool bar button width (exact measure depends on the system). This can be mitigated by merging Tools Toolbar and Misc Toolbar which may save few pixels and it might be a good idea to do that anyway.

## Details

The toolbar names are Data Toolbar and Vector Toolbar and they should be included in that order.

### Display tab active

The two toolbars are part of the Display tab/panel. Created by just moving the toolbars around (the small toolbar with help and settings is missing in the picture).

![Screenshot from 2020-12-18 22-20-36](https://user-images.githubusercontent.com/5449060/102679685-7b498580-417f-11eb-8f9f-8c6146b768a3.png)

### Data tab active

The toolbars are not visible because they not part of the main toolbar. Created by removing the toolbars from the window.

![Screenshot from 2020-12-18 22-22-55](https://user-images.githubusercontent.com/5449060/102679704-a207bc00-417f-11eb-9123-c5a2e0f0a52f.png)

**Comment by Ashutoshmitra** [comment]
I want to work on this issue.
