### ISSUE TITLE
[Feat] g.gui.tplot: add trend line option (linear regression)

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1197]
**Is your feature request related to a problem? Please describe.**

When plotting time series with [g.gui.tplot](https://grass.osgeo.org/grass79/manuals/g.gui.tplot.html) it would be nice to be able to optionally show a trend line (linear regression).

I found that _scikit-learn_ offers that (but would be a new dependency):
- https://scikit-learn.org/stable/auto_examples/linear_model/plot_ols.html
and probably _numpy_ (already there):
- https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html

**Describe the solution you'd like**
A button in `g.gui.tplot` adding a linear regression line to the plot, ideally with mean squared error etc.

**Describe alternatives you've considered**
So far I use the CSV export and plot in LibreOffice but...

**Comment by tmszi** [comment]
Markus something like that?

![wxgui_tplot_show_linear_regression_line](https://user-images.githubusercontent.com/50632337/102784404-a230d300-439c-11eb-8880-648d3a17b37e.png)

**Comment by neteler** [comment]
Cool @tmszi ! Yes, like that. If possible, could also the equation be printed?

**Comment by tmszi** [comment]
> could also the equation be printed

Equation with calculated intercept and slope variable (add to legend printed to stdout)?
Y = a + b * X (a is intercept, b is slope)
e.g.
Y = -161.4131 + 0.0002 * X
r² = 0.0018

**Comment by neteler** [comment]
It looks great to me.

**Comment by tmszi** [comment]
Could @neteler test this [PR](https://github.com/OSGeo/grass/pull/1207), please? I tested it with raster temporal dataset only (I don't have some vector sample data), and compared result calculated with R, and it works as expected.
