### ISSUE TITLE
r.out.gdal hangs when run from GUI [Bug] 

### ISSUE THREAD

**Issue by h-inge** [OSGeo/grass#1211]
When calling iteratively (both within and outside of a loop) r.out.gdal in a small python routine (grass.script, pygrass) an exception is raised and the running hangs. The stop button doesn't work and no further command an be run from the GUI after the exception raising. Tested it on 2 machines (MacOS and Linux). Here's the error message printed on the GUI:

> r.out.gdal complete. File </Volumes/Maxtor/GISDBASE_histogram_analysis/clipped_maps_sectors/sentinel/20190223/rhow_20190223_B01_southern_wetlands_sector.tif> created. Checking GDAL data type and nodata value... Exception in thread Thread-1 : Traceback (most recent call last): File "/Applications/GRASS-7.8.app/Contents/Resources/lib/p ython3.8/threading.py", line 932, in _bootstrap_inner
> 
> self.run() File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w xpython/core/gconsole.py", line 162, in run
> 
> self.resultQ.put((requestId, self.requestCmd.run())) File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w xpython/core/gcmd.py", line 603, in run
> 
> self._redirect_stream() File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w xpython/core/gcmd.py", line 632, in _redirect_stream
> 
> self.stderr.write(line) File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w xpython/core/gconsole.py", line 299, in write
> 
> value = int(line.rsplit(':', 1)[1].strip()) IndexError : list index out of range
> 

The issue does not occur if the script is run from shell instead of GUI.

**To Reproduce**

1. Prepare a mapset with some (e.g. 5) sentinel scenes
2. Create 4 smaller raster maps per scene by clipping the tiles 
3. Write a small routine that calls r.out.gdal several consecutive times (like this: drive.google.com/file/d/1dMzmeP8fBuGPxyh3JBTw3PAopDwsaY5F/…)
4. Run the script from the GUI
5. See error

**System description:**

- Operating System: MacOS Big Sur 11.0.1  and  Linux Manjaro
- GRASS GIS version: 7.8.4

- details about further software components:
    - GUI details: version=7.8.4
date=2020
revision=exported
build_date=2020-10-06
build_platform=x86_64-apple-darwin19.6.0
build_off_t_size=8
libgis_revision=2020-10-06T19:20:03+00:00
libgis_date=2020-10-06T19:20:03+00:00
proj=6.3.1
gdal=3.0.4
geos=3.8.1
sqlite=3.33.0
    - python details: 3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ]
4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5

**Comment by h-inge** [comment]
The issue is very similar to: https://github.com/OSGeo/grass/issues/866

**Comment by tmszi** [comment]
Today I encountered a similar error, but when bulk importing raster data (wxGUI Import raster data dialog).

Problem is with parsing the percent value:

Percent value is in the newline (in some cases) e.g.

```
...
GRASS_INFO_PERCENT: 87
GRASS_INFO_PERCENT: 
90
```

Correct:

```
GRASS_INFO_PERCENT: 90
```

**Comment by neteler** [comment]
Silly question: what would be the solution? Standardize the `G_percent()` usage or is there a way to better parse the various percent values?

**Comment by tmszi** [comment]
> Silly question: what would be the solution? Standardize the `G_percent()` usage or is there a way to better parse the various percent values?

In the case of import, this error occurs if the checkbox Add imported layers into layer tree is checked. My opinion is that two threads writes at once to the output of the Layer Manager Console and then it happens that the percent line is wrapped in irregular parts.

Something like that:
```
GRASS_INFO_PERCENT: 
93
```
or 
```
G
RASS_INFO_PERCENT: 93
```
....

I think the writing and parsing percentages are fine (e.g. try import some raster maps, data source: https://opendata.dwd.de/climate_environment/CDC/grids_germany/annual/air_temperature_mean/, without checked Add imported layers into layer tree checkbox).

**Comment by tmszi** [comment]
For testing purpose (import raster data via wxGUI import dialog):

1. Try download raster data from https://opendata.dwd.de/climate_environment/CDC/grids_germany/annual/air_temperature_mean/
2. Python script for download  raster data (save as /tmp/download_raster_data.py)
```
#!/usr/bin/env python

import gzip
import os
import re
import sys
import shutil
from urllib.request import urlopen, urlretrieve

if len(sys.argv) < 2:
    print('Set script data path arg e.g. /tmp/data')
    sys.exit(1)

DATA_DIR = sys.argv[1]
if not os.path.exists(DATA_DIR):
    print("Path doesn't exists <{}>".format(DATA_DIR))
    sys.exit(1)
if not os.access(DATA_DIR, os.W_OK):
    print("Check directory <{}> write permission".format(DATA_DIR))
    sys.exit(1)

URL = 'https://opendata.dwd.de/climate_environment/CDC/grids_germany/annual/air_temperature_mean/'
BASE_URL = "https://opendata.dwd.de/climate_environment/CDC/grids_germany/annual/air_temperature_mean/{file_name}"


def main():
    r = urlopen(URL)
    result = r.read().decode('utf-8')
    for l in result.split('\r\n'):
        name = re.search(r'<a href="(.*.)">', l)
        if name and '.gz' in name.group(1):
            urlretrieve(
                url=BASE_URL.format(file_name=name.group(1)),
                filename="{}".format(os.path.join(DATA_DIR, name.group(1))),
            )
            with gzip.open("{}".format(os.path.join(DATA_DIR, name.group(1))), 'rb') as f_in:
                with open("{}".format(os.path.join(DATA_DIR, name.group(1).replace('.gz', ''))), 'wb') as f_out:
                    shutil.copyfileobj(f_in, f_out)

if __name__ == '__main__':
    main()

```
3. Make dir `mkdir /tmp/data`
4. Launch script: `python /tmp/download_raster_data.py /tmp/data`
5. Create new LOCATION (EPSG 31467, Datum 1 used in whole Potsdam region)
6. Try import raster data, bulk import (Arc/Info ASCII Grid) and check Add imported layers into layer tree checkbox

Could @neteler test [PR](https://github.com/OSGeo/grass/pull/1228) if it possible, please?

**Comment by neteler** [comment]
I have tested #1228 successfully.
