### ISSUE TITLE
GRASS 7.8.5 x64 for windows does not start with error message about missing DLL

### ISSUE THREAD

**Issue by newcomb-d** [OSGeo/grass#1218]
**Describe the bug**
GRASS GUI does not start upon installation of GRASS 7.8.5-1 64 bit on Windows

**To Reproduce**
1) Install GRASS
2) Click on GRASS 78 option in Start menu

**Expected behavior**

Standard GRASS startup screen
**Screenshots**
What I get is a text window with the following text:
Starting GRASS GIS...
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\gis_set.py", line 43, in <module>
    from core.gcmd import GMessage, GError, DecodeString, RunCommand
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\core\gcmd.py", line 43, in <module>
    from win32file import ReadFile, WriteFile
ImportError: DLL load failed: The specified module could not be found.
ERROR: Error in GUI startup. See messages above (if any) and if necessary, please report this error to the GRASS developers.
On systems with package manager, make sure you have the right GUI package, probably named grass-gui, installed.
To run GRASS GIS in text mode use the --text flag.
Use '--help' for further options
     grass78 --help
See also: https://grass.osgeo.org/grass78/manuals/helptext.html
Exiting...
Press any key to continue . . .

Upon key press, Text window closes and GRASS does not start.

**System description (please complete the following information):**

- Operating System: Windows 10 
- GRASS GIS version 7.8.5 -1 

**Additional context**

**Comment by hellik** [comment]
quick check with OSGeo4W-winGRASS 7.8.5 -1; GUI starts normally. 

so it seems it's an standalone winGRASS issue.

related to python's win32file ; see https://trac.osgeo.org/osgeo4w/ticket/37#comment:9 

are another python in %PATH% or %PYTHONPATH% ?

**Comment by hellik** [comment]
something similar in http://osgeo-org.1560.x6.nabble.com/wingrass-6-4-installation-problem-td4052462.html

**Comment by newcomb-d** [comment]
I reloaded 7.8.4 and it runs without a problem.  Is there a difference in the python settings in Standalone between 7.8.4 and 7.8.5?

**Comment by hellik** [comment]
@landam any inside about difference in the python settings in Standalone between 7.8.4 and 7.8.5?

**Comment by hellik** [comment]
installed standalone here, issue confirmed. @landam repackaging needed?

**Comment by hellik** [comment]
> 
> 
> I reloaded 7.8.4 and it runs without a problem. Is there a difference in the python settings in Standalone between 7.8.4 and 7.8.5?

any chance to use OSGeo4W-winGRASS 7.8.5 in the meantime?

**Comment by hellik** [comment]
compared standalone and OSGeo4W python, no difference in first quick check

**Comment by tmszi** [comment]
I confirm this bug (standalone installer).

**Comment by landam** [comment]
> @landam any inside about difference in the python settings in Standalone between 7.8.4 and 7.8.5?

there is no change to my knowledge

**Comment by landam** [comment]
> installed standalone here, issue confirmed. @landam repackaging needed?

@hellik I will trigger repackaging. But I am not sure if it helps.

**Comment by hellik** [comment]
> 
> 
> I confirm this bug (standalone installer, version 7.9). This seems to be a problem with the pywin32 module version in combination with the specific python version ([issue](https://github.com/mhammond/pywin32/issues/1431#issuecomment-662974531)).
> 
> Quick fix:
> 
>     1. Download [pywin32 whl file](https://download.lfd.uci.edu/pythonlibs/z4tqcw5k/pywin32-300-cp37-cp37m-win_amd64.whl)
> 
>     2. Launch cmd with Admin rights
> 
>     3. Change directory `C:\Users\IEUser>cd "C:\Program Files\GRASS GIS 7.8\Python37"`
> 
>     4. Install new pywin32 module version
>        `C:\Program Files\GRASS GIS 7.8\Python37>python.exe Scripts\pip3.7.exe install C:\Users\IEUser\Desktop\pywin32-300-cp37-cp37m-win_amd64.whl`
>        Change path of pywin32 whl file `C:\Users\IEUser\Desktop\pywin32-300-cp37-cp37m-win_amd64.whl` to the path where you download this whl file
> 
>     5. Check that the installation was successful
> 
> 
> ```
> C:\Program Files\GRASS GIS 7.8\Python37>python.exe Scripts\pip3.7.exe freeze list
> 
> pywin32==300
> ```
> 
>     1. Try launching a GRASS GIS GUI `g.gui`

as pywin32 should be the same in OSGeo4W and standalone winGRASS, not sure why it works then in OSGeo4W.

**Comment by hellik** [comment]
> C:\Program Files\GRASS GIS 7.8\Python37>python.exe Scripts\pip3.7.exe freeze list
> 
> pywin32==300
> ```

in winGRASS, it's: **python3-pywin32-224-2.tar.bz2**, see http://download.osgeo.org/osgeo4w/x86_64/release/python3/python3-pywin32/

**Comment by tmszi** [comment]
With WinGRASS-7.8.5-1-Setup-x86_64.exe, WinGRASS-7.9.dev-6-Setup-x86_64.exe it works fine.

**Comment by petrasovaa** [comment]
> With WinGRASS-7.8.5-1-Setup-x86_64.exe, WinGRASS-7.9.dev-6-Setup-x86_64.exe it works fine.

Just tested 7.8.5. and it still doesn't work.

**Comment by tmszi** [comment]
> > With WinGRASS-7.8.5-1-Setup-x86_64.exe, WinGRASS-7.9.dev-6-Setup-x86_64.exe it works fine.
> 
> Just tested 7.8.5. and it still doesn't work.

Interesting, on the day I sent a message here (downloaded version 7.8.5-1 and 7.9.dev-6) it worked for me.

**Comment by hellik** [comment]
> 
> 
> > > With WinGRASS-7.8.5-1-Setup-x86_64.exe, WinGRASS-7.9.dev-6-Setup-x86_64.exe it works fine.
> > 
> > 
> > Just tested 7.8.5. and it still doesn't work.
> 
> Interesting, on the day I sent a message here (downloaded version 7.8.5-1 and 7.9.dev-6) it worked for me.

do you activate _installing MS runtimes_ during standalone installation?

**Comment by tmszi** [comment]
> > > > With WinGRASS-7.8.5-1-Setup-x86_64.exe, WinGRASS-7.9.dev-6-Setup-x86_64.exe it works fine.
> > > 
> > > 
> > > Just tested 7.8.5. and it still doesn't work.
> > 
> > 
> > Interesting, on the day I sent a message here (downloaded version 7.8.5-1 and 7.9.dev-6) it worked for me.
> 
> do you activate _installing MS runtimes_ during standalone installation?

Yes I did.

**Comment by hellik** [comment]
> > do you activate _installing MS runtimes_ during standalone installation?
> 
> Yes I did.

I tried here with and without MS runtimes installing, no difference

**Comment by tmszi** [comment]
> > > do you activate _installing MS runtimes_ during standalone installation?
> > 
> > 
> > Yes I did.
> 
> I tried here with and without MS runtimes installing, no difference

I uninstalled version 7.8.5 completely and install it again. 

Screenshot:

![win_grass](https://user-images.githubusercontent.com/50632337/104234121-38fc2700-5453-11eb-9576-56b2df89cd03.jpeg)

**Comment by hellik** [comment]
> > I tried here with and without MS runtimes installing, no difference
> 
> I uninstalled version 7.8.5 completely and install it again.
> 
> Screenshot:
> 
> ![win_grass](https://user-images.githubusercontent.com/50632337/104234121-38fc2700-5453-11eb-9576-56b2df89cd03.jpeg)

tested here now on 2 different win 10 boxes, standalone still not starting. 

some kind of mysterious that it works on some/your win 10 box. additionally I've tested the standalone release candidate, it worked back then.

@landam should we update python's win32 in OSGeo4W?

**Comment by hellik** [comment]
> 
> some kind of mysterious that it works on some/your win 10 box. additionally I've tested the standalone release candidate, it worked back then.

winGRASS 7.8.5 and winGRASS7.9dev are working in the OSGeo4W environment which is the base environment for standalone.

**Comment by tmszi** [comment]
> tested here now on 2 different win 10 boxes, standalone still not starting.
> 
> some kind of mysterious that it works on some/your win 10 box. additionally I've tested the standalone release candidate, it worked back then.

Only one thing that I done on my win 10 box was an installation pywin32 version 300 from (whl binary version installer). Pywin32 has [pywin32_postinstall.py ](https://github.com/mhammond/pywin32/blob/master/pywin32_postinstall.py) which according script doc (Copies PyWinTypesxx.dll and PythonCOMxx.dll into the system directory,  and creates a pth file. If you installed pywin32 via a .exe installer, this should be run automatically after installation, but if it fails you can run it again. If you installed pywin32 via PIP, you almost certainly need to run this to setup the environment correctly.)

Maybe that is the difference between OSGeo4W (where the pywin32 pywin32_postinstall.py script  is called) and Standalone version (where the pywin32 pywin32_postinstall.py script isn't called automatically).

**Comment by hellik** [comment]
> Only one thing that I done on my win 10 box was an installation pywin32 version 300 from (whl binary version installer). Pywin32 has [pywin32_postinstall.py ](https://github.com/mhammond/pywin32/blob/master/pywin32_postinstall.py) which according script doc (Copies PyWinTypesxx.dll and PythonCOMxx.dll into the system directory, and creates a pth file.

copying anything into the system directory in ms windows isn't a good idea. OSGeo4W winGRASS is working here; searching for something like PyWinTypesxx.dll and PythonCOMxx.dll in the system path, nothing found.

In OSGeo4W, pythoncom37.dll and pywintypes37.dll are living in C:\OSGeo4W64\apps\Python37.

pywin32.pth is living in C:\OSGeo4W64\apps\Python37\lib\site-packages

the content of pywin32.pth:

```
# .pth file for the PyWin32 extensions
win32
win32\lib
Pythonwin
# Entries needed for a "portable" installations, where the post_install script
# isn't run, which would normally copy the pywin32 core DLL files to either
# the top of the python directory.
# We just stick the source of these DLLs directly on the PATH.
import os;os.environ["PATH"]+=(';'+os.path.join(sitedir,"pywin32_system32"))
```

check needed where these file are in the standalone installation path.

**Comment by hellik** [comment]
```
C:\Program Files\GRASS GIS 7.8\Python37>dir /b
DLLs
Lib
LICENSE.txt
python.exe
python3.dll
python37.dll
pythoncom37.dll
pythonw.exe
pywintypes37.dll
Scripts
```

vs.

```
C:\OSGeo4W64\apps\Python37>dir /b
DLLs
etc
include
lib
libs
LICENSE.txt
python.exe
python3.dll
python37.dll
pythoncom37.dll
pythonw.exe
pywintypes37.dll
qt.conf
Scripts
share
sip
tcl
Tools
```

pythoncom37.dll and pywintypes37.dll are there in standalone as well as in OSGeo4W, though in standalone are few subfolders.


```
C:\Program Files\GRASS GIS 7.8\Python37\Lib\site-packages>ls | grep pywin
pywin32-224.dist-info
pywin32.pth
pywin32.version.txt
```

```
C:\OSGeo4W64\apps\Python37\lib\site-packages>ls | grep pywin
pywin32-224.dist-info
pywin32.pth
pywin32.version.txt
```
pywin32.pth is there in standalone as well as in OSGeo4W

**Comment by hellik** [comment]
>Copies PyWinTypesxx.dll and PythonCOMxx.dll into the system directory

ok, found it; adding python folder **%GISBASE%\Python37** to **%PATH%** in C:\Program Files\GRASS GIS 7.8\etc\env.bat 

```
set PATH=%GISBASE%\extrabin;%GISBASE%\bin;%GISBASE%\Python37;%PATH%
```
 GUI starts then.

@landam: any idea what was changed that **%GISBASE%\Python37**  has to be in %PATH% now?

repackaging with an updated env.bat ? I guess no new release should be needed for this issue, right?

**Comment by hellik** [comment]
![grafik](https://user-images.githubusercontent.com/12000843/105411217-673bec80-5c33-11eb-8085-fd4443a4896f.png)

**Comment by cmbarton** [comment]
Great news. Can you let me know when the new package is ready? Thanks.

**Comment by hellik** [comment]
**C:\OSGeo4W64\bin\py3_env.bat** checked:

```
SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python37
SET PYTHONPATH=%PYTHONHOME%;%PYTHONHOME%\Scripts
PATH %PYTHONPATH%;%PATH%
```

it seems that %PYTHONHOME% respectively %PYTHONPATH% is added to %PATH%. that's why OSGeo4W winGRASS seems to work.

**Comment by landam** [comment]
@hellik Is there any reason why aa6dc77 hasn't been applied in master? 

I will repackage winGRASS standalone today.

**Comment by hellik** [comment]
>Is there any reason why aa6dc77 hasn't been applied in master?

Yes, simply found no time yet to do so. Please apply it to master too!

Thanks for repackaging!

**Comment by hellik** [comment]
fix now also applied to master by  56b21d1

**Comment by chljl** [comment]
Tried to download winGRASS 7.8.5.2 from https://grass.osgeo.org/download/windows/ but still got 7.8.5.1. Please update the link.

**Comment by hellik** [comment]
see [#249](https://github.com/OSGeo/grass-website/pull/249), updating link is on the way

**Comment by neteler** [comment]
> Tried to download winGRASS 7.8.5.2 from https://grass.osgeo.org/download/windows/ but still got 7.8.5.1. Please update the link.

Now the updated link is on the server, thanks for your patience.

**Comment by hellik** [comment]
announcement to the community, see https://lists.osgeo.org/pipermail/grass-user/2021-January/082155.html
