### ISSUE TITLE
[Bug] g.gui.mapswipe flickers when dragging slider

### ISSUE THREAD

**Issue by mankoff** [OSGeo/grass#1236]
version=7.8.4
date=2020
revision=exported
build_date=2020-12-19
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2020-12-19T12:38:20+00:00
libgis_date=2020-12-19T12:38:20+00:00
proj=7.2.0
gdal=3.2.0
geos=3.9.0
sqlite=3.31.1

**Comment by tmszi** [comment]
Interestingly, when you use the slider circle button, the flickering doesn't occur.

**Comment by veroandreo** [comment]
Just tested and it happens in 7.8.5 and 7.9, as well

**Comment by ninsbl** [comment]
Still relevant in 8.4/8.5?

**Comment by tmszi** [comment]
> Still relevant in 8.4/8.5?

Yes it is.
