### ISSUE TITLE
[Bug] addons directory unavailable for GRASS 7.8.5 on Windows

### ISSUE THREAD

**Issue by obrl-soil** [OSGeo/grass#1238]
**Describe the bug**
g.extension on Windows is hardcoded to download extensions from a URL generated [here](https://github.com/OSGeo/grass/blob/3eb01a6be27d0f4ed62e8b760ec95612f4994618/scripts/g.extension/g.extension.py#L1214). The folder referenced in that URL has yet to be created on the server. As a result, all attempts to install extensions on windows fail.

There is a folder called 'latest' on the server; its unclear to me whether 7.8.5 should be installing from there, or if that folder is reserved for the development version of the software.

**To Reproduce**

1. Install OSGeo4W64 on a windows machine
2. run g.extension and attempt to install anything.

**Expected behavior**
Extensions should install. Do they need to be recompiled for 7.8.5 and placed in a new folder? If this is already in someone's job queue, no worries.

**System description (please complete the following information):**

- Operating System: Windows 10
- GRASS GIS version 7.8.5

**Additional context**
Its unclear why users can't specify a destination URL in Windows, or install from a local ZIP. This seems like a parameter that should also be editable in Settings > Preferences, or in the g.extensions GUI.

**Comment by tmszi** [comment]
I confirm this bug.

e.g. `g.extension g.proj.identify` 

try install addon from the URL which doesn't exists on the server:

https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.5/g.proj.identify.zip

correct URL on the server is:

https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/g.proj.identify.zip

**Comment by agiudiceandrea** [comment]
@tmszi this seems now fixed.

**Comment by obrl-soil** [comment]
It certainly is. Thanks, whoever!

**Comment by neteler** [comment]
> @tmszi this seems fixed now.

Yes, @landam fixed the winGRASS server.
