### ISSUE TITLE
grass-7.8.5 fails to build using python2

### ISSUE THREAD

**Issue by dmacks** [OSGeo/grass#1241]
**Describe the bug**
The conversion to python3 created mistakes in the python2 fallback code.

**To Reproduce**

1. Patch all #! lines that call python3 to instead call python2.7
2. Install all dependencies via fink
3. Use fink's build recipe (CompileScript from https://github.com/fink/fink-distributions/blob/master/10.9-libcxx/stable/main/finkinfo/sci/grass72.info

**Expected behavior**
Build succeeds.

**Screenshots**
```
Traceback (most recent call last):
  File "./ctypesgen.py", line 162, in <module>
    descriptions = ctypesgencore.parser.parse(options.headers, options)
  File "/sw/build.build/grass78-x11-7.8.5-1/grass-7.8.5/lib/python/ctypes/ctypesgencore/parser/__init__.py", line 21, in parse
    parser = DataCollectingParser(headers, options)
  File "/sw/build.build/grass78-x11-7.8.5-1/grass-7.8.5/lib/python/ctypes/ctypesgencore/parser/datacollectingparser.py", line 31, in __init__
    ctypesparser.CtypesParser.__init__(self, options)
  File "/sw/build.build/grass78-x11-7.8.5-1/grass-7.8.5/lib/python/ctypes/ctypesgencore/parser/ctypesparser.py", line 63, in __init__
    super(CtypesParser, self).__init__(options)
  File "/sw/build.build/grass78-x11-7.8.5-1/grass-7.8.5/lib/python/ctypes/ctypesgencore/parser/cparser.py", line 90, in __init__
    self.preprocessor_parser = preprocessor.PreprocessorParser(options, self)
  File "/sw/build.build/grass78-x11-7.8.5-1/grass-7.8.5/lib/python/ctypes/ctypesgencore/parser/preprocessor.py", line 141, in __init__
    module=pplexer)
  File "/sw/build.build/grass78-x11-7.8.5-1/grass-7.8.5/lib/python/ctypes/ctypesgencore/parser/lex.py", line 738, in lex
    f.sort(key=lambda x, y: cmp(get_func_code(x[1]).co_firstlineno,
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**System description (please complete the following information):**
- OS X 10.13, python2.7
- GRASS 7.8.5

**Additional context**
The problem is due to 7e1945f230e57b32adda5f23f070f0c2e1525a00 in lex.py around line 730 (and again a few lines later):
```
-        f.sort(lambda x, y: cmp(get_func_code(x[1]).co_firstlineno, get_func_code(y[1]).co_firstlineno))
+        if os.sys.version_info.major >= 3:
+            f.sort(key=lambda x: get_func_code(x[1]).co_firstlineno)
+        else:
+            f.sort(key=lambda x, y: cmp(get_func_code(x[1]).co_firstlineno,
+                                        get_func_code(y[1]).co_firstlineno))
```
The python2 fallback still includes the python3-specific syntax for f.sort(), using "key=" instead of a simple function as the pre-existing code had.

**Comment by nilason** [comment]
The shebangs (#! lines) calls python3 for a reason. If I'm not mistaken, support for Python 2 was dropped with GRASS GIS 7.8.
That fink recipe seem to be quite dated. If you are just aiming to get a GRASS 7.8.5 working, using [grass-conda](https://github.com/nilason/grass-conda) may be a solution for you, but in case you want to update the recipe you may find hints there for the configurations needed, alternatively take a look at [MacPorts](https://github.com/macports/macports-ports/blob/master/gis/grass7) configurations.

**Comment by dmacks** [comment]
I'm aiming to update fink's to 78 and into the python3 world:) But along the way, I found this bug. Obviously sane and consistent if grass (upstream people) hardcodes python3 and wants to only *support* python3, but if the code is retaining fallback for python2, at least it should not have really trivial python2 syntax errors in that code. Alternative is to simply delete the python2 fallback outright rather than pretend that it's even an end-user-hackable option. This is one of only two python3isms I've found.

**Comment by nilason** [comment]
I'm not sure what you mean with "python2 fallback".

**Comment by dmacks** [comment]
The codeblock in lex.py is "if (pythonversion>=3) **this** else **that**". I'm focusing on the "**that**", which is the block that happens when the python version is not >=3 (i.e., when running python2 not python3). This construct seems clearly intended to retain python2 support.

**Comment by nilason** [comment]
I suppose that is a remnant of transitional code, but I wouldn't swear on it.

By the way, great initiative updating for fink. I have no experience with fink, but I'm happy to assist in any way I can.

**Comment by wenzeslaus** [comment]
It seems to me that fully supporting Python 2.7 and >=3.4 was not possible in practice, but the Python 2.7 was left there because too much would be risked in 7.8 branch by removing it (and too much work with little gain too) and the transition needed to be done quickly. I'm closing this adding wontfix label. Please open a new ticket or PR if Python 2.7 is what you need to restart the discussion.
