### ISSUE TITLE
[Bug] SQL Builder needs to generate == instead of =

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1260]
**Describe the bug**
The SQL Builder is a very nice addition to more easily generate WHERE statements for vector queries. However, the "=" button only generates single equal signs "=" and SQL needs double equal signs to represent equivalence "==". This is a minor change but can cause confusion and frustration in using a very nice interface too. 

**System description (please complete the following information):**

- Operating System: all systems
- GRASS GIS version 7.8.5 and above (for 7.8.6 milestone)

**Comment by mlennert** [comment]
SQL does not use == AFAIK.

**Comment by marisn** [comment]
SQL uses singe `=` for equivalence comparison. Search for `<equals operator>` in SQL standard: http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

**Comment by nilason** [comment]
With SQLite ["equals can be either = or =="](https://sqlite.org/lang_expr.html#operators), but that is rather an exception to standard sql.

**Comment by cmbarton** [comment]
Yes. My mistake. Vector display selection used to require == but no longer does. Much better for all.
