### ISSUE TITLE
[Bug] wxGUI bug, Linux Mint 20.1

### ISSUE THREAD

**Issue by Guyver2095** [OSGeo/grass#1262]
Dear Grass developers:
Recently I upgraded my Linux mint, and after install grass, I have a surprise. It can't render complete maps in 2 or 3d view.
What I can do to solve this problem?
![image](https://user-images.githubusercontent.com/32247028/105131631-f66bc780-5aae-11eb-87db-d60d5740d072.png)

Thanks in advance for all your help.

**Comment by kuszinger** [comment]
Same effect sometimes in remote X2Go session with LXDE or (don't hurt me too much) WSL-Ubuntu and native Win XSRV....
In both cases it seems like yours.
It could be related somehow to the actual Window Manager and wxWidgets framework, window resize events or so...

Map area remains always the same as it was opened....

I'm also curious about the answer.

COULD YOU PLEASE post the output of:

`inxi -xx -S -G`

**Comment by Guyver2095** [comment]
Dear OSGEO 7 Grass friends:
Some of my INXI info is here. System:    Host: loki-H8SGL Kernel: 5.4.0-66-generic x86_64 bits: 64 compiler: gcc
           v: 9.3.0 Desktop: Cinnamon 4.8.6 wm: muffin dm: LightDM
           Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal

The solution of the aforementioned problem wasn't hardware related, and I  found it  here.
https://github.com/OSGeo/grass/issues/612

I want to mention that the Grass Gis and Qgis Connection to grass is broken in the current version of Gis software, included in Linux mint ulyssa. Maybe we can tell Linux Mint admin, that they have this problems and update to a newer version. Also Grass has another problems related to WMS parsing (Even with xml2 installed) and incompatibilities related to python versions.

Thanks for all your kind attentions.

Javier García Prieto.
________________________________

**Comment by neteler** [comment]
Please add details about the software components
- run `g.version -rge` in a GRASS GIS terminal session or check in the GUI menu "Help > About"
- run `python3 -c "import sys, wx; print(sys.version); print(wx.version())"` to print the Python and wxPython version numbers

**Comment by ldesousa** [comment]
I had this issue on Ubuntu 20.04 with 7.8.2 (and I believe also with 7.8.0). I now updated to 7.8.5 and it got fixed. For future reference I leave below the software details.

```
> g.version -rge
version=7.8.2
date=2019
revision=exported
build_date=2020-03-24
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=00000
libgis_date="?"
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1
```
```
> python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
4.0.7 gtk3 (phoenix) wxWidgets 3.0.4
```
```
$ inxi -xx -S -G
System:
  Host: luis-notebook Kernel: 5.4.0-67-generic x86_64 bits: 64 compiler: gcc 
  v: 9.3.0 Desktop: i3 4.17.1 dm: GDM3 Distro: Ubuntu 20.04.2 LTS (Focal Fossa) 
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] 
  vendor: Hewlett-Packard EliteBook 840 G3 driver: i915 v: kernel 
  bus ID: 00:02.0 chip ID: 8086:1916 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.2.6 
  direct render: Yes 
```

**Comment by neteler** [comment]
Seems all (possible) done here, closing. Please reopen if it still doesn't work with the latest GRASS GIS version.
