### ISSUE TITLE
[Bug] Cmd-C on Mac closes interactive color table modules

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1281]
**Describe the bug**
Pressing Cmd-C, which is "copy" on the Mac (=Ctrl-C on Windows and Linux) closes the window of the interactive color managers for raster and vector. 

**Expected behavior**
Pressing Cmd-C should copy whatever is selected, not close a window. 

**System description (please complete the following information):**

- Operating System: Mac OS
- GRASS GIS version 7.8.6 dev

**Comment by nilason** [comment]
@cmbarton Please test #1293, it should work on 7.8 release branch (7.8.6dev, but not 7.8.5) too.

**Comment by cmbarton** [comment]
Thanks Nicklas. I will test this soon.

**Comment by cmbarton** [comment]
I just tested this on 7.8.6RB compiled a few minutes ago and Ctrl-C still closes the window. 

Here is the build info:

version=7.8.6dev
date=2021
revision=5ebba2a8d
build_date=2021-02-03
build_platform=x86_64-apple-darwin20.2.0
build_off_t_size=8

I opened the 'manage color rules interactively' GUI module, selected a map in the map pull down list, highlighted the map and pressed Ctrl-C to copy it. The color rules window closes. It is the same for both raster and vector color modules.

**Comment by cmbarton** [comment]
Looks like it hasn't been merged and I need to test the pull request

**Comment by nilason** [comment]
No big changes, maybe you can manually insert the modified code to an existing 7.8.6dev of 7.9.dev build.

**Comment by nilason** [comment]
See https://github.com/OSGeo/grass/pull/1293/files

**Comment by cmbarton** [comment]
I just compiled and tested this pull request and Ctrl-C still closes the windows. I will manually apply the change and see if it works.

**Comment by cmbarton** [comment]
When I test this manually, it works. Thanks

**Comment by nilason** [comment]
Good, I will merge the PR then. Thanks for testing!
