### ISSUE TITLE
[Bug] v.colors cannot properly copy color table

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1297]
**Describe the bug**
The 'raster=' argument does not seem to work correctly. It colors the vector map but not at all like the raster map from which it is copied. Thereafter, the color cannot be set in d.vect unless the color table is removed using v.colors. 

**To Reproduce**
Using the NC dataset, make a raster map from TOTAL_POP from the SW Wake census map, and give it a nice histogram stretched blue color ramp (It does not matter what colors are used, the results are similarly random)
```
v.to.rast input=censusblk_swwake@PERMANENT output=censusblk_swwake_vect@spatialtech2021 use=attr attribute_column=TOTAL_POP --o
r.colors -e map=censusblk_swwake_vect@spatialtech2021 color=blues
```

Try to copy this raster color table to the original vector map 
```
v.colors map=censusblk_swwake@PERMANENT use=attr column=TOTAL_POP raster=censusblk_swwake_vect@spatialtech2021
```

**Expected behavior**
The color table in the vector map should be the same as in the raster map but it is not

The incorrect colors are also written to a selected RGB column if the rgb_column= argument is used

**Screenshots**
Raster version of census blocks
![census_raster](https://user-images.githubusercontent.com/8967599/106678479-15229180-6578-11eb-800c-093ceb8616cb.png)

Vector of census blocks after running v.color to copy the raster color table
![census_vector](https://user-images.githubusercontent.com/8967599/106678486-1a7fdc00-6578-11eb-8ecb-729aa16125f6.png)

**System description (please complete the following information):**

- Operating System: Mac OS 11
- GRASS GIS version 7.8.6 dev

**Additional context**
Possibly the problem is that a raster color table has colors assigned to raster values (TOTAL_POP here). But a vector color table has colors assigned to the CAT value, not the attribute value that it is supposed to match. I think that in this case, v.colors is assigning raster colors to whatever vector objects have CAT values that match raster values (TOTAL_POP here) instead of objects that have matching attribute values, even though the v.color arguments use=attr column=TOTAL_POP  are specified. 

Also note that v.colors is lacking histogram equalization.

**Comment by cmbarton** [comment]
Unlike importing a raster color table, if you export a raster color table to a **rules** file (r.colors.out) and import the rules file into v.colors, this does create a good color table that matches the raster.

**Comment by cmbarton** [comment]
Further color weirdness. If rgb_column= is used, v.colors will not create a color table. Now I see that it is sort of implied in the docs for rgb_column= , but not stated. Seems like writing a color table should at least be a user option, regardless of whether the info is written to a column or not. 

When a selection criteria is used in in d.vect (where=), area boundaries become invisible because they take on the color of the fill. Selecting transparent for the boundary color does make them transparent.

**Comment by wenzeslaus** [comment]
> ...area boundaries become invisible because they take on the color of the fill...

I have a similar issue. See discussion in #1146.

**Comment by HuidaeCho** [comment]
@cmbarton `column=` is only used when either `color=` or `rules=` is specified. It's not meant to be used with `raster=`, so your last command is the same as
```bash
v.colors map=censusblk_swwake@PERMANENT raster=censusblk_swwake_vect
```
and, yes, you're right. You're doing TOTAL_POP to cat color transfer.

When you use `r.colors.out`, `rules=`, and `column=TOTAL_POP`, you do TOTAL_POP to TOTAL_POP.

It would be great if we could do
```bash
r.colors.out censusblk_swwake_vect rules=- | v.colors map=censusblk_swwake@PERMANENT use=attr column=TOTAL_POP rules=-
```
but reading rules from stdin is not implemented yet.

**Comment by HuidaeCho** [comment]
Check  #1389.

```bash
v.to.rast input=censusblk_swwake use=attr attribute_column=TOTAL_POP output=censusblk_swwake_total_pop
r.colors -e map=censusblk_swwake_total_pop color=blues
r.colors.out map=censusblk_swwake_total_pop rules=- | v.colors map=censusblk_swwake use=attr column=TOTAL_POP rules=-
```

**Comment by HuidaeCho** [comment]
@cmbarton Please check #1392.

**Comment by HuidaeCho** [comment]
The original command (`raster=` with `use=attr` and `column=`) implemented in #1393.

**Comment by cmbarton** [comment]
I will do so. Thanks much.

**Comment by cmbarton** [comment]
I approved the PR and it works great. Can this be backported to 7.8? Then we can close this issue. Histogram is still open.

**Comment by HuidaeCho** [comment]
> 
> 
> I approved the PR and it works great. Can this be backported to 7.8? Then we can close this issue. Histogram is still open.

Are you talking about both #1393 and #1389, or just #1393?

**Comment by cmbarton** [comment]
#1393

Sorry if there was confusion. That was the main issue reported here.

**Comment by HuidaeCho** [comment]
@cmbarton Please test #1429 for 7.8. It should work, but just in case.

**Comment by cmbarton** [comment]
I'll test. Thanks.

**Comment by HuidaeCho** [comment]
Related issue #1432
