### ISSUE TITLE
[Bug] r.sun sunset/sunrise in layer's metadata incorrect in parallelized version

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#1298]
**Describe the bug**
The metadata of resulting rasters from r.sun are incorrect, specifically sunset and sunrise and others, see below. This happens when r.sun is compiled with OpenMP. I believe only the final metadata is the problem not the actual computation.

**To Reproduce**
```
g.region raster=elev_lid792_1m@PERMANENT
r.slope.aspect elevation=elev_lid792_1m@PERMANENT slope=slope aspect=aspect
r.sun elevation=elev_lid792_1m@PERMANENT aspect=aspect slope=slope incidout=incidence day=100 time=12
```
r.info result with OpenMP:
```
 |     ----------------------------------------------------------------       |
 |     Day [1-365]:                              100                          |
 |     Local (solar) time (decimal hr.):         12.0000                      |
 |     Solar constant (W/m^2):                   1367.000000                  |
 |     Extraterrestrial irradiance (W/m^2):      1362.410121                  |
 |     Declination (rad):                        0.138928                     |
 |     Latitude min-max(deg):                    35.7328 - 35.7395            |
 |     Sunrise time (hr.):                       -0.00                        |
 |     Sunset time (hr.):                        0.00                         |
 |     Daylight time (hr.):                      0.00                         |
 |     Solar altitude (deg):                     0.0000                       |
 |     Solar azimuth (deg):                      0.0000                       |
 |     Linke turbidity factor:                   3.0                          |
 |     Ground albedo:                            0.200                        |
 |     -----------------------------------------------------------------  
```
**Expected behavior**

r.info result without OpenMP:

```
 |     ----------------------------------------------------------------       |
 |     Day [1-365]:                              100                          |
 |     Local (solar) time (decimal hr.):         12.0000                      |
 |     Solar constant (W/m^2):                   1367.000000                  |
 |     Extraterrestrial irradiance (W/m^2):      1362.410121                  |
 |     Declination (rad):                        0.138928                     |
 |     Latitude min-max(deg):                    35.7328 - 35.7395            |
 |     Sunrise time (hr.):                       5.61                         |
 |     Sunset time (hr.):                        18.39                        |
 |     Daylight time (hr.):                      12.77                        |
 |     Solar altitude (deg):                     62.2205                      |
 |     Solar azimuth (deg):                      180.0000                     |
 |     Linke turbidity factor:                   3.0                          |
 |     Ground albedo:                            0.200                        |
 |     ----------------------------------------------------------------- 
```

**Screenshots**

**System description (please complete the following information):**

- Operating System: Ubuntu
- GRASS GIS version: 7.9

**Comment by AniketDGiri** [comment]
Hi Anna,
I am Aniket Giri from India. Currently, I am pursuing Masters in Geoinformatics from CSRE, Indian Institute of Technology Bombay (IITB). I have my bachelor's in Computer Science. I have had exposure to GIS, spatial databases in the last semester. I have also won the hacktoberfest contest. I have also implemented the image processing algorithms using Jupyter notebook in python. I have also implemented the shape-based image retrieval system using parallel processing.
I also have built a web-based application for Augmented Reality based GIS applications using AR.js.
Below is the link to my GitHub repo for the above project:
https://github.com/AniketDGiri/GIS_Version_1

I am fond of the open-source community as it provides me an opportunity to keep my skills updated, build connections, and improve my communications skills. Thus, I would love to contribute to Google Summer of Code 2021. I would be very grateful to get any directions to pursue and participate in Google Summer of Code 2021 with your organization.


I would like to work on this bug.

**Comment by AniketDGiri** [comment]
Hi Anna,
I am new to Grass Gis.
Can you please help me with how to reproduce the above results?

**Comment by ninsbl** [comment]
@AniketDGiri : Thanks for your interest. Please download the sample dataset used in the testing framework:
https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.zip
and run the commands Anna pasted above:
```
g.region raster=elev_lid792_1m@PERMANENT
r.slope.aspect elevation=elev_lid792_1m@PERMANENT slope=slope aspect=aspect
r.sun elevation=elev_lid792_1m@PERMANENT aspect=aspect slope=slope incidout=incidence day=100 time=12
```
 in a GRASS Session the North Carolina location...

If needed, you can find introduction material to GRASS GIS here:
https://grass.osgeo.org/learn/newcomers/

Finally, here is information on how to contribute:
https://github.com/OSGeo/grass/blob/master/CONTRIBUTING.md

**Comment by AniketDGiri** [comment]
@ninsbl,
Thank you so much for the information.
I will download the above dataset and run the commands given above.
I will let you know in case of any concerns.

**Comment by petrasovaa** [comment]
Hi @AniketDGiri, I would suggest to compile GRASS on ubuntu with (and without) OpenMP to reproduce the differences. Are you specifically looking at applying for the [topic](https://trac.osgeo.org/grass/wiki/GSoC/2021#Parallelizationofexistingmodules) I assume?

**Comment by AniketDGiri** [comment]
Hi @petrasovaa,
Yes, am looking at applying for the above topic.

**Comment by AniketDGiri** [comment]
Hi @ninsbl, @petrasovaa,

While reproducing the above error without openMP, I was unable to get the required r.info shown above.

I have done the following steps:
![used permanent as mapset](https://user-images.githubusercontent.com/50539447/108079342-b9d2c200-7094-11eb-80fa-abfbacce3961.PNG)

**Comment by AniketDGiri** [comment]
Hi @ninsbl, @petrasovaa,

While reproducing the above error without openMP, I was unable to get the required r.info shown above.

I have done the following steps:

1. I have used the above sample dataset and used grass mapset as permanent.

![image](https://user-images.githubusercontent.com/50539447/108079523-ebe42400-7094-11eb-9c9b-60822a9fc78e.png)

2. I have run the above commands in the console as shown below:

![image](https://user-images.githubusercontent.com/50539447/108079730-2483fd80-7095-11eb-9109-bedb4577b599.png)

3. After running r.info in the console, it was asking me for the raster map. I have taken the raster map as: 

![image](https://user-images.githubusercontent.com/50539447/108079900-54330580-7095-11eb-9ada-57611682c022.png)

4. After running below is the output I got:

![image](https://user-images.githubusercontent.com/50539447/108079998-6ca32000-7095-11eb-881c-0c9e28365698.png)



Could you please help me?

**Comment by nilason** [comment]
Try `r.info` on `r.sun` output file, in your case `incidence`.

**Comment by AniketDGiri** [comment]
Hi @nilason,
Thank you for your response. I am able to get the result shown above for (without)OpenMP.

But I am unable to get the desired results for (with)OpenMP.
1. I have compiled GRASS first without OpenMP and then with OpenMP.
2. but when I am running the above commands shown, I am getting the same result as (without) OpenMP.

Can you please help me?

**Comment by nilason** [comment]
I'm not sure I understand you correctly.

1. The desired output should be the same for both with and without OpenMP.
2. If your two results deviate, the result without OpenMP is more likely to be correct.
3. If your result without OpenMP is not identical with the one @petrasovaa presented above, are the differences small enough to be explained by compiler floating point deviations?

**Comment by AniketDGiri** [comment]
I am able to reproduce the result for (without) OpenMP, same as shown by @petrasovaa, But I am unable to reproduce the result for (With) OpenMP.

**Comment by nilason** [comment]
Right. Now **that** is the task at hand...
To fix the with-OpenMP-result to be (in practice) equal to the without-OpenMP-result.

**Comment by petrasovaa** [comment]
So you are saying you get the same result with and without OpenMP, right? Just to be clear, the resulting raster is the same, what this bug is about is the metadata information of the resulting layer are different (for me). If you get the same metadata, that's weird, because I don't, however there may be some undefined behavior and could perhaps depend on compiler etc. If you dive deeper in the code and have some OpenMP experience maybe you can spot the problem, for example check `sunrise_min` variable in main.c.

**Comment by AniketDGiri** [comment]
yes, I am getting the same metadata information for both cases. 

I will check, the main.c file.

**Comment by aaronsms** [comment]
Hi everyone, I have drafted a PR relating to this issue #1514. I would appreciate some review, and this is my first time contributing to this project, so I'm still getting familiarized with the contributing guidelines. Thanks!
