### ISSUE TITLE
[Bug] GUI: Move or copy location/mapset isn't allowed

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#1299]
**Describe the bug**
Whenever I click a location or mapset (even currently selected or the current) from the Data catalog, I'm getting a warning: "Move or copy location isn't allowed" or "Move or copy mapset isn't allowed".

**To Reproduce**

1. Go to 'Data'
2. Click on any location or mapset
3. See error

**Expected behavior**
No warnings or errors when simply clicking a location or mapset. I'm not trying to "move or copy" anything.

**Screenshots**

![image](https://user-images.githubusercontent.com/7456117/106762120-86f3ed00-6603-11eb-9680-379a17b13849.png)

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version: trunk

**Additional context**
Add any other context about the problem here. N/A

**Comment by petrasovaa** [comment]
Aren't you dragging the item? But yes I agree it shouldn't probably give you such error message anyway.

**Comment by nilason** [comment]
I can confirm this on Mac. Never got to report it, because it is little difficult to describe. No dragging involved for me.

**Comment by nilason** [comment]
In general working better when the window is in focus already.

**Comment by HuidaeCho** [comment]
> Aren't you dragging the item? But yes I agree it shouldn't probably give you such error message anyway.

No dragging. Just tested it again.
1. Click: no popup.. all good
2. Start moving the cursor (with no button pushed, so no dragging): got this popup.

I guess, this popup is only hooked with a mouse move event, not push-hold-move (dragging)?

**Comment by nilason** [comment]
For me this happens only with single left button click. Either on a list item, below the list (within the list frame) or the arrow. But it seems so random, only every now and then.

**Comment by petrasovaa** [comment]
I get this only when I actually drag the item and the dialog is initiated with wx.EVT_TREE_BEGIN_DRAG

**Comment by nilason** [comment]
> I get this only when I actually drag the item. The dialog is initiated with wx.EVT_TREE_BEGIN_DRAG so wx are detecting dragging.

After an attempt to drag, it is difficult to get rid of the warning dialog, no matter what...
It is probably related to this event somehow.

**Comment by HuidaeCho** [comment]
Please check https://github.com/OSGeo/grass/pull/1303#issuecomment-773699069. It doesn't seem to be a GRASS issue.
