### ISSUE TITLE
[Feat] Switch to separate addons subdirectories for GRASS GIS 7.8 and 7.9

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1308]
**Is your feature request related to a problem? Please describe.**

Since compiled C addons are not binary compatible between GRASS GIS 7.8 and 7.9 it would be natural to separate them, version-wise.

In the terminal, when starting the GUI from command line (`g.gui`) I see respective error messages and of course the C based addons fail to work in a non-compliant GRASS GIS version.

**Describe the solution you'd like**

Store the addons in separate addons subdirectories for GRASS GIS 7.8 and 7.9.:

```
$HOME/.grass7/addons    # -- keep as is for <= G78
$HOME/.grass7/addons79  # -- new for G79
$HOME/.grass7/addons80  # -- new for G80 (future)
...
```

**Describe alternatives you've considered**

None known.

**Comment by nilason** [comment]
For those of us who doesn't peek in `$HOME/.grass7` too often, it may after awhile be full of version dependent subdirectories. Maybe something in the line of:

```
$HOME/.grass7/addons      # -- (latest) stable
$HOME/.grass7/addons-dev  # -- for development
```

could be an alternative?

**Comment by nilason** [comment]
Come to think of it `$HOME/.grass7`: shouldn't it be `$HOME/.grass8`?

**Comment by wenzeslaus** [comment]
Solved with `.grass8` for 8.0.0.
