### ISSUE TITLE
[Bug] GUI crash on version 7.9  Linux Mint

### ISSUE THREAD

**Issue by ericrpatton** [OSGeo/grass#1315]
**Describe the bug**
Launching any location causes the gui to crash with the following error:

Traceback (most recent call last):
  File "/usr/local/grass79/gui/wxpython/wxgui.py", line 109, in OnInit
    mainframe = GMFrame(parent=None, id=wx.ID_ANY,
  File "/usr/local/grass79/gui/wxpython/lmgr/frame.py", line 237, in __init__
    self.NewDisplay(show=False)
  File "/usr/local/grass79/gui/wxpython/lmgr/frame.py", line 2088, in NewDisplay
    self.currentPage.maptree = LayerTree(
  File "/usr/local/grass79/gui/wxpython/lmgr/layertree.py", line 181, in __init__
    self.mapdisplay = MapFrame(self, giface=self._gifaceForDisplay,
  File "/usr/local/grass79/gui/wxpython/mapdisp/frame.py", line 149, in __init__
    self.MapWindow2D.InitZoomHistory()
  File "/usr/local/grass79/gui/wxpython/mapwin/buffered.py", line 1940, in InitZoomHistory
    self.zoomhistory.append((self.Map.region['n'],
KeyError: 'n'
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(477) in ~wxWindowBase(): any pushed event handlers must have been removed

**To Reproduce**
Launch a location from the command line: (Either a fully-qualified database/location/mapset or not, it doesn't seem to matter which):

grass79 /home/epatton/Projects/Scotian_Shelf_Bioregion/PERMANENT

Then see error above. Additionally, a dialog box pops up that
says "Enable to get the geographic extent. Force quitting wxGUI. Please run
g.region manually to fix the problem."

Runing g.region -p prints the following:

g.region -p
projection: 99 (unnamed)
zone:       0
datum:      wgs84
ellipsoid:  wgs84
north:      -383300
south:      -918400
west:       -951200
east:       764600
nsres:      100
ewres:      100
rows:       5351
cols:       17158
cells:      91812458
free(): invalid pointer
Aborted (core dumped)

**Expected behavior**
The gui launches normally with no errors pritned to the terminal.

**Screenshots**
![grass_gui_error](https://user-images.githubusercontent.com/19192513/107251577-df175e80-6a0a-11eb-824c-a46184e708cc.png)

**System description (please complete the following information):**

uname -a
Linux L-102377 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

g.version -gre
version=7.9.dev
date=2021
revision=exported
build_date=2021-02-08
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2021-02-08T04:01:23+00:00
libgis_date=2021-02-07T12:00:00-04:00
proj=7.0.1
gdal=3.2.1
geos=3.9.0
sqlite=3.31.1

python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
4.0.7 gtk3 (phoenix) wxWidgets 3.0.4

wx-config --version
3.0.4

**Additional context**

**Comment by ericrpatton** [comment]
It turns out I had a tangled python installation, although I don't know how, as I never (knowingly) mess with those libraries. I revisited the install instruction for Linux Mint at https://grasswiki.osgeo.org/wiki/Compile_and_Install and re-installed all the requirements again, and I must have picked up something I was missing. Grass 7.8.5 builds and runs fine now. Although, grass79 does not, I still get the same errors.

**Comment by wenzeslaus** [comment]
You need to have some confusion in libraries, possibly system ones judging by the `free(): invalid pointer` at the end. You need to re-compile with everything fresh.

You are of course welcome to submit a PR for Linux Mint build to have this checked permanently in CI (it is mostly Bash scripting although inside GitHub Actions workflow), however, I don't think this is specific issue to Mint and we do have a Ubuntu test already which should cover Mint sufficiently well.

**Comment by ninsbl** [comment]
Is this still an issue with 8.0 or 8.1?

**Comment by ericrpatton** [comment]
No, it doesn't Appear to be anymore. I’m not sure what exactly fixed it, but all is good now.

~ Eric.

**Comment by ninsbl** [comment]
Thanks for the feedback! Closing the ticket accordingly....
