### ISSUE TITLE
[Bug] GRASS 7.9 no longer launches in Mac OS

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1318]
**Describe the bug**
Sometime between 11 January and 3 February, GRASS 7.9 broke for the Mac. I just compiled it again and still won't launch, even though it compiles without error. Could this be linked to trying to have GRASS run with a terminal??

**To Reproduce**
Launch GRASS from the desktop by clicking the launch icon. It tries to launch and fails, with the following error in the terminal. 

/usr/bin/env -i HOME=/Users/cmbarton LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 BASH_SILENCE_DEPRECATION_WARNING=1 SHELL=/bin/bash PATH=/usr/bin:/bin:/usr/sbin:/etc:/usr/lib /Applications/GRASS-7.9.app/Contents/MacOS/Grass.sh
cmbarton@TCLASHE-C02V435YJ1GQ ~ % /usr/bin/env -i HOME=/Users/cmbarton LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 BASH_SILENCE_DEPRECATION_WARNING=1 SHELL=/bin/bash PATH=/usr/bin:/bin:/usr/sbin:/etc:/usr/lib /Applications/GRASS-7.9.app/Contents/MacOS/Grass.sh
Rebuilding Addon HTML manual pages index...
Rebuilding Addon menu...
usage: grass79 [-h] [-v] [--text] [--gtext] [--gui] [-c [CRS]] [-e]
               [--config [CONFIG [CONFIG ...]]] [--tmp-mapset]
               [--tmp-location CRS] [-f] [--exec ...]
               [PATH]
grass79: error: unrecognized arguments: -gui

**System description (please complete the following information):**

- Operating System: Mac OS 11.2 (also failed with 11.1)
- GRASS GIS version 7.9 dev (compiled 9 February 2021)

**Additional context**

**Comment by cmbarton** [comment]
@nilason I found out the problem. Sometime after 11 Jan, the -gui argument was deprecated. This means that the final launch command for the grass.sh script in your grass conda build must be slightly different for GRASS 7.9 after the deprecation date than before it. 

11 January and before 
"$GRASS_PYTHON" "$GISBASE/bin/grass79" "-gui" "$@"

After the change in late January
"$GRASS_PYTHON" "$GISBASE/bin/grass79" "$@"

To all, it would be nice if grass79 simply ignored -gui rather than failing with an error.

**Comment by neteler** [comment]
> @nilason I found out the problem. Sometime after 11 Jan, the -gui argument was deprecated. 

@cmbarton it is actually `--gui`, not `-gui`.

See
https://github.com/OSGeo/grass/blob/1384f522622519e00300269a065cf5837858afda/lib/init/grass.py#L330

**Comment by nilason** [comment]
Before changes of late, evidently `-gui` worked too. I just updated the [conda build script](https://github.com/nilason/grass-conda) to use `--gui`.

**Comment by cmbarton** [comment]
Thanks. I'll update and rebuild.

**Comment by cmbarton** [comment]
Also, it does seem like --gui is unnecessary at least in 7.9. GRASS launches fine without it. Is --gui the default?

**Comment by nilason** [comment]
> Also, it does seem like --gui is unnecessary at least in 7.9. GRASS launches fine without it. Is --gui the default?

It is still needed, but last used preference is set in `~/.grass7/rc`. Starting without argument will launch that.

**Comment by cmbarton** [comment]
Works fine with the new update. Thanks.
