### ISSUE TITLE
[Feat] Realistic power line render that includes sag

### ISSUE THREAD

**Issue by jidanni** [OSGeo/grass#1320]
Longterm wishlist item:
If one day anybody is writing a 3D renderer for power lines,
don't forget the [sag](https://www.wired.com/2017/04/lets-physics-power-lines-sag/)
else they will be unrealistic straight lines:
![view](https://user-images.githubusercontent.com/1230959/107603255-14b88380-6c67-11eb-9c3f-ff08d783a82f.jpg)
(Like I made with Google Earth.)
https://support.google.com/earth/thread/97604994

**Comment by neteler** [comment]
Maybe something like this?:

- digitize the 2D vector line, densify the nodes
- add appropriate attribute values to the nodes, using one of the (Python) models from the article 
- turn it into a 3D line using [v.to.3d](https://grass.osgeo.org/grass-stable/manuals/v.to.3d.html) -  transforming 2D vector features to 3D based on attribute

**Comment by jidanni** [comment]
Markus, Markus, Markus, aren't all those solutions just ones that rely on increasing the nodes, thus swelling files?
I was thinking more like just implementing it in the renderer, 
https://support.google.com/earth/thread/97604994?msgid=97740618

**Comment by wenzeslaus** [comment]
@jidanni, is this "I'm already using GRASS GIS for all my 3D infrastructure visualizations and I'm missing this feature" or is it "I would consider using 3D view in GRASS GIS if there is this feature"? If it is the latter, I would say that's indication this is out of scope for GRASS GIS, thus won't fix for an issue (that would be different of a PR).

**Comment by jidanni** [comment]
Just thought it would make Grass more powerful. OK, my mistake.

**Comment by wenzeslaus** [comment]
> Just thought it would make Grass more powerful.

I agree!

**Comment by neteler** [comment]
@jidanni sure, improvements are welcome!
