### ISSUE TITLE
[Bug] r.stream.extract stream directions

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#1354]
**Describe the bug**
*r.stream.extract* generates invalid stream lines.

**To Reproduce**

1. Unpack https://data.isnew.info/grass/tmp_dem.pack into an EPSG:4326 location.
2. `r.watershed -s -a ele=tmp_dem acc=tmp_acc drain=tmp_drain`
3. `r.stream.extract ele=tmp_dem acc=tmp_acc stream_vec=tmp_streams threshold=1`
4. Compare `tmp_drain` and `tmp_streams`.

**Expected behavior**
Extracted streams (`tmp_streams`) must follow the drainage directions (`tmp_drain`).

**Screenshots**
The green arrows are drainage directions obtained from *r.watershed* and the blue lines are streams extracted by *r.stream.extract*. Incorrect stream paths are circled in red.

![image](https://user-images.githubusercontent.com/7456117/108165683-f5838100-70c0-11eb-8822-e092a1299076.png)

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version: master

**Additional context**

A similar approach using *r.slope.aspect*, *r.mapcalc*, and *r.accumulate*:
1. `r.watershed -s -a ele=tmp_dem acc=tmp_acc drain=tmp_drain`
2. `r.slope.aspect ele=tmp_dem slope=tmp_slope`
3. `r.mapcalc ex='tmp_acc_2=tan(tmp_slope)^0.4*tmp_acc'`
4. `r.accumulate dir=tmp_drain stream=tmp_streams_acc input_acc=tmp_acc_2 threshold=1`
5. Compare `tmp_drain` (*r.watershed*, green), `tmp_streams` (*r.stream.extract*, blue), and `tmp_streams_acc` (*r.accumulate*, red).

![image](https://user-images.githubusercontent.com/7456117/108170300-fa97fe80-70c7-11eb-90a4-0ac40df41bc9.png)

**Comment by metzm** [comment]
`r.stream.extract` uses diagonal shortcuts where possible. Back then when I wrote the module, I found that the resultant stream lines look cleaner and more realistic using these diagonal shortcuts. The reported bug is intended to be a feature.

**Comment by HuidaeCho** [comment]
> `r.stream.extract` uses diagonal shortcuts where possible. Back then when I wrote the module, I found that the resultant stream lines look cleaner and more realistic using these diagonal shortcuts. The reported bug is intended to be a feature.

I got it. Actually, I found this paragraph from the manual, which was not very clear when I reported this feature as a bug.
> Output direction raster map contains flow direction for all non-NULL cells in input elevation. Flow direction is of D8 type with a range of 1 to 8. Multiplying values with 45 gives degrees CCW from East. Flow direction was adjusted during thinning, taking shortcuts and skipping cells that were eliminated by the thinning procedure. 

So, thanks to this feature, the input accumulation and output stream_raster/_vector/direction will rarely match after *thinning* and *shortcutting*, I think. I tested repeating this module by feeding its outputs to itself:
```bash
r.watershed -s -a ele=tmp_dem acc=tmp_acc drain=tmp_dir
r.stream.extract ele=tmp_dem acc=tmp_acc stream_vec=tmp_streams dir=tmp_dir_2 threshold=1
r.accumulate dir=tmp_dir_2 acc=tmp_acc_2 -N
r.stream.extract ele=tmp_dem acc=tmp_acc_2 stream_vec=tmp_streams_2 dir=tmp_dir_3 threshold=1
r.accumulate dir=tmp_dir_3 acc=tmp_acc_3 -N
r.stream.extract ele=tmp_dem acc=tmp_acc_3 stream_vec=tmp_streams_3 dir=tmp_dir_4 threshold=1
```
`tmp_streams` (blue), `tmp_streams_2` (red), `tmp_streams_3` (black)
![image](https://user-images.githubusercontent.com/7456117/108566196-022bf300-72d4-11eb-9ac6-e6a8de3f9d1d.png)

I don't think it is meant to be used sequentially because the module adjusts flow directions every time it runs. I think we should make all this *very* clear in the manual to avoid careless mistakes.

**Comment by metzm** [comment]
> > `r.stream.extract` uses diagonal shortcuts where possible. Back then when I wrote the module, I found that the resultant stream lines look cleaner and more realistic using these diagonal shortcuts. The reported bug is intended to be a feature.

> So, thanks to this feature, the input accumulation and output stream_raster/_vector/direction will rarely match after _thinning_ and _shortcutting_, I think. 

On the contrary, if you inspect input accumulation and output streams, this shortcutting is supposed to reduce artefacts in input accumulation, but still matching input accumulation. Do you have an example where input accumulation and output streams do not match?

**Comment by HuidaeCho** [comment]
> > > `r.stream.extract` uses diagonal shortcuts where possible. Back then when I wrote the module, I found that the resultant stream lines look cleaner and more realistic using these diagonal shortcuts. The reported bug is intended to be a feature.
> 
> > So, thanks to this feature, the input accumulation and output stream_raster/_vector/direction will rarely match after _thinning_ and _shortcutting_, I think.
> 
> On the contrary, if you inspect input accumulation and output streams, this shortcutting is supposed to reduce artefacts in input accumulation, but still matching input accumulation. Do you have an example where input accumulation and output streams do not match?

`matching input accumulation` as in the overall shape (i.e., stream lines falling on highly accumulated cells), but not actual cell values in the correct order because original flow directions, which input accumulation was based on, are adjusted by the module.

flow directions: red from `r.stream.extract` and green from `r.watershed`; numbers: flow accumulation
![image](https://user-images.githubusercontent.com/7456117/108572103-8afc5c00-72df-11eb-8bbe-21bdd4ef2e7c.png)

**Comment by metzm** [comment]
The red arrows seem correct to me, the one in the lower-right corner takes the correct shortcut.

Surface flow is accumulated using MFD (multiple flow directions). `r.stream.extract` selects the predominant direction from these multiple directions.

**Comment by HuidaeCho** [comment]
@metzm I see. Since everything is normal and as expected, this issue is invalid and I'm closing it now. Thanks for checking it.
