### ISSUE TITLE
[Bug] r.geomorphon multi-resolution mode does not work

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1355]
**Describe the bug**
The multi-resolution mode in r.geomorphon creates empty maps, does not seem to respond to any multires settings, and is not documented in the manual. 

This part of the module code should be deactivated, removed, or fixed. Relevant arguments are: prefix, start, and step. 

**To Reproduce**
Fill in required fields and enter something in the "prefix" argument to activate multires mode. Regardless of any other settings, a set of 5 empty maps are produced with the suffixes of: _scale_10, _scale_20, _scale_50, _scale_100, _scale_300.

**Expected behavior**
No idea. Multi-resolution mode is not documented. 

**System description (please complete the following information):**

- Operating System: I tested on Mac OS 11.2.1, but it seems to be the same on all systems
- GRASS GIS version 7.8.5 and above

**Comment by infrastation** [comment]
I had found other discrepancies in this plugin before and managed to fix them, but not this one. It would help a lot if the original developers clarified the use case for multires, maybe with that information the bugfix will be trivial. However, if that does not work out, deactivating the multires code should not make anything worse.

**Comment by neteler** [comment]
> It would help a lot if the original developers clarified the use case for multires

He might be reachable via email, see [here](http://sil.uc.edu/index.php?id=jaroslaw-jasiewicz)

**Comment by infrastation** [comment]
I have requested the feedback today.

**Comment by neteler** [comment]
The code in question has been deactiavated in  #1570
