### ISSUE TITLE
[Bug] Add-ons, which call python scripts/modules, fail execution on macOS binary distribution

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#1414]
**Describe the bug**

Executing addons, which internally call python scripts (modules), on the conda based Mac binary distribution fails with message like:

```
...

Writing raster map <my_basin_elevation_dist2out>...
 100%
------------------------------
 100%
Tot. cells 88407.0
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

------------------------------

An ERROR occurred running r.basin
Please check for error messages above or try with another pairs of outlet
coordinates

...
```

This was originally reported with https://github.com/OSGeo/grass-addons/issues/443.

**To Reproduce**

1. Install add-on r.basin and dependencies
2. In location `nc_spm_08` execute `g.region raster=elevation@PERMANENT -p`
3. `r.basin map=elevation@PERMANENT prefix=my_basin coord=637304.924954,218617.100523 dir=/Users/Shared threshold=1000`

**System description (please complete the following information):**

- Operating System: macOS
- GRASS GIS version 7.8.5 and 7.9.dev (binary dist)

**Additional context**
This is caused by the specifics of the conda based GRASS distribution for Mac.

**Comment by nilason** [comment]
A possible permanent solution could the following be:
```
cd /Applications/GRASS-7.8.app/Contents/Resources/bin
ln -sf pythonw python3
ln -sf pythonw python
```
which seems to me to work fine. It need some testing whether it affects use of the GRASS binary in some way.
 @cmbarton @IreneM21 Would appreciate if you could test general use with the above changes.


How to revert to original:
```
cd /Applications/GRASS-7.8.app/Contents/Resources/bin
ln -sf python3.8 python3
ln -sf python3.8 python
```

**Comment by IreneM21** [comment]
Il’definitely try tomorrow, first thing in the morning

**Comment by IreneM21** [comment]
This morning I've tried to apply some GRASS functions (g.region, r.report, r.stats and r.slope.aspect) and everything seems to work fine

**Comment by nilason** [comment]
> This morning I've tried to apply some GRASS functions (g.region, r.report, r.stats and r.slope.aspect) and everything seems to work fine

Thanks! That might be the fix for this then.

**Comment by IreneM21** [comment]
Great! Thank you for your help!

**Comment by cmbarton** [comment]
The proposed fix works and r.basin runs with no errors. 

One note, threshold should be listed as required, since r.basin will not run without it.
