### ISSUE TITLE
[Bug] demo location uses a hard-coded path instead of `GISDBASE`?

### ISSUE THREAD

**Issue by infrastation** [OSGeo/grass#1419]
**Describe the bug**
The GUI disregards an existing non-default database directory when automatically creating and activating a demo location.

**To Reproduce**
1. install GRASS from the master branch one or two months ago (it could be related to commit 28876fe)
2. configure a non-default `GISDBASE` in `~/.grass7/rc` and fill it with a few locations and layers
3. exit GRASS, update to the current master branch and start it again
4. upon start the GUI will create a new database in `~/grassdata` with a location named `world_latlong_wgs84` and a vector layer, it will also switch to the new mapset

**Expected behavior**
It would seem more logical to create the demo location in the current database, and to prompt the user before doing so. Perhaps that's how it works when `GISDBASE` points to the default directory, but when it is different, the behaviour becomes inconsistent.

**Comment by lindakladivova** [comment]
Please, see https://github.com/OSGeo/grass/pull/1400. Here is explained how the suggested startup is gonna look like. 
As @HuidaeCho suggested, I will probably make another variable in rc called "default_gisdbase" which could be manually set up by a user.
