### ISSUE TITLE
v.colors invert colors does not work correctly

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1432]
**Describe the bug**
Yet another issue with v.colors. The 'invert colors' flag in v.colors does not correctly invert the colors

**To Reproduce**
Steps to reproduce the behavior using the censusblk_swwake vector map from the NC demo data set:

Set the color table for MEDIAN_AGE to plasma
```
v.colors map=censusblk@spatialtech2021 use=attr column=MEDIAN_AGE color=plasma
```
Here is a close up screen shot of a relevant section of the map showing the values and colors. High values are yellow; low values are dark purple and blue

![censusblk_plasma](https://user-images.githubusercontent.com/8967599/110361625-8503bc00-7ffd-11eb-8149-bf2b2c93e59c.png)

Do the same thing with inverted colors
```
v.colors -n map=censusblk@spatialtech2021 use=attr column=MEDIAN_AGE color=plasma
```
The same view shows inconsistent colors. Some high values are yellow (as with not inverted) and others are shades of purple. Some very low values are dark blue (as with not inverted), but other are light purple or even yellowish as they should be. There seems to be no pattern to the erroneous color assignment

![censusblk_plasma_inverted](https://user-images.githubusercontent.com/8967599/110362318-6225d780-7ffe-11eb-8e88-76801b421694.png)

**Expected behavior**
Low values with an inverted color table should take on the colors of high values in a non-inverted color table

**System description (please complete the following information):**

- Operating System: Mac OS 11.2.2
- GRASS GIS version: 7.9dev

**Comment by HuidaeCho** [comment]
@cmbarton Please test #1478.

**Comment by cmbarton** [comment]
Thanks. I’ll test Monday if I can

**Comment by cmbarton** [comment]
Your changes fixes invert colors (-n flag). Thanks. 

You are correct. -g and -a give identical, and clearly incorrect colors. 

I've never had much luck with log and absolute log on raster color tables either. When I try -g for the raster version of the vector map I'm testing (censusblk_swwake, MEDIAN_AGE), it creates a blank map. -a should be identical to -g because there are no negative values in the map,  but it gives a non-blank map that seems sort of like an inverted colors map (you can test with a grey scale color table). So maybe -a and -g are broken for both r.colors and v.colors.

**Comment by HuidaeCho** [comment]
> Your changes fixes invert colors (-n flag). Thanks.
> 
> You are correct. -g and -a give identical, and clearly incorrect colors.
> 
> I've never had much luck with log and absolute log on raster color tables either. When I try -g for the raster version of the vector map I'm testing (censusblk_swwake, MEDIAN_AGE), it creates a blank map. -a should be identical to -g because there are no negative values in the map, but it gives a non-blank map that seems sort of like an inverted colors map (you can test with a grey scale color table). So maybe -a and -g are broken for both r.colors and v.colors.

Good to know that. I'll take a look at it later.

**Comment by cmbarton** [comment]
Has this been back ported to 7.8?

**Comment by HuidaeCho** [comment]
> Has this been back ported to 7.8?

Backported in #1479.

**Comment by cmbarton** [comment]
Thanks. Unless you think you'll be able to solve the log enhancement issue soon, I'll go ahead and make new binaries this week. 

Michael

**Comment by HuidaeCho** [comment]
I just tested `r.colors` and you're right. `-g` clears the map! I think this is a bigger problem than just vector coloring. Please go ahead and make new binaries this week.

```bash
v.to.rast input=censusblk use=attr attcol=MEDIAN_AGE output=censusblk_median_age
r.colors map=censusblk_median_age col=plasma
```
![image](https://user-images.githubusercontent.com/7456117/112320920-da8aca80-8c85-11eb-852d-431cf0935751.png)
```bash
r.colors map=censusblk_median_age col=plasma -g
```
![image](https://user-images.githubusercontent.com/7456117/112321154-1887ee80-8c86-11eb-9450-1e0e9792fded.png)

```bash
r.colors map=censusblk_median_age col=plasma -a
```
![image](https://user-images.githubusercontent.com/7456117/112321059-fa21f300-8c85-11eb-995d-3e4ebce11441.png)

**Comment by HuidaeCho** [comment]
Unless this is our misunderstanding of log and abs-log colors, it needs to be fixed. Created a ticket for this. #1480.
