### ISSUE TITLE
[Bug] Using g.gisenv does not refresh the Data catalog properly

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#1443]
**Describe the bug**
When I switch mapset from the CMD window using `g.gisenv` and refresh (the current mapset refresh button) the Data catalog, it displays both old and new mapsets as current. I have to collapse either mapset to update the tree correctly.

**To Reproduce**

1. Start in a mapset
2. `g.mapset another_mapset`
3. Click the refresh current mapset button
4. See two current mapsets <--- Bug
5. Collapse either old or new mapset
6. Now, only one current mapset

**Expected behavior**
Only the current mapset is labeled as current.

**Screenshots**

![image](https://user-images.githubusercontent.com/7456117/110655932-7f3ce080-818d-11eb-82c5-efb76a0b87b3.png)

**System description (please complete the following information):**

- Operating System: Windows
- GRASS GIS version: master

**Additional context**

**Comment by HuidaeCho** [comment]
> This should be addressed in #1174, it would automatically change the current mapset in data catalog.

Awesome! I'll try #1174 (still draft).

**Comment by petrasovaa** [comment]
This should be more or less addressed in now merged #1174. Note, that switching mapsets using g.gisenv leaves .gislock behind, so using g.mapset is preferable.
