### ISSUE TITLE
[Bug] r.colors: -g (log) and -a (absolute log) don't work as expected

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#1480]
**Describe the bug**
`r.colors -g` clears the map and `r.colors -a` produces different colors from `r.colors -g` for non-negative rasters.

**To Reproduce**

```bash
v.to.rast input=censusblk use=attr attcol=MEDIAN_AGE output=censusblk_median_age
r.colors map=censusblk_median_age col=plasma
r.colors map=censusblk_median_age col=plasma -g
r.colors map=censusblk_median_age col=plasma -a
```

**Expected behavior**

Same colors for raster cell, log(raster cell), and log(abs(raster cell)).

**Screenshots**

```bash
v.to.rast input=censusblk use=attr attcol=MEDIAN_AGE output=censusblk_median_age
r.colors map=censusblk_median_age col=plasma
```
![image](https://user-images.githubusercontent.com/7456117/112320920-da8aca80-8c85-11eb-852d-431cf0935751.png)
```bash
r.colors map=censusblk_median_age col=plasma -g
```
![image](https://user-images.githubusercontent.com/7456117/112321154-1887ee80-8c86-11eb-9450-1e0e9792fded.png)

```bash
r.colors map=censusblk_median_age col=plasma -a
```
![image](https://user-images.githubusercontent.com/7456117/112321059-fa21f300-8c85-11eb-995d-3e4ebce11441.png)

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version: master

**Additional context**

The minimum of `censusblk_median_age` is 0, so `log(min)` is `-inf`
https://github.com/OSGeo/grass/blob/647162b017cfa70c05f7274f7eb0f4a0bfda5892/lib/raster/color_xform.c#L197
and `lx` is `-nan`.
https://github.com/OSGeo/grass/blob/647162b017cfa70c05f7274f7eb0f4a0bfda5892/lib/raster/color_xform.c#L219
This is why its colr file is empty with just header, I think:
```
% 0 -1
nv:255
*:255
```
```

**Comment by HuidaeCho** [comment]
```bash
r.mapcalc ex='tmp=if(censusblk_median_age==0,1,censusblk_median_age)'
r.colors map=tmp col=plasma -g
```
![image](https://user-images.githubusercontent.com/7456117/112325147-d19bf800-8c89-11eb-97ae-a9e5b1299bd0.png)

**Comment by HuidaeCho** [comment]
@cmbarton For `-g`, cell=0 => NULL color or make it the same as `-a`?

Actually, `Rast_abs_log_colors()` looks weird. It adds 1 to min and max to avoid `inf` lmin and lmax 
https://github.com/OSGeo/grass/blob/647162b017cfa70c05f7274f7eb0f4a0bfda5892/lib/raster/color_xform.c#L256
(understandable), but it doesn't use the log of the minimum absolute value (lmin) at all for color stretching.
https://github.com/OSGeo/grass/blob/647162b017cfa70c05f7274f7eb0f4a0bfda5892/lib/raster/color_xform.c#L281
Also, it uses 1 as the minimum cell value inside the for loop?
https://github.com/OSGeo/grass/blob/647162b017cfa70c05f7274f7eb0f4a0bfda5892/lib/raster/color_xform.c#L277
What if min < 1? Confusing...

**Comment by cmbarton** [comment]
0 is not null. So same as -a.

**Comment by HuidaeCho** [comment]
> 0 is not null. So same as -a.

I used the default color in #1481. `Rast_abs_log_colors()` uses 1 instead of `GRASS_EPSILON`. Maybe, I need to change that or #1481?

**Comment by cmbarton** [comment]
Isn't null normally transparent?

**Comment by cmbarton** [comment]
alpha=0

**Comment by HuidaeCho** [comment]
When not *set*, null and default colors are both white.

**Comment by cmbarton** [comment]
If there is no default color for non-null raster cells, I suppose a 50% grey makes sense (as with vectors).

**Comment by HuidaeCho** [comment]
> If there is no default color for non-null raster cells, I suppose a 50% grey makes sense (as with vectors).

Agreed. I have never set a default color for rasters. Do we even have any module that can do that? What about a null color? @neteler?

**Comment by cmbarton** [comment]
Isn't null transparent alpha=0?

**Comment by HuidaeCho** [comment]
> 
> 
> Isn't null transparent alpha=0?

I don't think we have transparency in raster colors (at least in rules). It's currently the display driver's job to handle transparency, I think.
https://github.com/OSGeo/grass/blob/647162b017cfa70c05f7274f7eb0f4a0bfda5892/lib/raster/color_get.c#L127-L142

**Comment by cmbarton** [comment]
Then perhaps a default of 50% grey for non-null cells and white for null cells?

**Comment by neteler** [comment]
> > If there is no default color for non-null raster cells, I suppose a 50% grey makes sense (as with vectors).
> 
> Agreed. I have never set a default color for rasters. Do we even have any module that can do that? What about a null color? @neteler? Maybe, using rule syntax (`default` and `nv`).

I think that "null" should remain transparent as default to not cover underlying other maps. If the user wants to change that then e.g. `nv white` can be assigned with `r.colors`.

**Comment by cmbarton** [comment]
> > > If there is no default color for non-null raster cells, I suppose a 50% grey makes sense (as with vectors).
> > 
> > 
> > Agreed. I have never set a default color for rasters. Do we even have any module that can do that? What about a null color? @neteler? Maybe, using rule syntax (`default` and `nv`).
> 
> I think that "null" should remain transparent as default to not cover underlying other maps. If the user wants to change that then e.g. `nv white` can be assigned with `r.colors`.

This makes sense if possible

**Comment by susi** [comment]
This looks interesting, I'll take a stab at this one. :)

**Comment by susi** [comment]
A little progress today:

```shell
r.colors map=censusblk_median_age col=plasma -g
```
Results in
![Screenshot_2021-10-02_20-50-52](https://user-images.githubusercontent.com/166694/135728631-2da064ec-9d63-417a-8ced-5c2f78a051cb.png)
