### ISSUE TITLE
[Feat] wxGUI: Better infobar color on Windows?

### ISSUE THREAD

**Issue by lindakladivova** [OSGeo/grass#1491]
**Is your feature request related to a problem? Please describe.**
The blue color of infobar seems to be a bit strange.

**Describe the solution you'd like**
Something similar to orange color in Linux?

**Comment by petrasovaa** [comment]
Could you provide a screenshot on Windows?

Note, the color now is not fixed but depends on your theme. So for example I have blue (not orange) on my Ubuntu with default dark theme. Specifically, the color we use currently is defined in wx.SYS_COLOUR_HIGHLIGHT. wx.SYS_COLOUR_INFOBK is the appropriate color, however on my system it is black which looks rather weird and native infobars on my system do not use wx.SYS_COLOUR_INFOBK, but that may be different for windows (or mac).

@lindakladivova, @nilason what are these colors on Windows/Mac?

**Comment by lindakladivova** [comment]
Windows master:
![strange_color](https://user-images.githubusercontent.com/49241681/113326725-5803aa00-931a-11eb-9afc-962eb9ab4936.PNG)

**Comment by petrasovaa** [comment]
And the color?
```
wx.SystemSettings.GetColour(wx.SYS_COLOUR_INFOBK)
```
I guess it's yellow?

**Comment by hellik** [comment]
```
System Info                                                                     
GRASS version: 7.9.dev                                                          
Code revision: 61d6f8c7d                                                        
Build date: 2021-03-31                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.1.4                                                                     
PROJ: 6.3.2                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.19041-SP0 (OSGeo4W)   
```
```
import wx
wx.SystemSettings.GetColour(wx.SYS_COLOUR_INFOBK)
(255, 255, 225, 255)
```

**Comment by nilason** [comment]
Mac:
![colours-mac](https://user-images.githubusercontent.com/14186207/113351155-be98c000-933a-11eb-8ef2-a6a0a826a4f7.jpg)

**Comment by nilason** [comment]
This is what it looks on Mac now:
<img width="637" alt="Screenshot1" src="https://user-images.githubusercontent.com/14186207/113398028-3ba95100-939e-11eb-84d7-013440e14dd5.png">


With `wx.SYS_COLOUR_INFOBK` (background) and `wx.SYS_COLOUR_INFOTEXT` (foreground):
<img width="637" alt="Screenshot2" src="https://user-images.githubusercontent.com/14186207/113398156-6bf0ef80-939e-11eb-905d-ad1a508124ef.png">
which in my opinion would be acceptable.

What bothers me is that the white background isn't filled down to the edge, but that is a separate issue. (I think this a Mac+wxPython 4.1 issue).

**Comment by lindakladivova** [comment]
With wx.SYS_COLOUR_INFOBK (background) and wx.SYS_COLOUR_INFOTEXT (foreground) on Windows
![win](https://user-images.githubusercontent.com/49241681/113402543-72cf3080-93a5-11eb-8155-5d47116378e1.PNG)
:-(
Even if the text would be in a different color, I personally do not like the very light yellow... I think we need some more "expressive" color, e.g. as Linux orange color :-) 
Maybe, it is good as it is. I really don't know.

**Comment by petrasovaa** [comment]
> Sorry, I made mistake in the previous picture.
> 
> With `wx.SYS_COLOUR_INFOBK` (background) and `wx.SYS_COLOUR_INFOTEXT` (foreground) on Windows:
> 
> ![win](https://user-images.githubusercontent.com/49241681/113404022-cfcbe600-93a7-11eb-96e2-f77db67d78cf.PNG)

I think we should go with wx.SYS_COLOUR_INFOBK on Windows and wx.SYS_COLOUR_HIGHLIGHT elsewhere. I don't think we should use a fixed color (like blue or orange) because that doesn't take into account the theme and could look strange. 

Not sure about the buttons, we could also keep them with default background.
