### ISSUE TITLE
[Bug] i.band possibly hides error details, misses error handling

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#1494]
**Describe the bug**

There is an unused variable in i.band code. Although in other cases this would be a trivial fix. This one requires some investigation. A snipped of the problematic code follows:

```
    except OpenError as e:
        gs.error(_("Map <{}> not found").format(name))
```

Is the OpenError raised only in case `Map <{}> not found` or are there other cases. What the error message should report? Details of the error? Another message?

Furthermore, the function reports an error (`gs.error()`), but does not end the program. This might be a perfectly fine behavior, but it is not documented as far as I can tell while the usual behavior is to trigger a fatal error (`gs.fatal()`) and the other function in the file failure causes the script to return non-zero return code indicating an error.

**To Reproduce**

```
flake8 --isolated scripts/i.band/i.band.py
```

**Expected behavior**

**Screenshots**

```
./i.band/i.band.py:66:5: F841 local variable 'e' is assigned to but never used
./i.band/i.band.py:98:5: F841 local variable 'e' is assigned to but never used
```

**System description:**

- GRASS GIS version: master branch

**Additional context**

OpenError definition is simple and was already present before addition of band references. It is raised by RasterRow.

```
class OpenError(Exception):
    pass
```

**Comment by ninsbl** [comment]
ì.band`does not exist any more. i.bands.library does not contain the quoted code...

Can this be closed?

**Comment by wenzeslaus** [comment]
> ...does not contain the quoted code...

This is really based on the specific code, so closing.

BTW, closing as fixed (error is not there anymore with recent version).
