### ISSUE TITLE
Add a new option for r.watershed

### ISSUE THREAD

**Issue by dustming** [OSGeo/grass#1500]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
when we use recently developed hydrological pre-conditioned DEM, the depression in these DEM is real depressions. However the r.watershed is designed to overcome these depressions which will result in the incorrect drainage system.  

**Describe the solution you'd like**
Add another option, to make r.watershed do not overcome depressions

**Describe alternatives you've considered**
Add another option, to make r.watershed do not overcome depressions

**Additional context**

**Comment by HuidaeCho** [comment]
[r.watershed](https://grass.osgeo.org/grass78/manuals/r.watershed.html) uses the A^T least-cost search algorithm that does not require sink filling or does not even recognize sinks (?), but you can pass a depression raster to this module. If detecting depressions is an issue, check [r.fill.dir](https://grass.osgeo.org/grass78/manuals/r.fill.dir.html) and run [r.accumulate](https://grass.osgeo.org/grass78/manuals/addons/r.accumulate.html), which takes a flow direction raster as input ([similar output to r.watershed](https://grass.osgeo.org/grass78/manuals/addons/r.accumulate.html#longest-flow-path-calculation-and-subwatershed-delineation-in-one-run)).
