### ISSUE TITLE
[Bug] Unused encoding in start_command

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#1521]
**Describe the bug**

The `start_command` function in `grass.script` contains the following code:

```python
    if "encoding" in kwargs.keys():
        encoding = kwargs.pop("encoding")
```

However, it is not used.

Is the encoding missing somewhere, should the lines be deleted, or is only the removal of encoding from kwargs important?

**To Reproduce**

See the source code or run:

```
flake8 --isolated --disable-noqa --select="F841" --show-source python/grass/script/core.py
``` 

**Expected behavior**

No unused variables.

**Screenshots**

```
./script/core.py:468:9: F841 local variable 'encoding' is assigned to but never used
        encoding = kwargs.pop("encoding")
        ^
1     F841 local variable 'encoding' is assigned to but never used
```

**System description**

GRASS GIS version: master branch and also 7.8 release branch

**Additional context**

Introduced as unused in 7e1945f230e57b32adda5f23f070f0c2e1525a00 (experimental GSoC 2018 Python 3 support) before the Flake8 checks were in place.

**Comment by neteler** [comment]
FYIW, I found another one here (not sure if relevant):

https://github.com/OSGeo/grass/blob/0140b987a5004672125a4fe5bde295dfe440863c/python/grass/script/vector.py#L442
