### ISSUE TITLE
[Bug] Temporal database remembers old timestamps

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass#1532]
**Buggy behaviour?**

Removing a space-time dataset, without physically removing the maps pertaining to it, then updating the individual timestamps of the maps and finally re-creating the previously removed space-time dataset and re-registering the maps in to it, does not obtain the new/updated timestamps, when listing the maps of the newly created space-time dataset.

Why is that so?

**Steps to reproduce**

1. remove an existing space-time dataset via `t.remove space-time-data-set`
```
Note: registered maps themselves have not been removed, only the strds
```
2. Updating the timestamps of the maps that where parts of the remove space-time dataset
3. Creating the (removed) space-time dataset (same-name, does it matter?)
4. Registering the maps (with the updated) timestamps in the newly created space-time dataset
5. Listing the maps of the space-time dataset in question

The result is that the old timestamps are retained, the new/updated timestamps are not registered in the temporal database.

A practical example using an existing space-time dataset
```
→ trl C -u column=name,start_time
C1|2019-12-11 01:30:00
C2|2019-12-19 01:30:00
C3|2019-12-27 01:30:00
```

Remove it
```
→ t.remove C
Note: registered maps themselves have not been removed, only the strds
```

Re-timestamp (i.e. here keep only the data part) and check
```
→ for MAP in $(glr pattern=C?) ;do r.timestamp $MAP date="$(r.timestamp $MAP |cut -d' ' -f1,2,3)" ;done
→ for MAP in $(glr pattern=C?) ;do r.timestamp $MAP ;done
11 Dec 2019
19 Dec 2019
27 Dec 2019
```

Re-create the space-time dataset
```
→ t.create output=C title=C description=C temporaltype=absolute
```
and re-register the maps (I prefer a loop after weird experiences seen in massive processing setups)
```
→ for MAP in $(glr pattern=C?) ;do t.register input=C map=$MAP ;done
```

Finally, why are the timestamps not up-to-date?
```
→ trl C -u column=name,start_time
C1|2019-12-11 01:30:00
C2|2019-12-19 01:30:00
C3|2019-12-27 01:30:00
```

**Expected behavior**

The new/updated timestamps should be registered in the temporal database too

**System description**

- Operating System: Linux
- GRASS GIS version 7.8.5dev (2020)

**Comment by NikosAlexandris** [comment]
Maybe `t.remove` deserves an option to remove all registered maps from the temporal database but _not_ from the spatial database, in a clean way. I.e., no leftover timestamps of the remove maps in the temporal database.

**Comment by lucadelu** [comment]
> Maybe `t.remove` deserves an option to remove all registered maps from the temporal database but _not_ from the spatial database, in a clean way. I.e., no leftover timestamps of the removed maps in the temporal database.

Yes I fully agree, look at [this ticket](https://trac.osgeo.org/grass/ticket/3362) for more info. I think Vero proposal sounds good.

**Comment by NikosAlexandris** [comment]
> > Maybe `t.remove` deserves an option to remove all registered maps from the temporal database but _not_ from the spatial database, in a clean way. I.e., no leftover timestamps of the removed maps in the temporal database.
> 
> Yes I fully agree, look at [this ticket](https://trac.osgeo.org/grass/ticket/3362) for more info. I think Vero proposal sounds good.

I see. Yes it looks good!

Yet, for my own understanding, I write it my way here, again.

The temporal database does not hold a copy of a raster map. Right? There is only an entry/record of a(ny) registered map. Most importantly, with a timestamp. My 'problem' currently is that  `t.remove` removes only the space-time dataset (which is something virtual is my understanding, just a construct to link to and group timestamped raster maps).

- remove the space-time dataset (this means automagically removal of all related records from the temporal database -- is there any reason to not clean the database once a space-time dataset has been removed, **except** when some maps are re-used by other space-time datasets?)
- remove the space-time dataset and the maps
- a force flag for any removal

**Comment by veroandreo** [comment]
I believe the problem is you are updating timestamps with r.timestamp, the temporal framework can read those, but once a map is the temporal database, its timestamp can be only modified with t.register; r.timestamp does not write in the temporal database

**Comment by veroandreo** [comment]
> > > Maybe `t.remove` deserves an option to remove all registered maps from the temporal database but _not_ from the spatial database, in a clean way. I.e., no leftover timestamps of the removed maps in the temporal database.
> > 
> > 
> > Yes I fully agree, look at [this ticket](https://trac.osgeo.org/grass/ticket/3362) for more info. I think Vero proposal sounds good.
> 
> I see. Yes it looks good!
> 
> Yet, for my own understanding, I write it my way here, again.
> 
> The temporal database does not hold a copy of a raster map. Right? There is only an entry/record of a(ny) registered map. 

yes

> Most importantly, with a timestamp. My 'problem' currently is that `t.remove` removes only the space-time dataset (which is something virtual is my understanding, just a construct to link to and group timestamped raster maps).

why is that a problem? currently, if you wish to remove all (i.e., stds and registered maps within that stds), you need to use -rf, otherwise only the container table, i.e., stds, will be removed, but maps will remain registered in the temporal database (you check that with `t.list type=raster`). If you want to remove some of them from the temporal database after having removed a stds, you need to use `t.unregister`, which will basically remove the timestamp from maps but won't remove them physically from the mapset that you can then do with g.remove

**Comment by NikosAlexandris** [comment]
> I believe the problem is you are trying to update timestamps with r.timestamp. The temporal framework can read those timestamps from maps if they exist, but once a map is the temporal database, its timestamp can be only modified with t.register; r.timestamp does not write in the temporal database

No Vero, update a map's timestamp with `r.timestamp` and then re-register it with `t.register`. The new timestamp does not make it to the temporal database registry.

**Comment by NikosAlexandris** [comment]
> why is that a problem? currently, if you wish to remove all (i.e., stds and registered maps within that stds), you need to use -rf, otherwise only the container table, i.e., stds, will be removed, but maps will remain registered in the temporal database (you check that with `t.list type=raster`). If you want to remove some of them from the temporal database after having removed a stds, you need to use `t.unregister`, which will basically remove the timestamp from maps but won't remove them physically from the mapset that you can then do with g.remove

Thanks for both tips! `t.list raster` and `t.unregister`.  I think the latter one especially will solve a lot of my problems. Great!

**Comment by NikosAlexandris** [comment]
@veroandreo So, currently `t.register --o` won't overwrite existing entries in the temporal database. One needs to `t.unregister`, then `t.register`. Right?

Is this by design so?

**Comment by veroandreo** [comment]
> @veroandreo So, currently `t.register --o` won't overwrite existing entries in the temporal database. One needs to `t.unregister`, then `t.register`. Right?

No, see below

```
r.mapcalc expression="prec_1 = 100"
r.mapcalc expression="prec_2 = 200"
r.mapcalc expression="prec_3 = 300"
r.mapcalc expression="prec_4 = 400"
r.mapcalc expression="prec_5 = 500"
r.mapcalc expression="prec_6 = 600"

t.create type=strds temporaltype=absolute \
    output=precip_abs title="Example" \
    descr="Example"

t.register -i type=raster input=precip_abs \
    maps=prec_1,prec_2,prec_3,prec_4,prec_5,prec_6 \
    start="2001-01-01" increment="1 months"

t.rast.list  precip_abs
name|mapset|start_time|end_time
prec_1|user1|2001-01-01 00:00:00|2001-02-01 00:00:00
prec_2|user1|2001-02-01 00:00:00|2001-03-01 00:00:00
prec_3|user1|2001-03-01 00:00:00|2001-04-01 00:00:00
prec_4|user1|2001-04-01 00:00:00|2001-05-01 00:00:00
prec_5|user1|2001-05-01 00:00:00|2001-06-01 00:00:00
prec_6|user1|2001-06-01 00:00:00|2001-07-01 00:00:00

## Here, I change the timestamp of one map and overwrite it in the temporal database and in the stds

t.register type=raster input=precip_abs maps=prec_6 start="2002-01-01" end="2002-02-01" --o

## Check again

t.rast.list precip_abs
name|mapset|start_time|end_time
prec_1|user1|2001-01-01 00:00:00|2001-02-01 00:00:00
prec_2|user1|2001-02-01 00:00:00|2001-03-01 00:00:00
prec_3|user1|2001-03-01 00:00:00|2001-04-01 00:00:00
prec_4|user1|2001-04-01 00:00:00|2001-05-01 00:00:00
prec_5|user1|2001-05-01 00:00:00|2001-06-01 00:00:00
prec_6|user1|2002-01-01 00:00:00|2002-02-01 00:00:00 <<<<=== timestamp changed
```

To change timestamps in the temporal framework you *need* to use t.register (see [here](https://github.com/OSGeo/grass/issues/1532#issuecomment-822065293) again ;))

**Comment by NikosAlexandris** [comment]
Alright, I see now. Thank you for patience and the practical example.  I am closing this issue. However, the question is then if `t.register` should respect `r.timestamp's` modifications? And if I should open a new issue with this request?

@OSGeo/grass-contributors Please target high internal consistency for future GRASS GIS versions.
