### ISSUE TITLE
winGRASS and OSGeo4W next generation - review of possible changes in compilation files

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass#1561]
OSGeo4W next generation (with PROJ 8 etc) is in a testing phase.

in [ jef-n /OSGeo4W/src/grass/osgeo4w/](https://github.com/jef-n/OSGeo4W/tree/master/src/grass/osgeo4w)

there are some changes in the compilation files.

a review should be done if some changes can be merged.

**Comment by neteler** [comment]
@hellik Is there anything left open here, given the merge of #2074?

**Comment by hellik** [comment]
> @hellik Is there anything left open here, given the merge of #2074?

I think we can close this ticket here.
