### ISSUE TITLE
[Bug] 7.86RC1 does not install grass.1 manpage

### ISSUE THREAD

**Issue by sebastic** [OSGeo/grass#1588]
The Debian package build for GRASS 7.8.6RC1 failed because the `grass.1` manpage is no longer installed:
```
mv debian/tmp/usr/lib/grass78/docs/man/man1/grass7.1 debian/grass78.1
mv: cannot stat 'debian/tmp/usr/lib/grass78/docs/man/man1/grass7.1': No such file or directory
```

`g.html2man` is executed as usual for it:
```
VERSION_NUMBER=7.8.6RC1 /build/grass-7.8.6~rc1/dist.x86_64-pc-linux-gnu/tools/g.html2man.py "/build/grass-7.8.6~rc1/dist.x86_64-pc-linux-gnu/docs/html/grass7.html" "/build/grass-7.8.6~rc1/dist.x86_64-pc-linux-gnu/docs/man/man1/grass7.1"
```
But it doesn't seem to be installed by `make install`.

**Comment by nilason** [comment]
Did compilation (`make`) succeed without issues?

**Comment by sebastic** [comment]
Yes, see: [grass_7.8.6~rc1-1~exp1_amd64.txt](https://github.com/OSGeo/grass/files/6513380/grass_7.8.6.rc1-1.exp1_amd64.txt)

**Comment by nilason** [comment]
Thanks. Still looking at the log, but should mention this is the first release with DESTDIR support (still untested in the wild). Maybe related...?

**Comment by sebastic** [comment]
`DESTDIR` is set to `debian/tmp` by `dh_auto_install` which shouldn't change things, unless GRASS not ignores `INST_DIR`:
```
        dh_auto_install -- \
                INST_DIR=$(CURDIR)/debian/tmp/usr/lib/$(BASE_NAME) \
                UNIX_BIN=$(CURDIR)/debian/tmp/usr/bin
```

**Comment by sebastic** [comment]
Thanks for looking into this issue, I made it work with:
```
        dh_auto_install -- \
                INST_DIR=/usr/lib/$(BASE_NAME) \
                UNIX_BIN=/usr/bin
```

**Comment by nilason** [comment]
> Thanks for looking into this issue, I made it work with:
> 
> ```
>         dh_auto_install -- \
>                 INST_DIR=/usr/lib/$(BASE_NAME) \
>                 UNIX_BIN=/usr/bin
> ```

Great, glad it worked out that "easy"!
