### ISSUE TITLE
[Feat] wxGUI: easier switching between locations (GRASS GIS 8)

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1595]
**Is your feature request related to a problem? Please describe.**

I started GRASS GIS 7.9 with the demolocation, then decided via "Data" tab to look at a map in a different mapset.
While the dialog is fine I am not sure how to actually switch to the other location:

![image](https://user-images.githubusercontent.com/1295172/119274617-19e78000-bc11-11eb-8c9d-84e74fca77ce.png)

Here I hoped that the "OK" button would actually *do* the switching. Since it doesn't I am not sure where to go now (assume I am a new user).

**Describe the solution you'd like**

Enhance the "OK" button above to let the user switch to the different location (or not).

**Describe alternatives you've considered**

At least pls explain where the switching can be done (maybe show icon in the dialog?).

**Comment by hellik** [comment]
right click on the mapset you want to change to works.

maybe an addition about that to the dialogue?

**Comment by wenzeslaus** [comment]
> Enhance the "OK" button above to let the user switch to the different location (or not).

Notably, switching _to_ another location also means switching _from_ the current one and that's when all your currently displayed layers need to disappear. That might be a surprising outcome when all you originally wanted was to take a quick look at some data. If this is clearly communicated in the message, buttons _Switch now_ | _Stay in the current one_ may work well (we have similar ones elsewhere already).

**Comment by veroandreo** [comment]
See #1598

**Comment by petrasovaa** [comment]
#1598 was merged
