### ISSUE TITLE
[Feat]  drop 32bit support with upcoming winGRASS 8.0

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass#1601]
GRASS GIS 8 is in the pipeline. 

winGRASS is build within the OSGeo4W framework; in midterm, the 32bit OSGeo4W will be phased out. 

That's a very good moment, to drop winGRASS 32bit with the next major GRASS GIS 8.0 release.

**Comment by hellik** [comment]
it has to be decided if it should be adapted to the actual OSGeo4W environment or to the OSGeo4W NG environment.

@jef-n any timeline available when OSGeo4W **NG** will displace the actual OSGeo4W environment?

**Comment by jef-n** [comment]
QGIS 3.20 will require dependencies not available in the old OSGeo4W

**Comment by hellik** [comment]
> 
> 
> QGIS 3.20 will require dependencies not available in the old OSGeo4W

[QGIS roadmap](https://www.qgis.org/de/site/getinvolved/development/roadmap.html)

`LR/PR 3.20.0 3.16.8 2021-06-18`

so it's due in about 3 weeks.

@jef-n  any reason why not informing the broader community of OSGeo/OSGeo4W earlier?  what about community involvment work?

@landam @neteler @HuidaeCho how we should proceed?

**Comment by jef-n** [comment]
> @jef-n any reason why not informing the broader community of OSGeo/OSGeo4W earlier?

Of what?  Both repos will continue to exists for now.  I just didn't know that 3.20 will cease to work with the old versions when I informed about the start of the testing repo.  The next 3.16 (LTR) point release will be still in both.  AFAIK you were the only one else to look at building GRASS in/with dependencies of testing.

> what about community involvement work?

volunteering?
