### ISSUE TITLE
[Feat] How to obtain the sub-basin with r.watershed 

### ISSUE THREAD

**Issue by wjcper2008** [OSGeo/grass#1613]
Thanks for your attention!

Hi, I use `r.watershed` to divide the whole DEM into some adjoined sub-basin. 

``
r.watershed -s --overwrite --quiet elevation=DEM threshold=1000000 basin=dem_basin
``

![image](https://user-images.githubusercontent.com/14107030/120424047-34062880-c39e-11eb-8f1e-77c4ff553f52.png)

How can I obtain sub-basin separately? That is, I want to handle each basin  `sub_basin` independently with different parameters AS

```
r.watershed -s --overwrite --quiet elevation=sub_basin1 threshold=10000 basin=dem_sub_basin
r.watershed -s --overwrite --quiet elevation=sub_basin2 threshold=20000 basin=dem_sub_basin
...
```

**Comment by veroandreo** [comment]
I do not use r.watershed, really, but have you tried using [r.mask](https://grass.osgeo.org/grass78/manuals/r.mask.html)? You could iteratively mask all but the sub-basin you want, and like that treat each sub-basin separately.

Probably these kind of questions are a better fit for the mailing list: [grass-user](https://lists.osgeo.org/mailman/listinfo/grass-user). I recommend to subscribe :)
