### ISSUE TITLE
[Bug] PyGRASS: MultiModule instances hang when run in the background.

### ISSUE THREAD

**Issue by Viech** [OSGeo/grass#1618]
**Describe the bug**
I have a collection of sequences of small module jobs that must run sequentially within each sequence while the sequences themselves may run in parallel with each other. Using a `ParallelModuleQueue` separately for each computational step of the sequences works but is very slow, potentially due to the overhead of running a module in a subprocess. I found that the `MultiModule` class can be used to define a sequence of modules running in one process and I hope to improve performance with it. However, when I try to run such `MultiModule` instances in parallel through a `ParallelModuleQueue` as the documentation suggests, then my program hangs indefinitely once `ParallelModuleQueue.wait` is called (which happens as soon as the queue is full).

**To Reproduce**
Run the following script:
```python
#!/usr/bin/env python3

from copy import deepcopy
from grass.pygrass.modules.interface.module import (
    Module,
    MultiModule,
    ParallelModuleQueue,
)

SYNC = False  # Fails for both True and False.

module = Module("g.region", flags="t", run_=False)
queue = ParallelModuleQueue(nprocs=2)

for i in range(2):
    print(f"Iteration: {i + 1}")
    modules = [deepcopy(module) for _ in range(2)]
    multi = MultiModule(module_list=modules, sync=SYNC)
    print(f"Adding to queue...")
    queue.put(multi)
    print(f"Now running: {queue.get_num_run_procs()}")

print("Left loop.")
queue.wait()
print("Done.")
```
Running the script will print the following, then hang indefinitely:
```
Iteration: 1
Adding to queue...
Now running: 1
Iteration: 2
Adding to queue...
590040/608970/4914050/4927970
590040/608970/4914050/4927970
590040/608970/4914050/4927970
590040/608970/4914050/4927970
```
Following a keyboard interrupt (`Ctrl + C`), one can see the following traceback:
```
Traceback (most recent call last):
  File "…/fix_multimodule.py", line 20, in <module>
    queue.put(multi)
  File "/opt/grass/etc/python/grass/pygrass/modules/interface/module.py", line 248, in put
    self.wait()
  File "/opt/grass/etc/python/grass/pygrass/modules/interface/module.py", line 305, in wait
    self._finished_modules.extend(proc.wait())
  File "/opt/grass/etc/python/grass/pygrass/modules/interface/module.py", line 967, in wait
    proc_list = self.q.get()
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

**Expected behavior**
The script should print `Left loop.`, then `Done.`, then it should exit.

**System description**
- Operating System: Linux 5.12.9-arch1-1 x86_64
- GRASS GIS version: 7.8.5
```
% g.version -rge
version=7.8.5
date=2020
revision=4e3f393
build_date=2021-04-27
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2021-04-27T07:33:34+00:00
libgis_date=2021-04-27T10:00:00+02:00
proj=8.0.0
gdal=3.2.2
geos=3.9.1
sqlite=3.35.5
```
```
% python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0]
4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
```

**Additional context**
The script is inspired by the _Check MultiModule approach with three by two processes running in a background process_  [example](https://grass.osgeo.org/grass78/manuals/libpython/pygrass.modules.interface.html#pygrass.modules.interface.module.ParallelModuleQueue).

**Comment by Viech** [comment]
The same behavior can be reproduced without the use of `ParallelModuleQueue` when the `MultiModule` instances are run  in the background using `sync=False`:

```python
#!/usr/bin/env python3

from copy import deepcopy
from grass.pygrass.modules.interface.module import Module, MultiModule

module = Module("g.region", flags="t", run_=False)
multis = []

for i in range(2):
    print(f"Iteration: {i + 1}")
    modules = [deepcopy(module) for _ in range(2)]
    multi = MultiModule(module_list=modules, sync=False)
    multis.append(multi)
    multi.run()

print("Left loop.")

for multi in multis:
    multi.wait()

print("Done.")
```
This hangs after printing:
```
Iteration: 1
Iteration: 2
Left loop.
590040/608970/4914050/4927970
590040/608970/4914050/4927970
590040/608970/4914050/4927970
590040/608970/4914050/4927970
```
Aborting gives the similar traceback:
```
Traceback (most recent call last):
  File "…/fix_multimodule.py", line 18, in <module>
    multi.wait()
  File "/opt/grass/etc/python/grass/pygrass/modules/interface/module.py", line 967, in wait
    proc_list = self.q.get()
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

**Comment by petrasovaa** [comment]
Could you test master? Or even latest 7.8 branch, there has been some fixes done and just recently backported to 7.8 branch.

**Comment by ninsbl** [comment]
See: #1606
This works for me now. @Viech, can you confirm and in case close the issue?

**Comment by Viech** [comment]
I'd like to test but I need to find the time to setup PyGRASS from source. Could you assign me so I don't forget?

**Comment by ninsbl** [comment]
Thanks to recent work by @chaedri you can test the python interface with a build from the releasebranch here:
https://mybinder.org/v2/gh/OSGeo/grass/releasebranch_7_8?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fexample_notebook.ipynb

or simply click the `launch binder` button in the readme of the GRASS repo...

**Comment by Viech** [comment]
I thought I should test locally. Note that I don't have any relevant code left, apart from the two reproduction scripts I posted here, to test on the binder instance.

**Comment by Viech** [comment]
I've retested with GRASS `7.8.6` and the script terminates now, as it should.
