### ISSUE TITLE
[Bug] CI: shall ubuntu-16.04 tests remain in the 7.8 release branch GH actions?

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1642]
**Describe the bug**
Ubuntu-16.04 (Xenial) lacks the PDAL package, leading to a CI error after the backport of PDAL support:

https://github.com/OSGeo/grass/runs/2813712126

Open question: shall the Ubuntu-16.04 tests remain? According to https://ubuntu.com/16-04, Ubuntu 16.04 LTS is supported until 2024.

If yes, I wonder
- if to revert the backport (5b9b736);
- or, if there is a way to conditionalize the PDAL support in our CI to > Ubuntu-16.04

?

**Comment by wenzeslaus** [comment]
Given that 8.0 is just around the corner:

* Generally, I would say that reason for supporting 7.8 branch is the same as supporting Ubuntu 16.04 - old "stable" systems. This would mean, yes, use different ppa/apt and configs through the matrix like e.g. for GCC on master branch.
* However, in the last release planning meeting we more or less ended up with policy that if someone needs to support old releases, they can open PRs, maintainers merge PRs, but not attempt to keep it alive themselves and focus only on the latest release. ([Scenario 2](https://trac.osgeo.org/grass/wiki/Release/Schedule#Scenario2): We have only one actively updated, maintained, and supported release series.)

Needless to say, fragile backports should in general go through PRs.

**Comment by neteler** [comment]
OK, I have reverted the PDAL support backport for now (bfc90b48d21a2d5d3de5d3176e9ddc16cfdd8350).
