### ISSUE TITLE
[Bug] ctypesgen does not support C bool (_Bool) data type

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#1647]
**Describe the bug**

Embedded ctypegen version doesn't support and generate Python bridge code for C `bool` data type. This is particularly troublesome for GRASS C API used with Python. This was discovered during attempt to implement bool into lib/raster with #1272.

The function in question was declared as `bool Rast_legal_bandref(const char *);` and calling it with Python lead to following error message:

```
cd lib/raster/testsuite
python3 test_raster_metadata.py
Traceback (most recent call last):
  File "/Volumes/grass/lib/raster/testsuite/test_raster_metadata.py", line 22, in <module>
    from grass.lib.raster import Rast_legal_bandref, Rast_read_bandref, Rast_write_bandref
ImportError: cannot import name 'Rast_legal_bandref' from 'grass.lib.raster' (/Volumes/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/lib/raster.py)

```

However, using (slightly modified) code generated by latest version of [ctypesgen](https://github.com/davidjamesca/ctypesgen):

```py
for _lib in six.itervalues(_libs):
    if not hasattr(_lib, 'Rast_legal_bandref'):
        continue
    Rast_legal_bandref = _lib.Rast_legal_bandref
    Rast_legal_bandref.argtypes = [String]
    Rast_legal_bandref.restype = c_bool
    break
```
to the file `etc/python/grass/lib/raster.py`, calling the Python function works.

**To Reproduce**

1. Add a function with boolean return value or argument to GRASS C API in any of the lib parts 
2. Try call the function with Python
3. See error

**Expected behavior**
Ctypesgen should support bool (_Bool) C data type.

**System description (please complete the following information):**

- Operating System: all
- GRASS GIS version: master and 7.8 branch

**Additional context**
The issue with bool support was addressed some years ago with https://github.com/davidjamesca/ctypesgen/issues/19. Unfortunately the patches are no longer available and the active ctypesgen version has deviated considerably from the embedded version in GRASS making it difficult to replicate the fix.

**Comment by marisn** [comment]
There is a bug in Trac for moving 8.0 back to community ctypesgen:
https://trac.osgeo.org/grass/ticket/3900
There was also some discussion regarding ctypesgen upgrade here:
https://trac.osgeo.org/grass/ticket/4018

Any reason why to not upgrade ctypesgen before 8.0?

**Comment by lucadelu** [comment]
On Wed, 16 Jun 2021 at 11:36, Māris Nartišs ***@***.***>
wrote:

> There is a bug in Trac for moving 8.0 back to community ctypesgen:
> https://trac.osgeo.org/grass/ticket/3900
> There was also some discussion regarding ctypesgen upgrade here:
> https://trac.osgeo.org/grass/ticket/4018
>
> Any reason why to not upgrade ctypesgen before 8.0?
>
yes, this is a good idea

-- 
ciao
Luca

www.lucadelu.org

**Comment by petrasovaa** [comment]
> There is a bug in Trac for moving 8.0 back to community ctypesgen:
> https://trac.osgeo.org/grass/ticket/3900
> There was also some discussion regarding ctypesgen upgrade here:
> https://trac.osgeo.org/grass/ticket/4018
> 
> Any reason why to not upgrade ctypesgen before 8.0?

I am for upgrade, but last time I looked at it, it was just not straightforward as I hoped. But I am no expert on this.

**Comment by nilason** [comment]
> There is a bug in Trac for moving 8.0 back to community ctypesgen:
> https://trac.osgeo.org/grass/ticket/3900
> There was also some discussion regarding ctypesgen upgrade here:
> https://trac.osgeo.org/grass/ticket/4018

Good, I vaguely recall their existence, thanks for the links!


>> Any reason why to not upgrade ctypesgen before 8.0?

> I am for upgrade, but last time I looked at it, it was just not straightforward as I hoped. But I am no expert on this.

Would be good if feasible, I put up a draft PR #1651 for easy comparison of changes. Please take a look. There are likely fixes to our version that need to be pushed upstream for things to work.
