### ISSUE TITLE
Save display to named region broken in 7.9/8.0

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1679]
**Describe the bug**
Trying to save display geometry to named region generates an error

**To Reproduce**
Click on menu button in display to save display to a named region. Generates following error in console:

```
Traceback (most recent call last):
  File "/Applications/GRASS-7.9.app/Contents/Resources/gui/w
xpython/mapdisp/frame.py", line 1524, in OnSaveDisplayRegion

self.MapWindow.SaveRegion(display=True)
  File "/Applications/GRASS-7.9.app/Contents/Resources/gui/w
xpython/mapwin/buffered.py", line 2152, in SaveRegion

dlg = SavedRegion(parent=self, title=title, loadsave="save")
  File "/Applications/GRASS-7.9.app/Contents/Resources/gui/w
xpython/gui_core/dialogs.py", line 633, in __init__

sizer.Add(
wx._core
.
wxAssertionError
:
C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at
/Users/runner/miniforge3/conda-bld/wxpython_1616628568892/wo
rk/ext/wxWidgets/src/common/sizer.cpp(2147) in DoInsert():
Vertical alignment flags are ignored in vertical sizers
```

- Operating System: Mac
- GRASS GIS version 7.9 compiled 5 May 2021
- details about further software components
version=7.9.dev
date=2021
revision=515095365
build_date=2021-05-05
build_platform=x86_64-apple-darwin20.4.0
build_off_t_size=8
libgis_revision=61d6f8c7d
libgis_date=2021-05-05T20:46:27+00:00
proj=7.1.1
gdal=3.1.4
geos=3.8.1
sqlite=3.35.4
--->

**Additional context**

**Comment by cmbarton** [comment]
Thanks. I'll recompile and test.

**Comment by cmbarton** [comment]
Tested in GRASS 8. Works as expected. Thanks.

**Comment by nilason** [comment]
> Tested in GRASS 8. Works as expected. Thanks.

Great!
