### ISSUE TITLE
[Bug] Use -std=c99 for centos:7 build

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass#1709]
As C99 is now considered to be OK, we need to adjust our automatic tests to accept C99 (should it be -std=gnu99 to match other tests?). This change is only needed if GRASS is compiled with GCC older than 5.1.0.
From GitHub automatic build error log (PR #1501):
```
iclass_signatures.c:52:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (unsigned int i = refer->nfiles; i--;) {
     ^
iclass_signatures.c:52:5: note: use option -std=c99 or -std=gnu99 to compile your code
```

**Comment by nilason** [comment]
I stumbled upon this too in https://github.com/OSGeo/grass/pull/1401#issuecomment-784599235.

**Comment by marisn** [comment]
It seems that we must upgrade autotools to more recent version where automatic switch to C11 is done by default. Although a separate check to fail if compiler does not support C11 might be needed.

**Comment by wenzeslaus** [comment]
We can also switch to CentOS 8 if that helps or follow CentOS Stream (I'm not sure how useful testing on latest CentOS is) or remove the CentOS build completely (it is partially Conda anyway, so again, I'm not sure if it is worth it, it seemed like the only way when I initially wrote it). Opinions?

**Comment by marisn** [comment]
There is a workaround in the master. Closing as autotools upgrade is tracked in #560
