### ISSUE TITLE
[Feat] New splash screen for 8.0.0 (post ideas here)

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#1716]
It is time to change the splash screen for GUI.

Submit your ideas here. Attache files to your comment or open a PR and show the image from it here using Markdown.

Use GitHub thumbs up, down, etc. at will to show your preference.

## Old splash screens

These are FYI, not entering the competition.

### 6.4

![6.4 silesia](https://raw.githubusercontent.com/OSGeo/grass-legacy/releasebranch_6_4/gui/images/silesia_splash.png)

### 7.0

![7.0 grass world lowercase](https://raw.githubusercontent.com/OSGeo/grass/releasebranch_7_0/gui/images/splash_screen.png)

### 7.2 - 7.8

![7.2 grass world uppercase](https://raw.githubusercontent.com/OSGeo/grass/releasebranch_7_2/gui/images/splash_screen.png)

## See also

https://grass.osgeo.org/about/brand/
https://grasswiki.osgeo.org/wiki/Identity#GRASS_GIS_Splash_screen
https://grasswiki.osgeo.org/wiki/GRASS_Logo

**Comment by wenzeslaus** [comment]
Here is my suggestion. Keeping many ideas from the current splash image, but focusing on the logo and text rather than the background image. The background image is from my personal archive. The GRASS GIS text (with custom spacing) comes from the SVG logo on the website (which has only vectorized font version). Unlike the current splash image, this is using Fira Sans also for the motto text.

![grass_gis_with_bg_4](https://user-images.githubusercontent.com/5449060/124856015-d3a76f80-df77-11eb-8a5b-056e42594450.png)

**Comment by lindakladivova** [comment]
> Here is my suggestion. Keeping many ideas from the current splash image, but focusing on the logo and text rather than the background image. The background image is from my personal archive. The GRASS GIS text (with custom spacing) comes from the SVG logo on the website (which has only vectorized font version). Unlike the current splash image, this is using Fira Sans also for the motto text.
> 
> ![grass_gis_with_bg_4](https://user-images.githubusercontent.com/5449060/124856015-d3a76f80-df77-11eb-8a5b-056e42594450.png)

I like your idea Vashek :-) but maybe it would be nice to have it more similar to the logo on the main GRASS website? I would suggest to let the layout (maybe make the whole logo rectangular a bit smaller) but change colors -  the text could be in black and grasses lighter and yellower - exactly as we know it from the website. What the grassy hungry cow thinks about it? :-)

From a different point of view - now the background also seems to me a bit disturbing, first I noticed the background, and then I read the text. But this is my personal feeling, probably everyone perceives it differently.

**Comment by veroandreo** [comment]
Following Linda's suggestion, I was playing a bit using the website banner image as background, but sort of following Vaclav design that I like a lot. Here's what I got:

![splash_screen_vero_1](https://user-images.githubusercontent.com/20075188/124991243-ae7f3380-e041-11eb-8710-86a2f1c0791e.png)

![splash_screen_vero_3](https://user-images.githubusercontent.com/20075188/124991259-b3dc7e00-e041-11eb-8875-9524efcda901.png)

(I do not know if there's a rule for having the motto there too, it just didn't look nice to me so I removed)

**Comment by lucadelu** [comment]
> Following Linda's suggestion, I was playing a bit using the website banner image as background, but sort of following Vaclav design that I like a lot. Here's what I got:
> 
> ![splash_screen_vero_1](https://user-images.githubusercontent.com/20075188/124991243-ae7f3380-e041-11eb-8710-86a2f1c0791e.png)
> 
> ![splash_screen_vero_3](https://user-images.githubusercontent.com/20075188/124991259-b3dc7e00-e041-11eb-8875-9524efcda901.png)
> 
> (I do not know if there's a rule for having the motto there too, it just didn't look nice to me so I removed)

The background is too clear and the white text is not simple to read, try to change the text color or add a border to the text

**Comment by petrasovaa** [comment]
> The background is too clear and the white text is not simple to read, try to change the text color or add a border to the text

Or dim the image, like in @wenzeslaus suggestion. I like the foreground text/logo in @wenzeslaus's suggestion more, I like having the motto there especially because we don't have it now on the startup screen. As for the bg image, I am open to both options as long as the foreground is readable.

**Comment by veroandreo** [comment]
I changed dimensions a bit to keep the darker part and adjusted the light/shadows a bit, but it's tricky since the image itself has a lot of sunshine. Anyway, I had fun with inkscape and the svg is available if you want to adjust light differently (I found that it also changes according to monitor settings, so I don't know how you'll see them).

![splash_screen_vero_4](https://user-images.githubusercontent.com/20075188/125092558-c0a8b280-e0d1-11eb-823b-4e309d198fc4.png)
![splash_screen_vero_5](https://user-images.githubusercontent.com/20075188/125092567-c3a3a300-e0d1-11eb-8f60-b2917dd14762.png)

**Comment by lindakladivova** [comment]
> > Here is my suggestion. Keeping many ideas from the current splash image, but focusing on the logo and text rather than the background image. The background image is from my personal archive. The GRASS GIS text (with custom spacing) comes from the SVG logo on the website (which has only vectorized font version). Unlike the current splash image, this is using Fira Sans also for the motto text.
> > ![grass_gis_with_bg_4](https://user-images.githubusercontent.com/5449060/124856015-d3a76f80-df77-11eb-8a5b-056e42594450.png)
> 
> I like your idea Vashek :-) but maybe it would be nice to have it more similar to the logo on the main GRASS website? I would suggest to let the layout (maybe make the whole logo rectangular a bit smaller) but change colors - the logo could be in black and grasses in the background lighter and yellower - exactly as we know it from the website. What the grassy hungry cow thinks about it? :-)
> 
> From a different point of view - now the background also seems to me a bit disturbing, first I noticed the background, and then I read the text. But this is my personal feeling, probably everyone perceives it differently.

I'm also sending one suggestion. Unfortunately, I couldn't find the FiraSans text type in Inkscape... :(, if any of you know how to do it, I'd be happy for advice :-)
![logo3](https://user-images.githubusercontent.com/49241681/125113888-83e8b580-e0e9-11eb-9ab6-cfc090d6e8f4.png)

**Comment by baharmon** [comment]
I prefer either @wenzeslaus or @veroandreo 's versions. The motto is okay, but it makes it more cluttered. I think it looks best without the motto and with the GRASS GIS text aligned horizontally with the center of the logo. @veroandreo 's earlier version were to bright and the later versions a bit too dark, but heading in a promising direction. Adding boxes around the text looks bad. 

@lindakladivova Hi Linda, do you have Fira Sans installed? If you haven't, then [download Fira](https://github.com/mozilla/Fira/releases/tag/4.202)m, install it, and then try Inkscape.

**Comment by lindakladivova** [comment]
> I prefer either @wenzeslaus or @veroandreo 's versions. The motto is okay, but it makes it more cluttered. I think it looks best without the motto and with the GRASS GIS text aligned horizontally with the center of the logo. @veroandreo 's earlier versions were too bright and the later versions a bit too dark, but heading in a promising direction. Adding boxes around the text looks bad.
> 
> @lindakladivova Hi Linda, do you have Fira Sans installed? If you haven't, then [download Fira](https://github.com/mozilla/Fira/releases/tag/4.202)m, install it, and then try Inkscape.

Hi Brendan, thank you, now I got it installed :-) I am sending the variant with Fira Sans and without a box.
![logo4](https://user-images.githubusercontent.com/49241681/125134397-9d005f00-e107-11eb-809f-6a160e5e59c3.png)
The motion is to have a very similar appearance as the website has... but I also like @veroandreo 's and @wenzeslaus suggestions!
I think all proposals with nice grassy backgrounds will suit well and will be catchy. :-)

**Comment by veroandreo** [comment]
Here my last attempt considering @baharmon suggestion too. I adjusted light and shadows differently now  (I'm not proficient in Inkscape ;)):

![image1063-3-3](https://user-images.githubusercontent.com/20075188/125174592-c0d6aa00-e1c6-11eb-88ce-2ee30dcaf96c.png)

**Comment by lindakladivova** [comment]
> Here my last attempt considering @baharmon suggestion too. I adjusted light and shadows differently now  (I'm not proficient in Inkscape ;)):
> 
> 
> 
> ![image1063-3-3](https://user-images.githubusercontent.com/20075188/125174592-c0d6aa00-e1c6-11eb-88ce-2ee30dcaf96c.png)
> 
> 

Looks much more positive! 🤗

**Comment by lucadelu** [comment]
> 
> Hi Brendan, thank you, now I got it installed :-) I am sending the variant with Fira Sans and without a box.
> ![logo5](https://user-images.githubusercontent.com/49241681/125136622-7e03cc00-e10b-11eb-8de7-70f97a0deb0f.png)
> 

I really like this proposal, probably I would reduce a little bit the GRASS logo until it not break the black border of the box.

**Comment by petrasovaa** [comment]
> Here my last attempt considering @baharmon suggestion too. I adjusted light and shadows differently now (I'm not proficient in Inkscape ;)):
> 
> ![image1063-3-3](https://user-images.githubusercontent.com/20075188/125174592-c0d6aa00-e1c6-11eb-88ce-2ee30dcaf96c.png)

I like the darker one little bit more, but this is nice too.

**Comment by petrasovaa** [comment]
> > Hi Brendan, thank you, now I got it installed :-) I am sending the variant with Fira Sans and without a box.
> > ![logo5](https://user-images.githubusercontent.com/49241681/125136622-7e03cc00-e10b-11eb-8de7-70f97a0deb0f.png)
> 
> I really like this proposal, probably I would reduce a little bit the GRASS logo until it not break the black border of the box.

I prefer the white versions of the logo, the green in the logo doesn't look too good together with the background I think, and also the white makes it look more modern than the black.

**Comment by wenzeslaus** [comment]
See that a broken line in the bottom is part of [the official standard logo](https://grass.osgeo.org/about/brand/). That's what Vincent's [identity](https://grasswiki.osgeo.org/wiki/Identity) proposals including selected 7.0/7.2 splash screen images have.

![Plain logo](https://grass.osgeo.org/images/logos/grassgis_logo_colorlogo_text_whitebg.png)

**Comment by lindakladivova** [comment]
> 
> 
> > Here my last attempt considering @baharmon suggestion too. I adjusted light and shadows differently now (I'm not proficient in Inkscape ;)):
> > ![image1063-3-3](https://user-images.githubusercontent.com/20075188/125174592-c0d6aa00-e1c6-11eb-88ce-2ee30dcaf96c.png)
> 
> I like the darker one little bit more, but this is nice too.

The dark looks good but I am not sure whether is not too aggresive.

**Comment by tmszi** [comment]
![splash_screen](https://user-images.githubusercontent.com/50632337/125456886-fb47ad2c-04ed-4913-9a25-f3bd226d4713.png)

**Comment by veroandreo** [comment]
According to what we discussed in the las PSC-birthday meeting, here are my last 2 attempts:

a) darker version, complete lines
![splash_screen_darker_complete_lines](https://user-images.githubusercontent.com/20075188/127780662-f362a3ec-86c1-4547-a96c-13d9e8f807f7.png)

b) darker version, split lines and larger logo
![splash_screen_darker_cut_lines](https://user-images.githubusercontent.com/20075188/127780668-9073686b-c287-4231-8039-cbd6653fc31f.png)

**Comment by petrasovaa** [comment]
> According to what we discussed in the las PSC-birthday meeting, here are my last 2 attempts:
> 

+1 for b)

**Comment by baharmon** [comment]
Another +1 for option b

**Comment by neteler** [comment]
Also from my side +1 for b)

**Comment by SunveerSingh** [comment]
Hello Everyone, here is my idea: 
![Group 3](https://user-images.githubusercontent.com/33540878/128612239-02a31b43-99db-4141-87c4-ac1a97708924.png)

No use of any background or text and to be used without a background. Let me know what you guys think :)

**Comment by ReyGeomatics** [comment]
cool !!


ReyGeomatics 
Regards REYJAL Remy GIS.S F.T
C: 506.862.9581
***@***.***
Lat: 46.0913, long: -64.77065

**Comment by petrasovaa** [comment]
I like the idea of reversing the colors, but I think I would stick with Vero's latest suggestion for the splash screen. Maybe we could use this for something else.

**Comment by petrasovaa** [comment]
> > According to what we discussed in the las PSC-birthday meeting, here are my last 2 attempts:
> 
> +1 for b)

@veroandreo  seems we have some agreement here so I suggest to create a PR to not prolong this anymore. You will probably need to downscale it. The old files (gui/images/grass_splash.xcf.bz2 and grass_world3-nq8.png) can be removed.

Thanks to everyone!

**Comment by veroandreo** [comment]
Great! Thanks a lot everyone! 
I'll create the PR tonight and close this issue!
