### ISSUE TITLE
[Feat] Single-Window GUI:  Decide on the form of the GUI arrangement

### ISSUE THREAD

**Issue by lindakladivova** [OSGeo/grass#1747]
**Is your feature request related to a problem? Please describe.**
This Issue opens the place for the discussion. :-)
We still have a lot of work to do to create a Single-Window GUI, but I think it makes sense to open this Issue now so that everyone has enough time to share their thoughts.

As the result of this Issue, we should decide how the initial GUI startup will look like and we can also set up the further coding priorities.

Please, feel free to ask questions and express your preferences related to the Single-Window GUI in general. This is a good place for sharing it.

**Comment by lindakladivova** [comment]
I am suggesting here some ideas which came into my mind:

Idea 1:
All panes are visible immediately after startup:
![Screenshot from 2021-07-24 08-00-38](https://user-images.githubusercontent.com/49241681/126859227-c3c57d75-0e1f-4f35-8551-39d3eb0ddbff.png)

Idea 2:
The Console is in the bottom part, Modules and Python panes have their own notebook:
![Screenshot from 2021-07-24 08-03-42](https://user-images.githubusercontent.com/49241681/126859342-5440f980-9806-4d44-ad0a-09e98f9e2838.png)

Idea 3:
The Modules, Console, Python have their own notebook:
![Screenshot from 2021-07-24 08-04-42](https://user-images.githubusercontent.com/49241681/126859374-edc96948-6b09-4194-92eb-0e2070a501d8.png)

Idea 4:
The Modules, Console, Python panes are minimized:
![Screenshot from 2021-07-24 08-16-18](https://user-images.githubusercontent.com/49241681/126859448-14be0f92-aa73-4621-82e0-3e71b8fa0588.png)

**Comment by mlennert** [comment]
Just to make sure: we're talking about first startup ? Afterwards the user can define other defaults ?

I have a clear preference for options 3 and 4, as I think console and Python are already advanced use cases and should, therefore, not encumber the GUI at first startup.

In 4 it would be nice if there could be something more explicit than the small icons that there is something available. Either slightly larger icons (maybe longer vertically) with text, or possibly a button saying "open other windows", or something like that.

If that is not possible, I prefer 3.

**Comment by lindakladivova** [comment]
> 
> 
> Just to make sure: we're talking about first startup ? Afterwards the user can define other defaults ?
> 
Yes, all presented options (and of course others) are simply reachable by moving/docking given panes.

> I have a clear preference for options 3 and 4, as I think console and Python are already advanced use cases and should, therefore, not encumber the GUI at first startup.
> 
> In 4 it would be nice if there could be something more explicit than the small icons that there is something available. Either slightly larger icons (maybe longer vertically) with text, or possibly a button saying "open other windows", or something like that.
>
Yes, the fourth option seems to me also not suitable for the first startup, even though I believe that this option will be the standard way of using GRASS for many people.

> If that is not possible, I prefer 3.

**Comment by veroandreo** [comment]
For a first time user, yes, option 3 seems better, so they know which other panes are available.

**Comment by lindakladivova** [comment]
Is addressed here: https://github.com/OSGeo/grass/pull/1775

**Comment by lindakladivova** [comment]
Fully addressed by https://github.com/OSGeo/grass/pull/1775 and https://github.com/OSGeo/grass/pull/2216.
