### ISSUE TITLE
[Bug] r.compress returns EXIT_FAILURE incorrectly

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#1802]
**Describe the bug**
When recompressing data from one compression to another, everything works but you still get 
```
[1]   Exit 1                  r.compress SVI_2000_log
```

**To Reproduce**
```
r.compress elevation
echo $?
1
```

**Additional context**
Looks like the problem is here:
https://github.com/OSGeo/grass/blob/master/raster/r.compress/main.c#L99
The logic should be reverse, if one fails, it should report failure.

**Comment by Lucifergene** [comment]
@petrasovaa This would be my first contribution. 
Please assign this to me. I am working on it.

**Comment by petrasovaa** [comment]
Great, assigned!
