### ISSUE TITLE
[Feat] t.rast.mapcalc should support also absolute temporal type

### ISSUE THREAD

**Issue by landam** [OSGeo/grass#1843]
Steps to reproduce:

### Download Sentinel data 

```
i.sentinel.download producttype=S2MSI2A settings=sentinel.txt limit=1 output=data
```

### Import Sentinel data

```
i.sentinel.import -l input=data pattern="B(04|8A)_20m" register_output=sentinel-timestamps.txt
```

### Create space-time dataset & register data

```
t.create output=sen_tile_5606 title="Sentinel L2A 2021" desc="Tile 5606"
t.register input=sen_tile_5606 file=sentinel-timestamps.txt
```

### Extract 4 & 8 bands

```
t.rast.extract input=sen_tile_5606 where="name like '%B04%'" output=b4
t.rast.extract input=sen_tile_5606 where="name like '%B8A%'" output=b8
```

### Try to compute NDVI

```
t.rast.mapcalc input=b4,b8 output=ndvi expression="float(b8 - b4) / ( b8 + b4 )" basename=ndvi
```

The command fails with:

```
Starting temporal sampling...
ERROR: The temporal map type of the sample dataset must be interval
No samples found for map calculation
```

Note that changing `method` to `start` doesn't help as it could be expected.

**Comment by metzm** [comment]
The description of the issue seems wrong because `t.rast.mapcalc` does support absolute temporal type.

Maps in a stds can represent a time interval or a time instance, which is independent of absolute or relative time.

Reading through the docs and the code I found out that for `t.rast.mapcalc`, if several strds's are listed as input, "The first space time raster dataset that is listed as input will be used to temporally sample all other space time raster datasets." and in this case the first strds must span a time interval.

`t.rast.algebra` supports more temporal operators and functions, but should, according to the manual, also work with pure spatial mapcalc expressions like
```
t.rast.algebra basename=ndvi expression="ndvi = float(S2_b8 - S2_b4) / ( S2_b8 + S2_b4 )"
```
The `t.rast.mapcalc` equivalent would be, using band references:
```
t.rast.mapcalc inputs=test.S2_8,test.S2_4 output=ndvi basename=ndvi \
     expression="float(test.S2_8 - test.S2_4) / (test.S2_8 + test.S2_4)"
```
with only a single strds "test" as input.

**Comment by landam** [comment]
You are right @metzm. Closing this issue as invalid.

**Comment by veroandreo** [comment]
Then, the example in the manual page of t.rast.mapcalc should be fixed to: 

```
t.rast.mapcalc inputs=test output=ndvi basename=ndvi \
     expression="float(test.S2_8 - test.S2_4) / (test.S2_8 + test.S2_4)"
```

right? (maybe with a nicer name than just test too :-))

**Comment by metzm** [comment]
> Then, the example in the manual page of t.rast.mapcalc should be fixed to:
> 
> ```
> t.rast.mapcalc inputs=test output=ndvi basename=ndvi \
>      expression="float(test.S2_8 - test.S2_4) / (test.S2_8 + test.S2_4)"
> ```
> 
> right? (maybe with a nicer name than just test too :-))

I think the current example is correct: if you want to refer to specific bands in a strds as input, you need to append the bands separated by a dot to the input strds as in `t.rast.mapcalc inputs=test.S2_8,test.S2_4 ...`. In theory, something like `t.rast.mapcalc inputs=test.ndvi,test.mask ...` should also work, e.g. to apply a mask for each scene to the ndvi for each scene.

But something like
```
t.rast.mapcalc inputs=test output=ndvi basename=ndvi \
     expression="float(test.S2_8 - test.S2_4) / (test.S2_8 + test.S2_4)"
```
seems more intuitive, however it is not implemented this way.

Band references are IMHO still experimental and would need some attention.

**Comment by veroandreo** [comment]
> > Then, the example in the manual page of t.rast.mapcalc should be fixed to:
> > ```
> > t.rast.mapcalc inputs=test output=ndvi basename=ndvi \
> >      expression="float(test.S2_8 - test.S2_4) / (test.S2_8 + test.S2_4)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > right? (maybe with a nicer name than just test too :-))
> 
> I think the current example is correct: if you want to refer to specific bands in a strds as input, you need to append the bands separated by a dot to the input strds as in `t.rast.mapcalc inputs=test.S2_8,test.S2_4 ...`. In theory, something like `t.rast.mapcalc inputs=test.ndvi,test.mask ...` should also work, e.g. to apply a mask for each scene to the ndvi for each scene.
> 
> But something like
> 
> ```
> t.rast.mapcalc inputs=test output=ndvi basename=ndvi \
>      expression="float(test.S2_8 - test.S2_4) / (test.S2_8 + test.S2_4)"
> ```
> 
> seems more intuitive, however it is not implemented this way.
> 
> Band references are IMHO still experimental and would need some attention.

Indeed. I still don't get how to work with them really and integrate them into my regular image analysis and time series workflows.
 
Thanks for the explanation. I got confused when you earlier said "with only a single strds "test" as input."
