### ISSUE TITLE
The repository's Sponsor button points to PayPal

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass#1864]
The repository's Sponsor button points to the [(old?) PayPal account](https://www.paypal.com/pools/c/86YKZiIEPV). Shouldn't it be updated to point to [opencollective.com/grass](https://opencollective.com/grass)?

**Comment by wenzeslaus** [comment]
I think the best procedure is: Open a PR changing [.github/FUNDING.yml](https://github.com/OSGeo/grass/blob/main/.github/FUNDING.yml) and ask @mlennert for review.
