### ISSUE TITLE
[Bug] GRASS misses GDAL dynamic library references on Windows

### ISSUE THREAD

**Issue by jef-n** [OSGeo/grass#1872]
There are explicit references to GDAL DLL  that miss versions above GDAL 3.0 on Windows: https://github.com/OSGeo/grass/blob/75dd60a694198f7bca17b7e3d6387b6eefa9bb7a/lib/raster/gdal.c#L119

See also qgis/QGIS#45079

**Comment by nilason** [comment]
Related issue #326 (in particular see rouault's https://github.com/OSGeo/grass/issues/326#issuecomment-619612799).
The big question, why is that part (`lib/raster/gdal.c`) needed at all?

**Comment by ninsbl** [comment]
This obviously affects several modules (https://lists.osgeo.org/pipermail/grass-dev/2021-October/095447.html). Therefore, I take the liberty to set the priority to blocker...

**Comment by hellik** [comment]
> 
> 
> This obviously affects several modules (https://lists.osgeo.org/pipermail/grass-dev/2021-October/095447.html). Therefore, I take the liberty to set the priority to blocker...

a quick rescue 7.8.7 release needed?

**Comment by ninsbl** [comment]
Given that this is an MS Windows only issue and GRASS code is currently patched in OSGeo4W anyway, I hope we can avoid a 7.8.7 release...
Therefore I made a PR to OSGeo4W.

But it would be great if a core dev with the right skills could have a shot at a proper fix in the main code base...

**Comment by wenzeslaus** [comment]
The proper fix according to the last comment in #326 means just removing all that code, no? Or is there something else needed to use the standard linking mechanism; it is probably used for all other libraries already.

**Comment by nilason** [comment]
FWIW, I removed the gdal patch for macports for the 7.8.6 release, therefore I assume gdal is working fully dynamically. Yet so far there has been no complaints reported. In addition, the official mac binary is also built in similar way, without any issues I’m aware of.  Seems to me #326 is not addressing any actual problem (at least not anymore). No idea how/why/if at all this is a problem on windows or elsewhere.

**Comment by nilason** [comment]
Quick browse through history seems to link this to `r.external` And `GDAL_LINK `.  Hope to get some time to dig into this. Anyone recollects anything on the history on this?

**Comment by neteler** [comment]
The easiest way to look up the history of `lib/raster/gdal.c` might be here:

https://trac.osgeo.org/grass/log/grass/trunk/lib/raster/gdal.c

which points to (note the different path, initially it was part of `lib/gis/`)

https://trac.osgeo.org/grass/log/grass/trunk/lib/gis/gdal.c?rev=34748

(in GitHub somewhere here: https://github.com/OSGeo/grass-legacy/commits/develbranch_6/lib/gis/gdal.c but the navigation in SVN seems to be easier for these old files)

Related discussion:

- GRASS raster "live links" proposal:
   - https://lists.osgeo.org/pipermail/grass-dev/2008-August/039550.html
   - https://trac.osgeo.org/grass/browser/grass/branches/releasebranch_5_4/gips/gip-0002.txt (Date: 2003-05-15)
- Initial code posting by Glynn Clements:
   - https://lists.osgeo.org/pipermail/grass-dev/2008-August/039555.html
   - https://lists.osgeo.org/pipermail/grass-dev/2008-August/039567.html
- Followup discussion: https://lists.osgeo.org/pipermail/grass-dev/2008-August/thread.html#39571

**Comment by nilason** [comment]
@neteler Thanks!

**Comment by ninsbl** [comment]
Hm. The latest GDAL runtime dependency defined for GRASS GIS in OSGeo4W is now 3.0.4, while the list of dlls here ends with 3.0.3. So,  these predefined links are outdated again.
A proper fix would be really appreciated.

**Comment by neteler** [comment]
> A proper fix would be really appreciated.

Does anyone know *how* to implement a proper fix? How is it addressed in other software packages?

**Comment by jef-n** [comment]
> Does anyone know _how_ to implement a proper fix? How is it addressed in other software packages?

Why is there GDAL_DYNAMIC to start with?  To have grass_raster work even if GDAL is not installed?   Or to make it work even with a different installed version of GDAL if one in installed?   That implies that the ABI didn't change - radically different from grass_gis, which will even refuse to work if a different commit of the same GRASS version is used.

If it would just link against GDAL it would still use the shared object/dll it was built with (just like v.in.ogr) and complain about a missing one if it's not available - just like now if the available one is not older - and that would fix itself by rebuilding against the available version.
