### ISSUE TITLE
[Feat] OSGeo4W batch files for Python scripts and sh.exe support

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#1906]
**Is your feature request related to a problem? Please describe.**
Currently, we create a bunch of wrapper batch files for Python scripts. Why don't we simply set `PATH=%PATH%;C:\OSGeo4W\...\scripts` and `PATHEXT=%PATHEXT%;.PY`? This way, we don't have to type `.py`, but Windows will take care of calling Python properly without wrapper batch files.

The above question is for GRASS running on `cmd.exe`, which is typical.

Now, I want to support GRASS running on `sh.exe` so I don't have to worry about the differences in command lines between Linux and Windows. `GRASS_SH` code is already there in `env.bat` and `grass.py`, but simply uncommenting the `GRASS_SH` line from `env.bat` doesn't work because there are no wrapper shell scripts for `*.py`. I couldn't find a way to call `*.py` scripts without the extension from `sh.exe`. Setting `$PATHEXT` didn't work.

Ideally, I want to support both `cmd.exe` and `sh.exe` from one installation.
* Renamed `scripts/v.db.addtable.py` to `scripts/v.db.addtable` and fixed the path in `bin/v.db.addtable.bat`: I got this error first and it worked from both `cmd.exe` and `sh.exe` (NOT usable)
![image](https://user-images.githubusercontent.com/7456117/135344160-2a28b1e8-e63c-42d3-9222-6713aa7ab97c.png) 
* Deleted `bin/v.db.addtable.bat` and created `bin/v.db.addtable` (just `"$GRASS_PYTHON" "$GISBASE/scripts/v.db.addtable.py" "$@"`), then added `C:\OSGeo4W64\...\grass\scripts` to `PATH` before `bin` (so `cmd.exe` finds `v.db.addtable.py` first): Worked from both `cmd.exe` and `sh.exe`

**Describe the solution you'd like**
* Don't create wrapper batch files for Python scripts
* Instead, set `PATHEXT=%PATHEXT%;.PY` and add `scripts` to `PATH` before `bin` for `cmd.exe`
* Create new shell scripts in `bin` for `sh.exe`

**Describe alternatives you've considered**

**Additional context**

**Comment by HuidaeCho** [comment]
OK.. I got it. It's the association. The default Python interpreter is not necessarily the OSGeo4W Python. So I guess I need both batch and shell scripts. :-(

**Comment by hellik** [comment]
> OK.. I got it. It's the association. The default Python interpreter is not necessarily the OSGeo4W Python. So I guess I need both batch and shell scripts. :-(

Yes.  There are so many flavours how Windows and python may be configured out there in the wild. 

AFAIR there was a discussion on the dev ML back then when all scripts have been converted from shell to python. and pathext we've experimented with.

**Comment by hellik** [comment]
Why do you want to create new shell scripts in bin for sh.exe in Windows?

One of the reason to switch to python was to be platform agnostic, wasn't it?

**Comment by hellik** [comment]
>This way, we don't have to type .py

at the moment you don't have to type  .py,  just the script name without any extension, the same like a binary module e.g. g.region.

**Comment by HuidaeCho** [comment]
> Why do you want to create new shell scripts in bin for sh.exe in Windows?

Because we cannot run batch files from sh.exe.

**Comment by hellik** [comment]
> > Why do you want to create new shell scripts in bin for sh.exe in Windows?
> 
> Because we cannot run batch files from sh.exe.

Than it's a limitation of sh.exe and not of winGRASS

**Comment by HuidaeCho** [comment]
> Than it's a limitation of sh.exe and not of winGRASS

Then winGRASS only supports sh.exe partially and we should delete the GRASS_SH code (?) because we cannot run scripts.

**Comment by hellik** [comment]
> > Than it's a limitation of sh.exe and not of winGRASS
> 
> Then winGRASS only supports sh.exe partially and we should delete the GRASS_SH code (?) because we cannot run scripts.

@landam @ninsbl  any opinion  ?

**Comment by HuidaeCho** [comment]
Check this screenshot:
![image](https://user-images.githubusercontent.com/7456117/135444638-6d7c2c36-74ea-40d9-849d-6217e39d5b0a.png)

Basically, my goal is to support `sh.exe` (GNU bash) *fully* on Windows so we don't have to worry about any differences in command lines between Linux bash and (somehow limited?) Windows `cmd.exe`. `env.bat` and `grass.py` already support `GRASS_SH` and the only missing part is shell wrappers, just like batch wrappers for `cmd.exe`.

Even simple multi-line commands are different: `\` for `sh.exe`, but `^` for `cmd.exe`

**Comment by hellik** [comment]
![grafik](https://user-images.githubusercontent.com/12000843/135447378-3c7653e4-990b-4316-9250-51cef29477a2.png)

at least here in my OSGeo4W vers 2 setup environment, shell isn't available any more.

**Comment by hellik** [comment]
>using the manuals that are mostly written for UN*X.

IMHO, in a long term perspective, the manuals should be more platform agnostic

**Comment by hellik** [comment]
>Even simple multi-line commands are different: \ for sh.exe, but ^ for cmd.exe

not sure that it's winGRASS duty to overcome OS differences and flaws.

**Comment by HuidaeCho** [comment]
> more platform agnostic

Agreed and that would be ideal, but oftentimes, it's just not practical to implement/run everything in Python. That usually involves more coding.

**Comment by HuidaeCho** [comment]
> not sure that it's winGRASS duty to overcome OS differences and flaws.

Maybe, you're right, but IMHO having a consistent cross-platform CLI would be great for GRASS users in general.

**Comment by HuidaeCho** [comment]
> at least here in my OSGeo4W vers 2 setup environment, shell isn't available any more.

I think `sh.exe` is part of the msys package:
![image](https://user-images.githubusercontent.com/7456117/135449575-5ee23827-acc6-4719-a643-c581bebdcd53.png)

**Comment by hellik** [comment]
> 
> 
> > not sure that it's winGRASS duty to overcome OS differences and flaws.
> 
> Maybe, you're right, but IMHO having a consistent cross-platform CLI would be great for GRASS users in general.

yep.

here in the [wiki](https://grasswiki.osgeo.org/wiki/GRASS_and_windows_console), I've added some simple examples how you do windows command line working; and yes, in *nix all is a little bit smoother ... ;-D

**Comment by hellik** [comment]
> 
> 
> > at least here in my OSGeo4W vers 2 setup environment, shell isn't available any more.
> 
> I think `sh.exe` is part of the msys package: ![image](https://user-images.githubusercontent.com/7456117/135449575-5ee23827-acc6-4719-a643-c581bebdcd53.png) ![image](https://user-images.githubusercontent.com/7456117/135449703-40382f7b-0c0a-4d8a-9e0b-5d3bc0728bba.png)

![grafik](https://user-images.githubusercontent.com/12000843/135450022-a5f81c4f-5bec-42ad-87cb-f257257b5286.png)

not yet/not anymore maintained in OSGeo4W  vers 2.:

http://download.osgeo.org/osgeo4w/v2/x86_64/release/

**Comment by HuidaeCho** [comment]
> here in the [wiki](https://grasswiki.osgeo.org/wiki/GRASS_and_windows_console), I've added some simple examples how you do windows command line working

That's a great tutorial! I'd like to add multi-line examples ;-).

My use case for this `sh.exe` support is... I want to teach GRASS GIS from my Linux laptop, obviously, and don't want to worry about new Windows-only students struggling with all this different syntax. From another perspective, let's say I just don't have access to a Windows machine for any reason...

**Comment by hellik** [comment]
>That's a great tutorial! I'd like to add multi-line examples ;-).

please go ahead! many more nice windows command line examples are very welcome :-)

**Comment by HuidaeCho** [comment]
> not yet/not anymore maintained in OSGeo4W vers 2.:

Oops! No...

**Comment by HuidaeCho** [comment]
I guess I don't want to upgrade my OSGeo4W for now :-(.

**Comment by HuidaeCho** [comment]
I tried some tricks and don't think that my idea is going to be easy to implement. I created separate folders for batch files and shell scripts, but `shutil.which()` was not able to find scripts without an extension (with a trailing `;` after `PATHEXT`). Even with a dirty patch to find scripts without an extension for `sh.exe`, calling these scripts from inside Python didn't work (understandable because Python is native and outside `sh.exe`) while the same scripts works from `sh.exe` directly. It's going to be so dirty if I really want it.. Not worth it..

My short-term solution is.. just use regular winGRASS and start `sh.exe` if I need bash. Then call `cmd /c script arguments...`.

**Comment by hellik** [comment]
>sh.exe if I need bash. Then call cmd /c batch arguments....

May you document it in the wiki? Thanks

**Comment by HuidaeCho** [comment]
> May you document it in the wiki?

I'll after some testing.

**Comment by HuidaeCho** [comment]
Just for my records... `cmd` required quoted strings in `sh.exe`, unlike in `cmd.exe`.
```bash
cmd() { $COMSPEC /c "$*"; }
cmd v.db.addtable help
```
I've tried other combinations:
* `cmd() { $COMSPEC /c $*; }`
* `cmd() { $COMSPEC /c "$@"; }` <- it should work, right?
* `cmd() { $COMSPEC /c $@; }`
These three functions just started `cmd.exe` without executing anything.

**Comment by landam** [comment]
> Oops! No... The maintainer was our @landam (https://trac.osgeo.org/osgeo4w/wiki/pkg-msys). He should know?

Currently I don't have any plan to introduce `msys` to osgeo4w v2. Feel free to do it if you feel that it's important for you. Thanks for understanding.

**Comment by HuidaeCho** [comment]
> > Oops! No... The maintainer was our @landam (https://trac.osgeo.org/osgeo4w/wiki/pkg-msys). He should know?
> 
> Currently I don't have any plan to introduce `msys` to osgeo4w v2. Feel free to do it if you feel that it's important for you. Thanks for understanding.

Let me look into it. Do I have any good starting point like a GitHub repo or more information than the wiki page, how to make it available in the OSGeo4W installer, etc? Thanks!

**Comment by wenzeslaus** [comment]
...or there is another solution to this issue. You could also consider moving to Python for a uniform cross-platform scripting experience. For non-trivial commands, Python will likely be a better experience for students (ifs, for loops, output processing, ...). For trivial commands, such as `g.region -p`, anything will work including the Console tab in GUI.

**Comment by ninsbl** [comment]
> I tried some tricks and don't think that my idea is going to be easy to implement. I created separate folders for batch files and shell scripts, but `shutil.which()` was not able to find scripts without an extension (with a trailing `;` after `PATHEXT`).

I encountered the same issues when I tried to make the shell scripts in the unit-tests run on MS Windows. Here is what helped:
https://github.com/OSGeo/grass/blob/dde9939029f1bcdea3a050a0c190cd2ad354b2c9/mswindows/osgeo4w/build_osgeo4w.sh#L86-L100
and later:
https://github.com/OSGeo/grass/blob/dde9939029f1bcdea3a050a0c190cd2ad354b2c9/mswindows/osgeo4w/build_osgeo4w.sh#L179-L193

It is a dirty hack, but works...

**Comment by ninsbl** [comment]
> ...or there is another solution to this issue. You could also consider moving to Python for a uniform cross-platform scripting experience. 

I agree that, though often a bit more code, Python would be the most platform independend solution and it is becoming also more common among people that are not programers in the first place. 

There are two things that could make it more easy for students / newcomers to start with Python syntax right away:
1. the copy button in the GUI could copy the command in Python Syntax (or there could be alternative buttons for Python or shell) See also: https://trac.osgeo.org/grass/ticket/2226
2. Examples in the manual could be improved to be more like here: https://ncsu-osgeorel.github.io/grass-temporal-workshop/ where users can choose to follow the examples in shell or Python syntax. It would be quite some work to change that, and more to maintain, but it might help people to get started with GRASS and Python.

Then we would only have to decide if we would use PyGRASS (`Module()`) or GRASS Script syntax (`run_command()`)... ;-)

**Comment by HuidaeCho** [comment]
>     2\. Examples in the manual could be improved to be more like here

Maybe, we could write a Python module or invent a simple markup language that can understand our example markup code and spit out examples for different platforms or shells? Maybe, we can just use the bash syntax and write a simple script that can translate it to the batch syntax and create an additional tab in the manual?

**Comment by HuidaeCho** [comment]
Since the msys package that installs sh.exe mentioned originally is not maintained any longer and I found an alternative that can run both shell scripts and batch files, I'm closing this request.
