### ISSUE TITLE
[Bug] Win GRASS GIS 8.0 standalone installer doesn't use last code for compilation and installation

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass#1931]
**Describe the bug**
According GRASS GIS System info, code revision point to commit no.  https://github.com/OSGeo/grass/commit/3ad82d314f296652eeef379b9ccde1a3d46aec28 (committed on Aug 22). It seems that GRASS GIS compilation not use last code.

**To Reproduce**

1. Download [WinGRASS-8.0.dev-0-1-Setup-x86_64.exe](https://wingrass.fsv.cvut.cz/grass80/x86_64/WinGRASS-8.0.dev-0-1-Setup-x86_64.exe)
2. Install GRASS GIS 
3. Manually fix this issue https://github.com/OSGeo/grass/issues/1911
4. Launch GRASS GIS
5. On the GRASS GIS main window menu go to Help -> About system
6.  You get system info (check Code revision)

```
System Info                                                                     
GRASS version: 8.0.dev                                                          
Code revision: 3ad82d314                                                        
Build date: 2021-10-05                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.1.4                                                                     
PROJ: 6.3.2                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.17763-SP0 
``` 

**Expected behavior**
Use the latest code for compilation and installation.

**System description (please complete the following information):**

- Operating System: MS Windows
- GRASS GIS version 8.0.dev

**Comment by tmszi** [comment]
e.g. one of my merged commit https://github.com/OSGeo/grass/pull/1815/commits/219f4da7902144cdd0ee13beed8e525144407395 (from 26th August)  is not included in the installed source file `C:\Program Files\GRASS GIS 8.0\gui\wxpython\vdigit\mapwindow.py`

**Comment by landam** [comment]
@tmszi Please try new builds from `releasebranch_8_0` (no: 22+): https://wingrass.fsv.cvut.cz/grass80/x86_64/

**Comment by tmszi** [comment]
Thanks, It works as expected. The last commit https://github.com/OSGeo/grass/commit/c30d632c20e7b8519c834fc2b4c4d15d14bf3231 is included.
