### ISSUE TITLE
Improvements in the readme file

### ISSUE THREAD

**Issue by shubhamshah14102** [OSGeo/grass#1950]
Hi ,
There are scopes of improvements in the readme file .
An example being the statement "You can  locally generate the GRASS GIS Programmer's Manual."  conveys better than "You can generate locally the GRASS GIS Programmer's Manual".
Can you assign this issue to me so that I can make updations in the minute errors.

**Comment by ninsbl** [comment]
Hi @shubhamshah14102 , thanks for your suggestion. Looking forward to your PR with concrete suggestions like this.
