### ISSUE TITLE
[Bug] not all extensions available through g.extension

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass#1960]
**Describe the bug**
When using g.extension to fetch extension, not all extensions are available.

**To Reproduce**

1. Run g.extension -l  
2. Compare with list on https://grass.osgeo.org/grass78/manuals/addons/

**Expected behavior**
All extensions on the grass gis addon repository are available for installation using g.extension

**System description (please complete the following information):**

- Operating System: Windows 10, Linux Ubuntu 20.04
- GRASS GIS version 7.8.6, 8.0dev
<!---

**Comment by veroandreo** [comment]
I can confirm this behavior in fedora 34, both in 7.8 release branch and main

**Comment by neteler** [comment]
Will be fixed through https://github.com/OSGeo/grass-addons/pull/656

as there was a completely outdated `modules.xml` file (from 2020) in 

https://grass.osgeo.org/addons/grass7/

which I have replaced today.

New is the corresponding file in https://grass.osgeo.org/addons/grass8/ which is now also generated.

**Comment by ecodiv** [comment]
Great, thanks @neteler!  How is this file generated? Is this something that needs to be updated when a new addon is added?

**Comment by neteler** [comment]
> Great, thanks @neteler! How is this file generated? Is this something that needs to be updated when a new addon is added?

See my previous comment :) It is auto-generated, and now on the server itself (the former mechanism was broken for a long time).
