### ISSUE TITLE
GRASS GIS 8.0 wxGUI doesn't launch 

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass#1982]
**Describe the bug**
GRASS GIS 8.0 wxGUI doesn't launch.

**To Reproduce**

1. Download [Standalone Win GRASS GIS 8.0 installer](https://wingrass.fsv.cvut.cz/grass80/x86_64/WinGRASS-8.0.dev-7be7cf9b0-2-Setup.exe)
2. Install GRASS GIS
3. Try launch GRASS GIS 8.0 with wxGUI
4. You get error message

```
C:\Users\IEUser>ERROR: wxGUI requires wxPython. DLL load failed while importing _core: The specified module could not be found.
You can still use GRASS GIS modules in the command line or in Python.
```

**Expected behavior**
Launch GRASS GIS with wxGUI.

**System description (please complete the following information):**
- MS Windows 10 Enterprise Evaluation version as VirtualBox image obtained from official Microsoft page https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (on the page choose from Virtual Machines Select Box: MS Edge on Win 10 (x86_64) Stable 1809).
- Standalone [WinGRASS-8.0.dev-7be7cf9b0-2-Setup.exe installer](https://wingrass.fsv.cvut.cz/grass80/x86_64/WinGRASS-8.0.dev-7be7cf9b0-2-Setup.exe)

**Additional context**
```
C:\Users\IEUser>"C:\Program Files\GRASS GIS 8.0\Python39\python.exe" -c "import wx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\GRASS GIS 8.0\Python39\lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Program Files\GRASS GIS 8.0\Python39\lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ImportError: DLL load failed while importing _core: The specified module could not be found.
```

**Comment by neteler** [comment]
@hellik any idea here?

**Comment by hellik** [comment]
are the important MS runtimes DLLs installed?

**Comment by hellik** [comment]
now testing with: https://wingrass.fsv.cvut.cz/grass80/x86_64/WinGRASS-8.0.dev-7be7cf9b0-2-Setup.exe

**Comment by hellik** [comment]
> now testing with: https://wingrass.fsv.cvut.cz/grass80/x86_64/WinGRASS-8.0.dev-7be7cf9b0-2-Setup.exe

![grafik](https://user-images.githubusercontent.com/12000843/144116928-9e659241-19b8-4739-a0f7-dba2c37baf08.png)

here it works for me.

**Comment by hellik** [comment]
@landam https://wingrass.fsv.cvut.cz/grass80/x86_64/ it seems there are no updated standalone installer; the last is:

`WinGRASS-8.0.dev-7be7cf9b0-2-Setup.exe        2021-11-14 11:31  662M`

**Comment by tmszi** [comment]
> are the important MS runtimes DLLs installed?

Yes, I did not install it with this version. It works properly after installation.

**Comment by hellik** [comment]
> > are the important MS runtimes DLLs installed?
> 
> Yes, I did not install it with this version. It works properly after installation.

thanks for confirming it works after installing the runtimes. unfortunately, runtime DLL management is really a big mess in MS windows operating system.
