### ISSUE TITLE
[Bug] i.vi: The formula for the PVI computation is wrong

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass#1984]
**Describe the bug**

The formula should be `PVI = sin(a) * NIR - cos(a) * red`. However, the code used for the computation is `result = (sin(1) * nirchan) / (cos(1) * redchan)`

**Comment by neteler** [comment]
FWIW, here some interesting background discussion with explanations:

* https://forum.step.esa.int/t/pvi-index-which-formula-is-right/6416

**Comment by pesekon2** [comment]
@neteler: Yeah, I have seen that when I was checking my formula. Seems like this source and few others agree with the new formula; I think that the old one was just a typo using `/` instead of `-`. So I take it as agreed upon and will merge the PR (and backport it to 7.8).
