### ISSUE TITLE
Discussions' page header

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass#1996]
Can we modify the Discussions' page header/background? Something like in https://github.com/pytest-dev/pytest/discussions?discussions or more functional like https://github.com/github/feedback/discussions.

(I'd like to try the very cool https://svn.osgeo.org/grass/grass/trunk/gui/images/grass_world3-nq8.png image.)

**Comment by wenzeslaus** [comment]
See https://github.com/github/feedback/discussions/2896 for (not) changing the background image.

Functional thing is created by pinned comments, i.e., the thing on top is one or more pinned comments with GitHub-generated background.
