### ISSUE TITLE
Python distutils deprecated in 3.12

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#2016]
**Describe the bug**
With Python 3.10 I get a deprecation warning from g.extension
```
g.extension:167: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.dir_util import copy_tree
```

Alternatives would be `shutil.copytree()`, however only since Python 3.8 it takes additional argument `dirs_exist_ok` that we probably need, see https://stackoverflow.com/a/64340026/1058453 and note in g.extension (https://github.com/OSGeo/grass/blob/main/scripts/g.extension/g.extension.py#L1500)

**Comment by ninsbl** [comment]
Fixed with https://github.com/OSGeo/grass/pull/2592
