### ISSUE TITLE
[Bug]: wxGUI crash at launch: TypeError: ToolBar.AddTool(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2019]
I have upgraded my system to F35 today (moved here from #1971) and get a wxGUI crash at launch:

```
# G78
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/wx/core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/wxgui.py", line 83, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/lmgr/frame.py", line 143, in __init__
    self.notebook = self._createNoteBook()
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/lmgr/frame.py", line 365, in _createNoteBook
    self.datacatalog = DataCatalog(
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/datacatalog/catalog.py", line 45, in __init__
    self.toolbar = DataCatalogToolbar(parent=self)
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/datacatalog/toolbars.py", line 47, in __init__
    self.InitToolbar(self._toolbarData())
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/toolbars.py", line 123, in InitToolbar
    self.CreateTool(*tool)
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/toolbars.py", line 145, in CreateTool
    toolWin = self.AddLabelTool(tool, label, bitmap,
  File "/home/mneteler/software/grass78/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/wrap.py", line 434, in AddLabelTool
    return wx.ToolBar.AddTool(self, toolId=toolId, label=label, bitmap=bitmap, bmpDisabled=bmpDisabled,
TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: 'toolId' is not a valid keyword argument
  overload 2: argument 'toolId' has unexpected type 'WindowIDRef'
  overload 3: argument 'toolId' has unexpected type 'WindowIDRef'
```
and
```
G8:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/wx/core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/wxgui.py", line 88, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/lmgr/frame.py", line 153, in __init__
    self._createDataCatalog(self.notebook)
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/lmgr/frame.py", line 337, in _createDataCatalog
    self.datacatalog = DataCatalog(parent=parent, giface=self._giface)
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/datacatalog/catalog.py", line 67, in __init__
    self.toolbar = DataCatalogToolbar(parent=self)
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/datacatalog/toolbars.py", line 64, in __init__
    self.InitToolbar(self._toolbarData())
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/toolbars.py", line 119, in InitToolbar
    self.CreateTool(*tool)
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/toolbars.py", line 141, in CreateTool
    toolWin = self.AddLabelTool(
  File "/home/mneteler/software/grass_main/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/wrap.py", line 504, in AddLabelTool
    return wx.ToolBar.AddTool(
TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: 'toolId' is not a valid keyword argument
  overload 2: argument 'toolId' has unexpected type 'WindowIDRef'
  overload 3: argument 'toolId' has unexpected type 'WindowIDRef'
```

_Originally posted by @neteler in https://github.com/OSGeo/grass/issues/1971#issuecomment-993954837_

**Comment by petrasovaa** [comment]
See my reply in https://github.com/OSGeo/grass/issues/1971#issuecomment-994856311, you need newer wx. I just tested gui with Python 3.10 and wxPython 4.1 and it works.

**Comment by neteler** [comment]
Well, then I need to tell the wxPython maintainer in Fedora to cherry-pick the needed fix(es). For the time being it will remain wxPython 4.0: https://koji.fedoraproject.org/koji/packageinfo?packageID=26351

However, searching for the error messages above in the internet does not return any result. So I'm a bit lost here...
I also don't see any deprecate warning above.

**Comment by petrasovaa** [comment]
I believe it's this one:
https://github.com/wxWidgets/Phoenix/pull/1533

But in general, there are pretty big changes in 4.1, mainly due to using newer wxWidgets, so I recommend using 4.1 when possible. There are some wheels for (older) fedora here https://extras.wxpython.org/wxPython4/extras/linux/gtk3/.

**Comment by neteler** [comment]
(cross-linking a related Fedora ticket here: https://bugzilla.redhat.com/show_bug.cgi?id=1827788)

**Comment by wenzeslaus** [comment]
The piece of information which is missing in the Fedora ticket is that Fedora has latest Python release (3.10), but has old wxPython release. Either you need old Python and then wxPython 4.0 is fine, or you have Python 3.10, but then you need wxPython 4.1. Notably, the issue is not in how GRASS GIS uses wxPython.

**Comment by tmszi** [comment]
Actually under Fedora 35 with Python 3.10 version it possible build own wxPython 4.1.1 ([whl doesn't exist yet for Python 3.10](https://pypi.org/project/wxPython/4.1.1/#files))

```
[fedora@fedora35 ~]$ sudo dnf install -y gcc gcc-c++ gtk+-devel pipenv

[fedora@fedora35 ~]$ mkdir wxpy-4_1_1 && cd wxpy-4_1_1 && pipenv install wxPython

[fedora@fedora35 wx-4_1_1]$ pipenv shell

(wxpy-4_1_1) [fedora@fedora35 wxpy-4_1_1]$ python -c "import wx; print(wx.version())"
4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
```
But launch GRASS GIS 7.8.6 (installed from the official repository ) crash during wxGUI initialization (it seem bug related with Python 3.10 version and wxPython 4.1.1, same issue as #1971)

```
(wxpy-4_1_1) [fedora@fedora35 wxpy-4_1_1]$ grass78

Launching <wxpython> GUI in the background, please wait...
GRASS 7.8.6 (fire_grass6data):~/wx-4_1_1 > Traceback (most recent call last):
  File "/usr/lib64/grass78/gui/wxpython/wxgui.py", line 73, in OnInit
    splash = SC.AdvancedSplash(bitmap=introBmp,
  File "/home/fedora/.local/share/virtualenvs/wx-4_1_1-JAhJbCMk/lib64/python3.10/site-packages/wx/lib/agw/advancedsplash.py", line 251, in __init__
    self.SetTextFont()
  File "/home/fedora/.local/share/virtualenvs/wx-4_1_1-JAhJbCMk/lib64/python3.10/site-packages/wx/lib/agw/advancedsplash.py", line 442, in SetTextFont
    self._textfont.SetPointSize(self._textsize)
TypeError: Font.SetPointSize(): argument 1 has unexpected type 'float'
OnInit returned false, exiting...
```

```
GRASS 7.8.6 (fire_grass6data):~/wxpy-4_1_1 > g.version -g
version=7.8.6
date=2021
revision=exported
build_date=2021-11-07
build_platform=x86_64-redhat-linux-gnu
build_off_t_size=8
```

**Comment by petrasovaa** [comment]
> But launch GRASS GIS 7.8.6 (installed from the official repository ) crash during wxGUI initialization (it seem bug related with Python 3.10 version and wxPython 4.1.1, same issue as #1971)
> 
> ```
> (wxpy-4_1_1) [fedora@fedora35 wxpy-4_1_1]$ grass78
> 
> Launching <wxpython> GUI in the background, please wait...
> GRASS 7.8.6 (fire_grass6data):~/wx-4_1_1 > Traceback (most recent call last):
>   File "/usr/lib64/grass78/gui/wxpython/wxgui.py", line 73, in OnInit
>     splash = SC.AdvancedSplash(bitmap=introBmp,
>   File "/home/fedora/.local/share/virtualenvs/wx-4_1_1-JAhJbCMk/lib64/python3.10/site-packages/wx/lib/agw/advancedsplash.py", line 251, in __init__
>     self.SetTextFont()
>   File "/home/fedora/.local/share/virtualenvs/wx-4_1_1-JAhJbCMk/lib64/python3.10/site-packages/wx/lib/agw/advancedsplash.py", line 442, in SetTextFont
>     self._textfont.SetPointSize(self._textsize)
> TypeError: Font.SetPointSize(): argument 1 has unexpected type 'float'
> OnInit returned false, exiting...
> ```

Right, it looks like that one was fixed 2 days ago:
https://github.com/wxWidgets/Phoenix/pull/2039/files#diff-2537211974747ccfd5758e02d7775fe899ab7e1b8e47ce5a6caf9275713d66b5

@neteler I suggest closing this

**Comment by neteler** [comment]
> Actually under Fedora 35 with Python 3.10 version it possible build own wxPython 4.1.1 ([whl doesn't exist yet for Python 3.10](https://pypi.org/project/wxPython/4.1.1/#files))

This is really cool, thanks for having posted the wxPython 4.1.1  installation instructions!
Now the wxGUI starts.

**Comment by danhox** [comment]
the build of wxpython don't work. I launch it many time but without result

**Comment by tmszi** [comment]
> the build of wxpython don't work. I launch it many time but without result

The compilation doesn't seem to be successful. Could you provide more information (compilation error message)?

**Comment by danhox** [comment]
There is not any compilation. The compilation does not finish. 
file:///home/danhoneuba/Images/Capture%20d%E2%80%99%C3%A9cran%20du%202021-12-21%2013-17-19.png

**Comment by danhox** [comment]
I use pip install -U wxpython

**Comment by tmszi** [comment]
> There is not any compilation. The compilation does not finish. file:///home/danhoneuba/Images/Capture%20d%E2%80%99%C3%A9cran%20du%202021-12-21%2013-17-19.png

The installation process `pip install -U wxpython`  first compile (compilation output is not visible to the user terminal in this case) the wxPython source code and then install it. Compiling wxPython takes quite a long time, depending on the performance of your computer, the number of processor cores.

**Comment by tmszi** [comment]
I'm build binary wxPython 4.1.1 whl file (easy installation, which doesn't require compile wxPython from source code) for Python 3.10. 

Size of binary wxPython-4.1.1-cp310-cp310-linux_x86_64.whl file is 135M. @neteler Where I could upload this binary file for downloading, please?

1. Donwload binary wxPython-4.1.1-cp310-cp310-linux_x86_64.whl file
2. Check hash:

```
[fedora@fedora35 ~]$ pip hash wxPython-4.1.1-cp310-cp310-linux_x86_64.whl 
wxPython-4.1.1-cp310-cp310-linux_x86_64.whl:
--hash=sha256:2cd17438b679c47e1bb1c63183ff43de5452220904ecc799bb0bc4fdbaa2bb67
```

3. Install whl package:

`pip install wxPython-4.1.1-cp310-cp310-linux_x86_64.whl`

**Comment by neteler** [comment]
This is cool: https://transfer.sh/

**Comment by tmszi** [comment]
> This is cool: https://transfer.sh/

Thanks Markus for great tip!

**Comment by tmszi** [comment]
@danhox I prepare easy wxPython 4.1.1 installation manual (without time-consuming compilation wxPython from source code), check [comment above](https://github.com/OSGeo/grass/issues/2019#issuecomment-998869908), please.

**Comment by danhox** [comment]
> @danhox I prepare easy wxPython 4.1.1 installation manual (without time-consuming compilation wxPython from source code), check [comment above](https://github.com/OSGeo/grass/issues/2019#issuecomment-998869908), please.

Thank you

**Comment by danhox** [comment]
> This is cool: https://transfer.sh/

<wxpython> GUI in the background, please wait...
Traceback (most recent call last):
  File "/usr/local/grass78/gui/wxpython/wxgui.py", line 73, in OnInit
    splash = SC.AdvancedSplash(bitmap=introBmp,
  File "/home/danhoneuba/grass_gis_wxpython/lib64/python3.10/site-packages/wx/lib/agw/advancedsplash.py", line 251, in __init__
    self.SetTextFont()
  File "/home/danhoneuba/grass_gis_wxpython/lib64/python3.10/site-packages/wx/lib/agw/advancedsplash.py", line 442, in SetTextFont
    self._textfont.SetPointSize(self._textsize)
TypeError: Font.SetPointSize(): argument 1 has unexpected type 'float'
OnInit returned false, exiting...


the installation of wxpython 4.11 in virtual env did not solve the problem

**Comment by petrasovaa** [comment]
> the installation of wxpython 4.11 in virtual env did not solve the problem

That's expected, the error was solved in wxPython only a week ago. I backported a workaround to 7.8 branch, but 7.8.7 is not released yet.

**Comment by tmszi** [comment]
It seems combination wxPython 4.1.1 (self compiled master git branch with last [commit](https://github.com/wxWidgets/Phoenix/commit/d3bdb14365ca754e83732cccd04e94a2ded5029f)) is much more problematic (tested on Gentoo and Fedora 35 distribution). I tried launch GRAS GIS 7.8.7 dev version, and wxGUI start without error, but main window has wrong rendered Notebook widget layout.

**Screenshot**

![wxgui_notebook_widget_layout](https://user-images.githubusercontent.com/50632337/147239263-159e6f35-30fd-47ea-983b-1ea7533edd73.png)

**Additional context**

If I comment out these lines code, I get error message:

https://github.com/OSGeo/grass/blob/f9f30f33f5b057289d8817cf57f8508ad3556fad/gui/wxpython/lmgr/frame.py#L320-L402

Error mesage:

```
Traceback (most recent call last):
  File "/home/tomas/src/wxpython-4_1_1/lib/python3.10/site-packages/wx/lib/agw/flatnotebook.py", line 5201, in OnPaint
    renderer.DrawTabs(self, dc)
  File "/home/tomas/src/wxpython-4_1_1/lib/python3.10/site-packages/wx/lib/agw/flatnotebook.py", line 2269, in DrawTabs
    PaintStraightGradientBox(dc, pc.GetClientRect(), pc._tabAreaColour, LightColour(pc._tabAreaColour, lightFactor))
  File "/home/tomas/src/wxpython-4_1_1/lib/python3.10/site-packages/wx/lib/agw/flatnotebook.py", line 865, in PaintStraightGradientBox
    p = wx.Pen(wx.Colour(r, g, b))
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
```

It seems this bug wasn't fixed via https://github.com/wxWidgets/Phoenix/pull/2039/files#diff-d6e82f0c19ffaf555199107232c701b02b50518c41f6b86c1c1052eeed265ddaR861-R863.

**Comment by petrasovaa** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> It seems this wxPython bug wasn't fixed via this PR https://github.com/wxWidgets/Phoenix/pull/2039/files.

Hm, I think it is fixed:
https://github.com/wxWidgets/Phoenix/pull/2039/files#diff-d6e82f0c19ffaf555199107232c701b02b50518c41f6b86c1c1052eeed265dda
