### ISSUE TITLE
[Bug] wxGUI legend: selected map names not shown with Python 3.10

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2045]
**Describe the bug**

The map name(s) is/are unreadable.

![wxpython_2d_legend_gone](https://user-images.githubusercontent.com/1295172/147597265-29eed251-8ca6-49f6-963e-15c9b8de3164.png)

How it should be

![wxpython_2d_legend__how_it_should_be](https://user-images.githubusercontent.com/1295172/147597276-23b56056-0f39-41e3-9adc-f203db3a51f5.png)

**To Reproduce**

1. Load a map
2. Select it in the GUI
3. it becomes white'ish
4. unselect brings it back

**System description (please complete the following information):**

- Operating System: Fedora 35

```
GRASS version: 7.8.7dev                                                         
Code revision: f9f30f33f                                                        
Build date: 2021-12-14                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.3.2                                                                     
PROJ: 8.2.0                                                                     
GEOS: 3.9.2                                                                     
SQLite: 3.36.0                                                                  
Python: 3.10.1                                                                  
wxPython: 4.0.7                                                                 
Platform: Linux-5.15.6-200.fc35.x86_64-x86_64-with-glibc2.34
```

Note: this is wxPython: 4.0.7-23 (i.e., with multiple recent patches to make the wxGUI start).

**Comment by neteler** [comment]
Does anyone know how to fix this? Or at least, where the related code snippet is?

Here what happens in G8:
![image](https://user-images.githubusercontent.com/1295172/148635823-82b5fb88-375d-4296-bef8-2c7b63271ccb.png)
--> when selecting, map name(s) disappear.

The lack of visible map names turns the usage of wxGUI to a more "difficult" experience, both in G7 and G8.

**Comment by veroandreo** [comment]
I experience the same glitch in F34 both with G78 and G80. Anyone else?

**Comment by petrasovaa** [comment]
The fix in wxPython was merged.

**Comment by neteler** [comment]
Thanks @petrasovaa : I patched wxPython locally, problem solved.
