### ISSUE TITLE
[Bug] winGRASS compilation: mswindows/generic.manifest.rc dependency dropped

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2081]
By chance I discovered this message in the current OSGeo4W CI log files (random copy-paste, happens all across the code):

```
make[4]: Entering directory '/d/a/grass/grass/vector/v.clean'
make[4]: Circular ../../mswindows/generic.manifest.rc <- ../../mswindows/generic.manifest.rc dependency dropped.
sed	-e 's/@CMD@/v.clean/' \
	-e 's/@VER_MAJOR@/8/' \
	-e 's/@VER_MINOR@/1/' \
	-e 's/@VER_RELEASE@/dev/' \
	../../mswindows/generic.manifest.rc > OBJ.x86_64-w64-mingw32/v.clean.manifest.rc
sed 's/@CMD@/v.clean/' ../../mswindows/generic.manifest > OBJ.x86_64-w64-mingw32/v.clean.exe.manifest
```

Perhaps it should first go into a .tmp file or `sed` is simply missing the inline editing flag?

https://github.com/OSGeo/grass/blob/4d1496e483fb31ed29927531ea6edf623b392847/include/Make/Compile.make#L50

**Comment by echoix** [comment]
Does this still happen?

**Comment by neteler** [comment]
Apparently no longer. Random logs:
https://github.com/OSGeo/grass/actions/runs/10027150762/job/27712431608
