### ISSUE TITLE
[Bug] Temporal modules failing with `sqlite3.OperationalError: table strds_metadata has no column named number_of_semantic_labels`

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass#2114]
Running t.create or t.info (potentially others too) temporal modules in grass dev (main branch freshly updated as of today) returns:
```
ERROR: Unable to execute :
SELECT id , title , description , command , number_of_maps , min_max ,
max_max , min_min , max_min , nsres_min , nsres_max , ewres_min , ewres_max
, aggregation_type , number_of_semantic_labels , raster_register FROM
strds_metadata WHERE id = 'LST_Day_monthly@modis_lst';
Traceback (most recent call last):
  File "/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu/scripts/t.info", line 135, in <module>
    main()
  File "/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu/scripts/t.info", line 121, in main
    dataset.select(dbif)
  File "/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/abstract_dataset.py", line 373, in select
    self.metadata.select(dbif)
  File "/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/base.py", line 375, in select
    dbif.execute(sql, mapset=self.mapset)
  File "/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/core.py", line 1201, in execute
    return self.connections[mapset].execute(statement, args)
  File "/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/core.py", line 1540, in execute
    self.cursor.execute(statement)
sqlite3.OperationalError: no such column: number_of_semantic_labels
```
The temporal database is already updated to version 3. So far I have encountered this error while trying to create a STRDS (see #2109 ) and while running `t.info` in an existing and previously upgraded STRDS. 

**To Reproduce**
Just run `t.create output=test semantictype=mean title=title description=desc` in any location.

**Expected behavior**
New strds should not mandatorily require semantic labels, and upgraded old ones should be possible to be read

**System description (please complete the following information):**
```
Operating System: Linux, Fedora 34
GRASS GIS version: 8.1 dev
Code revision: ed7b8b12a                                                        
Build date: 2022-01-20                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.2.2                                                                     
PROJ: 7.2.1                                                                     
GEOS: 3.9.0                                                                     
SQLite: 3.34.1                                                                  
Python: 3.9.9                                                                   
wxPython: 4.0.7                                                                 
Platform: Linux-5.15.13-100.fc34.x86_64-x86_64-with-glibc2.33 
```

**Comment by metzm** [comment]
The problem is most probably that the TGIS db was previously upgraded with G79 or G80dev before the introduction of `semantic_label`. In this case the TGIS db has a column named `number_of_bands` instead of `number_of_semantic_labels`.

Dirty hack:
```
mv sqlite.db sqlite_old.db
sqlite3 sqlite_old.db .dump >tgis1.sql
sed 's/band_reference/semantic_label/g' tgis1.sql > tgis2.sql
sed 's/number_of_bands/number_of_semantic_labels/g' tgis2.sql > tgis3.sql
sqlite3 sqlite.db < tgis3.sql
rm -f sqlite_old.db *.sql
```

**Comment by veroandreo** [comment]
> The problem is most probably that the TGIS db was previously upgraded with G79 or G80dev before the introduction of `semantic_label`. In this case the TGIS db has a column named `number_of_bands` instead of `number_of_semantic_labels`.
> 
> Dirty hack:
> 
> ```
> mv sqlite.db sqlite_old.db
> sqlite3 sqlite_old.db .dump >tgis1.sql
> sed 's/band_reference/semantic_label/g' tgis1.sql > tgis2.sql
> sed 's/number_of_bands/number_of_semantic_labels/g' tgis2.sql > tgis3.sql
> sqlite3 sqlite.db < tgis3.sql
> rm -f sqlite_old.db *.sql
> ```

Ahhhh... and t.upgrade olnly does version 2 to version 3, not version 3 old to version 3 new... Indeed, I ran `t.upgrade` and got a message saying `Nothing to do`. I'll test the hack and report back. Thanks, @metzm !!

Right now, I was testing in a different laptop, and didn't get any errors.

**Comment by veroandreo** [comment]
The hack worked. Thanks @metzm! I'll have to check which mapsets I had ran t.upgrade in before band_reference --> semantyc_label change happened and do the same... Closing.
