### ISSUE TITLE
[Feat] Include parallel efficiency in benchmark plots

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#2118]
**Is your feature request related to a problem? Please describe.**
As described in the link below, add parallel efficiency to benchmark plots in benchmark library (python/grass/benchmark)
https://github.com/sinkovit/Parallel-concepts

![parallel efficincy](https://raw.githubusercontent.com/sinkovit/Parallel-concepts/main/strong2_log.png)

**Additional context**
Looks like parallel efficiency is computed as t_1 / (n * t_n) where t is time and n is number of cores

**Comment by seifashraf1** [comment]
Hello,

I am a GSoC'23 aspirant, I am confused about the graph. You said "Looks like parallel efficiency is computed as t_1 / (n * t_n) where t is time and n is number of cores" but why would the parallel efficiency decrease with more cores?

**Comment by HuidaeCho** [comment]
> Hello,
> 
> I am a GSoC'23 aspirant, I am confused about the graph. You said "Looks like parallel efficiency is computed as t_1 / (n * t_n) where t is time and n is number of cores" but why would the parallel efficiency decrease with more cores?

That efficiency ratio compares t_1 and n * t_n. If it's 1, a task that costs t_1 using one core takes t_1 / n time using n cores. In other words, the task is evenly distributed to n cores time-wise on average. If it's greater than 1, t_n is shorter than t_1 / n, which means that dividing the task by n is more efficient than just dividing t_1 by n or an efficiency ratio of 1. If it's less than 1, distributing the task to n cores is not as efficient as dividing t_1 by n.

The decreasing trend of the efficiency curve in the above plot doesn't necessarily mean that it takes more time using parallelism. It can indicate an increasing overhead of parallelism (e.g., scheduling overhead, data sharing overhead, etc.).

**Comment by jameshu15869** [comment]
Hi,
I came across Grass from GSoC and am interested in this project, as I have some past experience with C and OpenMP. I've watched the video associated with the Parallel-concepts talk and believe I have a fundamental understanding of the goal. I just had a few questions while working on the starter project.

1. Should I download the preinstalled binaries or clone from git and manually compile? I am working on WSL, if that makes a difference.
2. The project is listed as "Take your pick" for 175 or 350 hours. What would the difference in scope be between the two lengths be? I am new to open source and would be interested in a shorter project. 

Thanks

**Comment by wenzeslaus** [comment]
@jameshu15869 This is a discussion which is better to have at [grass-dev mailing list](https://lists.osgeo.org/listinfo/grass-dev) or in [gitter chat](https://app.gitter.im/#/room/#grassgis_community) (your choice). Please, introduce yourself there and we can discuss. On GitHub, you should address this or another "good first issue" to show your skills.

**Comment by petrasovaa** [comment]
Fulfilled in #3835.
