### ISSUE TITLE
v.distance: required paramters do not allow creation of vector map with lines

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass#2126]
**Describe the bug**
Combinaion of required paramters in v.distance makes it impossible to produce a output vector lines map.
Likely introduced with #601 (which I reviewd).

Now, `upload` is a required parameter. When I add it, I get the following error:
```
ERROR: Option <upload> requires at least one of <-p>, <table> or <columns>
```
When I leave it out, I get the error message that the required parameter `upload` is missing.
 
**To Reproduce**
Try a version of the "Create a new vector map" example from the manual.
```
v.distance from=pnt to=ln out=connections upload=dist column=dist
```
Also the other example
```
v.distance from=pnt to=ln out=connections upload=cat,dist column=to_cat,dist table=connections
```
Does not work because `output` and `table` are mutually exclusive.

**Expected behavior**
The module allows creation of vector maps and examples from the manual work.

**System description (please complete the following information):**

- Operating System: Ubuntu 18.04
- GRASS GIS version: 8.1

**Additional context**
Tests should be added that cover these issues.

Personally, I think we should not ship a release with this issue, so I take the liberty to flag it as a blocker. Please feel free to change the label if you disagree.
Will try if I can fix it fast.

**Comment by wenzeslaus** [comment]
On the other hand, we do plan to release a bugfix release 8.0.1...
