### ISSUE TITLE
[Bug] winGRASS is missing PROJ utilits (proj, cs2cs)

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass#2196]
**Describe the bug**
as mentioned in [#2013](https://github.com/OSGeo/grass/issues/2013#issuecomment-1025218771)

```
    m.proj -o coordinates=638300,220750
    ERROR: cs2cs program not found, install PROJ first:

we're shipping only PROJ library in standalone, but not the PROJ tools e.g. proj, cs2cs, geod
```

**Expected behavior**
**m.proj** is working.

PROJ utilities are provided by winGRASS standalone

**System description (please complete the following information):**

```
GRASS Version: 8.0.0                                                            
Code revision: 65675c832                                                        
Build date: 2022-02-09                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.4.1                                                                     
PROJ: 8.2.1                                                                     
GEOS: 3.10.2                                                                    
SQLite: 3.37.2                                                                  
Python: 3.9.5                                                                   
wxPython: 4.1.1                                                                 
Platform: Windows-10-10.0.19044-SP0   
```

**Comment by hellik** [comment]
the winGRASS standalone packaging environment needs to include the **PROJ** utilities.

**Comment by hellik** [comment]
AFAIR @landam has a OSGeo4W winGRASS build environment and a OSGeo4W winGRASS packaging environment.

a simple fix of this issue is to include PROJ dll and utilities in the a OSGeo4W winGRASS packaging environment.

though I can't find anything in the [winGRASS maintenance scripts ](https://github.com/landam/wingrass-maintenance-scripts)

**Comment by ninsbl** [comment]
My guess is, that the build system needs to install the `proj` package, as maintenance of previously installed packages seems to happen here:
https://github.com/landam/wingrass-maintenance-scripts/blob/master/osgeo4w_update.bat

`proj` should be added as a runtime dependency also to OSGeo4W, though...

Cause this is a pure packaging issue (no changes in GRASS code needed), it would be great if it could be solved for 8.0.1...

**Comment by ninsbl** [comment]
See also: https://github.com/jef-n/OSGeo4W/pull/7

**Comment by hellik** [comment]
> See also: [jef-n/OSGeo4W#7](https://github.com/jef-n/OSGeo4W/pull/7)

[GRASS setup hint](https://github.com/OSGeo/grass/blob/main/mswindows/osgeo4w/setup.hint.tmpl) needs to be adapted accordingly

**Comment by hellik** [comment]
`requires: liblas gdal303-runtime proj81-runtime avce00 gpsbabel gs python3-gdal python3-matplotlib libtiff python3-wxpython python3-pillow python3-pip python3-ply python3-pyopengl python3-psycopg2-binary python3-six zstd python3-pywin32`

proj should be added to the list.

and OSGeo4W is already at [proj82-runtime/](http://download.osgeo.org/osgeo4w/v2/x86_64/release/proj/proj82-runtime/)

**Comment by ninsbl** [comment]
@hellik or @landam, do you know if this setup.hint is actually uesd? Is it used for the winGRASS standalone installer?

The setup.hint in OSGeo4W defines these dependencies:
`liblas gdal304-runtime proj82-runtime avce00 proj gpsbabel gs python3-gdal python3-matplotlib libtiff python3-wxpython python3-pillow python3-pip python3-ply python3-pyopengl python3-psycopg2-binary python3-six zstd python3-pywin32 netcdf wxwidgets`

See: http://download.osgeo.org/osgeo4w/v2/x86_64/release/grass8/setup.hint

**Comment by hellik** [comment]
> @hellik or @landam, do you know if this setup.hint is actually uesd? Is it used for the winGRASS standalone installer?
> 
> The setup.hint in OSGeo4W defines these dependencies: `liblas gdal304-runtime proj82-runtime avce00 proj gpsbabel gs python3-gdal python3-matplotlib libtiff python3-wxpython python3-pillow python3-pip python3-ply python3-pyopengl python3-psycopg2-binary python3-six zstd python3-pywin32 netcdf wxwidgets`
> 
> See: http://download.osgeo.org/osgeo4w/v2/x86_64/release/grass8/setup.hint

Yes, I've seen the difference in our source and the  OSGeo4W setup.hint. 

Not sure where the OSGeo4W comes from. 

@landam any idea?

We should update our source and add proj to setup.hint. 

  @landam which  proj version are you using for compiling? Is it in sync with the latest OSGeo4W version?

**Comment by ninsbl** [comment]
> Yes, I've seen the difference in our source and the OSGeo4W setup.hint.
> 
> Not sure where the OSGeo4W comes from.
> 
> @landam any idea?

It is generated here: https://github.com/jef-n/OSGeo4W/blob/master/src/grass/osgeo4w/package.sh#L89

**Comment by neteler** [comment]
New installer version: https://lists.osgeo.org/pipermail/grass-dev/2022-February/095587.html

**Comment by neteler** [comment]
Is this still an issue?
Since the [8.0.2](https://github.com/OSGeo/grass/milestone/15) milestone is due now to which milestone may this report be bumped?

**Comment by hellik** [comment]
> Is this still an issue? Since the [8.0.2](https://github.com/OSGeo/grass/milestone/15) milestone is due now to which milestone may this report be bumped?

seems to be fixed now. closing.
