### ISSUE TITLE
[Bug] fails to open: ModuleNotFoundError: No module named 'grass.grassdb'

### ISSUE THREAD

**Issue by oskeng** [OSGeo/grass#2209]
**Describe the bug**
Everything worked fine until a few hours ago. Then all of a sudden $ grass resulted in:

Usage: grass [OPTIONS]
Try 'grass -h' for help.

Error: Missing option '--config'.

and:

$ ./bin.x86_64-pc-linux-gnu/grass 

results in:

Starting GRASS GIS...
Traceback (most recent call last):
  File "/home/oskeng/src/grass/./bin.x86_64-pc-linux-gnu/grass", line 2741, in <module>
    main()
  File "/home/oskeng/src/grass/./bin.x86_64-pc-linux-gnu/grass", line 2545, in main
    from grass.grassdb.checks import can_start_in_mapset
ModuleNotFoundError: No module named 'grass.grassdb'

I have tried $ make clean and $ make distclean and recompiled several times. The problem persists.

**To Reproduce**

$./configure --with-geos=/usr/bin/geos-config --with-blas --with-lapack --with-freetype-includes=/usr/include/freetype2/ --enable-64bit --with-libs=/usr/lib64

$ make -j16

$ sudo make install

$ grass

**Expected behavior**
grass starts

**Screenshots**

**System description (please complete the following information):**

- Operating System:  Linux anarchy-home 5.16.9-zen1-1-zen x86_64 GNU/Linux

- GRASS GIS version [e.g. 7.8.4]: main (15 Feb)

- Python:
3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
4.1.2a1 gtk3 (phoenix) wxWidgets 3.1.5

**Additional context**

**Comment by oskeng** [comment]
Removed the bin manually, and now, after another recompilation, I get the ModuleNotFoundError also when running $ grass.

**Comment by oskeng** [comment]
Thanks a lot, it is indeed weird. I have no other `grass` installed. It worked just fine this morning. The issue started after a reboot.

The `Error: Missing option --config.` is gone now after i manually removed `/usr/local/bin/grass`, which was apparently not overwritten by `sudo make install`. After a new recompilation, `$ grass` gives the `ModuleNotFoundError`, just as `$ ./bin.x86_64-pc-linux-gnu/grass`

`$ which grass`
`/usr/local/bin/grass`

`$ python -c "import grass; print(grass.__file__)"`
`/usr/lib/python3.10/site-packages/grass/__init__.py`

**Comment by wenzeslaus** [comment]
The `/usr/lib/python3.10/site-packages/grass/__init__.py` is suspicious. `make [install]` does not (1) put the files into `site-packages`, but it puts them under `etc/python` under the install prefix directory (`dist...` for `make` and e.g. `/usr/lib/grass78/` for my GRASS from packages).

What is in you site-packages (`tree /usr/lib/python3.10/site-packages/grass/`)? And do you have any guesses on how it got there?

(1) I would actually prefer `site-packages`, but it does not behave like that currently.

**Comment by oskeng** [comment]
`__init__.py  iterGrass.py  processLabels.py`

I can only assume that these files are left from a previous installation using the package manager (pacman).

**Comment by wenzeslaus** [comment]
That's a name collision with COMBINE-lab/GRASS project (Graph Regularized Annotation via Semi-Supervised learning; last active in 2016 on GitHub).

https://github.com/COMBINE-lab/GRASS/tree/master/grass

**Comment by oskeng** [comment]
A bit confused now - that grass has never been installed on my system. But I have had (our) grass76 and grass78 installed using the package manager. Perhaps these mysterious files are remnants from that?

What really confuses me is that grass8 worked for several days before, supposedly, committing suicide.

**Comment by marisn** [comment]
Not our issue.

Steps to reproduce:
```
virtualenv --py python2.7 tmp_env
source tmp_env/bin/activate
pip install grass
grass
```
results in:
```
Usage: grass [OPTIONS]
Try 'grass -h' for help.

Error: Missing option '--config'.
```
Conclusion – grass is working as expected, but that's grass not GRASS. Solution is `pip uninstall grass` or, if grass was installed with system package tools, use your system tools to remove wrong grass and install the correct one.

**Comment by oskeng** [comment]
Many thanks @wenzeslaus and @marisn. I had no idea that I had a pip install of grass-0.1.2. Works as expected after uninstall. 

A mystery though that it worked just fine until yesterday morning when the issue appeared. But all is well now.
