### ISSUE TITLE
Problems with GRASS 8 integration 

### ISSUE THREAD

**Issue by oskeng** [OSGeo/grass#2235]
On Fedora 35.

I have built both grass (8.1-dev) and qgis (3.25.0-Master) from source and they work individually. 

The GRASS core plugin is activated by default but there is no "GRASS" entry in the "Plugins" menu.

I can access and start grass tools in the processing toolbox. 

Grass data not recognized in the browser (which is what I primarily need). 

Any advice?

**Comment by HuidaeCho** [comment]
I'm not sure if this is a GRASS issue. It looks to me that it's an issue in QGIS menu? Please check with the QGIS developers as well.

**Comment by oskeng** [comment]
Oops - sorry, I meant to post this in the QGIS community but accidentally posted it here instead. Sorry.
