### ISSUE TITLE
[Bug] Compiling with tarball still fails sometimes

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#2254]
**Describe the bug**

Attempts to build with a tarball (without .git) still fails *occasionally*. Now with an exception:

`http.client.RemoteDisconnected: Remote end closed connection without response`

Seems that the fix https://github.com/OSGeo/grass/pull/2139 for https://github.com/OSGeo/grass/issues/2137 didn't cover all situations.

[errorlog.txt](https://github.com/OSGeo/grass/files/8197250/errorlog.txt)

**Comment by neteler** [comment]
Is this still an issue?
Since the [8.0.2](https://github.com/OSGeo/grass/milestone/15) milestone is due now - to which milestone may this report be bumped?

**Comment by nilason** [comment]
> Is this still an issue?
> Since the [8.0.2](https://github.com/OSGeo/grass/milestone/15) milestone is due now - to which milestone may this report be bumped?

I don't know if this is still an issue. Difficult to reproduce and a second attempt right after a failure succeeded (which makes this a non-blocker). I'll bump it to 8.0.3.

**Comment by nilason** [comment]
I have not experienced this since... closing.
