### ISSUE TITLE
[Win Bug] DBMI-SQLite driver error: Unable to open database X:\\path\\sqlite.sql

### ISSUE THREAD

**Issue by PiperLiu** [OSGeo/grass#2300]
**Describe the bug**
I installed the latest version [GRASS GIS 8.0.1 for windows](https://grass.osgeo.org/download/windows/). There is a bug when path 
of database containing a Chinese character.

**To Reproduce**
```cmd
# create a new project, which contains Chinese a character
mkdir E:\文档\grassdata
# some codes for creating a location in E:\文档\grassdata
...
# use v.in.ogr to load vector data
v.in.ogr path/to/data output=name

Check if OGR layer <name> contains polygons...
 100%
Creating attribute table for layer <name>...
DMI-SQLite driver error:
Unable to open database: E:\\\grassdata\\location\\PERMANENT\\sqlite\\sqlite.sql
unable to open database file

...
```

Three `\` after `E:` in `E:\\\grassdata\\...` means grassgis cannot parse path containing a Chinese character.

**Comment by neteler** [comment]
Out of curiosity I have tried this on Linux:

```
mneteler@caddy: ~$ mkdir 文档
mneteler@caddy: ~$ cd 文档
mneteler@caddy: ~/文档$ mkdir grassdata
grass80 -c epsg:32632 grassdata/utm32N_32632

# import of some data
GRASS utm32N_32632/PERMANENT:文档 > v.import ~/data/brd_plz_einwohner_OSM/brd_plz_gebiete_pop2011.shp
...
# no errors occurred

GRASS utm32N_32632/PERMANENT:文档 > v.info brd_plz_gebiete_pop2011
 +----------------------------------------------------------------------------+
 | Name:            brd_plz_gebiete_pop2011                                   |
 | Mapset:          PERMANENT                                                 |
 | Location:        utm32N_32632                                              |
 | Database:        /home/mneteler/文档/grassdata                             |
 | Title:                                                                     |
 | Map scale:       1:1                                                       |
 | Name of creator: mneteler                                                  |
 | Organization:                                                              |
 | Source date:     Tue Apr 12 16:56:39 2022                                  |
 | Timestamp (first layer): none                                              |
 |----------------------------------------------------------------------------|
 | Map format:      native                                                    |
...

# also tested successfully with v.in.ogr
```

It seems to be a Windows specific problem.
Could maybe @hellik try out?

**Comment by hellik** [comment]
> It seems to be a Windows specific problem. Could maybe @hellik try out?

![grafik](https://user-images.githubusercontent.com/12000843/163038358-073b571b-ba1a-472a-966b-0ea8c38adad2.png)

trying to create a location with chinese characters doesn't work.

**Comment by hellik** [comment]
`D:\wd\文档`

creating a folder within the file explorer works; though the windows console, the characters aren't displayed correctly

![grafik](https://user-images.githubusercontent.com/12000843/163039369-d9d6e7fd-a9f2-4277-a4ee-e4c02e3ea747.png)

**Comment by hellik** [comment]
![grafik](https://user-images.githubusercontent.com/12000843/163040286-bcdd1952-fe80-419f-9eee-d4c0b242bf2a.png)

windows console in win 10 seems not to be unicode safe

**Comment by PiperLiu** [comment]
> ![grafik](https://user-images.githubusercontent.com/12000843/163040286-bcdd1952-fe80-419f-9eee-d4c0b242bf2a.png)
> 
> windows console in win 10 seems not to be unicode safe

Thanks for your reply! So it seems it's win 10's defect. Will this software be planned to be compatible with windows 10? Or I will close this issue.

**Comment by hellik** [comment]
> > ![grafik](https://user-images.githubusercontent.com/12000843/163040286-bcdd1952-fe80-419f-9eee-d4c0b242bf2a.png)
> > windows console in win 10 seems not to be unicode safe
> 
> Thanks for your reply! So it seems it's win 10's defect. Will this software be planned to be compatible with windows 10? Or I will close this issue.

I'm not sure that GRASS GIS is able to overcome MS Windows' unicode shortcoming.

**Comment by PiperLiu** [comment]
> > > ![grafik](https://user-images.githubusercontent.com/12000843/163040286-bcdd1952-fe80-419f-9eee-d4c0b242bf2a.png)
> > > windows console in win 10 seems not to be unicode safe
> > 
> > 
> > Thanks for your reply! So it seems it's win 10's defect. Will this software be planned to be compatible with windows 10? Or I will close this issue.
> 
> I'm not sure that GRASS GIS is able to overcome MS Windows' unicode shortcoming.

Tranks. I'll close the issue.
