### ISSUE TITLE
[Feat] Add links and full basic intro to grass.jupyter intro

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#2303]
The _grass.jupyter_ intro page introduced in #2284 should include intro sentence for Jupyter, notebooks, perhaps Python, more complete basic example, and a link to main intro notebook.

https://github.com/OSGeo/grass/blob/main/doc/notebooks/basic_example.ipynb
https://mybinder.org/v2/gh/OSGeo/grass/main?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fbasic_example.ipynb

The page URL is or will be:

https://grass.osgeo.org/grass81/manuals/libpython/grass.jupyter.html

Questions:

Which link or links to include? Binder link pointing to main will take long time to load. GitHub link is not interactive. Both need to be different for different versions unless we say that pointing to main is fine.

How much introductory material to include? It is intro to using GRASS GIS from Python? Intro to Python? To Jupyter? We have few sentences, two short paragraphs max to make the general introduction.

**Comment by neteler** [comment]
> How much introductory material to include?

Overall, we should be "invitive", i.e. don't assume too much knowledge but point to relevant material in a structured way (for sure no need to reinvent the wheel).

> It is intro to using GRASS GIS from Python? Intro to Python? To Jupyter?

I'd suggest to introduce jupyter (draft suggestions):
- one line why jupyter
- installation
    - get jupyter: link to installation
    - for interactive display with leaflet, run `pip install folium`
- how to start `jupyter notebook` and in which directory (e.g., `basic_example_grass_jupyter.ipynb`) - start in running GRASS GIS 8.2 session or run from outside?
    - `cd doc/notebooks/`
    - `jupyter notebook`
    - see terminal for link to start in browser
    - Note: to run a selected part which is called a cell, hit `Shift + Enter`. You can also edit code and (re-)run it.
    - In the `Start` jupyter cell, update in `Start GRASS Session` as needed the path to `grassdata` in order to match the path of your local copy.
    - Start running the jupyter code by hit `Shift + Enter`. Results will be displayed under the executed cell including maps with legends.
- If interested in the "Interactive Map Display", run `grass_jupyter.ipynb`

Further material:
- One line about Binder + link to start GRASS GIS session
- point to https://grasswiki.osgeo.org/wiki/GRASS_GIS_Jupyter_notebooks (needs to be updated)
