### ISSUE TITLE
[Feat] Document differences between Vect_line_intersection versions

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass#2345]
There are two similarly named functions Vect_line_intersection and Vect_line_intersection2 but both of them have identical descriptions. One can only assume that there must be some kind of difference otherwise only one would exist but the documentation does not reveal anything.
Difference between both functions should be documented along recommendations or caveats in their use (if there are some).

**Comment by neteler** [comment]
Vect_line_intersection2() is the Bentley-Ottmann algorithm to find line intersections, 
added in e395e4eb2686a753b784517bc165149acc6003ea. I agree that the description to Vect_line_intersection() should differ.

It was offered as a GSoC project in 2013:
https://lists.osgeo.org/pipermail/grass-dev/2013-March/062384.html
https://grasswiki.osgeo.org/wiki/GRASS_SoC_Ideas_2013#Vector

**Comment by metzm** [comment]
I agree that the descriptions should explain the difference between the two functions. In short, the two functions `Vect_line_intersection()` and `Vect_line_intersection()` behave identical, but `Vect_line_intersection2()` based on the Bentley-Ottmann algorithm is much faster than the original version. I will prepare a PR.

The proposed GSoC project did not get a student, so I implemented the Bentley-Ottmann algorithm myself back then.

**Comment by metzm** [comment]
@marisn What do you mean with "identical descriptions"? The descriptions are already slightly different. I guess you want to know the reason for the existence of `Vect_line_intersection2()`?

The reason for the existence of `Vect_line_intersection2()` is speed. The reason for the continued existence of `Vect_line_intersection()` is to to have the original version available for easy debugging in case a bug appears in `Vect_line_intersection2()`.

**Comment by marisn** [comment]
> @marisn What do you mean with "identical descriptions"? The descriptions are already slightly different.

Are we talking about same functions in same files?!? I fail to find any difference in documentation of both functions at all. Even worse – Vect_line_get_intersections2 claims to be „ A wrapper around Vect_line_check_intersection() function“ although it is a wrapper around Vect_line_check_intersection2()
https://github.com/OSGeo/grass/blob/394970d61c04570d7c8aaf6244cb4ed23d973a6a/lib/vector/Vlib/intersect.c#L1447
https://github.com/OSGeo/grass/blob/394970d61c04570d7c8aaf6244cb4ed23d973a6a/lib/vector/Vlib/intersect2.c#L1557

**Comment by metzm** [comment]
Ah, it's the documentation for `Vect_line_get_intersections2()` that is wrong. The documentation for `Vect_line_intersection()` and `Vect_line_intersection2()` seems to be correct, but does not explain the differences and why these two functions exist with `Vect_line_intersection()` being unused. The same applied to `Vect_line_check_intersection()` and `Vect_line_check_intersection2()`.
