### ISSUE TITLE
Can´t install r.viewshed.exposure on Windows

### ISSUE THREAD

**Issue by Tobias1234** [OSGeo/grass#2373]
*I can´t install "r.viewshed.exposure" on Windows Grass GIS 7.8.7 dev version 

![image](https://user-images.githubusercontent.com/7010225/168318587-18190bc2-f1d4-41b8-b72a-e443909ac08e.png)

It says 
```
Downloading precompiled GRASS Addons <r.viewshed.exposure>...
Fetching <r.viewshed.exposure> from <http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/r.viewshed.exposure.zip> (be patient)...
Updating extensions metadata file...
Updating extension modules metadata file...
Installation of <r.viewshed.exposure> successfully finished
(Fri May 13 17:40:52 2022) Command finished (7 sec)  
```
But I can´t see any addon under the raster menu. This is the closest I get to install the addon.
I tried other versions of grass on windows but the download links doesn´t work then.

Is it another way to install this addon on Windows? It is not possible to install the addon in the latest version of Grass because the download link is different and doesn´t work. 

Best, Tobias

**Comment by petrasovaa** [comment]
> But I can´t see any addon under the raster menu. This is the closest I get to install the addon. I tried other versions of grass on windows but the download links doesn´t work then.

Just to make sure, you still don't see it even after you restart the GUI?
> 
> Is it another way to install this addon on Windows? It is not possible to install the addon in the latest version of Grass because the download link is different and doesn´t work.

What is the specific version of GRASS you have troubles with? Consider also posting the error.

**Comment by Tobias1234** [comment]
No can´t see it after a restart either. Grass GIS 7.8.7 dev version. I don´t get an error (so I guess it is installed maybe?). But I can´t see it in the GUI.
![image](https://user-images.githubusercontent.com/7010225/168337185-79380a09-f102-4454-b3f7-ec22aad2a826.png)  

But where can I access the addon?

**Comment by petrasovaa** [comment]
When you go to Modules tab in GUI (Layer manager window), there should be the addons as separate item. Or just type it in the command console.
But that's a good point that it's not visible, we should improve that.

**Comment by Tobias1234** [comment]
Perfect! :-)
Now I see it here:
![image](https://user-images.githubusercontent.com/7010225/168342489-912a76b4-b399-43dd-a981-551ce05ce80f.png)
But it is not under drop down meny in the top which I searched in before.
Thanks!

**Comment by dnewcomb** [comment]
Try running it from the command prompt

**Comment by Tobias1234** [comment]
It´s also possible

**Comment by Tobias1234** [comment]
The addon installation works
