### ISSUE TITLE
[Bug] Main GUI window bad placed on Mac

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#2415]
**Describe the bug**
The default placement of the new single window GUI is putting the window title bar below the OS menu on Mac. As the title bar is the only element with which it is possible to move the window, this is a very annoying bug.

**Expected behavior**
The whole GRASS gui window should be placed below the OS menu bar.

**Screenshots**
This is the default placement:
<img width="1079" alt="gui_mac" src="https://user-images.githubusercontent.com/14186207/172040040-9b01e5c5-4f50-4b02-8880-96b459b429a4.png">

This is what the whole window looks like:
<img width="705" alt="mac_window" src="https://user-images.githubusercontent.com/14186207/172040340-42fcaa08-6317-45dc-9eca-fe33623b684e.png">

**System description (please complete the following information):**

- Operating System: Mac
- GRASS GIS version 8.2.0

g.version -rge                                                                                                 Mapset <user1> in <nc_spm_full_v2alpha2>
version=8.2.0
date=2022
revision=exported
build_date=2022-06-05
build_platform=aarch64-apple-darwin21.4.0
build_off_t_size=8
libgis_revision=2022-06-05T06:31:19+00:00
libgis_date=2022-06-05T06:31:19+00:00
proj=8.2.1
gdal=3.4.3
geos=3.10.2
sqlite=3.38.5

4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5

**Comment by nilason** [comment]
Seems a similar issue to https://trac.osgeo.org/grass/ticket/1233 has been reintroduced.

**Comment by tmszi** [comment]
Same on the OS MS Windows, if OS panel position is on top of the screen.

![wxgui_def_main_window](https://user-images.githubusercontent.com/50632337/172133472-588388a5-21dc-44df-83e2-bcdacdcffd04.png)
