### ISSUE TITLE
wxGUI with Single Window Mode activated crashes after changing the position of the floating Pane widget window, e.g. Layers

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass#2430]
**Describe the bug**
wxGUI with Single Window Mode activated crashes after changing the position of the floating Pane widget window, e.g. Layers

**To Reproduce**

1. Download and install [WinGRASS-8.3.dev](https://wingrass.fsv.cvut.cz/grass83/WinGRASS-8.3.dev-1e0f8882d-128-Setup.exe)
2. Launch wxGUI with Single Window Mode option 
4. Make e.g. Layers Pane widget as floating window with double left mouse click on the Layer Pane widget header
5. Try to change position (move) of floating Layers Pane widget window
6. wxGUI crash without showing error message

**Expected behavior**
Move floating Pane widget window without crash wxGUI same as on other OS platform (wxGTK, wxMAC)

**System description (please complete the following information):**

- Operating System: MS Windows
- GRASS GIS version: 8.3.dev, 8.2 (with Single Window Mode option)

```
4.1.1 msw (phoenix) wxWidgets 3.1.5
```

**Additional context**
On the OS platform GNU/Linux (wxGTK) this bug doesn't occur.

**Comment by lindakladivova** [comment]
It works with wxpython 4.2.0. Please reopen if you will encounter this problem again with the newer wxpython version.
