### ISSUE TITLE
g.extension fails to compile some addons in grass 8.0.1 and grass 8.2 

### ISSUE THREAD

**Issue by ewCrg** [OSGeo/grass#2471]
**Describe the bug**
g.extension and g.extension.all fail to compile and install some (but not all) addons in grass 8.0.1 and 8.2.0

**To Reproduce**

1. run g.extention from gui or g.extension.all from console
2. in g.extension.all window that opens, click reinstall and "force"
4. for those addons that do not compile, g.extension returns the error message:
5.  "**/usr/bin/ld: cannot open linker script file /builddir/build/BUILD/grass-8.0.1/.package_note-grass-8.0.1-1.fc36.x86_64.ld: No such file or directory**
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/grass80//include/Make/Module.make:18: /usr/lib64/grass80/bin/r.accumulate] Error 1"

**Expected behavior**
All addons should compile and install. Some do, but not all.

**Screenshots**

**System description (please complete the following information):**

- Operating System: Linux Fedora 36
- GRASS GIS version 8.0.1 and 8.2.0 installed from Fedora repository

**Additional context**
This bug  had been reported and resolved in a discussion group, and I understood that it had been reported, but I cannot find the bug here or in Redhad Bugzilla.

The problem is resolved in both grass 8.0.1 and grass 8.2 by removing:
""  -Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/grass-8.0.1/.package_note-grass-8.0.1-1.fc36.x86_64.ld"" from line 78 of /usr/lib64/grass82/include/Make/Platform.make (for grass 8.0.1, substitute /grass82/ with /grass80/.

It should not be necessary to change files within distributed rpm's, so I have reported this in Redhat Bugzilla. However, since this same bug has found its way in two releases of grass, reporting it here as well.

**Comment by tmszi** [comment]
Dublicated #2472.
