### ISSUE TITLE
[Bug] wx._core.wxAssertionError: C++ assertion ""node"" failed at /tmp/pip-install-u096cwqt/wxpython_dc2f9072538a4405aa1b3547e540e5c1/ext/wxWidgets/src/common/menucmn.cpp(886) in GetMenu(): bad index in wxMenuBar::GetMenu()

### ISSUE THREAD

**Issue by krcabrer** [OSGeo/grass#2485]
Iniciando GRASS GIS...
Limpiando archivos temporales...

          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

Bienvenido a GRASS GIS 8.3.dev (adc9118a7)
Página web de GRASS GIS:                 https://grass.osgeo.org
Esta versión corriendo a través de:      Bash Shell (/bin/bash)
La ayuda está disponible con el comando: g.manual -i
Vea los términos de la licencia con:     g.version -c
Leer opciones para citar con:            g.version -x
Si lo necesita, reinicie la GUI con:     g.gui wxpython
En cuanto esté listo para salir escriba: exit

Lanzando GUI <wxpython> en el fondo, por favor espere...
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

GRASS world_latlong_wgs84/PERMANENT:~ > Traceback (most recent call last):
  File "/home/kenneth/.local/lib/python3.10/site-packages/wx/core.py", line 3407, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/local/grass83/gui/wxpython/wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File "/usr/local/grass83/gui/wxpython/lmgr/frame.py", line 156, in __init__
    self.workspace_manager.CreateRecentFilesMenu(
  File "/usr/local/grass83/gui/wxpython/lmgr/workspace.py", line 507, in CreateRecentFilesMenu
    file_menu = menu.GetMenu(
wx._core.wxAssertionError: C++ assertion ""node"" failed at /tmp/pip-install-u096cwqt/wxpython_dc2f9072538a4405aa1b3547e540e5c1/ext/wxWidgets/src/common/menucmn.cpp(886) in GetMenu(): bad index in wxMenuBar::GetMenu()

**To Reproduce**
Download the latest git code.
git clone https://github.com/OSGeo/grass.git
Complile
Install

On console:
grass

**Expected behavior**
Normal execution

**System description (please complete the following information):**
- Linux
- GRASS GIS version 8.3-dev

version=8.3.dev
date=2022
revision=adc9118a7
build_date=2022-07-20
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8

**Comment by tmszi** [comment]
Could @krcabrer post output of this command `python3 -c "import sys, wx; print(sys.version); print(wx.version())"` and what kind of GNU/Linux distribution do you use, please? 

Seems you are using Python 3.10 and bug is related with specific wxPython version.

With Python 3.9.13  and wxPython 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5 works wxGUI correctly tested on the Gentoo GNU/Linux distribution.
