### ISSUE TITLE
[Bug] r.area.createweight Add-on fails to install from Official Source.

### ISSUE THREAD

**Issue by d-load1ng** [OSGeo/grass#2492]
**Describe the bug**
**"r.area.createweight" Add-on fails to install from Official Source.**
-- zip file without metadata 
http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7/r.area.createweight.zip

**To Reproduce**

1. Go to 'from gui try to install the add-on r".area.createweight" '
2. Click on 'install'
4. See error below

**Expected behavior**
WARNING: No metadata available for module 'r.area.createweight': Unable to fetch interface description for command '<r.area.createweight>'.

Details: <Cannot find the executable r.area.createweight>
ERROR: Unable to read manual page: [Errno 2] No such file or directory

**System description (please complete the following information):**

- Operating System: [e.g. Windows]
- GRASS GIS version [all version from 7.8.7 dosent have the metadata in zip file]

**Comment by neteler** [comment]
I have found the reason:

https://grass.osgeo.org/grass78/manuals/addons/
--> [Windows log files](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7/logs/)
----> raster/r.area.createweight FAILED 	log
------> `ERROR: Pandas is not installed`

@landam After your holidays, could you please install Pandas on the wingrass server?

**Comment by neteler** [comment]
Or, update `r.area.createweight.py` to use lazy pandas import if that's possible? Any volunteer?

**Comment by tmszi** [comment]
> Or, update `r.area.createweight.py` to use lazy pandas import if that's possible? Any volunteer?

 I'm going to look at it.
