### ISSUE TITLE
[Bug] selecting layer in v.in.ogr window does not work

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass#2493]
**Describe the bug**
When running v.in.ogr using the gui, selecting a layer is ignored, i.e., it does not result in only that layer being imported. 

**To Reproduce**
Assuming you have a geopackage with multiple feature layers.

1. Open the v.in.ogr window
2. Select a Geopackage under the tab 'required'
3. Under the tab 'Input', select one of the feature layers
4. Fill in the output name under the 'Output' tab
5. Click on Run.

The imported vector layer contains all layers from the Geopackage, not only the selected one.

**Expected behavior**
Only the selected layer should be imported. In other words, it should run:

`v.in.ogr input="C:\data\bebouwde_kom.gpkg" layer=woonbuurten output=woonbuurten`.

Instead, it runs:

`v.in.ogr input="C:\data\bebouwde_kom.gpkg" output=woonbuurten`.

**Screenshots**
The screenshot below shows that selecting a layer does not add this parameter setting to the command.

![dHZ0krlPHn](https://user-images.githubusercontent.com/7816789/180487024-7e7a4806-7dbc-4517-b5b8-f0fa4b5734b4.png)

**System description (please complete the following information):**

- Operating System: Windows 10
- GRASS GIS version 8.2
- GRASS GIS version 7.8.7

**Additional context**

**Comment by tmszi** [comment]
I am confirming this bug and this bug only occurs on OS MS Windows.
