### ISSUE TITLE
Why r.walk calculates different cumulative cost depending on calculation direction

### ISSUE THREAD

**Issue by skitourenguru** [OSGeo/grass#2496]
**Describe the bug**
I have two points A and B. If I calculate cumulative costs from A to B respectively from B to A I expect the same cumulative costs at the arrival points. Take into account that the walk_coeff are set symmetrically:

From A to B: a,b,c,d=0.72,6,10,-10
From B to A: a,b,c,d=0.72,10,6,-6

Details for abcd you find under [r.walk](https://grass.osgeo.org/grass78/manuals/r.walk.html)

**To Reproduce**
[Data-Sample](https://info.skitourenguru.ch/download/data/rwalk_data.zip). All data have EPSG=21781.

r.walk elevation=dem@PERMANENT friction=cost@PERMANENT output=cumCostUp outdir=movDirUp start_points=start@PERMANENT stop_points=stop@PERMANENT max_cost=10000000 null_cost=16000 walk_coeff=0.72,6,10,-10 lambda=0.2 --overwrite

v.what.rast map=stop@PERMANENT raster=cumCostUp@PERMANENT column=cumCost

r.walk elevation=dem@PERMANENT friction=cost@PERMANENT output=cumCostDown outdir=movDirDown start_points=stop@PERMANENT stop_points=start@PERMANENT max_cost=10000000 null_cost=16000 walk_coeff=0.72,10,6,-6 lambda=0.2 --overwrite

v.what.rast map=start@PERMANENT raster=cumCostDown@PERMANENT column=cumCost

**Expected behavior**
Cumulative costs should be the same at the arrival-points independent of direction. With resolution=1 the cumulative costs differ: start/stop = 50021.4056830234/50129.4681520099. If calculated at resolution=10, the cumulative costs differ much more.

**System description (please complete the following information):**

- Operating System: Windows 10
- GRASS GIS version: 7.8.6

**Additional context**
- dem and cost have a resolution of 10m. Pixels are tapped to 10 m (-tap from GDAL)
- start and stop coordinates are in X and Y: n*10 + 5. Also the problem remains, if start and end is set to the center of a pixel.
- Calculation resolution: The difference becomes big if r=10. The difference becomes minimal with very small resolutions r=1 or r=0.1 (r.region res=r). So the mirroring of abcd is correct. 
- If b=c=d=0 there isn't anymore an asymmetry.
- If uphill and downhill cost are set both to 6 there is still an asymmetry.

**Stackexchange**
[Issue at Stackexchange](https://gis.stackexchange.com/questions/436723/why-r-walk-calculates-different-cumulative-cost-depending-on-calculation-directi)

**Comment by petrasovaa** [comment]
There is an answer on Stackexchange, does that sufficiently answer the question?

**Comment by skitourenguru** [comment]
No, the answer on Stackexchange makes clear, that no careful look at the parameters a,b,c,d was done.

**Comment by isaacullah** [comment]
This behavior is correct because r.walk is an *anisotropic* cost function. Therefore, the costs from A --> B *should be different* than from B --> A. If you want the costs to be the same, you need to use r.cost with an isotropic algorithm to calculate the input friction values.

**Comment by petrasovaa** [comment]
> This behavior is correct because r.walk is an _anisotropic_ cost function. Therefore, the costs from A --> B _should be different_ than from B --> A. If you want the costs to be the same, you need to use r.cost with an isotropic algorithm to calculate the input friction values.

I think @skitourenguru was trying to address this with the changed a,b,c,d parameters, no?

**Comment by skitourenguru** [comment]
Please take into account the third additional remark:
**Calculation resolution: The difference becomes big if r=10. The difference becomes minimal with very small resolutions r=1 or r=0.1 (r.region res=r). So the mirroring of abcd is correct.**

If the parameters are made symmetric, r.walk becomes almost anisotropic. I can proove that by setting r to very small values.

**Please try it out. r.walk has a minor bug!**

**Comment by skitourenguru** [comment]
[Is Dijkstra's Algorithm symmetrical?](https://stackoverflow.com/questions/58454287/is-dijkstras-algorithm-symmetrical)
If the graph is not directional, the set of shortest paths from A to B is the same as set of shortest paths from B to A. You can prove it by the contradiction.
With the mentioned settings a,b,c,d the graph is **not directional**. Therefore r.walk must have a minor bug.

**Comment by skitourenguru** [comment]
**c must be equal to d.**

The following example produces a symmetrical result for all resolutions r, also for r=10:
From A to B: a,b,c,d=0.72,6,-10,-10
From B to A: a,b,c,d=0.72,10,-6,-6
