### ISSUE TITLE
[Bug] wx.metadata addon installation error

### ISSUE THREAD

**Issue by dnewcomb** [OSGeo/grass#2517]
**Describe the bug**
The wx.metadata extension does not install using either the gui extension manager or the command line g.extension

**To Reproduce**

1. Go to Settings -> Addons extensions-> Install extension from addons 
2. Click on wx.metadata under wxGUI section. 
3. In console tab, the following message appears: 
4. g.extension extension=wx.metadata
5. Downloading precompiled GRASS Addons <wx.metadata>...
6. ERROR: canoont open URL: http://wingrass.fsv.cvut.cz/grass82/addons/grass-82.0/wx.metadata.zip
7. Alternatively, running g.extension extension=wx.metadata from the command window gets：
8. Downloading precompiled GRASS Addons <wx.metadata>...
Fetching <wx.metadata> from
<http://wingrass.fsv.cvut.cz/grass82/addons/grass-8.2.0/wx.metadata.zip>
(be patient)...
Updating extensions metadata file...
Updating extension modules metadata file...
WARNING: No metadata available for module 'g.gui.metadata': Unable to fetch
         interface description for command '<g.gui.metadata>'.

         Details: <Cannot find the executable g.gui.metadata>
WARNING: No metadata available for module 'g.gui.cswbrowser': Unable to
         fetch interface description for command '<g.gui.cswbrowser>'.

         Details: <Cannot find the executable g.gui.cswbrowser>
ERROR: Unable to read manual page: [Errno 2] No such file or directory:
       'C:\\Users\\dnewcomb\\AppData\\Roaming\\GRASS8\\addons\\docs\\html\\g.gui.metadata.html'

**Expected behavior**
wx.metadata to load normally

**Screenshots**

**System description (please complete the following information):**

- Operating System: Windows 10 Professional
- GRASS GIS version 8.2.0 Standalone

**Additional context**

**Comment by tmszi** [comment]
Currently `wx.metadata` addon is not precompiled/prebuilded on MS Windows OS platform due bug related with incorrect GDAL library version during compilation Win GRASS GIS  issue #2497, https://github.com/OSGeo/grass/issues/2288#issuecomment-1194101047, https://github.com/OSGeo/grass-addons/issues/771. Affected are other addons too. 

Currently quick workaround is install this addon under GNU/Linux OS platform.

**Comment by tmszi** [comment]
> It seems owslib is missing on the buildsystem too: https://wingrass.fsv.cvut.cz/grass82/addons/grass-8.2.1/logs/wx.metadata.log Or the addon could use lazy imports of third party libraries...

Yes you are right, lazy import is the way how to solve this issue.

**Comment by tmszi** [comment]
Looks like it's already been resolved.

**Comment by tmszi** [comment]
It is recommended to move to the latest stable version 8.3.
