### ISSUE TITLE
[Feat] r.univar: implement OpenMP parallelization also for extended statistics

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#2564]
r.univar uses OpenMP parallelization, but only without -e (extended statistics). It would be good to add the parallelization support for this option as well. See also #1634.

**Comment by cwhite911** [comment]
@petrasovaa I'm working on added json output for r.univar. Do you want me to add the parallelization support too or have you already started?

**Comment by petrasovaa** [comment]
That may not be that simple, I am not planning to work on this anytime soon.
