### ISSUE TITLE
A recipe for homebrew

### ISSUE THREAD

**Issue by alexm98** [OSGeo/grass#2571]
Hello everyone,

I have created a formula for the MacOS package manager (homebrew) that compiles GRASS version 8.2.0 and works on Apple Silicon (M1 chips).

As I have found it appropriate, I opened a pull request in the osgeo4mac tap repository which can be found [here](https://github.com/OSGeo/homebrew-osgeo4mac/pull/1423)

We should consider how to further approach this, to make it into a formula that is available in the [homebrew core](https://github.com/Homebrew/homebrew-core) so GRASS could be installed by mac users directly.

Also it would be good if there are other mac users for GRASS who would like to give this formula a go for testing.

**Comment by FlorisCalkoen** [comment]
Came across this as I was just looking whether such formula exists. Is it already available somewhere?

**Comment by alexm98** [comment]
@FlorisCalkoen I have opened a PR to the homebrew-core repository that is in progress now  [#111132](https://github.com/Homebrew/homebrew-core/pull/111132#issuecomment-1251986576) which I will hopefully soon be able to merge.

**Comment by echoix** [comment]
The linked PR was closed without merging
