### ISSUE TITLE
[Bug] r.in.gdal - Warning message when using --quiet option

### ISSUE THREAD

**Issue by tgrippa** [OSGeo/grass#2572]
**Describe the bug**
When using r.in.gdal with --overwrite option AND --quiet option, the warning message "WARNING: Raster map <XXXXX> already exists and will be overwritten" is printed.

**To Reproduce**
1. Import any raster with r.in.gdal
2. Execute again the same command with --overwrite and --quiet option
3. See error

**Expected behavior**
Using the --quiet option should disable the warning message. 

**System description (please complete the following information):**
- Ubuntu 20.04
- GRASS GIS 8.0.2

**Comment by marisn** [comment]
It is not a bug as --q allows messages of error and warning level to pass through. 
https://grass.osgeo.org/programming8/verbose_8c.html#a4de33312674f9f6f1ad8b74881ea4154
In this regard r.in.gdal is not exceptional – many of modules print warning when a map/file is overwritten. As messages are written to stderr, unless a real case where this causes problems is shown, I do not see a reason why to change current behaviour.

**Comment by tgrippa** [comment]
@marisn thank you for your feedback. I will try to manage it with the general verbose level so. I will close the thread. 
Cheers,

**Comment by wenzeslaus** [comment]
There is a super quiet flag `--qq` which should silence warnings. Also, the question is if this should even be a warning: You requested overwrite, so why the warning? Seems like a verbose message.

**Comment by tgrippa** [comment]
@wenzeslaus I was not aware of this super quiet flag, thanks for notifying me :) 
Also I agree with your: if the overwrite option is used, the current warning should be reclassified as a "simple" message.
