### ISSUE TITLE
[Bug] Remove outdated Dockerfile

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2575]
https://github.com/OSGeo/grass/blob/6b61d1087ba9cf7429df8830c636a827bc5c3f5d/Dockerfile#L1

This file should be removed as the latest ones are in `docker/`.

**Comment by wenzeslaus** [comment]
Nice thing about Dockerfile in the top directory was that `docker build` worked with GitHub repo URL and things such as `docker build -t grassgis .` from the readme work too. Is that still a nice feature to have even with the Docker directory to create reusable Docker images? Seems friendlier for experiments and it is short. Is there an easy way to point docker build to a specific file?

**Comment by neteler** [comment]
Conserving this outdated dockerfile:

- in GRASS GIS 8.2.x we cannot remove the outdated file (as that would be a breaking change) but we could sync it to docker/ubuntu/Dockerfile.

- in main (= upcoming G 8.3.0) we could delete the file unless the comment above is prevailing. Then still the fact that the file is badly outdated remains. No idea if a redirect to a subdirectory is possible in git.

**Comment by wenzeslaus** [comment]
> ...in GRASS GIS 8.2.x we cannot remove the outdated file (as that would be a breaking change)...in main (= upcoming G 8.3.0) we could delete the file unless...

Breaking change between 8.2. and 8.3 would break expectations in semantic versioning. As the [RFC Version Numbering draft](https://github.com/OSGeo/grass/pull/2357) says:

> Use version number in a format _major.minor.micro_ where
> - _major_ is for large additions or backwards incompatible changes,
> - _minor_ is for additions, and
> - _micro_ is for fixes.

While the semantic versioning is expected even now, the RFC is a draft, so we can change things there if needed.
