### ISSUE TITLE
[Bug] configure --with-wxwidgets doesn't do anything

### ISSUE THREAD

**Issue by ojwb** [OSGeo/grass#2578]
**Describe the bug**

The `--with-wxwidgets` option sets the `with_wxwidgets` variable, but this is no longer used anywhere.

This option was entirely removed in 3e6f76140d81b01f798b23dc26750a81cbc90f1c but then f1bb8d5ee89819918f9ce5d82c2026b34a051214 added PDAL support also partly restored the `--with-wxwidgets` option (my guess is due to a badly resolved merge conflict).

**To Reproduce**

1. configure with `--with-wxwidgets=/totally/bogus/path`
2. See that this bad value is silently accepted

**Expected behavior**
I would expect this option to have been removed and this option to be warned about as unrecognised:

```
configure: WARNING: unrecognized options: --with-wxwidgets
```

**Screenshots**

**System description (please complete the following information):**

- Operating System: Debian unstable
- GRASS GIS version git master (6b61d1087ba9cf7429df8830c636a827bc5c3f5d)

**Additional context**

**Comment by sisco0** [comment]
@ojwb Could you kindly check that the referenced PR #2593 works as expected by your side?

**Comment by nilason** [comment]
Fixed with #2593
