### ISSUE TITLE
[Bug] Unneeded branch 'Rele' (and 'previewbranch_8_0')

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#2583]
**Describe the bug**
There is a branch named *Rele*, which probably was accidentally created on official GRASS git repo (https://github.com/OSGeo/grass/tree/Rele).

If the branch was intentionally created, please close this report. Otherwise the branch may be deleted.

Indirectly related: there is also the branch *previewbranch_8_0* (https://github.com/OSGeo/grass/tree/previewbranch_8_0), which I assume doesn't serve any purpose anymore (if it ever did) and may also be deleted.

**Comment by tmszi** [comment]
`Rele` branch was deleted.

**Comment by nilason** [comment]
> `Rele` branch (made by me accidenttaly) was deleted.

Thanks!

**Comment by tmszi** [comment]
@neteler is this branch https://github.com/OSGeo/grass/tree/previewbranch_8_0 necessary please?

**Comment by neteler** [comment]
> @neteler is this branch https://github.com/OSGeo/grass/tree/previewbranch_8_0 necessary please?

I have deleted `previewbranch_8_0` now.
