### ISSUE TITLE
[Bug] SEO problems on mobile devices with the GRASS GIS manual pages

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2589]
**Describe the bug**
There are notable SEO problems on mobile devices with the GRASS GIS manual pages.

![image](https://user-images.githubusercontent.com/1295172/192159225-3bb60034-9fdb-4d73-b687-89573dae92a8.png)

- Text too small to read
    - see: https://support.google.com/webmasters/answer/9063469#small_font_size
- Clickable elements too close together
    - see: https://support.google.com/webmasters/answer/9063469#touch_elements_too_close
- Viewport not set
    - see: https://support.google.com/webmasters/answer/9063469#viewport_not_configured
- Content wider than screen
    - see: https://support.google.com/webmasters/answer/9063469#content_not_sized_to_viewport

Random example:
https://search.google.com/test/mobile-friendly/result?id=nIc8LtrwxGgKXYAouSsizw&hl=en
--> https://grass.osgeo.org/grass82/manuals/r.walk.html

![image](https://user-images.githubusercontent.com/1295172/192159428-7ba0469d-d91d-4dfd-9cef-896137f7caea.png)

**Expected behavior**

The manual pages should be responsive, i.e. mobile friendly.

**Proposed solution for "Viewport not set"**
 
It appears that fixing "Viewport not set" seems solvable by simply adding the next line to the page header:

` <meta name="viewport" content="width=device-width, initial-scale=1">`

which is easy to do here as in an additional line 42:

https://github.com/OSGeo/grass/blob/841e0b39811083e1b86b93b5500864d3f1558a1a/man/build_html.py#L41

**Result of a test**

Current state without `viewport`:
- content not readable

![image](https://user-images.githubusercontent.com/1295172/192159942-5dc79eca-1294-4f1a-8bb3-0300a1e5a157.png)

Potential fix with `viewport`:
- content readable
- menu is gone (but not really useful anyway on narrow mobile devices)

![image](https://user-images.githubusercontent.com/1295172/192159971-ec98975e-fb4d-482d-8674-068a70117b02.png)

If the `viewport` meta line makes sense I can open a PR.

**Comment by tmszi** [comment]
>     * menu is gone (but not really useful anyway on narrow mobile devices)

Maybe we could replace this menu with hamburger menu (HTML + CSS but without JavaScript), example is here https://dev.to/ljcdev/hamburger-css-no-js-2dfa and https://codepen.io/ljc-dev/pen/NWxJezy. What do you think @neteler?

**Comment by neteler** [comment]
Interesting idea!

**Comment by neteler** [comment]
The "Viewport not set" issue has been addressed in `main` (for the upcoming G8.3.0) and `releasebranch_8_2` (for the upcoming G8.2.1).
The other issues are still open.

**Comment by tmszi** [comment]
Module manual with hamburger menu (hamburger menu icon is showed for screen with width < 1023.99 px and for screen width > 1023.99 original right TOC menu is preserved).

Example `r.basin.fill` module:

Hamburger menu icon (screen width < 1023.99 px):

![module_manual_with_hamburger_menu_icon](https://user-images.githubusercontent.com/50632337/193567543-61cbd718-5c3c-4a8b-82d5-f797e92293ef.png)

Hamburger menu (screen width < 1023.99 px):

![module_manual_with_showing_hamburger_menu](https://user-images.githubusercontent.com/50632337/193568337-0f1a27bf-9862-410e-85ff-dc99f92c3300.png)

Preserved right TOC menu (screen witdh > 1023.99 px):

![module_manual_with_preserved_right_toc_menu](https://user-images.githubusercontent.com/50632337/193568805-7bfa5459-725f-497b-a3d4-5a6fa08ac803.png)

Hamburger menu icon and menu close icon (SVG format) is drawed be me in the Inkscape, with color which respect [GRASS GIS brand](https://grass.osgeo.org/about/brand/).

Example `r.basins.fill` module HTML man page I attached in the ZIP archive [module_html_man_with_hamburger_menu.zip](https://github.com/OSGeo/grass/files/9697233/module_html_man_with_hamburger_menu.zip)

How to test:

A. Localhost

1. `unzip module_html_man_with_hamburger_menu.zip`
2. `firefox-bin module_html_man_with_hamburger_menu/r.basins.fill.html`
3.  Mozilla Firefox _Ctrl + Shift + M_ the keyboard shortcut for responsive design 
4.  Change screen layout width < 1024 px

B. Upload HTML example page into our Apache web server

**Comment by neteler** [comment]
> Hamburger menu (screen width < 1023.99 px):

Works pretty well on my mobile phone!
Could the vertical empty space be removed (i.e., make it more compact)?

**Comment by tmszi** [comment]
> Could the vertical empty space be removed (i.e., make it more compact)?

Something like that (reduced height of empty space between links)?

![menu_with_reduced_height_of_empty_space_between_links](https://user-images.githubusercontent.com/50632337/193729483-8f8c2a28-f013-4735-9324-9a3a73ae29bb.png)

[grassdocs.zip](https://github.com/OSGeo/grass/files/9702598/grassdocs.zip)

**Comment by neteler** [comment]
Thanks, updated here for easy inspection:
https://data.neteler.org/tmp/module_html_man_with_hamburger_menu/r.basins.fill.html

**Comment by veroandreo** [comment]
This is how it looks like on my phone - does not seem responsive when I zoom in further:
![image](https://user-images.githubusercontent.com/20075188/193810793-17cf6772-1079-46ad-84c9-3219a82d7eb0.png)

How to get a responsive zoom level to make it more readable? I liked the zoom level in the last screenshot of @neteler's proposed fix with viewport

**Comment by tmszi** [comment]
> This is how it looks like on my phone - does not seem responsive when I zoom in further

Yes, you are right. This example HTML source code is without @neteler PR #2591  (without fixed viewport).

> How to get a responsive zoom level to make it more readable?

Could @neteler upload this example HTML [r_basins_fill_html.zip](https://github.com/OSGeo/grass/files/9706541/r_basins_fill_html.zip) (with fixed viewport) please? Thanks.

**Comment by neteler** [comment]
> Could @neteler upload this example HTML [r_basins_fill_html.zip](https://github.com/OSGeo/grass/files/9706541/r_basins_fill_html.zip) (with fixed viewport) please? Thanks.

Done:
https://data.neteler.org/tmp/module_html_man_with_hamburger_menu/r.basins.fill.html

**Comment by veroandreo** [comment]
> > Could @neteler upload this example HTML [r_basins_fill_html.zip](https://github.com/OSGeo/grass/files/9706541/r_basins_fill_html.zip) (with fixed viewport) please? Thanks.
> 
> Done: https://data.neteler.org/tmp/module_html_man_with_hamburger_menu/r.basins.fill.html

muuuch better now :)

**Comment by neteler** [comment]
> The "Viewport not set" issue has been addressed in `main` (for the upcoming G8.3.0), `releasebranch_8_2` (for the upcoming G8.2.1), and `releasebranch_7_8` (for the upcoming G7.8.8).

This change has good impact!

![image](https://user-images.githubusercontent.com/1295172/196633071-59dbde97-5633-468b-bf0e-2b7f6eca6116.png)

**Comment by neteler** [comment]
> Could @neteler upload this example HTML [r_basins_fill_html.zip](https://github.com/OSGeo/grass/files/9706541/r_basins_fill_html.zip) (with fixed viewport) please? Thanks.

@tmszi would you be willing to submit the mobile menu change as a PR?

**Comment by tmszi** [comment]
> @tmszi would you be willing to submit the mobile menu change as a PR?

Yes of course PR #2606.

**Comment by neteler** [comment]
FYI: The current state (SEO could still be improved) - compare to above plot:

![image](https://github.com/OSGeo/grass/assets/1295172/fbd76150-ed27-475e-8620-fb34e0956674)

**Comment by neteler** [comment]
Closing as it is pretty ok now.
