### ISSUE TITLE
[Feat] Copy mapset path from Data Catalog with right click

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#2613]
## Is your feature request related to a problem?

When switching between the GUI and Python scripting or CLI, I would find helpful if I can copy a path to mapset (the directory) from the Data Catalog panel (the Data tab).

## Describe the solution you'd like

The context menu (usually opened by right click) should have an item _Copy path to mapset_.

## Describe alternatives you've considered

Individual raster and vector maps have _Copy name_, so mapset and location could have the same. Combining that with copying the directory which is the database would work too, but would lack the speed and thus convenience. 

## Additional context

Current items in the context menu are:

* Paste
* Switch mapset
* Delete mapset
* Rename mapset
* Reload maps

I would use the copied path, e.g., for Python code like this:

```python
with gs.setup.init("/home/janedoe/grassdata/pseudo_mercator/road_network"):
    # ...
```

The related menu:

![Screenshot from 2022-11-14 20-33-15](https://user-images.githubusercontent.com/5449060/201804725-1078950b-84cf-4909-b237-ce0b44b90b4a.png)

**Comment by jalajk24** [comment]
Can I work on this issue? Don't know a lot about how to proceed with this

**Comment by wenzeslaus** [comment]
The steps are something like:

1. Follow [CONTRIBUTING.md](https://github.com/OSGeo/grass/blob/main/CONTRIBUTING.md)
2. Find a place in the code with the menu.
3. Find where in the code (in which data structure) is the information needed.
4. Modify the code.
5. Compile to test (see links contributing or possibly hack a system installation in a virtual machine - crude but may be enough here).
6. Create a pull request.

I have added a screenshot which is showing the current menu to the issue description.

**Comment by firedragonironfist** [comment]
Hello Wenzeslaus , I hope this message finds you well. I came across issue #2613 and I am interested in working on it. Could you please assign this issue to me? I would be happy to contribute to the project and work towards resolving this issue. Thank you in advance for your time and assistance

**Comment by firedragonironfist** [comment]
Thank you for assigning me the #2613 issue. I appreciate the opportunity to contribute to this project and I'm excited to get started on it.

Rest assured that I will approach this task with responsibility and dedication, and I will do my best to complete it as quickly as possible while ensuring a high level of quality.

If there are any specific instructions or requirements that I need to follow, please let me know. I'm here to collaborate and support the project in any way I can.

Thank you again for your trust and support. I look forward to delivering the results soon.

**Comment by firedragonironfist** [comment]
Hey petrasovaa,
I have made a function onCopyMapsetPath
![Screenshot_20230301_185518](https://user-images.githubusercontent.com/91149240/222153087-9daf9fac-af65-4a49-8997-d422e3ed62de.png)

and also added an item copy path to mapset to the context menu 
![Screenshot_20230301_185550](https://user-images.githubusercontent.com/91149240/222153145-57c7a94c-a6ef-400c-a329-aac40c071703.png)

now when I try to use black . on the repo i am getting 166 files changed and I am aware that black is a very powerful tool which gave me some trouble in the past I just wanted to confirm that is it okay that I am getting these many file changes so is it fine or it should give me few file changes?

**Comment by wenzeslaus** [comment]
Maybe a different version of Black. We need to check with the new 2023 version. ...or you have the older one. What is your version?

In the meantime, try to prepare a PR only containing the relevant files and ideally only the relevant lines. Try `git add -p file.py` in command line.

**Comment by firedragonironfist** [comment]
Thank you for letting me know and my version of Black is 23.1.0 is this the right one?
