### ISSUE TITLE
[Bug] r.in.pdal uses deprecated declarations from PDAL

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#2638]
**Describe the bug**

Use of `<<` for LasHeader is deprecated (triggers `-Wdeprecated-declarations`) with PDAL 2.4.1 (May 19, 2022).

The `[[deprecated]]` attribute was added in https://github.com/PDAL/PDAL/pull/3682, but only after previous removal (e.g., https://github.com/PDAL/PDAL/pull/3677), but I don't see an announcement or discussion of the removal. The relevant file in PDAL is [LasHeader.hpp](https://github.com/PDAL/PDAL/blob/master/io/LasHeader.hpp#L68).

**To Reproduce**

1. Get PDAL 2.4.0 or higher.
2. Compile r.in.pdal.
4. See the warning.

**Expected behavior**

No compilation warning, but what the code should do, that's up for discussion.

**Screenshots**

Compilation output:

```
info.cpp: In function ‘void print_lasinfo(StringList*)’:
info.cpp:103:22: warning: ‘std::ostream& pdal::operator<<(std::ostream&, const pdal::LasHeader&)’ is deprecated [-Wdeprecated-declarations]
  103 |         std::cout << las_header;
      |                      ^~~~~~~~~~
In file included from info.h:20,
                 from info.cpp:12:
/usr/local/usrapps/geospatial/grass-8.3.0-dev.2022-11-08/include/pdal/io/LasHeader.hpp:288:26: note: declared here
  288 |     friend std::ostream& operator<<(std::ostream& ostr, const LasHeader& h);
      |                          ^~~~~~~~
info.cpp:103:22: warning: ‘std::ostream& pdal::operator<<(std::ostream&, const pdal::LasHeader&)’ is deprecated [-Wdeprecated-declarations]
  103 |         std::cout << las_header;
      |                      ^~~~~~~~~~
In file included from info.h:20,
                 from info.cpp:12:
/usr/local/usrapps/geospatial/grass-8.3.0-dev.2022-11-08/include/pdal/io/LasHeader.hpp:288:26: note: declared here
  288 |     friend std::ostream& operator<<(std::ostream& ostr, const LasHeader& h);
      |                          ^~~~~~~~
```

**System description (please complete the following information):**

- Operating System: [e.g. Windows, Linux, ..., incl. version]
- GRASS GIS version [e.g. 7.8.4]

**Additional context**

This is not currently tested in the CI.

**Comment by nilason** [comment]
Seems there is no more any method in LASHeader returning a summary. One possibility would be to make a function of our own mirroring the functionality of:

https://github.com/PDAL/PDAL/blob/2.3.0/io/LasHeader.cpp#L524

Most, if not all, info are available one-by-one through its class methods.

**Comment by nilason** [comment]
It is more than a warning. `std::cout << las_header;` doesn't print anything starting with 2.4.
