### ISSUE TITLE
[Feat] Improve parallel support for v.surf.rst deviation and cross-validation

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#2644]
**Is your feature request related to a problem? Please describe.**
When running v.surf.rst, multi-threaded computing of deviations and cross-validation is disabled, because it was not implemented.

**Describe the solution you'd like**
Finish implementation of openmp support. That would include making sure writing to database is not done in parallel.

**Describe alternatives you've considered**
The functionality works with nprocs=1.

**Comment by echoix** [comment]
I think with @cyliang368 's work  in #3590 this can be considered done?
