### ISSUE TITLE
[Feat] Make single-window mode the default

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#2646]
**Is your feature request related to a problem? Please describe.**

From an informal survey, many users switched to single-window mode and did not switch back.

**Describe the solution you'd like**

Let's make single-window module the default for 8.3.0, i.e., change it now in the main branch.

**Describe alternatives you've considered**

Leave it for later, but remove the "experimental" note.

**Additional context**

On the other hand, so people can't find it, so switching in development branch will make it more exposed to testing.

![Screenshot from 2022-11-11 10-25-22](https://user-images.githubusercontent.com/5449060/201371536-8b11f64b-1f30-4523-a5e3-94fbe893d8b0.png)

**Comment by hellik** [comment]
Sounds reasonable

**Comment by neteler** [comment]
Yes, please make single-window mode the default.

**Comment by veroandreo** [comment]
+1 for making single-window the default in 8.3 and get it exposed to more testing! :)

**Comment by baharmon** [comment]
+1
