### ISSUE TITLE
[Bug] grasswiki documentation for interfacing with NumPy

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass#2659]
**Describe the bug**
With the deprecation of grass.script.array's read function with #1926, the documentation on grasswiki [for interfacing with NumPy](https://grasswiki.osgeo.org/wiki/GRASS_Python_Scripting_Library#Interfacing_with_NumPy) is out of date and the first example no longer works.

**To Reproduce**
Run the example from the wiki as a script in GRASS:
```
import grass.script as grass
import grass.script.array as garray

def main():
    map = "elevation.dem"

    # read map
    a = garray.array()
    a.read(map)

    # get raster map info
    print(grass.raster_info(map)['datatype'])
    i = grass.raster_info(map)
    
    # get computational region info
    c = grass.region()
    print("rows: %d" % c['rows'])
    print("cols: %d" % c['cols'])

    # new array for result
    b = garray.array()
    # calculate new map from input map and store as GRASS raster map
    b[...] = (a / 50).astype(int) * 50
    b.write("elev.50m")
```

**Expected behavior**
The example should be updated to:
```
import grass.script as grass
import grass.script.array as garray

def main():
    map = "elevation"

    # read map
    a = garray.array(map)

    # get raster map info
    print(grass.raster_info(map)['datatype'])
    i = grass.raster_info(map)
    
    # get computational region info
    c = grass.region()
    print("rows: %d" % c['rows'])
    print("cols: %d" % c['cols'])

    # new array for result
    b = garray.array()
    # calculate new map from input map and store as GRASS raster map
    b[...] = (a / 50).astype(int) * 50
    b.write("elev.50m")
```

**System description:**

- Operating System: Windows
- GRASS GIS version 8.3

**Comment by neteler** [comment]
It's a Wiki, please feel free to directly update it.

**Comment by veroandreo** [comment]
Contributions to update the GRASS-Python wikis are mostly welcome!

**Comment by baharmon** [comment]
@neteler I just tried to update the wiki and my username/IP is blocked. Can you please unblock me and I'll make the edits
IP address: fd42:c8fe:4a38:47ae:216:3eff:fe97:4594
block ID: 1152.

**Comment by neteler** [comment]
@baharmon I have unblocked you, please try (must have accidentally happened during spam mass removal in the Wiki).
