### ISSUE TITLE
wxGUI: After switching to 3D the map display toolbar is hidden [Bug] 

### ISSUE THREAD

**Issue by lindakladivova** [OSGeo/grass#2672]
**Describe the bug**
This error occurs in both GUI layouts (Single, Multi). After switching to 3D mode in map display, the toolbar hides so that it is not possible to switch back to 2D. (Not happening when switching to Raster and Vector Digitizer).

**To Reproduce**

1. Go to map display toolbar and choose 3D mode option
2. Map display toolbar is suddenly hidden

**Expected behavior**
Map display toolbar should be still visible

**Screenshots**
![Screenshot from 2022-11-30 09-01-15](https://user-images.githubusercontent.com/49241681/204740934-47497381-d65f-4b03-8535-9589299acc41.png)

**System description (please complete the following information):**

- Operating System: [Ubuntu 22.04.1 LTS]
- GRASS GIS version [8.3 (main)]
- wxPython: 4.2.0

**Comment by petrasovaa** [comment]
I can't reproduce this. Do you get an error?

**Comment by lindakladivova** [comment]
No, I do not get any error, the toolbar just disappears. Do you have the same system description?

    Operating System: [Ubuntu 22.04.1 LTS]
    GRASS GIS version [8.3 (main)]
    wxPython: 4.2.0
    Python: 3.10

**Comment by tmszi** [comment]
I can't reproduce this with:

1. OS GNU/Linux (Gentoo distribution)

- Python: 3.11.0, wxPython: 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0
- Python: 3.10.8, wxPython: 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0
- Python: 3.9.15, wxPython: 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5
- Python: 3.8.15, wxPython: 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5

2. OS MS Windows

- Python: 3.9.5, wxPython: 4.2.0 msw (phoenix) wxWidgets 3.2.1

**Comment by lindakladivova** [comment]
Related to Ubuntu and specific wxPython version. Same as as https://github.com/OSGeo/grass/issues/2671.
