### ISSUE TITLE
grass 8.2 and python 3.11

### ISSUE THREAD

**Issue by laurapoggio-sptools** [OSGeo/grass#2677]
I am trying to compile [GRASS-GIS 8.2.0](https://grass.osgeo.org/grass82/source/) with python 3.11. I am getting the error `TypeError: install() got an unexpected keyword argument 'codeset`. 

I see it is addressed [here](https://github.com/OSGeo/grass/issues/2538). 

Is there an option to have this patch without using the whole experimenting/preview branch (8.3)? 

Thanks

**Comment by pesekon2** [comment]
Thanks for opening the issue. 

I have just backported the fix to GRASS 8.2 in 722aaa0ada0a26d09c5dc9a6b25323abe5caaa98 and c726ae1a5f8e933c13746c1ad7fb236283559ca2. Once a new bugfix version will be released (8.2.1), it will be fixed there. But if you are compiling GRASS by your own, update your local copy and recompile it - it should work now.
