### ISSUE TITLE
[Bug] wrong link to citation in g.version manual page

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass#2693]
g.version manual page and GRASS wiki both point to https://grass.osgeo.org/download/ as a place where to look up GRASS citations but the page does not list any citations any more.

g.version manual should be updated to point to the latest page with citation examples. No PR as I have no idea where citation examples are located now.

**Comment by neteler** [comment]
This has been moved to
https://grasswiki.osgeo.org/wiki/GRASS_Citation_Repository

**Comment by neteler** [comment]
> This has been moved to https://grasswiki.osgeo.org/wiki/GRASS_Citation_Repository

Indeed, it is also on https://grass.osgeo.org/about/license/ (discovered thanks to Vero's PR #2695 :-) )
