### ISSUE TITLE
[Bug] GRASS 8.2 not opening in Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by rebecadurso** [OSGeo/grass#2800]
**Describe the bug**
GRASS 8.2.1 does not open in Ubuntu 22.04

**To Reproduce**
1. Compile and install GRASS 8.2.1 in Linux Ubuntu 22.04.1 LTS
2. Click on the GRASS icon in the Ubuntu apps menu or tried run it in terminal
3. See error, GRASS does not open

**Error messages**
`$ grass
Starting GRASS GIS...
Traceback (most recent call last):
  File "/usr/local/bin/grass", line 2748, in <module>
    main()
  File "/usr/local/bin/grass", line 2552, in main
    from grass.grassdb.checks import can_start_in_mapset
ModuleNotFoundError: No module named 'grass.grassdb'
`

**Expected behavior**
The GRASS should open by clicking on it, or when running it from the Linux terminal.

**Screenshots**
GRASS is installed 

![Screenshot from 2023-02-01 16-52-28](https://user-images.githubusercontent.com/57784298/216148580-70d55bf9-acae-40cb-803e-25a624f536f4.png)

**System description**
- Operating System: Linux Ubuntu 22.04.1 LTS
- GRASS GIS version 8.2.1 from [releasebranch_8_2](https://github.com/OSGeo/grass.git)
- Python and wxPython version:
- Python 3.10.6
- wxpython- tools 4.0.7+dfsg-13build1

**Additional context**
I followed instructions for the installation and compilation of Ubuntu 22.04 from [Compile and Install Ubuntu](https://grasswiki.osgeo.org/wiki/Compile_and_Install_Ubuntu)

I have tried to uninstall and install it again, but the error persists.

**Comment by tmszi** [comment]
Hello, Could @rebecadurso  post output of theses commands (from your terminal emulator), please? Thanks.

1.
 `grep 'GISBASE = os.path.normpath("' $(which grass)`

2.
```
grep 'GISBASE = os.path.normpath("' $(which grass) | cut -d '"' -f2 | awk '{print $1"/etc/python/grass"}' | xargs -n 1 ls -l
```

**Comment by rebecadurso** [comment]
Hello!

1. 

 `GISBASE = os.path.normpath("/usr/local/grass82")
`

2.
 `drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 app
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 benchmark
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 exceptions
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 grassdb
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 gunittest
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 imaging
-rw-r--r--  1 spamlab spamlab 4868 fev  1 16:17 __init__.py
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 jupyter
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:18 lib
drwxrwxr-x  2 spamlab spamlab 4096 fev  1 16:17 __pycache__
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 pydispatch
drwxrwxr-x 11 spamlab spamlab 4096 fev  1 16:17 pygrass
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 script
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 semantic_label
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 temporal
drwxrwxr-x  3 spamlab spamlab 4096 fev  1 16:17 utils
 `

3. Output screenshot



![Screenshot from 2023-02-02 10-18-08](https://user-images.githubusercontent.com/57784298/216335401-1fb4e3c6-831a-4a93-8d8a-e6590343f184.png)


Thanks!

**Comment by rebecadurso** [comment]
Thanks, @tmszi! 

Grass 8.2 worked perfectly after running `pip uninstall grass` . I had no idea that I had a pip install of grass-0.1.2

**Comment by neteler** [comment]
Yeah, that totally unrelated python package is creating confusion... no idea what to do about that.

**Comment by nilason** [comment]
Maybe make a check at startup, with a warning...
