### ISSUE TITLE
Problem with i18n #2

### ISSUE THREAD

**Issue by slichtzzz** [OSGeo/grass#2806]
The end of this line is not added to translation file.
In the end, the po-file contains only the larger chunk of this line:

"Coor file of vector <%s@%s> is shorter than it should be (%"

https://github.com/OSGeo/grass/blob/ce08116b890253ee5fc79ba6fda1e43bd8ee3355/locale/templates/grasslibs.pot#L5635

So, the end of this line ("%" PRI_OFF_T " bytes excess") will not be translated. Looks like this happens due to quotes around PRI_OFF_T.

https://github.com/OSGeo/grass/blob/ce08116b890253ee5fc79ba6fda1e43bd8ee3355/lib/vector/Vlib/open_nat.c#L159

**Comment by nilason** [comment]
@slichtzzz  Thanks for reporting this!
#2807 will, when merged, fix this for the dev version (on main) and eventually backported also for 8.2 branch (coming 8.2.2).
