### ISSUE TITLE
[Bug] GitHub sunsetting SVN on January 8, 2024 : g.extension and grass impacts

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#2834]
**Describe the bug**
GitHub has announced at the end of January 2023 that SVN support will end at the beginning of January 2024, in 11 months as of now. In there blog post, https://github.blog/2023-01-20-sunsetting-subversion-support/  we clearly understand that it is a very reasonable decision, and the impacted users are small: about 5000 repos have at least one SVN request each month. 

However, I do remember a discussion that SVN was still needed for extension installs. I understood at that time that source code downloads didn't use git, and may still use SVN in some cases. 

The goal of this issue here is to find cases where SVN is used and not git for operations with GitHub repos. It is not necessarily a request to remove SVN, SVN can still be hosted, but no longer with GitHub after January 2024. 

**Expected behavior**

A discussion about the extension install process might be pertinent too, if it is to be reworked on in the next year. If changes must be made, probably earlier would be better in order to not lock out users installing from Linux repos, but it's probably not like the whole application wouldn't work anymore, only one specific extension install source, when there are some alternatives (as I understood). 

**Screenshots**

**System description (please complete the following information):**

- Operating System: [e.g. Windows, Linux, ..., incl. version]
- GRASS GIS version [e.g. 7.8.4]

**Additional context**

Should this be transferred to the grass-addons repo? I chose here since it's where the g.extension code is located. As for the mailing list, if there are a lot of recipients that could be concerned that don't also follow this repo, maybe a ping might trigger discussion.

**Comment by ninsbl** [comment]
Thanks @echoix for the heads-up!

The reason SVN is still used is that `g.extension` has to checkout only parts / subdirectories of the addon source tree. One attempt to sunset svn in GRASS code was using Github API:
https://github.com/OSGeo/grass/issues/625#issuecomment-747305138
However, the drawback of the API is that it has a rate limit of a few requests an hour, so this approach was not implemented then. However, the article you link addresses exactly our use-case and mentions sparse checkouts (amongst others) as a new git feature, and that looks very promising.
From my point of view, we should implement that and drop SVN...

I can put that on my to-do list...

**Comment by echoix** [comment]
Closed by #2895
