### ISSUE TITLE
Docs about investigating history outdated

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#2864]
The following section in the investigating_history.md file is now outdated. 
https://github.com/OSGeo/grass/blob/78243ae0ab06acff51aa4269f721b7901b697658/doc/git/investigating_history.md?plain=1#L31-L35

This blog post announced the functionality in March 2022: https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
And this is the documentation for it: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

We are now using a .git-blame-ignore-revs file for a while now.

Is there anything else than deleting that section that would be appropriate?

**Comment by wenzeslaus** [comment]
Deleting sounds good to me.
