### ISSUE TITLE
[Feat] Fix compiler warnings from -Wpedantic

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#2880]
Compiling with -Wall -Wextra and `-Wpedantic` triggers a number of mostly (if not only) trivial warnings.
Addressing these warnings contribute to keep the code in good shape according to ISO standards, moreover potentially enables the use of -Wpedantic in combination with -Werror.

Following warnings are issued:

- -Wstrict-prototypes #2870
- -Winvalid-utf8 #2873
- -Wextra-semi #2871
- -Wformat-pedantic #2872
- -Wempty-translation-unit #2874
- -Wgnu-pointer-arith #2875
- -Wpedantic #2876
- -Wembedded-directive #2877
- -Wformat #2878
- -Woverflow #2879

Follow-up on #2747.

Background in parenthesis:
The initial reason for looking at also this level of warnings, was the four GCC CI runs, which all behaves as one and the same. I believe there is potential to reduce them to one runner. But that is a question for another issue.

**Comment by wenzeslaus** [comment]
> ...the four GCC CI runs, which all behaves as one and the same.

Part of the original motivation was indeed the different levels of required "code correctness" and understanding that while version A works, it not okay for version B. However, the other reason was compatibility. It explicitly checks all supported versions. I also remember fixing some C++ issue where two different versions allowed two different constructs, but only one one of these was accepted by both. However, I don't remember if this was more about compiler versions (both clang and GCC) or about standard versions. It was also without the pedantic behavior. The tests for all supported versions still makes sense to me, though.

**Comment by nilason** [comment]
GRASS code in itself now compiles without errors using -Wpedantic, only #2899 is needed to enable the flag on the CI runners.
