### ISSUE TITLE
[Bug] Python: other as advertised no support of ~ in the path for user home directory

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2928]
Here
https://github.com/OSGeo/grass/blob/ca1bc800aab76881122c59f32d7e1d7fa551267f/python/grass/script/setup.py#L317

it is said that `~` should be supported in the path for user home directory.

The attached [grass-session](https://github.com/zarch/grass-session) script (from `docker/testdata/test_grass_session.py`) [test_grass_session.py.gz](https://github.com/OSGeo/grass/files/11283447/test_grass_session.py.gz) which needs [simple.laz](https://github.com/PDAL/PDAL/raw/master/test/data/laz/simple.laz) shows the following error:

```
# cleanup
rm -rf ~/grassdata/test/

# run GRASS GIS session
python test_grass_session.py 
grass-session: tests for PROJ, GDAL, PDAL, GRASS GIS
{'GISDBASE': "'~/grassdata/';", 'LOCATION_NAME': "'test';", 'MAPSET': "'PERMANENT';"}
access: No such file or directory
ERROR: LOCATION <~/grassdata//test> not available
Traceback (most recent call last):
  File "/tmp/test_grass_session.py", line 19, in <module>
    gs.run_command(
  File "/home/mneteler/software/grass82/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 541, in run_command
    return handle_errors(returncode, result=None, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mneteler/software/grass82/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 429, in handle_errors
    raise CalledModuleError(module=module, code=code, returncode=returncode)
grass.exceptions.CalledModuleError: Module run `r.in.pdal --o -g input=/tmp/simple.laz output=count_1 method=n resolution=1` ended with an error.
The subprocess ended with a non-zero return code: 1. See errors above the traceback or in the error output.
```

Specifying the full path to `grassdata` solves this issue but could be better.

**Comment by wenzeslaus** [comment]
Thank you for the report @neteler. This is not related to the referenced code, but to a 3rd party package. If there are any references to it in the documentation of OSGeo/grass, they should be removed.

Seriously, the grass-session package should not be needed to run GRASS GIS. If GRASS GIS needs a fix, let's fix it.

**Comment by neteler** [comment]
Please point me to documentation how to avoid grass-session.

**Comment by wenzeslaus** [comment]
I would recommend the [grass.script.setup](https://grass.osgeo.org/grass82/manuals/libpython/grass.script.html#module-grass.script.setup) documentation or [doc/notebooks/scripting_example.ipynb](https://github.com/OSGeo/grass/blob/main/doc/notebooks/scripting_example.ipynb) ([binder](https://mybinder.org/v2/gh/OSGeo/grass/8.2.1?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fscripting_example.ipynb)).
