### ISSUE TITLE
[Bug] r.sun gives erroneous results when used with r.horizon for a 15 deg slope hillock

### ISSUE THREAD

**Issue by girishnand** [OSGeo/grass#2935]
**Describe the bug**

Output of r.sun is radically different based on whether r.horizon is or is not used. The difference is significant both qualitatively as well as quantitatively. 

![rsun1](https://user-images.githubusercontent.com/117836741/234604860-fc93e8cf-253b-4dc8-8bdc-70bb63edca06.jpg)

![rsun2](https://user-images.githubusercontent.com/117836741/234604896-b09e230b-37de-483a-966b-6e60491223a3.jpg)

The elevation raster is a small square hillock with a flat square central region and surfaces sloping downward at 15 degrees towards north, south, east and west to its north, south, east and west respectively. The location lat-long are Latitude : 34.179N, and Longtitude : -118.556. The output rasters above show Global Insolation for April 15th. 

Here's the input raster file: [hot.txt](https://github.com/OSGeo/grass/files/11333764/hot.txt)

For this location at 34 deg N, we can expect the south face to have the greatest insolation and the north face to have the least. This is what the output without r.horizon shows, but the case where r.horizon is used shows the exact opposite. I have used r.horizon with 10 degree horizon steps, but the result with horizon_step=5 is the same. 

**To Reproduce**
```shell
#I use epsg:32611 corresponding to UTM zone 11N for the above lat-long.  
g.proj -c epsg=32611 location=MyLocation
g.mapset mapset=PERMANENT location=MyLocation

r.in.gdal -o input=file-path\hot.txt output=hotraster
g.region raster=hotraster

r.latlong input=hotraster output=hotlatitude
r.latlong input=hotraster output=hotlongitude -l
r.slope.aspect elevation=hotraster slope=slope aspect=aspect

r.horizon elevation=hotraster step=10 output=hor10angle distance=0.5

r.sun elevation=hotraster horizon_basename=hor10angle horizon_step=10 slope=slope aspect=aspect lat=hotlatitude long=hotlongitude step=0.25 nprocs=10 day=105 glob_rad=Apr15h10 --verbose

r.sun elevation=hotraster slope=slope aspect=aspect lat=hotlatitude long=hotlongitude step=0.25 nprocs=10 day=105 glob_rad=Apr15 --verbose
```

**Expected behavior**
The output with and without r.horizon should be identical for the most part. The south facing slope should show the greatest global insolation compared to the other faces. There is also a slight east-west asymmetry in the output when r.horizon is used. For a symmetric raster aligned with the cardinal directions, this should not be so. 

**System description (please complete the following information):**
I am using Windows 11 with the following GRASS GIS 8.3 developmental build - WinGRASS-8.3.dev-c05cc14387-42-Setup.exe But results with 8.2.1 which has been released are identical. 
```
C:\Users\Girish>g.version -rge
version=8.3.dev
date=2023
revision=c05cc14387
build_date=2023-04-24
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=a82501dc85
libgis_date=2023-02-27T12:45:25+00:00
proj=9.2.0
gdal=3.6.4
geos=3.11.2
sqlite=3.41.1
```

regards,
Girish.

**Comment by petrasovaa** [comment]
This bug was introduced in 688d5885, which changes r.horizon output. @mmetz any opinion how to address this?

**Comment by petrasovaa** [comment]
Possible fix would be to leave horizon output as it is now and ignore negative values in r.sun:
```
diff --git a/raster/r.sun/main.c b/raster/r.sun/main.c
index 3ed5f93711..4e171b0295 100644
--- a/raster/r.sun/main.c
+++ b/raster/r.sun/main.c
@@ -1015,7 +1015,7 @@ int INPUT_part(int offset, double *zmax)
 
                     horizonpointer[i] =
                         (char)(rint(SCALING_FACTOR *
-                                    AMIN1(horizonbuf[i][j], 256 * invScale)));
+                                    AMIN1(AMAX1(horizonbuf[i][j], 0.), 256 * invScale)));
                     horizonpointer += arrayNumInt;
                 }
             }

```

**Comment by girishnand** [comment]
If r.horizon computes horizon angles solely based on raster elevations, it can be expected to generate unrealistically high (low) negative horizon angles whenever we have steep outward slopes adjacent to the raster boundaries. In reality, more distant geographical features outside the raster's boundaries will limit how low negative horizon angles can go. But we will see (slightly) negative horizon angles even in reality, for example on top of a high mountain in the middle of a plain. 

Is this what is happening?  

By the way, this effect (of greater insolation on the northern sloping face, compared to the south side) reduces as I steepen the slopes of my hillock. It disappears for slopes steeper than 60 degrees. 

regards,
Girish.

**Comment by metzm** [comment]
@petrasovaa Back then it was regarded as a bug that r.horizon did not handle negative angles, even though they are expected to occur in reality. Maybe it could help if tanh0 is not initialized with -inf, but some realistic negative value? The result of atan(-inf) as returned by searching would be -90 degrees.

**Comment by girishnand** [comment]
On a spherical earth of radius 'R', a crow's nest of a sailing ship located at a height 'h' above sea level will have a (negative) horizon angle of - 

    theta = - arccos( R/(R+h) ) 

If we ignore regions of the earth which lie below sea level, this can be taken as a lower bound for the horizon angle for a point at an altitude h. (More complex formulae can be derived for ellipsoids, if desired.) Elevation rasters will have to be specified as elevations above sea level, which may not be the case at present. 

For the highest point on earth, this comes to - 

    theta = -arccos(6378100/(6378100+8848)) = -3.01622438 degrees, 

which is quite low. So zero may be a reasonable first approximation. 

Unless r.horizon already does something similar and r.sun is breaking even for these low negative horizon angles? 

regards,
Girish.

**Comment by metzm** [comment]
@ girishnand You also need to correct for earth curvature, and there is a maximum distance option in `r.horizon`. Taken together, it is technically possible to get a horizon angle of close to -90 degrees in special cases.

I had a closer look at the outputs of `r.horizon` with and without allowing negative angles using the test case above. The results are nearly identical, often differing only by something smaller than 1e-23 degrees which is practically zero with single precision floating point. Therefore it is quite surprising that such small differences lead to such large differences in `r.sun`. I suspect that neither `r.horizon` nor `r.sun` can properly handle negative horizon angles.

Moreover, I go numerical instability in some pixels with apparent outliers in the output of `r.horizon`, and these arbitrary factors of 0.0001 and 0.0000001 at https://github.com/OSGeo/grass/blob/main/raster/r.horizon/main.c#L1172 and following make things worse.

Therefore my change from back then could be reverted and `r.horizon` would again produce only positive angles until a proper fix to support negative angles in both `r.horizon` and `r.sun` is available.

**Comment by girishnand** [comment]
@metzm The formula - `theta = - arccos( R/(R+h) ) `, does account for the earth's curvature - at least for a spherical earth. 

The figure below shows the horizon angle theta seen at point D which is at a height h above MSL (shown as a distance of R+h from the earth's center). Line of sight from D is tangential to the earth's surface at point E. 

![image](https://user-images.githubusercontent.com/117836741/236285645-f1da5a12-08e6-4793-9f76-60b294034071.png)

Applying this formula to the highest point on earth - Mount Everest at 8848m above MSL, and assuming that all of the surroundings are at sea level, gives us a horizon angle of -3.016 degrees. This suggests that a horizon angle more negative than this should be impossible in the real world. Could you provide a real-world counterexample? 

Reverting back to permitting only positive horizon angles may be best for the present.  

regards,
Girish.

**Comment by girishnand** [comment]
@metzm @petrasovaa 

This is a sample horizon raster generated using the following command sequence: 

```
g.proj -c epsg=32611 location=MyLocation
g.mapset mapset=PERMANENT location=MyLocation
r.in.gdal -o input=<file-path>\hot.txt output=hotraster
g.region raster=hotraster
r.horizon elevation=hotraster step=10 output=hor10angle distance=0.5

```
[hot.txt](https://github.com/OSGeo/grass/files/11403304/hot.txt) (This is the same file as I've posted earlier in this thread.) 

The raster shown is hor10angle_000, i.e. the horizon raster for a horizon direction of 0.0 degrees, meaning due east. I have marked raster values in each of the five regions where they occur on the image. 

![horizon-raster](https://user-images.githubusercontent.com/117836741/236374874-b5bda690-e567-43e9-a79d-65ed7dfebed7.jpg)

Horizon angle values on the four sloping surfaces are all as expected to occur when looking due east. Horizon angle on the eastern slope is -0.262 rad, which is -15 degrees, while that on the western slope is +15 degrees. Horizon angles on the northern and southern faces are approximately zero, which is also as expected. 

@metzm Could you provide more details of the comparison you did? I would expect the eastern slope horizon angle of -15 degrees seen above, to change to zero if negative horizon angles are disallowed. 

The major anomaly however is the central flat surface which shows a horizon angle of -1.57 radians, i.e., -90 degrees, instead of the expected zero! This anomaly is seen in all the direction rasters generated by r.horizon for this test case. 

There is also dark vertical strip a few pixels away from the eastern edge of the image, indicating a horizon angle value of -90 degrees there too. This too occurs in almost all of the 36 horizon rasters generated by the above sequence of commands, and always near the lower edge of faces (one or two) which have a negative horizon angle in that raster. 

I am unable to presently say what this does to r.sun. 

regards,
Girish.

**Comment by girishnand** [comment]
One possible issue - 

In the following snippet of code at https://github.com/OSGeo/grass/blob/main/raster/r.horizon/main.c#L936,  - 

```
        z2 = z_orig + curvature_diff + length * tanh0;
        zp100 = z100[jp100][ip100];
        G_debug(2, "ip:%d jp:%d z2:%lf zp100:%lf \n", ip, jp, z2, zp100);

        if (zp100 <= z2)

```
the check ```zp00 <= z2``` is valid only if ```tanh0``` is positive in the earlier computation of ```z2```. This assures that any increases in ```length``` can only increase ```z2``` further, and so if the condition ```zp100 <= z2``` is true, it will continue to remain so. 

If ```tanh0``` is negative, traversing that direction further and increasing ```length``` can instead lower ```z2```, possibly putting it below the value of ```zp100``` within the self-same low res (100x100) square. So, logic of skipping the whole low-resolution square is no longer valid. 

Have not thought of a fix yet. 

regards,
Girish.

**Comment by girishnand** [comment]
An unrelated Issue: 

For the case when the ```coordinates=east,north``` command line argument has been invoked and we are interested in the horizon for just a single point, the variables ```distcosangle``` and ```distsinangle``` are not initialized anywhere, and so carry their global initialization value of ```0``` throughout. Calls to the function ```test_low_res()``` at https://github.com/OSGeo/grass/blob/main/raster/r.horizon/main.c#L917 (in which these variables are used) therefore do not alter the values of ```xx0``` and ```yy0``` as expected at https://github.com/OSGeo/grass/blob/main/raster/r.horizon/main.c#L969. The code should still work, but the speedup for which this function has been introduced will not be obtained. 

This may be related to the fact that the function ```void com_par(double angle)``` (which initializes ```distcosangle``` and ```distsinangle```) at https://github.com/OSGeo/grass/blob/main/raster/r.horizon/main.c#L721 is not called anywhere in the code. 

regards,
Girish.

**Comment by wenzeslaus** [comment]
@girishnand Given the r.horizon versus no r.horizon issue was resolved, I'm closing this one.  Please, the open a new issue for the other things mentioned here to start a fresh discussion.
