### ISSUE TITLE
v.in.ogr: GUI works fine, CLI cannot read input file.with FileGDB input source [Bug] 

### ISSUE THREAD

**Issue by rs-aesi** [OSGeo/grass#2952]
**Describe the bug**
Using the CLI (bash shell) and specifying the input and output file names to v.in.ogr result in the error, "unable to open input file." Yet, using the GUI the v.in.ogr dialogue box tab for 'Required' information has a text entry widget for file type and 2 radio buttons to specify the input as a file or a directory. The command in the dialog box's status line does not show either the selected input data type nor whether it's a file or directory.

**To Reproduce**

`Invoke` a grass session using the location and mapset of your choide within a virtual terminal using the shell prompt. Enter 'v.in.ogr input=<a` FileGDB directory name>  output=<your desired output name>. You can add a layer specification if desired,. Press the Enter key. Grass responds with 'cannot read file name' or somehthing siimilar, I forget the exact wording but it means grass doesn't recognize the FileGDB as a directory.

**Expected behavior**
We expect the file to be imported. The v.in.ogr manual page (and implementation of the module itself) needs to allow user entry of the import data format (FileGDB in my uses) and that it's a directory  and not a file name like a shapefile.

**Screenshots**

**System description (please complete the following information):**

- Operating System: Slackware64-15.0
- GRASS GIS version 8.3.dev (but it has been an issue on the CLI  for a long time.

**Additional context**
I'm actually surprised that no one's noticed this before me. When I remember why the CLI command fails I start a new grass session using the GUI and move ahead with my project.

**Comment by petrasovaa** [comment]
It would be helpful to see the exact errors.

**Comment by petrasovaa** [comment]
You have a dot after NHDFlowline.shp, try to remove it.

**Comment by rs-aesi** [comment]
On Tue, 9 May 2023, Anna Petrasova wrote:

> You have a dot after NHDFlowline.shp, try to remove it.

Missed hat, Anna. Thanks.

Rich
