### ISSUE TITLE
[Bug]  ps.map Colortable is mis-leading name

### ISSUE THREAD

**Issue by rs-aesi** [OSGeo/grass#2961]
**Describe the bug**
"Colortable" is ambiguous and misleading. It implies a table to change the color patter of a raster map, similar to r.colors. It does not specify its purpose in creating a raster map legend.

**Expected behavior**
A ps.map option to create a raster map legend should be called 'rlegend', analygous to the vector map legend option, vlegend.

**Comment by neteler** [comment]
Since this would be an API break I suggest to leave it for GRASS GIS 9.

**Comment by wenzeslaus** [comment]
We can also implement this with backwards compatibility by introducing an alias. Little more work, but it can be done anytime. Good "first-time" issue.

**Comment by wenzeslaus** [comment]
I cleaned up the description from the things from the template.

@rs-aesi Can you please link the relevant documentation, provide example, ideally executable one and, if possible, find and link the relevant code. This would help someone who would be willing to pick this up to get started.

**Comment by rs-aesi** [comment]
On Thu, 9 Nov 2023, Vaclav Petras wrote:

> I cleaned up the description from the things from the template.

Thanks, Vaclav.

Regards,

Rich
