### ISSUE TITLE
[Bug] g.extension test often times out in CI

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#2979]
**Describe the bug**

The `scripts/g.extension/testsuite/test_addons_download.py` test times out quite often.

Duration of a successful execution in the CI is 1 min 42 sec. The time out is currently set to 4 mins.

**To Reproduce**

Hard to say if this specific issue can be reproduced locally, but happens quite often on main and in PRs at least for the macOS job.

Locally, the test fails for me and runs around 3 min 20 sec, but given that `test_github_download_official_module_src_code_only` test (function) fails, I don't know if the longer run time is relevant to the CI issue.

**Expected behavior**

Test always finishes successfully in the given time limit (whatever that is).

**Screenshots**

```
Running ./scripts/g.extension/testsuite/test_addons_download.py...
========================================================================
WARNING: Bug in UI description. Missing module description
.......========================================================================
FAILED ./scripts/g.extension/testsuite/test_addons_download.py - Timeout >300.0s
```

**System description**

- Operating System: macOS in CI virtual machine
- GRASS GIS version: main

**Comment by tmszi** [comment]
With using new `git sparse-checkout ` getting last commit with `git log -1 src/vector/v.surf.tps/` takes quite a long time (instead of calling GitHub REST API) during addon installation. And that's the source of the problem, why the tests time out.

Example:

```
test@test:/tmp$ git clone --no-checkout --branch grass8 --filter=tree:0 https://github.com/OSGeo/grass-addons.git

test@test:/tmp$ cd grass-addons/ && git sparse-checkout init && git sparse-checkout set src/vector/v.surf.tps/ 

test@test/tmp/grass-addons$ git checkout grass8

test@test:/tmp/grass-addons$ time git log -1 src/vector/v.surf.tps/

real	0m35.294s
user	0m0.710s
sys	0m0.296s
```
Get addon last commit take 35 s.

**Comment by tmszi** [comment]
> Do you have time to estimate the time either locally or by downloading couple of test results from CI and then increasing the time limit? ...maybe just increasing the time for macOS in this case (I think it still has a separate config file).

I ran the test locally and the time result is 12m.

```
Ran 9 tests in 741.623s
OK

real	12m21.752s
```

**Comment by tmszi** [comment]
> It may be related to the version of git and there may be ways to I.prove the performance of git log: https://stackoverflow.com/questions/35186829/how-to-improve-git-log-performance

`git log -1` is fast with fully cloned repository, but is slowly if repo is cloned with `git clone --no-checkout --branch grass8 --filter=tree:0` and  `git sparse-checkout init` is used.

My Git version is 2.39.3.
