### ISSUE TITLE
[Bug] r.fillnulls reports "Input map has no holes" with method=rst

### ISSUE THREAD

**Issue by geografin** [OSGeo/grass#2986]
**Describe the bug**
r.fillnulls grass command reports "Input map has no holes" with rst method when I process a raster without NaN values.

**To Reproduce**

1. Load a raster without NaN values to any grass mapset.
2. start r.fillnulls command for this raster with defaults
3. See error "Input map has no holes"

**Expected behavior**
r.fillnulls should check for NaNs and copy the input map to desired location with desired name without changing it if it has no NaN values. I the g.region is smaller than the map, it should export to the output only the extent of this region of course.

**System description (please complete the following information):**

- Operating System: Linux Centos
- GRASS GIS version 8.2

**Comment by neteler** [comment]
I have made a test with a sample map which does not contain any hole (North Carolina sample dataset):

A) using `method=bilinear` (works as expected):

```
g.region raster=elevation
r.fillnulls input=elevation output=elev_fill_test method=bilinear
Using bilinear bspline interpolation
Copy raster <elevation@PERMANENT> to current mapset as
<r_fillnulls_1844093_filled>
WARNING: Input map <elevation> has no holes. Copying to output without
         modification.
Patching fill data into NULL areas...
 100%
Filled raster map is: elev_fill_test
Done.
```

B) using default `method=rst`  method:

```
g.region raster=elevation
r.fillnulls input=elevation output=elev_fill_test2
Using RST interpolation...
Locating and isolating NULL areas...
 100%
Growing NULL areas
Assigning IDs to NULL areas
 100%
ERROR: Input map has no holes. Check region settings.
```

Expected would be: "Copying to output without modification." also for `method=rst` in case of no holes.
Solution: The copying process as done with `bilinear` method should also be run in case of `rst`.
