### ISSUE TITLE
g.extension fetch and install, fails to install r.basin packages in grass gis 8.4 dev on windows (admin modus)   

### ISSUE THREAD

**Issue by rengifoo** [OSGeo/grass#2989]
**The bug**
g.extension --verbose extension=r.stream.distance                               
Downloading precompiled GRASS Addons <r.stream.distance>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass84/addons/grass-8.4.0dev/r.stream.distance.zip>: HTTP Error 404: Not Found
(Wed May 31 13:27:16 2023) Command ended with non-zero return code 1 (3 sec)    

**Steps to reproduce the behavior:**

1. Install grass 8.4 dev for  testing jupyter lab
2. Open GRASS Command Line
3. Add GRASS to path variables with :set PATH=%PATH%;C:\Program Files\GRASS GIS 8.3\
4. Launch jupyter lab with python -m jupyter lab
5. try to import r.stream.distance into jupyter lab got the following error " 'r.stream.distance' is not recognized as an internal or external command,operable program or batch file."
6. try to install it  from  grass gui 8.4 in admin modus and without admin 
7. got the following message " Downloading precompiled GRASS Addons <r.stream.distance>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass84/addons/grass-8.4.0dev/r.stream.distance.zip>: HTTP Error 404: Not Found (Wed May 31 13:27:16 2023) Command ended with non-zero return code 1 (3 sec) "

8. try to install it on grass 8.2 and 7.8 and it works but jupyter package is not implemented  in any of those versions

Thanks for looking into it.

 Extra information. To run the jupyter notebook I use this recipe

https://github.com/ncsu-geoforall-lab/GIS714-assignments/blob/main/GRASS_GIS_Foundations/JupyterOnWindows_Tutorial.ipynb

best regards
Rengifo Ortega
**T:LO tangible objects**

**Comment by neteler** [comment]
> ERROR: Cannot open URL http://wingrass.fsv.cvut.cz/grass84/addons/grass-8.4.0dev/r.stream.distance.zip: HTTP Error 404: Not Found

@landam The directory `grass84/` is missing from https://wingrass.fsv.cvut.cz/ (`main` in the GitHub repository now contains G84, after the G83 release branch creation).
Can you please add it?
