### ISSUE TITLE
[Bug] Default single-window size is too small to see anything

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass#3013]
**Describe the bug**

When I open the GUI using `g.gui`, the default size is extremely small and covers more-or-less only the tabs. See the screenshot below.

**To Reproduce**

`g.gui`

**Screenshots**

![image](https://github.com/OSGeo/grass/assets/17025405/17ed06b1-fc20-4ae4-a16b-73121ef90396)

**System description:**

```
System Info                                          
Operating System: Debian testing                           
GRASS version: 8.4.0dev      
Code revision: e887353f6c
Python: 3.11.2
wxPython: 4.2.0 gtk3 (phoenix)
wxWidgets: 3.2.2
libgtk-3-0: 3.24.37
```

**Comment by veroandreo** [comment]
I get the same after a clean recompilation and switch to 8.4dev. At the end of the compilation I get: 
```
--------------------------------------------------
Started compilation: Sun Jun  4 01:30:28 PM -03 2023
--
Errors in:
/home/veroandreo/software/grass-dev/python/libgrass_interface_generator
--
In case of errors please change into the directory with error and run 'make'.
If you get multiple errors, you need to deal with them in the order they
appear in the error log. If you get an error building a library, you will
also get errors from anything which uses the library.
--
Finished compilation: Sun Jun  4 01:32:15 PM -03 2023
make: *** [Makefile:71: default] Error 1
```
and when starting grassdev I get tons of GTK errors in the terminal.

```
System Info                                                                     
GRASS version: 8.4.0dev                                                         
Code revision: e887353f6c                                                       
Build date: 2023-06-04                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.4.3                                                                     
PROJ: 8.2.1                                                                     
GEOS: 3.10.2                                                                    
SQLite: 3.36.0                                                                  
Python: 3.10.11                                                                 
wxPython: 4.0.7                                                                 
Platform: Linux-6.2.15-100.fc36.x86_64-x86_64-with-glibc2.35                    
```

**Comment by tmszi** [comment]
I have not been able to reproduce this behavior on Gentoo GNU/Linux distribution with Python 3.10.11 and wxPython
4.2.0 gtk3 (phoenix) wxWidgets 3.2.2.1.

**Comment by tmszi** [comment]
> and when starting grassdev I get tons of GTK errors in the terminal.
> 
> ```
> System Info                                                                     
> GRASS version: 8.4.0dev                                                                                                                      
> Python: 3.10.11                                                                 
> wxPython: 4.0.7                                                                                  
> ```

If  it possible, you would update the wxPython version to 4.2.0, please.

**Comment by pesekon2** [comment]
> If it possible, you would update the wxPython version to 4.2.0, please.

Sorry, forgot to mention that. I am using wxPython 4.2.0. Adding it also to the first post. 

```
System Info                                                                     
GRASS version: 8.4.0dev      
Code revision: e887353f6c
Python: 3.11.2
wxPython: 4.2.0
```

**Comment by tmszi** [comment]
With Python 3.11.3 and self compiled wxPython 4.2.0 (or last code from wxPython master Git branch) i get error:

```
GRASS tmploc/PERMANENT:~ > g.gui
Launching <wxpython> GUI in the background, please wait...
<gui_core.wrap.Menu object at 0x7ff9a315c5e0> 5002 New	Ctrl+N Create new workspace 0
Traceback (most recent call last):
  File "/home/tomas/src/wxpython-master-branch/venv-py3.11/lib/python3.11/site-packages/wx/core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/grass84/gui/wxpython/wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/grass84/gui/wxpython/lmgr/frame.py", line 160, in __init__
    self._createMenuBar()
  File "/usr/lib64/grass84/gui/wxpython/lmgr/frame.py", line 348, in _createMenuBar
    self.menubar = GMenu(
                   ^^^^^^
  File "/usr/lib64/grass84/gui/wxpython/gui_core/menu.py", line 48, in __init__
    self.Append(self._createMenu(child), child.label)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/grass84/gui/wxpython/gui_core/menu.py", line 56, in _createMenu
    subMenu = self._createMenu(child)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/grass84/gui/wxpython/gui_core/menu.py", line 62, in _createMenu
    self._createMenuItem(menu, label=child.label, **data)
  File "/usr/lib64/grass84/gui/wxpython/gui_core/menu.py", line 98, in _createMenuItem
    menuItem = wx.MenuItem(parentMenu=menu, id=wxId, text=label, helpString=helpString, kind=kind)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MenuItem(): argument 'id' has unexpected type 'StandardID'
```

**Comment by lindakladivova** [comment]
I came to the same problem as @pesekon2 had. I created the PR #3024 for it. Seems that the method Fit() was contraproductive.

Unfortunately, I could not reproduce the error @tmszi mentioned. I have these settings:

GRASS version: 8.3.dev                                                          
Code revision: f7d35e87a9                                                       
Build date: 2023-06-02                                                                                                                                                                                  
Python: 3.10.6                                                                  
wxPython: 4.2.0

**Comment by tmszi** [comment]
> > With Python 3.11.3 and self compiled wxPython 4.2.0 (or last code from wxPython master Git branch) i get error:
> > `...`
> 
> I don't get any error message. The link provided by @tmszi says that the issue didn't pop on GTK, but did on MSW. I am GTK-based (`libgtk-3-0==3.24.37`). @tmszi, are you MSW-based, by chance?

No I'm not MSW based.

```
=x11-libs/gtk+-3.24.37
Python 3.11.3
4.2.0 gtk3 (phoenix) wxWidgets 3.2.2.1
```

**Comment by tmszi** [comment]
Could @pesekon2 post complete output of command `python -c "import wx, print(wx.version())"`, (important is wxWidgets version), please?

**Comment by pesekon2** [comment]
> 

`4.2.0 gtk3 (phoenix) wxWidgets 3.2.2`
