### ISSUE TITLE
Add JSON and YAML C library dependency

### ISSUE THREAD

**Issue by cwhite911** [OSGeo/grass#3020]
### Discussed in https://github.com/OSGeo/grass/discussions/3019

<sup>Originally posted by **cwhite911** June  5, 2023</sup>
In an effort add additional output data formats to modules (e.g., r.report, r.info, etc..) we are discussing adding new library dependencies to aid in JSON and  YAML encoding.

Please share your feedback on the following candidate dependencies. 

## JSON

**parson**
https://github.com/kgabis/parson/
Current release: 1.5.2 (2023)

Parson is a lightweight [json](http://json.org/) library written in C.

- [X] Linux
- [X] Windows
- [X] Mac OSX

## YAML

**libyaml**
https://github.com/yaml/libyaml
Current release: 1.2.2 (2021-10-01)

LibYAML is a YAML parser and emitter library.

- [X] Linux
- [X] Windows
- [X] Mac OSX

## Related Issues and PRs

* https://github.com/OSGeo/grass/pull/2666
* https://github.com/OSGeo/grass/pull/2542
* https://github.com/OSGeo/grass/pull/2386
* https://github.com/OSGeo/grass/pull/2258
* https://github.com/OSGeo/grass/pull/476
* https://github.com/OSGeo/grass/pull/3033

## Candidate Modules 

Which modules should have JSON & YAML output support?

### General

- [x] g.mapsets https://github.com/OSGeo/grass/pull/2542
- [x] g.region (GSoC) https://github.com/OSGeo/grass/pull/3941
- [ ] g.proj (GSoC) https://github.com/OSGeo/grass/pull/4104
- [ ] g.mapset
- [ ] g.list
- [ ] g.version
- [ ] etc..

### Raster

- [x] r.univar (GSoC) https://github.com/OSGeo/grass/pull/3783
- [x] r.report https://github.com/OSGeo/grass/pull/3033
- [x] r.info (GSoC) https://github.com/OSGeo/grass/pull/3744
- [x] r.kappa https://github.com/OSGeo/grass/pull/2666
- [x] r.horizon https://github.com/OSGeo/grass/pull/3768
- [x] r.what (GSoc) https://github.com/OSGeo/grass/pull/3528
- [x] r.profile (GSoC) https://github.com/OSGeo/grass/pull/3872
- [x] r.category (GSoC) https://github.com/OSGeo/grass/pull/4018
- [x] r.object.geometry (GSoC) https://github.com/OSGeo/grass/pull/4105
- [ ] r.stats (GSoC) https://github.com/OSGeo/grass/pull/3884
- [ ] r.colors.out https://github.com/OSGeo/grass/pull/4555
- [ ] r.describe (GSoC)
- [ ] r.coin
- [ ] r.volume
- [ ] etc..

### 3d Raster
- [ ] etc..

### Vector

- [x] v.info (GSoC) https://github.com/OSGeo/grass/pull/3755
- [x] v.univar (GSoC) https://github.com/OSGeo/grass/pull/3784
- [x] v.db.select https://github.com/OSGeo/grass/pull/476
- [x] v.db.univar https://github.com/OSGeo/grass/pull/2386
- [ ] v.to.db (GSoC) https://github.com/OSGeo/grass/pull/4036
- [ ] v.distance (GSoC) https://github.com/OSGeo/grass/pull/3942
- [ ] v.category (GSoC) https://github.com/OSGeo/grass/pull/4020
- [ ]  v.report (GSoC)
- [ ] v.colors.out
- [ ] etc..

### Database

- [x] db.univar https://github.com/OSGeo/grass/pull/2386
- [x] db.describe (GSoC) https://github.com/OSGeo/grass/pull/4202
- [ ] etc..

## JSON output support without a library

- [x] v.db.select https://github.com/OSGeo/grass/pull/476
- [x] r.kappa https://github.com/OSGeo/grass/pull/2666
- [x] g.mapsets https://github.com/OSGeo/grass/pull/2542
- [ ] r.geomorphon
- [ ]

**Comment by florisvdh** [comment]
Adding here that the preferred JSON encoding for `g.proj` output would be the PROJJSON specification: https://proj.org/en/latest/specifications/projjson.html. It's a JSON encoding of WKT2:2019.

**Comment by nilason** [comment]
@cwhite911 could this be closed?

**Comment by cwhite911** [comment]
> @cwhite911 could this be closed?

@nilason I'm still using this issue to track all the work getting done implementing json outputs. I'm happy to close this issue and move this somewhere else if you have a good suggestion.

**Comment by wenzeslaus** [comment]
The original issue was solved. Let's create a new issue or I can create a project.

**Comment by cwhite911** [comment]
A project would be nice to keep track of this.

**Comment by NishantBansal2003** [comment]
Hey @cwhite911 @wenzeslaus , has JSON support been added to all the required modules, or are there still some modules left that need JSON support? If so, please let me know—I would love to contribute in this area!

**Comment by wenzeslaus** [comment]
Project to track it created a couple days ago: https://github.com/orgs/OSGeo/projects/10

**Comment by cwhite911** [comment]
@NishantBansal2003 any of the above tools that do not have an associated PR would be good to include. I also have some schema improvements in mind for some of the existing json enabled modules that I can make issues for.

**Comment by NishantBansal2003** [comment]
> @NishantBansal2003 any of the above tools that do not have an associated PR would be good to include. I also have some schema improvements in mind for some of the existing json enabled modules that I can make issues for.

Sure, I’ll look into this. Meanwhile, could you create issues for some schema improvements in the existing JSON-enabled modules? I’ll review them and work on the fixes. Thanks

**Comment by wenzeslaus** [comment]
I don't have the analysis for the schema. I wish. From my perspective, that's up for grabs if you feel like it. I noticed that r.univar always outputs a list of objects, but for one input, it seems to me it should output a single object. That's a one clear issue I noticed.

**Comment by echoix** [comment]
> I don't have the analysis for the schema. I wish. From my perspective, that's up for grabs if you feel like it. I noticed that r.univar always outputs a list of objects, but for one input, it seems to me it should output a single object. That's a one clear issue I noticed.

From a data parsing point of view, as json would be targeted around tool usage, it would be a nightmare to use if the schema/outputted format changed shape depending on the number of inputs. If it can be one or more, the. It should always be a list, and even empty if there is nothing.

**Comment by petrasovaa** [comment]
> Hi @wenzeslaus and @cwhite911! It looks like `v.colors.out` currently doesn’t support JSON output. Do we want the JSON output format to match the format used in the JSON output of `r.colors.out`?
> 
> Would you prefer that I open an issue for discussion first, or should I go ahead and create a PR?

Sounds like discussing it in an issue might be better.
