### ISSUE TITLE
[Bug] g.extension: installation addon fails because Git program is missing

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass#3077]
**Describe the bug**
g.extension module fails during installation addon under MS Windows OS because Git is not installed and distributed by default with GRASS GIS installation.

**To Reproduce**

1. Install GRASS GIS with [MS Windows standalone installer](https://wingrass.fsv.cvut.cz/grass84/)
1. Try install some addon e.g. `g.extension db.join`
2. See error

```
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS
8.4\scripts\g.extension.py", line 2853, in <module>
    sys.exit(main())
  File "C:\Program Files\GRASS GIS
8.4\scripts\g.extension.py", line 2828, in main
    get_addons_paths(gg_addons_base_dir=options["prefix"])
  File "C:\Program Files\GRASS GIS
8.4\scripts\g.extension.py", line 2732, in get_addons_paths
    addons_branch = get_version_branch(VERSION[0])
  File "C:\Program Files\GRASS GIS
8.4\scripts\g.extension.py", line 507, in get_version_branch
    branch = gs.Popen(
  File "C:\Program Files\GRASS GIS
8.4\etc\python\grass\script\core.py", line 55, in __init__
    raise OSError(_("Cannot find the executable
{0}").format(args[0]))
OSError: Cannot find the executable git
```

**Expected behavior**
g.extension module should install some addon without error message and Git program should be distributed with GRASS GIS installation by default.

**System description:**

- Operating System: MS Windows
- GRASS GIS version: 8.4.dev, 8.3.0

**Additional context**
We need to update the GRASS GIS installation/runtime dependencies (add Git program) for package maintainer on other OS platforms too.

Originally reported here https://github.com/OSGeo/grass/discussions/3059.

**Comment by hellik** [comment]
>System description:
>
>    Operating System: MS Windows

in MS windows we are using precompiled addons, right? is there git needed?

**Comment by tmszi** [comment]
> > System description:
> > Operating System: MS Windows
> 
> in MS windows we are using precompiled addons, right? is there git needed?

Yes you are right, but seems it Git is required for getting branch versions. However, this requires further investigation as to whether this is actually necessary to install precompilled addons.

https://github.com/OSGeo/grass/blob/6af1e4cb0402e2d6b53663288159ea578b37ce42/scripts/g.extension/g.extension.py#L502-L525

**Comment by tmszi** [comment]
Yes Git is required to detect multiple addons (including obtaining branch versions and etc.) during installation processing that only install the HTML page.

https://github.com/OSGeo/grass/blob/6af1e4cb0402e2d6b53663288159ea578b37ce42/scripts/g.extension/g.extension.py#L1517-L1521

We originally used the GitHub REST API (request/response), but due to API limitations, we decided use a Git clone instead.

**Comment by ldesousa** [comment]
There is a similar issue with the subversion package on Ubuntu. I recently reported it in the [UbuntuGis mail list](https://lists.osgeo.org/pipermail/ubuntu/2023-July/002042.html).

It makes sense to ask why these dependencies are necessary, but in any case the issue itself is with the software packaging. The most effective way is to report this directly with the [OSGeo4W project](https://trac.osgeo.org/osgeo4w/).

**Comment by ninsbl** [comment]
Hmm, it seems this is not trivial, unfortunately as `git` is not available in OSGeo4W yet (see: https://trac.osgeo.org/osgeo4w/ticket/799).

Both OSGeo4W as well as the WinGRASS installer are affected (thus it is good you reported the issue here).

For the WinGRASS part, we may have to copy the content of the git package, along with the other MSYS2 dependencies:
https://github.com/OSGeo/grass/blob/6af1e4cb0402e2d6b53663288159ea578b37ce42/mswindows/osgeo4w/package.sh#L250
Files in the git package can be found at the bottom here: https://packages.msys2.org/package/git?repo=msys&variant=x86_64
It is ~35MB installed and 6.5 MB packaged...

@landam and @hellik, any opinions / thoughts?

**Comment by hellik** [comment]
I didn't looked into g.extension code yet; though why is git needed to download precompiled addons?

**Comment by janneke-qgis** [comment]
Encountering this issue when trying to add the metadata editor in Grass 8.3.0-5 (installed using osgeo installer) on windows 11. Is there a work around so that I can use the metadata editor? Cheers, Janneke

**Comment by tmszi** [comment]
> Encountering this issue when trying to add the metadata editor in Grass 8.3.0-5 (installed using osgeo installer) on windows 11. Is there a work around so that I can use the metadata editor? Cheers, Janneke

Hello, if you plan to install and use the [wx.metadata](https://github.com/OSGeo/grass-addons/tree/grass8/src/gui/wxpython/wx.metadata) multi addon, some addons, especially those that use the custom wxPython GUI (g.gui.metadata) do not work properly under MS Window OS (due errors related with wxPython GUI lib). I recommend using it under GNU/Linux OS until these bugs are fixed.

Workaround for addon installation via g.extension module should be install standalone [Git for OS MS Windows](https://gitforwindows.org/), but there is another bug related with addon installation...

**Comment by petrasovaa** [comment]
I labeled this as blocker. Windows should not need to use git, we need some workaround in g.extension, at least for now.

**Comment by tmszi** [comment]
> I labeled this as blocker. Windows should not need to use git, we need some workaround in g.extension, at least for now.

Original solution was use proprietary GitHub REST API (request/response), but it has limitation and I rewrote it to use only Git. Currently, the g.extension module requires Git on MS Windows OS to post-process the HTML man page of the installed addon.

**Comment by petrasovaa** [comment]
> Currently, the g.extension module **requires Git** on MS Windows OS to **post-process** (not installation) the HTML man page of the installed addon.

My point is, we need to find a way without git running locally on windows, we are likely not getting git on Windows any time soon. I am not sure what the postprocessing does exactly, but ideally this could be done on the server? Or we just skip the postprocessing if possible on windows for now, having functioning addons is  more important, no?

There is the other issue with the branch, but that seems to be a separate problem.

**Comment by hellik** [comment]
> > Currently, the g.extension module **requires Git** on MS Windows OS to **post-process** (not installation) the HTML man page of the installed addon.
> 
> My point is, we need to find a way without git running locally on windows, we are likely not getting git on Windows any time soon. I am not sure what the postprocessing does exactly, but ideally this could be done on the server? Or we just skip the postprocessing if possible on windows for now, having functioning addons (and not throwing errors) is more important, no?
> 

agreed! having functioning addons is more important.

what is the postprocessing about?

in a midterm vision, we need a consolidated winGRASS/addon compiling/building strategy.

**Comment by hellik** [comment]
> > I didn't looked into g.extension code yet; though why is git needed to download precompiled addons?
> 
> Hi @hellik , as @tmszi mentioned, git is used to list available addons,

is it all about listing addons? what about addons which don't pre-compile on the server?

> so I think we could work around the git dependency (as well as the github API) on MS Windows. However, it would be needed if we at some point would decide to implement fetching python addons directly from the repo, instead of pre-compiled addons, as there had been requests or at least interests for that.

what about exe addons?

> 
> Maybe about time to re-consider the git dependency for MS Windows...

indeed

**Comment by tmszi** [comment]
I completely debug and refactor g.extension module addons installation on OS MS Windows platform, and Git program is no needed anymore as dependency. PR #3166 fixes this.
