### ISSUE TITLE
[Bug] r.slope.aspect does not open in GRASS 8.3 from OSGeo4W 

### ISSUE THREAD

**Issue by PedroVenancio** [OSGeo/grass#3093]
**Describe the bug**
I'm trying to run `r.slope.aspect` on GRASS 8.3, but it does not open. 

**To Reproduce**

1. Launching `r.slope.aspect` from cmd I get missing libgomp-1.dll:

![imagem](https://github.com/OSGeo/grass/assets/1331581/383221db-a729-46d0-9fb8-60d93e977391)

2. Launching the GUI and trying to run `r.slope.aspect` from there I get:

![Sem título](https://github.com/OSGeo/grass/assets/1331581/341112ed-5ce6-491d-a8f8-c583dec6dea2)

```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\gui_core\
forms.py", line 3090, in ParseCommand

self.grass_task = gtask.parse_interface(cmd[0],
blackList=_blackList)
  File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\scrip
t\task.py", line 547, in parse_interface

tree = etree.fromstring(get_interface_description(name))
  File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\scrip
t\task.py", line 511, in get_interface_description

raise ScriptError(
grass.exceptions
.
ScriptError
:
Unable to fetch interface description for command
'<r.slope.aspect>'.
Details: <C:\OSGeo4W\bin\python3.exe: can't open file
'C:\OSGeo4W\bin\r.slope.aspect': [Errno 2] No such file or
directory
>
During handling of the above exception, another exception
occurred:
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\gui_core\
treeview.py", line 73, in <lambda>

lambda evt: self._emitSignal(evt.GetItem(),
self.itemActivated),
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\gui_core\
treeview.py", line 200, in _emitSignal

signal.emit(node=node, **kwargs)
  File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pydis
patch\signal.py", line 233, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pydis
patch\dispatcher.py", line 344, in send

response = robustapply.robustApply(
  File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pydis
patch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\gui_core\
menu.py", line 190, in <lambda>

self._tree.itemActivated.connect(lambda node:
self.Run(node))
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\gui_core\
menu.py", line 262, in Run

eval(handler)(event=None, cmd=data["command"].split())
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\main_wind
ow\frame.py", line 1230, in OnMenuCmd

GUI(parent=self, giface=self._giface).ParseCommand(cmd)
  File "C:\OSGeo4W\apps\grass\grass83\gui\wxpython\gui_core\
forms.py", line 3092, in ParseCommand

raise gcmd.GException(e.value)
core.gcmd
.
GException
:
Unable to fetch interface description for command
'<r.slope.aspect>'.
Details: <C:\OSGeo4W\bin\python3.exe: can't open file
'C:\OSGeo4W\bin\r.slope.aspect': [Errno 2] No such file or
directory
>
```

3. Before those tests, I tried to run `r.slope.aspect` from QGIS 3.28.8, and it failed.

4. I have tested in GRASS 7.8 (also from OSGeo4W) and `r.slope.aspect` works as expected.

Could it be related to #2197 ?

**System description:**
                                                                
GRASS version: 8.3.0                                                            
Code revision: exported                                                         
Build date: 2023-07-18                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.7.1                                                                     
PROJ: 9.2.1                                                                     
GEOS: 3.12.0                                                                    
SQLite: 3.41.1                                                                  
Python: 3.9.5                                                                   
wxPython: 4.2.0                                                                 
Platform: Windows-10-10.0.22621-SP0 (OSGeo4W)

**Comment by hellik** [comment]
>Could it be related to #2197 ?

Yes

@landam who packaging for OSGeo4W at the moment?

**Comment by PedroVenancio** [comment]
@jef-n Do you have any idea about this issue?

**Comment by hellik** [comment]
> @jef-n Do you have any idea about this issue?

It's an issue of a missing dependency not packaged

**Comment by PedroVenancio** [comment]
Fixed by https://github.com/jef-n/OSGeo4W/commit/a9b4028d1b230ba782344f15de5570375b11086d
Thank you very much @jef-n !
