### ISSUE TITLE
infil raster map for r.sim.water[Bug] 

### ISSUE THREAD

**Issue by bonushenricus** [OSGeo/grass#3106]
**Describe the bug**
infil raster DCELL aligned with elevation map. Process more faster than infil_rate. Result in depth_water and discharge being very low and incomprehensible.

**To Reproduce**

1. r.mapcalc "infil = 24.1"
2. r.sim.water elevation=dem dx=dx dy=dy infil=infil man_value=0.368 depth=water_depth discharge=discharge --overwrite
3. r.sim.water elevation=dem dx=dx dy=dy infil_rate=24.1 man_value=0.368 depth=water_depth discharge=discharge --overwrite

**Expected behavior**
I expect the same results for 2. and 3.
But the results and time of processing are completely different

**System description (please complete the following information):**

- Operating System: Linux Debian 11
- GRASS GIS version 8.3.0 (but I tried also with 8.2.1)

**Comment by bonushenricus** [comment]
Hello
I try to compile the new grass 8.4 (because I have problem with 8.3 due to v.buffer, make error).
I try infil raster. The result is NaN depth and NaN discharge output.

**Comment by bonushenricus** [comment]
Hello. I managed to compile without errors grass 8.2, latest. I try r.sim.water with infil raster. Same problem: here the result was 0 for all pixels, in depth and discharge

**Comment by wenzeslaus** [comment]
@bonushenricus Given the input problem was fixed, please open a new issue for this zero problem.
