### ISSUE TITLE
dropping support for RHEL6

### ISSUE THREAD

**Issue by a-detiste** [OSGeo/grass#3114]
Hi,

I realize that when dropping support for Python2.x,
support for RHEL6 should be dropped too from `rpm/grass.spec`.

Ok ?

**Comment by neteler** [comment]
That should be fine.

Please note that the main SPEC file is here:
https://src.fedoraproject.org/rpms/grass/tree/rawhide/

(the one in `rpm/grass.spec` is a copy).

**Comment by a-detiste** [comment]
Ok I have a Fedora account, I'll submit a PR there.
