### ISSUE TITLE
[Bug] Updating STRDS metadata seems unnecessarily slow

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass#3136]
**Describe the bug**
When I register a few new maps into an existing, larger STRDS with a couple of thousands of maps, updating metadata takes some minutes.

**To Reproduce**

1. Create a larger STRS (t.create, t.register)
2. Add a few (one or two) new maps (t.register --v)
3. Notice the time it takes after message "Updati g metadata ..."

**Expected behavior**
Updating metadata when _adding_ a few new maps should only take seconds...

**System description (please complete the following information):**

- Operating System: Alpine Linux 3.18
- GRASS GIS 8.4

**Additional context**
Not sure what actually causes the issue. From a first inspection it seems both the register function and the SQL templates could be improved for better performance. E.g. if min/max values of new maps are known, STRDS min/max values do not have to be re-read/computed from the map register database...

**Comment by landam** [comment]
Both PR which are related to this issue haven't been backported to 8.3. Changing milestone to 8.4.0.

**Comment by landam** [comment]
@ninsbl Can we close this issue?

**Comment by ninsbl** [comment]
See also: #3723
And yes, I think we can close this and ship those features with the upcoming 8.4.
