### ISSUE TITLE
Update current mapset in Data tab when switching to the tab

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#314]
**Is your feature request related to a problem? Please describe.**
I'm using the Data tab in the Layer Manager a lot because it is really great, but when I switch to it, I usually have to press the Update current mapset button to see data I just created.

**Describe the solution you'd like**
When I switch to Data tab, I would like to see the latest state of the current mapset without clicking the refresh button.

**Describe alternatives you've considered**
Updating everything sounds like too much processing. It also might be good if it is updated when it is already active, but it gets focus. Clicking somewhere closer to the mapset name or content - like a context menu - would be an interesting alternative as it would apply to all mapsets (but it will require more clicks rather then less).

**Additional context**
The workflow I'm concerned with right now involves just one mapset.

**Comment by wenzeslaus** [comment]
This makes sense even after #748 because user might be switching back and forth.

**Comment by ninsbl** [comment]
Does #994 cover this?

**Comment by petrasovaa** [comment]
> Does #994 cover this?

Yes, thanks for catching this.
