### ISSUE TITLE
[Bug] v.db.connect does not recognize --overwrite flag

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#3149]
**Describe the bug**
v.db.connect does not recognize --overwrite and equivalent to -o. Hence, it throws an error if you try to overwrite from the GUI, which uses the long form of --overwrite instead of -o. 

When modules were converted to also use --overwrite, somehow v.db.connect was missed. 

**System description (please complete the following information):**

- Operating System: Mac OS 13.5.1
- GRASS GIS version 8.3.0

**Comment by HuidaeCho** [comment]
@cmbarton Would #3214 solve this problem?
