### ISSUE TITLE
[Bug] Unable to convert input map projection information to GRASS format.

### ISSUE THREAD

**Issue by Geek-007** [OSGeo/grass#3171]
I ran the [SICE project](https://github.com/GEUS-SICE/SICE) script to process the mask.tif file, and grass gis was used in the process. I suspected that the problem was caused by different grass gis versions. There was no error when I used 7.2, but the following error occurred when I used 7.4.5. It comes from this line `r.import input=./mask.tif output=mask`. Does anyone know the reason? I have uploaded the mask file.

[Greenland_300m.zip](https://github.com/OSGeo/grass/files/12697773/Greenland_300m.zip)

[Run steps](https://github.com/GEUS-SICE/SICE/tree/master#buffered-ice-mask)

![image](https://github.com/OSGeo/grass/assets/25733662/cabdd6b0-7920-4a80-8294-ab6312e6778f)

![image](https://github.com/OSGeo/grass/assets/25733662/4e81942b-1fbd-4475-8221-bc2c99c8805a)

**Comment by neteler** [comment]
Please post the output of

`gdalinfo mask.tif`

(preferably as text, not as a screenshot)

**Comment by Geek-007** [comment]
`gdalinfo Greenland_1km.tif`
Driver: GTiff/GeoTIFF
Files: Greenland_1km.tif
Size is 1487, 2687
Coordinate System is:
PROJCRS["WGS 84 / NSIDC Sea Ice Polar Stereographic North",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["US NSIDC Sea Ice polar stereographic north",
        METHOD["Polar Stereographic (variant B)",
            ID["EPSG",9829]],
        PARAMETER["Latitude of standard parallel",70,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8832]],
        PARAMETER["Longitude of origin",-45,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8833]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",south,
            MERIDIAN[45,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",south,
            MERIDIAN[135,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Polar research."],
        AREA["Northern hemisphere - north of 60°N onshore and offshore, including Arctic."],
        BBOX[60,-180,90,180]],
    ID["EPSG",3413]]
Data axis to CRS axis mapping: 1,2
Origin = (-637000.000000000000000,-662000.000000000000000)
Pixel Size = (1000.000000000000000,-1000.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -637000.000, -662000.000) ( 88d53'50.81"W, 81d32' 2.47"N)
Lower Left  ( -637000.000,-3349000.000) ( 55d46' 9.70"W, 59d15'34.71"N)
Upper Right (  850000.000, -662000.000) (  7d 5'15.73"E, 80d 4'41.82"N)
Lower Right (  850000.000,-3349000.000) ( 30d45'31.11"W, 58d51'46.46"N)
Center      (  106500.000,-2005500.000) ( 41d57'36.80"W, 71d36'49.06"N)
Band 1 Block=1487x1 Type=Float32, ColorInterp=Gray
  NoData Value=0

**Comment by neteler** [comment]
Do you see a chance to update the GRASS GIS version? 7.4 is from 2019.... (current is 8.3). Even 7.8.8 would be a good idea which contains updates for the projection management compared to 7.4.

**Comment by Geek-007** [comment]
Hahaha, because other problems occurred when running this project（[SICE](https://github.com/GEUS-SICE/SICE)） before, I used grass gis, which is the recommended version for the project. I tried to upgrade, but I was afraid that other problems would occur.

**Comment by neteler** [comment]
The gdalinfo output which you have sent above, is it from the same GDAL version used by GRASS GIS?

**Comment by Geek-007** [comment]
No, it's another version. Is it an error caused by it?

**Comment by neteler** [comment]
A more recent GRASS GIS version would be able to read the mask file. The 7.4 apparently not, too many meanwhile implemented changes concerning projections are not present.
Please update it to 7.8, I would not expect any compatibility issues.

**Comment by wenzeslaus** [comment]
@Geek-007 Thank you for the report. Let us know if this was resolved.
