### ISSUE TITLE
[Bug] t.register: use band from i.band

### ISSUE THREAD

**Issue by metzm** [OSGeo/grass#318]
i.band + t.register maps=... does not work, the band reference is not read by t.register
Providing text file with <name>|<start>|<end>|<band> works, but it would be more consistent if t.register would first and always check if a band name has been set with i.band.

**Comment by neteler** [comment]
(i.band has been renamed to r.semantic.label in #1983)

**Comment by veroandreo** [comment]
> (i.band has been renamed to r.semantic.label in #1983)

additionally, with @marisn changes any semantic label can be written to raster maps with r.support :)

**Comment by neteler** [comment]
@metzm is this bug report still relevant? If yes, I suggest to move it to milestone 8.0.2.
