### ISSUE TITLE
[Bug] Grass 8.3.0 app does not launch on Intel macOS 12.6.8

### ISSUE THREAD

**Issue by thynus** [OSGeo/grass#3180]
**Describe the bug**
Downloaded grass-8.3.0-x86_64.dmg from http://download.osgeo.org/grass/mac/grass-8.3.0-x86_64.dmg

**To Reproduce**
Dragged GRASS app to /Application folder
Double clicked on app
Application cannot be verified message displayed
Added exception in System Preferences (Open Anyway)

Double clicked on Grass app
Nothing happens no log files created.

Grass 8.3.0 app binary 
Intel macOS 12.6.8

**Comment by nilason** [comment]
The mac GRASS app is not code signed (yet), but a workaround is described in https://cmbarton.github.io/grass-mac/download/#installation-tips:

> To run them, you may need to control-click the app and select “open” the first time you run an app you have downloaded. After verification fails, you will be given the option to “open” the app anyway. You only have to do this once for each app or version you download.

**Comment by thynus** [comment]
Thanks for the note this happened because I said no to the installation script.  The workaround steps above reverse that mistake.  Could be helpful for other humans making the same mistake.

**Comment by thynus** [comment]
Work around for saying no to install script.
