### ISSUE TITLE
[Bug] Failing Additional checks since Dockerfile and docker/ubuntu/Dockerfile are different

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#3204]
**Describe the bug**

Since https://github.com/OSGeo/grass/issues/3170 modified the docker/ubuntu/Dockerfile without keeping in sync the main Dockerfile, one of the additional checks fails. It seems to have been placed exactly for this reason, to prevent diverging the two files. The PR was merged with that check indicating failure before merge.

Now every PR fails this check.

> This was merged with broken Additional checks check which is actually catching an issue relevant to this PR namely enforcing intentional code duplicity.

_Originally posted by @wenzeslaus in https://github.com/OSGeo/grass/issues/3170#issuecomment-1761767434_
            

**To Reproduce**

1. Open any new PR based on the main branch

**Expected behavior**

Keep the two files in sync.

**Screenshots**

**System description (please complete the following information):**

- Operating System: [e.g. Windows, Linux, ..., incl. version]
- GRASS GIS version [e.g. 7.8.4]

**Additional context**

**Comment by neteler** [comment]
The "diff" test is here:

https://github.com/OSGeo/grass/blob/0bc5039dd372684562b13f85ae087418a1add8a4/.github/workflows/additional_checks.yml#L45

How about making this a "required" test?

**Comment by echoix** [comment]
But in the meantime, this trivial PR (the changes were already longly discussed before merging the #3170) could be merged to not block any other PRs with that failing check. And that check, if ignored, prevents to see real failures that could run under it.
