### ISSUE TITLE
[Feat] g.gui: Minimize instead of "Hide" tabs

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#3212]
**Is your feature request related to a problem? Please describe.**

Hide the 'Tools' and 'Python' tabs in `g.gui` Preferences completely "hide" them and there is no way to unhide them in the same session. Currently, I have to uncheck those settings and restart the GUI.

**Describe the solution you'd like**

It would be more useful to "minimize" those tabs instead of hide and "remove" them.

**Comment by veroandreo** [comment]
see response in #3210, the option to minimize is already there for the whole panel

**Comment by HuidaeCho** [comment]
> see response in #3210, the option to minimize is already there for the whole panel

Right, it's there, but I have to minimize it "every time" I start the GUI. Hiding them from Preferences disallows unminimizing them.
