### ISSUE TITLE
[Feat] Add GRASS to system path variables during install on Windows

### ISSUE THREAD

**Issue by chaedri** [OSGeo/grass#3217]
**Is your feature request related to a problem? Please describe.**
On Windows, GRASS GIS does not launch from the command line.

**Describe the solution you'd like**
When GRASS GIS is being installed on Windows, I think it should run:
`setx PATH="C:\Program Files\GRASS GIS 8.2\"`

This adds the grass bat file to system path variables permanently so that grass can be launched from the command line.

**Describe alternatives you've considered**
The GRASS bat file needs to be a system path variable in order to use GRASS from within a Jupyter Notebook. Previously, I had been manually adding this each time with `set PATH=%PATH%;C:\Program Files\GRASS GIS 8.3\`. Then, I figured out I could edit my System Variables and permanently add the path. And finally, I realized it can be set permanently from the command line with `setx`.

**Additional context**
For running Jupyter Notebooks, you would still need to launch Jupyter from the GRASS GIS terminal. But, at least you could launch GRASS from the terminal first and wouldn't need to modify your path variables before launching Jupyter.

**Comment by hellik** [comment]
>When GRASS GIS is being installed on Windows, I think it should run:
>setx PATH="C:\Program Files\GRASS GIS 8.2\"

IMHO permanently set winGRASS installation path to %PATH% is some kind of opening Pandora's box of [windows DLL hell](https://en.wikipedia.org/wiki/DLL_Hell).

are there any documents of other software around how they working together with jupyter in windows?

**Comment by chaedri** [comment]
I knew there must be a reason why this is not done! I'll have a look around.
