### ISSUE TITLE
[Bug] cannot delete or rename mapsets

### ISSUE THREAD

**Issue by oskeng** [OSGeo/grass#3218]
**Describe the bug**
The selection to delete and rename mapsets are greyed out.

**To Reproduce**

1. Right click on a mapset
2. Note that "Delete mapset" and "Rename mapset" are greyed out.

**Expected behavior**
That "Delete mapset" and "Rename mapset" are not greyed out

**Screenshots**
Not necessary

**System description:**

GRASS version: 8.3.0                                                            
Code revision: 8694b45                                                          
Build date: 2023-08-20                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.7.0                                                                     
PROJ: 9.2.1                                                                     
GEOS: 3.12.0                                                                    
SQLite: 3.42.0                                                                  
Python: 3.11.5                                                                  
wxPython: 4.2.1                                                                 
Platform: Linux-6.5.5-1-MANJARO-x86_64-with-glibc2.38                           

**Additional context**

**Comment by veroandreo** [comment]
You need to activate the edit button first

![image](https://github.com/OSGeo/grass/assets/20075188/7624f25b-c8ff-4b1b-8ab8-e22fbbffe7cb)

**Comment by veroandreo** [comment]
closing as invalid

**Comment by petrasovaa** [comment]
It brings up the idea to get rid of that limitation. I implemented it because it corresponds to the standard behavior that you can't remove data fro other mapsets via g.remove. But perhaps we should reevaluate this, it's not an intuitive behavior, especially from the GUI user point of view.

**Comment by wenzeslaus** [comment]
> ...But perhaps we should reevaluate this, it's not an intuitive behavior, especially from the GUI user point of view.

Maybe the option can be always accessible in the menu, but will require an extra check box or something in the dialog it opens.

**Comment by veroandreo** [comment]
> > ...But perhaps we should reevaluate this, it's not an intuitive behavior, especially from the GUI user point of view.
> 
> Maybe the option can be always accessible in the menu, but will require an extra check box or something in the dialog it opens.

Perhaps that might work, yes. In my mind, it was indeed pretty intuitive since other GIS GUIs have the pencil button to edit layers, so when the pencil is active you know you must be careful, i.e., you are doing dangerous stuff eheh
