### ISSUE TITLE
[Bug] configure doesn't recognize PDAL 2.6.0

### ISSUE THREAD

**Issue by hjaekel** [OSGeo/grass#3220]
With PDAL 2.6.0 I get 

``` 
checking whether to use PDAL... yes
configure: error: *** Unable to locate suitable (>=1.7.1) PDAL library.
```

**Comment by neteler** [comment]
Please post the relevant parts of `config.log` (or attach the file zip'ed) so that we can see the real error.
Also add which operating system you use:

**System description (please complete the following information):**

- Operating System: [e.g. Windows, Linux, ..., incl. version]
- GRASS GIS version [e.g. 7.8.4]

**Comment by hjaekel** [comment]
Here is my system description:
* Operating System: Alpine Linux Edge
* GRASS GIS version: 8.3.0

**Comment by neteler** [comment]
Ok - did you actually also install `pdalcpp`?

**Comment by nilason** [comment]
I don't know how Alpine is packaging PDAL, but as far as I know `pdal_util` is from PDAL 2.6.0 merged into `pdalcpp` library (and thus ceased to exist). (I know of no pdal_base). Compiling with PDAL 2.6 seems to work fine with MacPorts.

**Comment by marisn** [comment]
I'm not certain if we can do anything about this. We use libs as provided by `pdal-config --libs`. If the output of `pdal-config --libs` is wrong, then it's the pdal-config that needs to be fixed.

**Comment by hjaekel** [comment]
Maybe you are right. But I really don't understand where the `-lpdal_util` is coming from. The output of `pdal-config --libs` seems to be correct
```
~/package/community/grass-gis $ pkg-config --libs pdal
-lpdalcpp -lgdal -lxml2
~/package/community/grass-gis $ pdal-config --libs
-L/usr/lib -lpdalcpp
~/package/community/grass-gis $ pdal-config --version
2.6.0
```

**Comment by nilason** [comment]
On Linux the `libpdalcpp` is supposed to be a "linker script":
https://github.com/PDAL/PDAL/blob/1492745b366afc6acea91e503f17aefb41c52c29/CMakeLists.txt#L42

I'd start looking what exactly is installed in lib.

Also, looking at https://git.alpinelinux.org/aports/tree/community/pdal/APKBUILD?h=3.18-stable it should be updated for 2.6 to take into account the changes of https://github.com/PDAL/PDAL/commit/a3faa03218e9ea6dee1503f635b17f57f4c82ff7#diff-d948007276311ede0b2bc1d7e8e2af4479f442a8bad9c2b420d34d945eb6d6a1 (for starter, I believe by removing the libpdal-util sub package).

**Comment by hjaekel** [comment]
Thank you, that was the hint I needed:
```
~/package/community/grass-gis $ cat /usr/lib/libpdalcpp.so
INPUT (-lpdal_base -lpdal_util)
```
This is wrong, so the probem is in my updated PDAL package, not in GRASS GIS.

**Comment by dnewcomb** [comment]
Just looking at the changelog for pdal 2.6.0,
https://github.com/PDAL/PDAL/releases
This change might be the issue.
https://github.com/PDAL/PDAL/pull/4139

**Comment by HuidaeCho** [comment]
I had the same problem on Slackware-current. Maybe, PDAL CMake is not yet updated? Its source tar ball still has the `libpdalcpp` script.

https://github.com/PDAL/PDAL/blob/d178b3a28bc088ff8efc51c6e167ee5338609555/CMakeLists.txt#L278-L286
```cmake
# On Linux, we install a linker script as libpdalcpp.so.  That file
# specifies linking in libpdal_base.so and libpdal_util.so.  This allows
# users to link a single library, libpdalcpp
#
if (UNIX AND NOT APPLE)
    set(LIBNAME ${CMAKE_SHARED_LIBRARY_PREFIX}${PDAL_LIB_NAME})
    install(FILES ${LIBNAME} DESTINATION ${CMAKE_INSTALL_LIBDIR}
        RENAME ${LIBNAME}${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()
```
I just replaced `/usr/lib64/libpdalcpp.so`:
```bash
cd /usr/lib64
ln -sf libpdalcpp.so.16 libpdalcpp.so
```

**Comment by kikislater** [comment]
> Thank you, that was the hint I needed:
> 
> ```
> ~/package/community/grass-gis $ cat /usr/lib/libpdalcpp.so
> INPUT (-lpdal_base -lpdal_util)
> ```
> 
> This is wrong, so the probem is in my updated PDAL package, not in GRASS GIS.

@hjaekel What is the correct output ? We face same issue in archlinux !

**Comment by kikislater** [comment]
>
> I just replaced `/usr/lib64/libpdalcpp.so`:
> 
> ```shell
> cd /usr/lib64
> ln -sf libpdalcpp.so.16 libpdalcpp.so
> ```

Thank you, it works in Archlinux as well

**Comment by nilason** [comment]
This should be addressed upstream, the problem is caused by https://github.com/PDAL/PDAL/blob/2.6.1/libpdalcpp.

**Comment by imincik** [comment]
> This should be addressed upstream, the problem is caused by https://github.com/PDAL/PDAL/blob/2.6.1/libpdalcpp.

Thank you. I agree.
