### ISSUE TITLE
[Bug] g.gui: Cannot display GUI becasuse of wxMenuBar error

### ISSUE THREAD

**Issue by Kazuya-Haganuma** [OSGeo/grass#3222]
**Describe the bug**
I installed GRASS GIS ver. 8.3.1 for Sonoma from here(https://cmbarton.github.io/grass-mac/announcement/GRASS-8.3.1_released/) and tried to start it, but although the terminal is launched and the logo is displayed, an error occurs in the part of the code related to the menu bar and the GUI does not start. I've tried to find the cause, but I'm not familiar with computers and codes, so I have no idea how to fix this error...

**To Reproduce**

1. Start GRASS
2. The terminal is launched, but the GUI doesn't be launched
3. `g.gui`
4. Same as 2

**Expected behavior**
g.gui starts properly.

**Screenshots**
<img width="912" alt="screenshot" src="https://github.com/OSGeo/grass/assets/99643952/fa8ea5ce-b4cd-42f4-ac05-7215da799657">

**System description (please complete the following information):**
- Operating System: MacOS Sonoma(Apple M1)
- GRASS GIS version: 8.3.1-Sonoma
- build_platform: aarch64-apple-darwin22.6.0
- build_off_t_size: 8
- libgis_revision: 8.3.1
- proj: 9.1.1
- gdal: 3.6.2
- geos: 3.11.1
- sqlite: 3.40.0
- sys.version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
- wx.version: 4.2.1 osx-cocoa (phoenix) wxWidgets 3.2.2.1

**Additional context**
There were no differences due to bash or zsh.
The packages are managed by homebrew.

**Comment by marisn** [comment]
There was a fix in this area some time a go: #2488
I can not reproduce the issue on my Linux box and thus I can only try to email code to you for testing. My guess – there is some nasty stuff with locales.

**Comment by Kazuya-Haganuma** [comment]
Thank you for your prompt response.
I thought there might be something wrong in local environment too, but I don't know where to check and modify.
What, if any, problems could there be? Also, is there anything I can show about my local environment to solve this error? 
(I tried changing the Python version to 3.9, 3.10 or 3.12, but it did not make sense. I don't know how to change the default wxPython version.)

**Comment by nilason** [comment]
> Thank you for your prompt response. I thought there might be something wrong in local environment too, but I don't know where to check and modify. What, if any, problems could there be? Also, is there anything I can show about my local environment to solve this error? (I tried changing the Python version to 3.9, 3.10 or 3.12, but it did not make sense. I don't know how to change the default wxPython version.)

If you use the official pre-built app (which you referenced to in the description), then everything needed is embedded in the app bundle. It is not possible to use out-of-bundle parts. This includes Python and wxPython.
You may try setting `export LC_ALL="en_US.UTF-8"` and/or `export LC_CTYPE="en_US.UTF-8"` before running `g.gui`.

**Comment by Kazuya-Haganuma** [comment]
> You may try setting export LC_ALL="en_US.UTF-8" and/or export LC_CTYPE="en_US.UTF-8" before running g.gui.

The GUI has been successfully started!  :-)
So it was a locale issue. I didn't realize that at all.
I would like to thank you for your cooperation!

**Comment by nilason** [comment]
> > You may try setting export LC_ALL="en_US.UTF-8" and/or export LC_CTYPE="en_US.UTF-8" before running g.gui.
> 
> The GUI has been successfully started! :-) So it was a locale issue. I didn't realize that at all. I would like to thank you for your cooperation!

Good! You may consider setting _Set locale environment variables on startup_ in the Terminal's Settings > Profiles > Advanced > International section.

**Comment by Kazuya-Haganuma** [comment]
> You may consider setting Set locale environment variables on startup in the Terminal's Settings > Profiles > Advanced > International section.

I will make sure to do it!
This was the first time I had faced such a problem, but I have learned about the importance of locale and I think I will be able to deal with similar problems in the future.
I really appreciate your cooperation!

**Comment by nilason** [comment]
> I'll reopen the issue as the code needs to be made more robust.

You are quite right!

I couldn't manage to reproduce this, however the log indicates bad index error here:

https://github.com/OSGeo/grass/blob/4e66071694144043f251c53df2c2237f01b5af9c/gui/wxpython/lmgr/workspace.py#L515-L517

I assume `menu.FindMenu(title=_("File"))` failed and returned an invalid index. It would be easy to make a check for a valid result and bail out if not. But that would brush the actual cause of the failure to retrieve the `File` menu item under the carpet.

**Comment by nilason** [comment]
From `wx.MenuBar` docs:
> FindMenu(self, title)
>    Returns the index of the menu with the given title or NOT_FOUND if no such menu exists in this menubar.

I suppose `NOT_FOUND` is the bad index. Under what circumstances is this menu item not found? Should always be present, shouldn't it?

**Comment by petrasovaa** [comment]
I am not entirely sure when this would fail, but apparantly it happens, so this should make it more robust. We could probably add some warning about it if it fails, but I am not sure it is worth it.
```
diff --git a/gui/wxpython/lmgr/workspace.py b/gui/wxpython/lmgr/workspace.py
index 792567b4c6..9b63c31fa4 100644
--- a/gui/wxpython/lmgr/workspace.py
+++ b/gui/wxpython/lmgr/workspace.py
@@ -514,12 +514,14 @@ class WorkspaceManager:
         :return None
         """
         if menu:
-            file_menu = menu.GetMenu(
-                menuIndex=menu.FindMenu(title=_("File")),
-            )
-            workspace_item = file_menu.FindItem(
-                id=file_menu.FindItem(itemString=_("Workspace")),
-            )[0]
+            menu_index = menu.FindMenu(_("File"))
+            if menu_index == wx.NOT_FOUND:
+                return
+            file_menu = menu.GetMenu(menu_index)
+            workspace_index = file_menu.FindItem(_("Workspace"))
+            if workspace_index == wx.NOT_FOUND:
+                return
+            workspace_item = file_menu.FindItemById(workspace_index)
             self._recent_files = RecentFilesMenu(
                 app_name="main",
                 parent_menu=workspace_item.GetSubMenu(),
```

**Comment by marisn** [comment]
> I am not entirely sure when this would fail, but apparantly it happens, so this should make it more robust. We could probably add some warning about it if it fails, but I am not sure it is worth it.

I would go with even more complicated version – in the case of `if menu_index == wx.NOT_FOUND` I'd try untranslated version first before giving up.

Generally if `menu.FindMenu` fails I would be more worried that there is something wrong with the system and this would not be the end of problems. It would be nice to figure out what exactly causes the call to fail to enable meaningful error message.

**Comment by nilason** [comment]
> Generally if `menu.FindMenu` fails I would be more worried that there is something wrong with the system and this would not be the end of problems. It would be nice to figure out what exactly causes the call to fail to enable meaningful error message.

This is what I meant by _"[b]ut that would brush the actual cause of the failure to retrieve the File menu item under the carpet."_

**Comment by petrasovaa** [comment]
> > I am not entirely sure when this would fail, but apparantly it happens, so this should make it more robust. We could probably add some warning about it if it fails, but I am not sure it is worth it.
> 
> I would go with even more complicated version – in the case of `if menu_index == wx.NOT_FOUND` I'd try untranslated version first before giving up.

We could certainly do that, but are all these additional lines of code worth it? My concern is for the GUI not to crash because of this minor thing.

> 
> Generally if `menu.FindMenu` fails I would be more worried that there is something wrong with the system and this would not be the end of problems. It would be nice to figure out what exactly causes the call to fail to enable meaningful error message.

I agree.

**Comment by nilason** [comment]
@Kazuya-Haganuma Would you mind sharing what language you have for the macOS?

**Comment by Kazuya-Haganuma** [comment]
My setting about locale before you told a solution was "ja_JP.UTF-8", but "en_US.UTF-8" was also already installed. (English is set a prioritized language next to Japanese in my environment.)
More than 100 languages was showed when I checked `locale -a` in Terminal, but I didn't do anything about language packages, so I think these were installed as default.

**Comment by nilason** [comment]
> My setting about locale before you told a solution was "ja_JP.UTF-8", but "en_US.UTF-8" was also already installed. (English is set a prioritized language next to Japanese in my environment.) More than 100 languages was showed when I checked `locale -a` in Terminal, but I didn't do anything about language packages, so I think these were installed as default.

Thank you!
Setting `export LC_ALL=ja_JP.UTF-8` enabled me to reproduce this error. Let's see if we'll be able to get to the bottom of this.

**Comment by nilason** [comment]
The workaround in https://github.com/OSGeo/grass/issues/3222#issuecomment-1799060460 enables GUI to start, without further hiccups.


<img width="553" alt="Screenshot 2023-11-08 at 13 40 17" src="https://github.com/OSGeo/grass/assets/14186207/266fc8ba-b591-48b4-ba5e-31d12b8d2aa3">


This is what debugging comes up with:

<img width="553" alt="Screenshot 2023-11-08 at 13 45 30" src="https://github.com/OSGeo/grass/assets/14186207/dea20f87-7097-48de-aaea-cc5b1af3de92">


which seems to deviate to what is displayed in the menu.

As my Japanese language skills are a bit rusty, I'd be happy for input on this.

**Comment by nilason** [comment]
@Kazuya-Haganuma Thank you for the information, I suspected it was gibberish.

I also suspect the problem originates from the string "File" is not translated to Japanese (in GRASS) therefore the menu item searched for is literally the English one (which fails). The gibberish string is likely "File" encoded in Japanese encoding. Besides adding "File" to the translated strings, we need a mechanism to detect this and only then bail out.
