### ISSUE TITLE
HTTP Error 470: status code 470 

### ISSUE THREAD

**Issue by rengifoo** [OSGeo/grass#3238]
** ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass83/addons/grass-8.3.1/r.stream.distance.zip>: HTTP Error 470: status code 470**
I get a error  470 when trying to install any l extension on newly installed AVD (Azure virtual device). I am running GRASS GIS 8.3.1 stable installed as standalone.

**To Reproduce**

1. Install standalone stable grass gis 8.3.1
2. g.extension  ' any  extension '
3. Compute 
4. See error : HTTP Error 470: status code 470 

**System description and entire  error log**

Launching <wxpython> GUI in the background, please wait...
Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. All rights reserved.

C:\Users\reno>g.extension
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\gui_core\forms.py", line 3257, in <module>
    task.set_options(cmd[1:])
  File "C:\Program Files\GRASS GIS 8.3\etc\python\grass\script\task.py", line 298, in set_options
    key, value = opt.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

C:\Users\reno>g.extension
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\gui_core\forms.py", line 3257, in <module>
    task.set_options(cmd[1:])
  File "C:\Program Files\GRASS GIS 8.3\etc\python\grass\script\task.py", line 298, in set_options
    key, value = opt.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

C:\Users\reno>g.extension extension=r.sim.water.mp
Downloading precompiled GRASS Addons <r.sim.water.mp>...
ERROR: Cannot open URL
       <http://wingrass.fsv.cvut.cz/grass83/addons/grass-8.3.1/r.sim.water.mp.zip>:
       HTTP Error 470: status code 470

C:\Users\reno>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

It seems to be an issue of GRASS GIS 8.3.1.   
thanks for help 

best regards 
Rengifo Ortega

**Comment by petrasovaa** [comment]
From quick googling of the error code, it looks like it has something to do with Azure, not sure what to do about it.

Regarding the other error, that does happen with any module? Maybe it would be better to create a separate issue for that one.

**Comment by hellik** [comment]
which windows OS flavour is this?

**Comment by rengifoo** [comment]
@hellik 
![grafik](https://github.com/OSGeo/grass/assets/92565915/987d8501-a321-4766-94e9-1c1f22298197)
I am running GRASS on a Azure Virtual  Device , with Window 11 enterprise multi-session, version 22H2.
Best regards.
Rengifo

**Comment by rengifoo** [comment]
> From quick googling of the error code, it looks like it has something to do with Azure, not sure what to do about it.
> 
> Regarding the other error, that does happen with any module? Maybe it would be better to create a separate issue for that one.

thanks for the quick response. Here what  I did sofar. Downgraded GRASS GIS to 7.8.8 [1] version and tried to install r.sim.water.mp [2] it says it was successfully installed, run it [3], failed [4].

Best regards
Rengifo 
![grafik](https://github.com/OSGeo/grass/assets/92565915/cadcfd10-89ac-446a-a9db-0c51fee4977d)

**Comment by rengifoo** [comment]
I guess I should devide these into  new issues since I  downgraded and reinstalled GRASS GIS !

**Comment by petrasovaa** [comment]
Looking at r.sim.water.mp, this is actually a leftover, the multiprocessing has been moved to core, so you should be able to use r.sim.water with multiple cores, you don't need this extension.

**Comment by rengifoo** [comment]
> Looking at r.sim.water.mp, this is actually a leftover, the multiprocessing has been moved to core, so you should be able to use r.sim.water with multiple cores, you don't need this extension.

thanks a lot. It saves me lot of  search time for answers. This information should more visible though!
Best regards
Rengifo

**Comment by rengifoo** [comment]
thanks for the great help. I short,  I removed Grass 8.3.1 from Azure Digital Device, installed  Grass 7.8.8.  As @petrasovaa explain r.sim.water.mp is not any longer require to run  multiprocessing. So I have an operative GRASS GIS runing on a virtual machine in Azure

**Comment by petrasovaa** [comment]
Issue to remove it from addons to avoid confusion:
https://github.com/OSGeo/grass-addons/issues/983
