### ISSUE TITLE
[Bug] docs: all "meta page description" HTML pages lack SOURCE CODE and Latest change section

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#3243]
**Describe the bug**

These "meta page description" HTML pages lack

```
SOURCE CODE

Available at: [xxxx Setup source code](https://github.com/OSGeo/grass/tree/main/zzzzzzzz) ([history](https://github.com/OSGeo/grass/commits/main/zzzzzzzz))

Latest change: wwwww
```

Pages affected (there may be more):

ag 'meta page description' -l | sed 's+^+- +g'
- db/drivers/dbf/grass-dbf.html
- db/drivers/mysql/grass-mysql.html
- db/drivers/mysql/grass-mesql.html
- db/drivers/odbc/grass-odbc.html
- db/drivers/ogr/grass-ogr.html
- db/drivers/postgres/grass-pg.html
- db/drivers/sqlite/grass-sqlite.html
- db/databaseintro.html
- display/displaydrivers.html
- raster/r.li/r.li.daemon/r.li.daemon.html
- raster/r.li/r.li.html
- raster/rasterintro.html
- raster3d/raster3dintro.html
- temporal/temporalintro.html
- vector/v.lrs/lrs.html
- vector/vectorintro.html
- utils/mkrest.py
- utils/mkhtml.py
- lib/cairodriver/cairodriver.html
- lib/db/sqlp/sql.html
- lib/htmldriver/htmldriver.html
- lib/init/helptext.html
- lib/init/grass.html
- lib/init/variables.html
- lib/pngdriver/pngdriver.html
- lib/psdriver/psdriver.html
- lib/vector/vectorascii.html
- doc/gui/wxpython/example/g.gui.example.html
- doc/grass_database.html
- doc/projectionintro.html
- gui/wxpython/animation/g.gui.animation.html
- gui/wxpython/datacatalog/g.gui.datacatalog.html
- gui/wxpython/dbmgr/g.gui.dbmgr.html
- gui/wxpython/docs/wxGUI.vnet.html
- gui/wxpython/docs/wxGUI.modules.html
- gui/wxpython/docs/wxGUI.components.html
- gui/wxpython/docs/wxGUI.toolboxes.html
- gui/wxpython/docs/wxGUI.html
- gui/wxpython/docs/wxGUI.iscatt.html
- gui/wxpython/docs/wxGUI.nviz.html
- gui/wxpython/gcp/g.gui.gcp.html
- gui/wxpython/gmodeler/g.gui.gmodeler.html
- gui/wxpython/iclass/g.gui.iclass.html
- gui/wxpython/image2target/g.gui.image2target.html
- gui/wxpython/mapswipe/g.gui.mapswipe.html
- gui/wxpython/photo2image/g.gui.photo2image.html
- gui/wxpython/psmap/g.gui.psmap.html
- gui/wxpython/rdigit/g.gui.rdigit.html
- gui/wxpython/rlisetup/g.gui.rlisetup.html
- gui/wxpython/timeline/g.gui.timeline.html
- gui/wxpython/tplot/g.gui.tplot.html
- gui/wxpython/vdigit/g.gui.vdigit.html
- imagery/imageryintro.html

**To Reproduce**

See manual pages on the web sites.

**Expected behavior**

The pages should also have the section like the module pages.

The bug is somewhere here:

https://github.com/OSGeo/grass/blob/974298753f8bcd8a0c6c3931f43fa4b6e99b0ee2/utils/mkhtml.py#L908

**Comment by veroandreo** [comment]
This should go into addons repo, I guess, but just to add to the discussion: 

In addons, only r.pi.html seems to get it right. i.landsat.html and i.modis.html have "hard coded" heading and source code links in the html files (no latest changes). i.sentinel.html has hard coded heading only (no source code or last modification), but the compiled html does not have source code nor latest change sections. Are these compiled with the same script than in core? 

Which is the correct way to create these meta-pages?

**Comment by tmszi** [comment]
> This should go into addons repo, I guess, but just to add to the discussion:
> 
> In addons, only r.pi.html seems to get it right. i.landsat.html and i.modis.html have "hard coded" heading and source code links in the html files (no latest changes). i.sentinel.html has hard coded heading only (no source code or last modification), but the compiled html does not have source code nor latest change sections. Are these compiled with the same script than in core?
> 
> Which is the correct way to create these meta-pages?

Python [mkhtml.py](https://github.com/OSGeo/grass/blob/main/utils/mkhtml.py) module dynamically add Source code section into HTML core/addon module man page.
