### ISSUE TITLE
[Bug] .dylib GDAL libs should be listed in lib/raster/gdal.c

### ISSUE THREAD

**Issue by Veence** [OSGeo/grass#326]
The file `lib/raster/gdal.c` has a list of possible GDAL lib names it can dlopen () in the `load_library` function. However, this list so far has only included .so or .dll suffixes, which are fine for Linux and Windows, but obviously not for MacOS. It would be nice to add something like:

`# ifdef _ _APPLE_ _`
`        "libgdal.26.dylib", `
`       …`

That would help eliminate a patch file. Thanks!

**Comment by neteler** [comment]
So, something like this?

```
index 6d1545e10..98fd9ddde 100644
--- a/lib/raster/gdal.c
+++ b/lib/raster/gdal.c
@@ -133,6 +133,9 @@ static void load_library(void)
        "gdal.1.0.dll",
        "libgdal-1.dll",
        "gdal.dll",
+# endif
+# ifdef __APPLE__
+       "libgdal.26.dylib",
 # endif
        NULL
     };
```

If you have a working patch, please submit it (easier...), thanks

**Comment by neteler** [comment]
@metzm may I apply my proposed fix? Any harm to be expected?

**Comment by metzm** [comment]
For a proper fix, you would need to list all supported GDAL dylib versions, not only libgdal.26.dylib.

Who could provide such a list of GDAL dylib versions?

**Comment by neteler** [comment]
@Veence any idea?

**Comment by neteler** [comment]
(un)related: https://trac.osgeo.org/grass/ticket/3230

**Comment by neteler** [comment]
> For a proper fix, you would need to list all supported GDAL dylib versions, not only libgdal.26.dylib.
> 
> Who could provide such a list of GDAL dylib versions?

@rouault do you have an idea for us?

**Comment by rouault** [comment]
> do you have an idea for us?

yes, but probably not the one you expect: use standard build-time mechanism instead of run-time one :-)
