### ISSUE TITLE
[Feat] Reduce duplicate code between grass.jupyter.SeriesMap and grass.jupyter.TimeSeriesMap

### ISSUE THREAD

**Issue by chaedri** [OSGeo/grass#3276]
**Is your feature request related to a problem? Please describe.**
In #3036, we added a new visualization class for viewing and animating a series of related rasters or vectors. Similar to TimeSeriesMap, SeriesMap uses ipywidgets. Because of the similarities between the two classes, there is a significant amount of duplicated code, particularly in the class `__init__` and image rendering.

**Describe the solution you'd like**
The code should be refactored to reduce duplication. One possible solution is a base class that consolidates methods used by both classes.

**Comment by 29riyasaxena** [comment]
Hi @chaedri, I would like to work on this. I think it's a good idea to create a base class that both can share to avoid writing the same code twice. Here's my plan:
1. Create a new base class (BaseMap) and move the common code into this class (from `__init__` and  `_render_baselayers`).
2. Make TimeSeriesMap and SeriesMap inherit from BaseMap.
3. Replace the common code in TimeSeriesMap and SeriesMap with calls to the base class code.

**Comment by petrasovaa** [comment]
> Hi @chaedri, I would like to work on this. I think it's a good idea to create a base class that both can share to avoid writing the same code twice. Here's my plan:
> 
> 1. Create a new base class (BaseMap) and move the common code into this class (from `__init__` and  `_render_baselayers`).
> 2. Make TimeSeriesMap and SeriesMap inherit from BaseMap.
> 3. Replace the common code in TimeSeriesMap and SeriesMap with calls to the base class code.

Welcome! Your plan sounds good, I would probably name it BaseSeriesMap. There are many methods that have very similar, but not identical code, so there may be a need to generalize the code a bit. I think you will find it helpful to first run the notebook with [TimeSeriesMap](https://github.com/OSGeo/grass/blob/main/doc/notebooks/temporal.ipynb) to better understand how it is being used.

**Comment by chaedri** [comment]
Welcome @29riyasaxena ! This sounds good to me too. I'll add the example mentioned in #3467 so you can see that too.

**Comment by Jasmitha-Mannam** [comment]
Hi..... ,I would like to work on this problem statement as a part of GSOC

**Comment by ayushjariyal** [comment]
@chaedri, I am planning to apply for GSoC 2026 and found this issue via one of your project descriptions. I have prior experience contributing to other open-source projects and would appreciate your guidance on how to start contributing here.

**Comment by ayushjariyal** [comment]
Hi @petrasovaa, @chaedri  I noticed that there are currently no tests for the `utils.py` file in `grass.jupyter.`
I’d like to start by adding unit tests for it .
Please let me know if this sounds good, and I’ll get started.

**Comment by chaedri** [comment]
@ayushjariyal Exciting! You've found the [GRASS GSoC Ideas 2026 page](https://grasswiki.osgeo.org/wiki/GRASS_GSoC_Ideas_2026) and [the discourse](https://discourse.osgeo.org/c/grass/developer/61). I think @petrasovaa can let you know if that's a good place to start since she's mentoring the project. I was just a GSoC participant in 2021 working on `grass.jupyter` :) Best of luck!

**Comment by petrasovaa** [comment]
> Hi [@petrasovaa](https://github.com/petrasovaa), [@chaedri](https://github.com/chaedri) I noticed that there are currently no tests for the `utils.py` file in `grass.jupyter.` I’d like to start by adding unit tests for it . Please let me know if this sounds good, and I’ll get started.

Writing a pytest for a selected function sounds good (in jupyter/tests/). As part of that, you could also try rewriting some of the functions in utils.py using the new [grass.tools API](https://grass.osgeo.org/grass-devel/manuals/python_intro.html#running-tools) instead of [grass.script](https://grass.osgeo.org/grass-devel/manuals/python_intro.html#shell-like-tool-calling) API.

**Comment by ayushjariyal** [comment]
Thanks @petrasovaa for suggestion, I’ll definitely try to rewrite the functions in the `utils.py` file.
