### ISSUE TITLE
[Bug] Using r.proj from epsg:4326 to epsg:2056 I got misplaced map by 150m in diagonal direction

### ISSUE THREAD

**Issue by cbic843** [OSGeo/grass#3295]
**Describe the bug**
I am trying to reproject a raster image from epsg:4326 projection to epsg:2056 the swiss coordinate system in QGIS.
The result is a raster with 150m misplacement in diagonal direction (around 15 pixels). Doing the same reprojection with gdal brings no problems.

**Expected behavior**
I compare the result with a vector layer. The raster is well georeferenced in epsg:4326 but not in target projection.

**Screenshots**
![Capture d'écran 2023-12-09 170001](https://github.com/OSGeo/grass/assets/152252491/943b0294-500f-4461-9c53-997b4dd345f2)

**System description (please complete the following information):**

- Operating System: Windows 11
- GRASS GIS version 8.3.1

version=8.3.1
date=2023
revision=exported
build_date=2023-12-02
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=8.3.1
libgis_date=2023-12-02T20:53:53+00:00
proj=9.3.1
gdal=3.8.1
geos=3.12.1
sqlite=3.41.1

**Additional context**

**Comment by hellik** [comment]
what is the command you used? is there a sample dataset available?

**Comment by neteler** [comment]
Probably the proj datum files are missing on your computer?

**Comment by cbic843** [comment]
You mean the proj datum files from https://github.com/OSGeo/PROJ-data/tree/master/ch_swisstopo?
They are installed if I check with projsync --list-files:
ch_swisstopo_README.txt,,ch_swisstopo,2197
ch_swisstopo_CHENyx06_ETRS.tif,Switzerland,ch_swisstopo,602809
ch_swisstopo_CHENyx06a.tif,Switzerland,ch_swisstopo,1021779
ch_swisstopo_chgeo2004_ETRS89_LHN95.tif,Switzerland,ch_swisstopo,259441
ch_swisstopo_chgeo2004_ETRS89_LN02.tif,Switzerland,ch_swisstopo,295192

**Comment by metzm** [comment]
Something might be missing in the projection pipeline that GRASS gets from PROJ. With `projinfo`:

```
projinfo -o PROJ -s EPSG:4326 -t EPSG:2056
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Inverse of CH1903+ to WGS 84 (1) + Swiss Oblique Mercator 1995, 1 m, Liechtenstein; Switzerland.

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=push +v_3
  +step +proj=cart +ellps=WGS84
  +step +proj=helmert +x=-674.374 +y=-15.056 +z=-405.346
  +step +inv +proj=cart +ellps=bessel
  +step +proj=pop +v_3
  +step +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=2600000 +y_0=1200000 +ellps=bessel
```
with `r.proj`:
```
Selected PROJ pipeline:
+proj=pipeline
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=2600000 +y_0=1200000 +ellps=bessel
```
the Helmert transform is missing.

**Comment by metzm** [comment]
Maybe a solution: I tested with an old GRASS latlon location that did not have a PROJ_WKT file in PERMANENT. After `g.proj srid="EPSG:4326" -c` in the latlon location, I get in the swiss EPSG:2056 location with `r.proj`:
```
Selected PROJ pipeline:
+proj=pipeline
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=push +v_3
  +step +proj=cart +ellps=WGS84
  +step +proj=helmert +x=-674.374 +y=-15.056 +z=-405.346
  +step +inv +proj=cart +ellps=bessel
  +step +proj=pop +v_3
  +step +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=2600000 +y_0=1200000 +ellps=bessel
```
which is now identical to `projinfo`

**Comment by cbic843** [comment]
> what is the command you used? is there a sample dataset available?

I used the grass function r.proj.
You can test it on the following dataset: https://cbic.ch/data/ge_dataset.zip

**Comment by metzm** [comment]
GRASS is indeed using the pipeline without helmert transformation for your data. The reason is that GRASS requires from PROJ that
```
The area of validity of transforms should strictly contain the area of interest.
```
while GDAL uses a more relaxed spatial criterion to restrict candidate operations:
```
The area of validity of transforms should at least intersect the area of interest.
``` 

The area of interest is here the extents of the image to be reprojected.

The effect is that the GDAL variant with a more relaxed spatial criterion might be more accurate for most parts of the image, as in your case, but transformation results at the edges might be worse.

PROJ itself seems undecided what is better: the default spatial criterion is the strict version, but PROJ itself overrides the default when creating a transformation pipeline, using the more relaxed criterion.

I tend to follow the current behaviour of GDAL and PROJ, that means a small adjustment to the GRASS reprojection mechanism to also use the more relaxed criterion to restrict candidate operations.
