### ISSUE TITLE
d.vect.thematic not working with GRASS 8.4

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#3383]
**Describe the bug**
d.vect.thematic works nicely on GRASS 8.3, but on GRASS 8.4 it produces nothing and no error. 

**To Reproduce**
Use the example from the manual in the console:
d.vect.thematic map=schools_wake@PERMANENT column=CORECAPACI algorithm=std nclasses=3 colors=149:203:255,45:143:240,0:81:161 icon=basic/circle size=15 legend_title="School capacity"

This does not produce a vector layer or a display of any kind. If you reproduce this using the GUI, it is the same blank result. 

Interestingly, the legend **IS** created and displays correctly with v.legend.vect

**Expected behavior**
Doing the same thing with GRASS 8.3.1 produces a nice vector thematic map

**System description (please complete the following information):**

- Operating System: Mac OS 13.6.3
- GRASS GIS 
version=8.4.0dev
date=2023
revision=bfef3d3961
build_date=2023-12-08
build_platform=aarch64-apple-darwin22.6.0
build_off_t_size=8

**Comment by petrasovaa** [comment]
I can't reproduce this, it works for me... Does the other example with average elevation from the manual work?

**Comment by cmbarton** [comment]
I didn't try it with areas, just points. Are you trying this on a Mac or another platform?

**Comment by petrasovaa** [comment]
> I didn't try it with areas, just points. Are you trying this on a Mac or another platform?

Ubuntu, but I don't know why this would be platform specific.

**Comment by cmbarton** [comment]
Who knows but even thought wxPython is supposed to be cross-platform (and usually is), there are some things that work differently in different platforms. Oddly, it works in 8.3.1. So it could also possibly be a glitch in the particular build I did last month.

**Comment by veroandreo** [comment]
I can't reproduce it either under 8.4 in Fedora

**Comment by cmbarton** [comment]
I tried it again and it seems to work fine. Weird. I tried it multiple times before and it did not display. But since it seems to be working I will close this for now unless there are new issues.

**Comment by echoix** [comment]
As I learned from a QA internship, a bug that resolved itself is worse than a bug that isn't fixed, but understand. (In the context that a bug is reproducible with a certain revision but not others. That would mean that it is probably still there, but hidden by something else. We would need to keep an eye on it)
