### ISSUE TITLE
[Bug] Profile Analysis Tool Segment break points position

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass#3418]
**Describe the bug**
When creating a profile with break points with the Profile Analysis Tool, I would expect the segment break points to be shown on the profile line. They are, however, positioned on the x=0 axis (see attached screenshot).

**To Reproduce**

1. Open raster lay
2. Open the Profile Analysis Tool from the Map Display toolbar
3. Draw a profile line, including at least one breakpoint

**Expected behavior**
I would expect the segment break points to be shown on the profile line instead of all on the x=0 axis. 

**Screenshots**
![ksnip_20240212-114455](https://github.com/OSGeo/grass/assets/7816789/8a61bfd6-f934-41e6-99fb-d58b441ba457)

**System description (please complete the following information):**

- Operating System: Linux, Ubuntu 22.04
- GRASS GIS version 8.4.0dev, code revision 53c362dbd1

**Additional context**
I have observed this behavior in earlier versions as well

**Comment by tmszi** [comment]
I wasn't successful with your reproducible example. All my line segments breaks triangle points lies on the profile line.

**Comment by ecodiv** [comment]
@tmszi You are right. The difference is that in my example I used 'unprojected' data (WGS84, EPSG 4326). It seems the tool does not properly handle such data?

**Comment by tmszi** [comment]
> @tmszi You are right. Using that data, it works as expected.
> 
> The difference is that in my example I used 'unprojected' data (WGS84, EPSG 4326). It seems the tool does not properly handle such data?

This will require a more detailed analysis.

**Comment by veroandreo** [comment]
I tested with a DEM in a 4326 location and I get the same behavior that @ecodiv describes, in NC sample data (i.e., a projected location) the breaks are on the profile curve.
