### ISSUE TITLE
[Bug] grasswxpy_de.po: has a duplicate message definition

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#3465]
**Describe the bug**

Compilation reports a warning: `file <grasswxpy_de.po> has some problems: <b'po/grasswxpy_de.po:20658: duplicate message definition...found 1 fatal error>`

This does not cause the compilation to fail. It just appears in the compilation output.

**To Reproduce**

```
make distclean
./configure ...
make
```

**Screenshots**

```
make[3]: Entering directory '.../grass/locale'
GISBASE=".../grass/dist.x86_64-pc-linux-gnu" python3 ./grass_po_stats.py
WARNING: file <grasswxpy_de.po> has some problems: <b'po/grasswxpy_de.po:20658: duplicate message definition...\npo/grasswxpy_de.po:4581: ...this is the location of the first definition\nmsgfmt: found 1 fatal error'>
make[3]: Leaving directory '.../grass/locale'
```

**System description**

- Operating System: Linux, Pop!_OS 20.04 LTS (Ubuntu 20.04)
- GRASS GIS version: main branch

**Additional context**

Everything works for me in English, but just noticed this warning when compiling.

**Comment by neteler** [comment]
Technically it would work like this:

```
# clean PO catalogue of duplicated messages
mv grasswxpy_de.po grasswxpy_de.po.BAD
# --no-wrap or  --width=XX?
msguniq --use-first --width=80 grasswxpy_de.po.BAD > grasswxpy_de.po
```

Just I don't seem to get the width right in order to have minimal changes.
Well, perhaps that doesn't matter and Weblate would reformat the file anyway...

**Comment by HuidaeCho** [comment]
> Technically it would work like this:
> 
> ```
> # clean PO catalogue of duplicated messages
> mv grasswxpy_de.po grasswxpy_de.po.BAD
> # --no-wrap or  --width=XX?
> msguniq --use-first --width=80 grasswxpy_de.po.BAD > grasswxpy_de.po
> ```
> 
> Just I don't seem to get the width right in order to have minimal changes. Well, perhaps that doesn't matter and Weblate would reformat the file anyway...

I thought `make update-po` takes care of merging.
https://github.com/OSGeo/grass/blob/76bcffb3571a2df5843c38a05a9e9e37434c5ebb/locale/Makefile#L70-L80

**Comment by neteler** [comment]
> I thought `make update-po` takes care of merging.

AFAIK no, as `msguniq` is missing in  `make update-po`.
