### ISSUE TITLE
[Feat] `topoidx` needs a projected raster, but this is not documented

### ISSUE THREAD

**Issue by adamlilith** [OSGeo/grass#3475]
`topoidx` needs a projected raster, but this is not noted in the documentation for the module.

![image](https://github.com/OSGeo/grass/assets/7577062/f7dd6f35-cd64-4466-b7a3-bf55c0f1e746)

It's not a big problem when running in GRASS because you get this error message, but if GRASS is called by another program (e.g., **R** through `rgrass`), then the error isn't apparent.

**Comment by veroandreo** [comment]
Hi @adamlilith, thanks for the report. Would you be willing to open a pull request with your suggestion to enhance documentation? Fork this repo in your account, edit the file html and suggest the change via PR.

**Comment by HuidaeCho** [comment]
Please check #3488 and let me know if you want to add more information.
