### ISSUE TITLE
[Bug] Display commands for `d.mon` can take a long time *unexpectedly* to update the `cmd` file when first run.

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass#3481]
**Describe the bug**
When we run a display command (`d.*`) from the terminal to add a layer to a `wx*` monitor, it runs twice:
1. Original process executed by the user without `GRASS_REGION` (display extent): This process adds a new command line to the `cmd` file. If the command takes a long time to finish for the entire raster region, we have to wait even if the display extent is very small.
2. Another process executed by the monitor with `GRASS_REGION`: The monitor runs the above command line saved in the `cmd` file, but this time with the current display extent. The same command can run quickly if the display extent is very small. Ultimately, we will only see this result.

**To Reproduce**

```bash
wget https://data.isnew.info/grass/nidp.pack https://data.isnew.info/grass/drain_tx.pack
grass -c epsg:5070 /tmp/grass_test
r.unpack -o nidp.pack
r.unpack -o drain_tx.pack
g.region rast=nidp -ap
d.mon wx0
d.rast nidp
# zoom to a very small region in the wx0 monitor (e.g., 50x50 grid)
d.rast.arrow -a drain_tx type=drainage # takes very long for a small region
```
See it takes long even though the display extent is very small

**Expected behavior**
Any display commands should *always* honor the current display extent.

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version: main branch

**Additional context**
`GRASS_REGION` is internal to the monitor and the terminal doesn't have access to it. Even if `GRASS_REGION` was exposed to the terminal, display commands would still run twice.

I changed

https://github.com/OSGeo/grass/blob/b45319c8a35c68d8d80c49f6e5e12da42a01961e/display/d.rast.arrow/main.c#L222-L223

to

```c
    /* Setup driver and check important information */
    D_open_driver();

    if (!getenv("GRASS_REGION")) {
        D_save_command(G_recreate_command());
        D_close_driver();
        exit(EXIT_SUCCESS);
    }
```
and it worked. Basically, `d.rast.arrow` just adds a new command line to the `cmd` file and exits. Then, it'll be executed by the monitor for actual rendering. This solution is not very elegant and takes the module developer's effort.

Maybe, we add to `D_open_driver()`:
```c
    if (!getenv("GRASS_REGION")) {
        D_save_command(G_recreate_command());
        D_close_driver();
        return 1;
    }
```
and in each display module:
```c
    /* Setup driver and check important information */
    if (D_open_driver() == 1) exit(EXIT_SUCCESS);
```
if rendering for the entire computational region can be expensive.

Still, I'm not 100% sure that `GRASS_REGION` must be required to render anything on a display. For example, render this entire raster on a PNG. I think we need a solution.

Created #3482.

**Comment by HuidaeCho** [comment]
Or something like this... In `D_open_driver()`
```c
    if (**running in a tty OR not in GUI**) {
        D_save_command(G_recreate_command());
        D_close_driver();
        return 1; /* it would be easier to just kill the process here, so we don't have to change anything
                     in display modules, but I'm not sure if that would be a better design */
    }
```
and in each display module:
```c
    /* Setup driver and check important information */
    if (D_open_driver() == 1) exit(EXIT_SUCCESS);
```

**Comment by HuidaeCho** [comment]
OK, `D_open_driver()` already `exit()`, but `d.rast.arrow` doesn't do that for some reason.

**Comment by HuidaeCho** [comment]
I did more testing. Without any changes to display modules, changing this:
https://github.com/OSGeo/grass/blob/b45319c8a35c68d8d80c49f6e5e12da42a01961e/lib/display/r_raster.c#L148-L155
to
```c
    if (p && G_strcasecmp(drv->name, p) != 0)
        G_warning(_("Unknown display driver <%s>"), p);
    G_verbose_message(_("Using display driver <%s>..."), drv->name);
    LIB_init(drv);

    init();

    if (!getenv("GRASS_REGION")) {
        D_close_driver();
        exit(0);
    }
```
worked.

**Comment by HuidaeCho** [comment]
#3482 now uses a less invasive approach by returning `-1` and letting individual modules decide what to do when `GRASS_REGION` is not defined (`D_open_driver() == -1`). Without any code changes in display modules (not checking `D_open_driver()` return value), everything should be the same as before.

**Comment by wenzeslaus** [comment]
I can confirm the issue, but the solution with `GRASS_REGION` does not look right to me because GRASS_REGION is what happens to be used in this context and is used in wxGUI and grass.jupyter, but that's not the only way to render.

Additionally, I actually tested the most bare bones way of rendering and that does not work with the new code (your two relevant PRs combined). The following takes ages with the current code, but with the proposed code, it does not render anything: 

```bash
export GRASS_RENDER_IMMEDIATE=cairo
export GRASS_RENDER_FILE_READ=TRUE
g.region rows=50 cols=50
rm map.png 
d.rast nidp
d.rast.arrow -a drain_tx type=drainage
echo $?  # 0 reported, but map.png contains only nidp
```

I must say I don't understand how GRASS_REGION fixes that since g.region does not fix it for me here. Are there two issues? Double rendering going on or double init and the region not being respected? Is that the case?

**Comment by HuidaeCho** [comment]
> I can confirm the issue, but the solution with `GRASS_REGION` does not look right to me because GRASS_REGION is what happens to be used in this context and is used in wxGUI and grass.jupyter, but that's not the only way to render.
> 
> Additionally, I actually tested the most bare bones way of rendering and that does not work with the new code (your two relevant PRs combined). The following takes ages with the current code, but with the proposed code, it does not render anything:
> 
> ```shell
> export GRASS_RENDER_IMMEDIATE=cairo
> export GRASS_RENDER_FILE_READ=TRUE
> g.region rows=50 cols=50
> rm map.png 
> d.rast nidp
> d.rast.arrow -a drain_tx type=drainage
> echo $?  # 0 reported, but map.png contains only nidp
> ```
> 
> I must say I don't understand how GRASS_REGION fixes that since g.region does not fix it for me here. Are there two issues? Double rendering going on or double init and the region not being respected? Is that the case?

The `-a` flag for `d.rast.(arrow|num)` currently means draw arrows and numbers aligned with original *raster* cells.

I think you meant:
```bash
export GRASS_RENDER_IMMEDIATE=cairo
export GRASS_RENDER_FILE_READ=TRUE
g.region rows=50 cols=50
rm map.png 
d.rast nidp
d.rast.arrow drain_tx type=drainage
```
which worked for me.

**Comment by wenzeslaus** [comment]
I can confirm that with the latest change the basic ("immediate") rendering works again.

Still, does the rendering actually happen twice? If yes, #3482 seems like fixing this double rendering issue using an implementation detail of the monitor-driven rendering somewhere deep in the monitor system, namely usage of GRASS_REGION. If user defines GRASS_REGION in the terminal, the GRASS_REGION-based test will pass and the situation is the same as what these PRs are trying to address. Is there a different way to tell that a d-command is being used as an interface in d.mon monitors rather than being used for actual rendering of data to a file? Or we say GRASS_REGION is the way and ignore the edge cases?
