### ISSUE TITLE
r3.out.netcdf seems to output only one 2D map

### ISSUE THREAD

**Issue by AlisterH** [OSGeo/grass#3507]
**Describe the bug**
It seems that r3.out.netcdf is not working.  If I try to export a temporal 3D raster I seem to just get a raster with a single grid of null cells.

If I instead try to export a non-temporal 3d raster, then I again only get a single grid of cells, but this time it does have values (from the first input I provided to r.to.rast3)

**To Reproduce**
I'm pretty sure I should be able to create a temporal raster in netcdf format with something like this:

```
r.mapcalc expression="t1 = 1"
r.mapcalc expression="t2 = 2"
r.mapcalc expression="t3 = 3"
r.mapcalc expression="t4 = 4"
r.mapcalc expression="t5 = 5"

t.create output=t temporaltype=relative semantictype=sum title=relative description=relative
t.register input=t maps=t1 start=1 unit=minutes
t.register input=t maps=t2 start=2 unit=minutes
t.register input=t maps=t3 start=3 unit=minutes 
t.register input=t maps=t4 start=4 unit=minutes
t.register input=t maps=t5 start=5 unit=minutes

t.rast.to.rast3 input=t output=t3d
r3.out.netcdf input=t3d output=t3d.nc
```

**Expected behavior**
Inspecting 3d rasters in GRASS before outputting to netcdf I believe they are correct.
But I have tried inspecting the netcdf output with various tools, starting with "drag and drop into QGIS", and it does not seem to be correct, as per the description above.
I also note that the netcdf file size is the same regardless of the number of rasters originally combined into the 3d raster.

**System description**

- Operating System: Windows
- GRASS GIS version 8.3.2
- I also tried testing with the GRASS in [RollApp](https://www.rollapp.com/home) (which appears to be a linux system, with a slightly older version of GRASS), and it seems to have the same problem.

**Comment by petrasovaa** [comment]
Before looking into this more, could you check the computational region? I would assume you need to do:
```
t.rast.to.rast3 input=t output=t3d
g.region raster_3d=t3d
r3.out.netcdf input=t3d output=t3d.nc

```

**Comment by AlisterH** [comment]
`g.region raster_3d=t3d`
Ah, thanks - you are exactly right.
It was perplexing coming at this wanting to export temporal data and not having worked in 3D before, but I guess I should have been able to figure it out from the docs.
Apologies for the noise; hopefully anyone else with the same difficulty can find this.
