### ISSUE TITLE
[Feat] Add JSON output to r.what

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#3518]
Add JSON output for easy parsing of r.what output.

**Describe the solution you'd like**
Adding option `format`, it would be something like `format=plain` for the current output format and `format=json` for the JSON output. There is a newly added parson library to GRASS (#3028), so it should be used here. 

See also discussion in #3019.

A test should be included.

**Comment by kritibirda26** [comment]
Thanks for opening the issue, I'll start looking into this,

**Comment by kritibirda26** [comment]
Hi! I had some trouble working with parson because there is no other use in the codebase so far but I was eventually able to figure it out. Hence, I have opened a PR above to add the JSON support. Kindly review whenever possible.
