### ISSUE TITLE
[Bug] Ensure doc compilation files are ignored in .gitignore

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#3521]
I'm filing an issue to add a work item to have a look at the .gitignore file, to make sure that generated docs are correctly ignored, as happened in this PR:

> Something went wrong and your PR has a bunch of unrelated files added. Perhaps `git add -A`? Try `git add -p` instead.

Huh! It seems that doc compilation files are missing from the `.gitignore`.

_Originally posted by @marisn in https://github.com/OSGeo/grass/pull/3516#issuecomment-2015736244_

**Comment by marisn** [comment]
I'm not that familiar with python documentation building thus there could be more files to ignore than I listed in the https://github.com/OSGeo/grass/pull/3522
