### ISSUE TITLE
[Feat] Add JSON output to r.colors.out

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#3537]
Add JSON output for easy parsing of r.colors.out output.

**Describe the solution you'd like**
Adding option format, it would be something like format=plain for the current output format and format=json for the JSON output. There is a newly added parson library to GRASS (https://github.com/OSGeo/grass/pull/3028), so it should be used here.

See also discussion in https://github.com/OSGeo/grass/discussions/3019.

A test should be included.
A possible JSON layout could be:
```
[
  {
    "value": 0,
    "red": 255,
    "green": 0,
    "blue": 0
  },
  {
    "value": 1,
    "red": 0,
    "green": 255,
    "blue": 0
  },
  {
    "value": 2,
    "red": 0,
    "green": 0,
    "blue": 255
  }
]
```

**Comment by cwhite911** [comment]
It might be nice to have the output in a usable formats.

```json
[
 {
    "value": 0,
    "hex": "#FF0000",
    "rgb": "rgb(255, 0, 0)",
    "rgb": "rgb(255, 0, 0, 0)",
    "hsl":  "hsl(0, 100, 50)"
  }
]
```

**Comment by NishantBansal2003** [comment]
Hey, I was trying to look up this issue. Can you help me out a little? I want to know how I can test any changes I make to check their output. 

> ```json
> [
>  {
>     "value": 0,
>     "hex": "#FF0000",
>     "rgb": "rgb(255, 0, 0)",
>     "rgb": "rgb(255, 0, 0, 0)",
>     "hsl":  "hsl(0, 100, 50)"
>   }
> ]
> ```

Also, if you could provide a specific test that generates this output, I can use it to test my changes. Additionally, can you tell me how to test the changes overall, including some commands for integration tests?
