### ISSUE TITLE
[Bug] r.in.pdal fails with PDAL 2.7

### ISSUE THREAD

**Issue by landam** [OSGeo/grass#3552]
**Describe the bug**

`r.in.pdal` fails to import LAZ files:

```
Reading data...
terminate called after throwing an instance of 'pdal::pdal_error'
  what():  writers.grassbinning: Missing value for positional argument 'filename'.
```

**To Reproduce**

1. Download sample data https://ags.cuzk.cz/geoprohlizec/?atom=dmr5g (or use attached sample: [KRAV59.zip](https://github.com/OSGeo/grass/files/14832557/KRAV59.zip))
2. Create location in EPSG 5514
3. Run `r.in.pdal -oe input=06/dmr5g/KRAV59.laz output=KRAV59 resolution=1`

**Expected behavior**

The same sample data is successfully imported when GRASS is compiled with PDAL 2.6.

**System description (please complete the following information):**

- Operating System: Debian Linux
- GRASS GIS version main

**Comment by marisn** [comment]
8.3 would also benefit from this fix.

**Comment by nilason** [comment]
> 8.3 would also benefit from this fix.

Indeed. The (merged) PR has the "backport" label, so this could be closed. It will not be forgotten.
