### ISSUE TITLE
[Bug] Adjust Windows CI workflows for Python 3.12

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#3596]
**Describe the bug**

OSGeo4W has updated the base packages. The biggest change is using Python 3.12 instead of Python 3.9. It builds the grass package successfully there.

Here, not the same script is used, and the Python version is hardcoded in a couple of places, thus failing ALL windows jobs. 

**To Reproduce**

1. Se recent Windows runs, like https://github.com/OSGeo/grass/actions/runs/8681515856 or https://github.com/OSGeo/grass/actions/runs/8687022235

**Expected behavior**

Python 3.9 not hardcoded, workflows work. 

**Additional context**

Maybe check if the package list is still up to date. Some packages compiles with VS2022, is it time to change to windows 2022 runner? (The 2022 doesn't _have_ to match though)

See https://lists.osgeo.org/pipermail/grass-dev/2024-April/096271.html for the explanation that not the same script is used, thus why ours fail.

**Comment by jef-n** [comment]
Both are "yours".   https://github.com/OSGeo/grass/blob/main/mswindows/osgeo4w/build_osgeo4w.sh#L21 vs. https://github.com/OSGeo/grass/blob/main/mswindows/osgeo4w/package.sh#L50
