### ISSUE TITLE
[ Reading settings from file: not enough values to unpack (expected 2, got 1) Line: '']

### ISSUE THREAD

**Issue by byasseepm** [OSGeo/grass#362]
_Apologies as I am very new to GRASS and python..._

Upon startup, command line reads:

```
Error: Reading settings from file <C:\Users\paige.byassee\AppData\Roaming\GRASS7\wx> failed.
                Details: not enough values to unpack (expected 2, got 1)
                Line: ''
```

This line will re-appear every time I call a function but doesn't seem to inhibit the function? (screenshot)

**To Reproduce**

Reproduced on previous ticket https://trac.osgeo.org/grass/ticket/3940#no1 **but** I've tried playing with the locale and software version but I cannot find a solution...

**Expected behavior**
Error message continues appearing; may not interfere

**Screenshots**
![GrassError](https://user-images.githubusercontent.com/60277584/74971703-5fe1e280-53d5-11ea-8741-377ce3445977.PNG)

**System description**

- Windows 10
- GRASS GIS version 7.9.dev (7069dd39d)

**Additional context**
I don't believe this computer ever had GRASS 7.6.1. I installed it a month or so back, no issues, then error suddenly appeared.

If I try to install notranslation function according to https://github.com/OSGeo/grass/pull/156/files I get the following message:

`C:\Users\paige.byassee>g.extension notranslation
WARNING: GRASS GIS libgis version and date number not available
Downloading precompiled GRASS Addons <notranslation>...
ERROR: Cannot open URL:
       http://wingrass.fsv.cvut.cz/grass79/x86_64/addons/grass-7.9.dev/notranslation.zip`

_Thanks and so sorry for any redundancies_

**Comment by marisn** [comment]
It is hard to say if your issue was fixed by pull #156 Judging by your version string (7.9), it is a different issue. You should attach your wx file for more detailed examination. Or as a workaround you could try to delete wx file and then launch GRASS. It will create a new wx file with default settings.

**Comment by byasseepm** [comment]
wx file as requested:

[lab_grass_wx.txt](https://github.com/OSGeo/grass/files/4246262/lab_grass_wx.txt)

If running g.region, incorrect values returned:

`C:\Users\paige.byassee>g.region -bg
ll_n=45.85142636
ll_s=-0.00000762
ll_w=-123.41959762
ll_e=-115.70360792
ll_clon=-119.56160277
ll_clat=22.92570937`

If running `r.univar -g DEM.tif`, no return--stalls out.

Thank you

**Comment by marisn** [comment]
> wx file as requested:

This is a wrong file. You should attach C:\Users\paige.byassee\AppData\Roaming\GRASS7\wx

> If running g.region, incorrect values returned:

This has nothing to do with the error reported.

> If running `r.univar -g DEM.tif`, no return--stalls out.

This has nothing to do with the error reported.

**Comment by byasseepm** [comment]
Corrected- 

[wx.txt](https://github.com/OSGeo/grass/files/4263505/wx.txt)
