### ISSUE TITLE
[Bug] CI: releasebranch_8_3 failure for CentOS and OSGeo4W

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#3653]
**Describe the bug**

The today's backporting of some PRs shows that the CI is no longer working ok for `releasebranch_8_3`.

CentoOS:

```
Run source $CONDA_ACTIVATE
/__w/_temp/10995748-8704-4199-986d-c0989f5a33ab.sh: line 1: source: filename argument required
source: usage: source filename [arguments]
Error: Process completed with exit code 2.
```

OSGeo4W:

```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```

Logs:
- CentOS: https://github.com/OSGeo/grass/actions/runs/8798695813/job/24146234239
- OSGeo4W: https://github.com/OSGeo/grass/actions/runs/8798695807/job/24146234192

**Expected behavior**
The CI jobs should complete.

**Additional context**

Probably some CI-related backports are missing?

**Comment by nilason** [comment]
Centos runner was removed on main with #3141.

**Comment by wenzeslaus** [comment]
> Centos runner was removed on main with #3141.

Removed on main AND not working with other changes we want -> remove.
