### ISSUE TITLE
[Bug] r.proj from EPSG:3031 to EPSG:4326 returns one grid cell

### ISSUE THREAD

**Issue by mankoff** [OSGeo/grass#3655]
**Describe the bug**

I'm trying to reproject an Antarctic dataset on EPSG:3031 to EPSG:4326. I can successfully do Greenland EPSG:3413 to EPSG:4326, but the same commands for Antarctica return 1 grid cell and report 

**To Reproduce**

1. Run the following commands

Set up 4326 mapset

```bash
grass --text -c EPSG:4326 ./G_4326
g.region res=1 -pa w=-180 e=180 s=-90 n=90 -pas # 1° x 1°
exit
```

3031 mapset

```bash
grass -c EPSG:3031 ./G_3031
# 500 m resolution, matching BedMachine boundaries
bound=3333250
g.region res=500 w=-${bound} e=${bound} s=-${bound} n=${bound} -ps
r.mapcalc "foo = 42"
exit
```

Reproject

```bash
grass ./G_4326/PERMANENT
r.proj location=./G_3031 mapset=PERMANENT input=foo # output: 1 column!
```

**Expected behavior**

The input dataset spans all longitudes and covers Antarctica. I'd expect the output dataset to do this, reprojected into EPSG:4326.

**Screenshots**

Screenshots come from earlier (see first version of this issue under the `edit` item above) using BedMachine. The current `g.region` matches that from BedMachine.

3031:

![image](https://github.com/OSGeo/grass/assets/145117/a868441e-5c7f-42ee-9a47-9790561230cd)

4326:

![image](https://github.com/OSGeo/grass/assets/145117/24491629-4497-4635-9118-f648f625cf26)

**System description (please complete the following information):**

```
t480:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
t480:~ $ uname -a
Linux t480 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
t480:~ $ ```


```
version=8.3.2
date=2024
revision=exported
build_date=2024-03-08
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=8.3.2
libgis_date=2024-03-08T09:26:59+00:00
proj=9.3.1
gdal=3.8.4
geos=3.12.1
sqlite=3.37.2
```

**Comment by mankoff** [comment]
@dhdeangelis 

> Can you reproject the grid using just GDAL (gdalwarp)?

Yes. With `gdalwarp -t_srs EPSG:4326 NETCDF:"BedMachineAntarctica-v3.nc":mask output.tiff` everything appears OK to me. I'm also happy to share the file if you want to help debug this, but don't want to post a public link to DropBox and am not sure how else to share it.

**Comment by mankoff** [comment]
Same issue when using GRASS 7.8.8 from `mundialis/grass-py3-pdal:7.8.8-alpine` https://grass.osgeo.org/download/docker/#GRASS-GIS-old

I've reproduced this without BedMachine. I apologize for the non-minimal example before. I include an MWE below and I will edit the original post with this simplified code.

Set up 4326 mapset

```bash
grass --text -c EPSG:4326 ./G_4326
g.region res=1 -pa w=-180 e=180 s=-90 n=90 -pas # 1° x 1°
exit
```

3031 mapset

```bash
grass -c EPSG:3031 ./G_3031
# 500 m resolution, matching BedMachine boundaries
bound=3333250
g.region res=500 w=-${bound} e=${bound} s=-${bound} n=${bound} -ps
r.mapcalc "foo = 42"
exit
```

Reproject

```bash
grass ./G_4326/PERMANENT
r.proj location=./G_3031 mapset=PERMANENT input=foo # output: 1 column!
```

**Comment by mankoff** [comment]
I note this is *sensitive*. If I change `g.region res=500` to `res=250` or `res=1000` the bug does not appear.

**Comment by dhdeangelis** [comment]
I have downloaded the BedMachine dataset and could reproduce the error.

**Comment by dhdeangelis** [comment]
I may have found a solution to this. It involves using the **-n** option:

From the r.proj manual (https://grass.osgeo.org/grass84/manuals/r.proj.html):

> When reprojecting whole-world maps the user should disable map-trimming with the -n flag. Trimming is not useful here because the module has the whole map in memory anyway. Besides that, world "edges" are hard (or impossible) to find in CRSs other than latitude-longitude so results may be odd with trimming. 

I tried and worked for me using the 500 m region as source and a LonLat region as target:

```
> r.proj -n project=antartida_500m mapset=PERMANENT input=bm

Input:
Cols: 13333 (original: 13333)
Rows: 13333 (original: 13333)
North: 3333250.000000 (original: 3333250.000000)
South: -3333250.000000 (original: -3333250.000000)
West: -3333250.000000 (original: -3333250.000000)
East: 3333250.000000 (original: 3333250.000000)
EW-res: 500.000000
NS-res: 500.000000

Output:
Cols: 1440 (original: 1440)
Rows: 133 (original: 133)
North: -56.750000 (original: -56.750000)
South: -90.000000 (original: -90.000000)
West: -180.000000 (original: -180.000000)
East: 180.000000 (original: 180.000000)
EW-res: 0.250000
NS-res: 0.250000

Allocating memory and reading input raster map...
 100%
Selected PROJ pipeline:
+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step
+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
************************
Projecting...
 100%
r.proj complete.
```

![image](https://github.com/OSGeo/grass/assets/51515911/26e03490-c8b1-47f4-873c-3cfd27d1f8fd)

**Comment by dhdeangelis** [comment]
@mankoff @veroandreo is this still of interest? IMO the problem was that the reprojection involving the pole and -n seems to take care of that. Perhaps some clarification can be added to the manual and then this cloud be closed.

**Comment by mankoff** [comment]
@dhdeangelis thanks for keeping this in mind and helping me solve the issue. I've added a small PR to recommend looking more carefully at the `Notes` section of the document if working in a global lat-lon setup. As I say in the PR, I'm not sure this is needed - maybe I just need to read the docs more carefully.
