### ISSUE TITLE
Grass GIS version 8.3.2.1   problem

### ISSUE THREAD

**Issue by MHaghiri** [OSGeo/grass#3676]
I use the Grass GIS version 8.3.2.1 jammy1
so when I open it, promptly is close, without any error.
so what should I do to fix this problem?
Best,
Mohammad.

**Comment by wenzeslaus** [comment]
Try opening GRASS GIS from a terminal:
* Use Ctrl+Alt+T to open a terminal.
* Type `grass` and press `Enter` to run GRASS GIS.
* Errors should be visible in the terminal.
* Take screenshot.
* Try to copy paste the errors from the terminal.

**Comment by MHaghiri** [comment]
mohammad@palaeohydrology-lab-2:~$ grass
Usage: grass [OPTIONS]
Try 'grass -h' for help.

Error: Missing option '--config'.

![Screenshot from 2024-04-30 09-11-29](https://github.com/OSGeo/grass/assets/153953196/451b71e0-ceba-48c6-b460-dfca5ab90163)
![Screenshot from 2024-04-30 09-11-29](https://github.com/OSGeo/grass/assets/153953196/65719a44-b488-48b1-9dd3-8b932261642c)

**Comment by wenzeslaus** [comment]
Can you please try

```
grass -h
```

and

```
grass --version
```

?

**Comment by MHaghiri** [comment]
yes
![grass version2](https://github.com/OSGeo/grass/assets/153953196/9f4f851c-fa4a-4d4b-9232-a27eab01c21f)
![grass](https://github.com/OSGeo/grass/assets/153953196/8ff01f43-98b7-4b03-b770-9c57b8339988)

**Comment by MHaghiri** [comment]
I use this code to install it:
sudo apt-get install grass

**Comment by wenzeslaus** [comment]
Didn't you install also with `pip install grass`? This is unrelated package in PyPI repository which may bring a binary called "grass". Try `pip uninstall grass`.

**Comment by MHaghiri** [comment]
Thank you.
My problem is solved
I tried pip uninstall grass
Thanks

**Comment by wenzeslaus** [comment]
Glad to hear that! Closing as solved.
