### ISSUE TITLE
Renovate naming convention issue

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#3703]
I asked the other day on what was happening, and I got an answer today: https://github.com/renovatebot/renovate/discussions/28516#discussioncomment-9396694

There's a hypothesis on what is going on, and an idea on how to fix it, but I'd like to know what you think we should use as naming convention for it. If we are going to work to tune the config to a very specific style to match the previous behaviour, we might as well choose any desired behaviour and do the change right now.

**Comment by wenzeslaus** [comment]
I tried to read through couple days ago and didn't get much out if it. If the convention is different, but distinguishable from what we use in general, then we can accommodate it in the procedure to sorting out PRs before a release. Obviously, consistency is preferable.
