### ISSUE TITLE
Tests are failing in CI with an ISO format error

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#3717]
The tests are failing in CI with this weird error but the build passes locally. Also, the string that is said to be invalid is actually a valid isoformat string.

```
gnu/docs/html/g.gui.timeline.html
Traceback (most recent call last):
  File "/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/utils/mkhtml.py", line 921, in <module>
    git_commit = get_last_git_commit(
  File "/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/utils/mkhtml.py", line 397, in get_last_git_commit
    return parse_git_commit(
  File "/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/utils/mkhtml.py", line 242, in parse_git_commit
    git_log["date"] = format_git_commit_date_from_local_git(
  File "/home/runner/work/grass/grass/dist.x86_64-pc-linux-gnu/utils/mkhtml.py", line 345, in format_git_commit_date_from_local_git
    return datetime.fromisoformat(
ValueError: Invalid isoformat string: '2024-05-17T16:09:45Z'
```

https://github.com/OSGeo/grass/actions/runs/9131120968/job/25109628154?pr=3704#step:8:6469

_Originally posted by @kritibirda26 in https://github.com/OSGeo/grass/issues/3704#issuecomment-2118039109_

**Comment by wenzeslaus** [comment]
Older Python does not support Z while recent one does ([3.8 does not, 3.11 does](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat)).

To test locally:

```python
>>> datetime.fromisoformat('2011-11-04T00:05:23Z')
```

Given that it seems this changed on us, the change might be coming from configuration of the CI machine either for time zone or for version of Git. In the code, we are using something like:

```bash
git log --format="%aI"
```

This gives committer time with different time zones (not influenced by TZ variable). I get some +00:00 but not Z (Z is short for +00:00). `%Ia` is "author date, strict ISO 8601 format" according to the [Git doc](https://git-scm.com/docs/git-log), but that can be Z or +00:00 as far as I understand.

```bash
$ git --version 
git version 2.25.1
$ python --version
Python 3.8.10
```

**Comment by wenzeslaus** [comment]
The latest version of Git is 2.45.1 ([source](https://git-scm.com/download/linux)) and it contains https://github.com/git/git/commit/1f49f7506f0d840e048ba78f7e0544c407568b58:

```
The output format for dates "iso-strict" has been tweaked to show
a time in the Zulu timezone with "Z" suffix, instead of "+00:00".

* bb/iso-strict-utc:
  date: make "iso-strict" conforming for the UTC timezone
```

How it actually is with Z vs +00:00 is not clear to me (whether Z is actually more strict when +00:00 refers to the local time zone rather than UTC time...), but that's not important here.

So anyway, the CI actually has latest Git which produces Z and Python is 3.10 which does not support Z in [fromisoformat (3.10)](https://docs.python.org/3.10/library/datetime.html#datetime.datetime.fromisoformat).

We need to either 1) upgrade Python in CI, 2) downgrade Git in CI, or 3) deal in code with non-matching "freshness" of Python and Git.

Number 1 seems best but 3 seems okay too and is doable (try endswith and replace on ValueError).

**Comment by wenzeslaus** [comment]
Note: Some PRs happily run (#3719). Maybe different Git on different VMs in CI...

**Comment by echoix** [comment]
https://github.com/actions/runner-images/releases

https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240516.4

There is an image 20240516.4.1 (the one used in the linked run), that I see has git 2.45.1 instead of 2.43.2 (for the 20240510.1.0).

![image](https://github.com/OSGeo/grass/assets/27212526/d279da6d-971f-4bf4-92b8-e200cee3a46e)

Images are changed almost weekly and can take up to a week to fully deploy, so, it's totally possible to have some running on different VMs, as it was yesterday.

You may want to see if there are other suspects in it.

At the same time, we can now use the ubuntu-24.04 tag, as beta, if we wanted to. I saw that they included a bit less of software for maintenance reasons, and less cached images. It at least has easy access to the newest gcc compiler.

**Comment by echoix** [comment]
You might also want to take a look at https://github.com/actions/runner-images/issues/9883

**Comment by wenzeslaus** [comment]
> You might also want to take a look at [actions/runner-images#9883](https://github.com/actions/runner-images/issues/9883)

Thanks. This helped me to decide that we just need to accommodate the different versions.
