### ISSUE TITLE
[Feat] Rename location to project in images in docs

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#3770]
**Is your feature request related to a problem? Please describe.**
Last weekend (or the one before) I found some occurrences of location instead of project in images (schema) of the architecture of grass. It might be an svg. I was searching for more context for a string to translate, and stumbled upon it. 

**Describe the solution you'd like**
Align the schema with the text of the same page.

**Comment by petrasovaa** [comment]
Do you know which one specifically?

**Comment by echoix** [comment]
https://grass.osgeo.org/grass84/manuals/grass_database.html
