### ISSUE TITLE
[Bug] Can't create new location in Grass 7.8.2 - missing projections

### ISSUE THREAD

**Issue by obrl-soil** [OSGeo/grass#381]
**Describe the bug**
Can't create new location in Grass 7.8.2 - missing projections. OSGeo4W, Win10

**To Reproduce**

1. Clean express install OSGeo4W64
2. Launch GRASS 
3. Click New grass location, then Next
4. Select radio button 'Select EPSG code of spatial reference system', next
5. list of codes is not visible and cannot be searched. Next is greyed out, cannot proceed further

**Expected behavior**
List of projections available for choosing

**System description (please complete the following information):**

- Operating System: Windows 10 Enterprise build 18363
- GRASS GIS version 7.8.2
- in OSgeo4w shell, `grass78 g.version - rge` errors out as database directory, mapset and location are not set correctly 

**Additional context**
`epsg` file missing from usual location `C:\OSGeo4W64\share\proj`
Can't see any relevant issues under `OSgeo/proj`
Adding proj5 using the advanced installer option causes the epsg file to appear but does not solve this problem
Error message on first launch that demolocation is missing - should be in   `C:\Users\%USER%\Documents\grassdata`, which was not created on install. Can find it in `C:\OSGeo4W64\apps\grass\grass78` tho...
All support packages mentioned in #371 are installed
Standalone GRASS installer works perfectly

**Comment by obrl-soil** [comment]
Update - rolling back to PROJ 6.3.0 solves this problem, so this issue may need to be migrated to OSGeo/PROJ.

**Comment by hellik** [comment]
which PROJ version did you use in the OSGeo4W environment when the error appeared?

**Comment by hellik** [comment]
Current is: proj, 6.3.1-1
See http://download.osgeo.org/osgeo4w/x86_64/versions.html

**Comment by hellik** [comment]
>in OSgeo4w shell, grass78 g.version - rge errors >out as database directory, mapset and location >are not set correctly

Grass78 g.version, error is correct as it is not intended to work in that way

**Comment by hellik** [comment]
>Additional context
>epsg file missing from usual location

not sure which PROJ version you want to use.

PROJ >6 doesn't use EPSG and other files from earlier versions anyone, but instead an sqlite proj.db.  have a look at www.oroj.org

**Comment by obrl-soil** [comment]
The express installer just uses whatever version of PROJ is current in the package, so 6.3.1 in this case. However, it appears that currently, one must run the express installer and then re-run it under the advanced workflow to roll PROJ back to 6.3.0 before GRASS and QGIS will work properly.

I'm aware of the internal changes to PROJ. I still can't tell exactly what's happening, but it looks like GRASS is able to find the projection info it requires using 6.3.0 but not 6.3.1. I can't see anything obvious in the [6.3.1 changelog](https://github.com/OSGeo/PROJ/releases/tag/6.3.1) that would be connected.

**Comment by landam** [comment]
@obrl-soil Please check a new GRASS OSGeo4W package (7.8.2-2), it's built against PROJ 6.3.1.

**Comment by obrl-soil** [comment]
Ah, that's fixed the issue. Thanks @landam !
