### ISSUE TITLE
r.in.pdal handling the number of returns

### ISSUE THREAD

**Issue by mazingaro** [OSGeo/grass#3827]
### Zero-indexed values of the return number
r.in.pdal reports zero-indexed values of the return number.
The first return is idexed as return[0], second as return[1] etc. 
`r.in.pdal -p input=point_cloud.laz`

I am appending a `pdal info --stats` report.

```
Using PDAL library version '2.7.1 (git-version: Release)'
File: point_cloud.laz
File version = 1.4
File signature: LASF
File source ID: 0
Global encoding: 17
Project UUID: 00000000-0000-0000-0000-000000000000
System ID: AL;
Software ID: TerraScan
Creation DOY: 34
Creation Year: 2024
VLR offset (header size): 375
VLR Count: 2
Point format: 8
Point offset: 729
Point count: 23595745
Point count by return[0]: 11930597
Point count by return[1]: 7817264
Point count by return[2]: 3105005
Point count by return[3]: 660896
Point count by return[4]: 80761
Point count by return[5]: 1200
Point count by return[6]: 22
Point count by return[7]: 0
Point count by return[8]: 0
Point count by return[9]: 0
Point count by return[10]: 0
Point count by return[11]: 0
Point count by return[12]: 0
Point count by return[13]: 0
Point count by return[14]: 0
Scales X/Y/Z: 0.00025/0.00025/0.00025
Offsets X/Y/Z: 500000/-0/-0
Max X/Y/Z: 479000/71000/808.982
Min X/Y/Z: 478000/69999.9/498.449
Ext. VLR offset: 0
Ext. VLR count: 0
Compressed: true
Dimensions: X, Y, Z, Intensity, ReturnNumber, NumberOfReturns, ScanDirectionFlag, EdgeOfFlightLine, Classification, Synthetic, KeyPoint, Withheld, Overlap, ScanAngleRank, UserData, PointSourceId, GpsTime, ScanChannel, Red, Green, Blue, Infrared, Deviation
```
The code in question seems to be

https://github.com/OSGeo/grass/blob/main/raster/r.in.pdal/info.cpp#L118C1-L118C67

**Return numbers have a range from 1 - 5 instead of the full range.**

When using r.in.pdal to create a raster of return numbers it imports just the first 5. The produces map is correct but it lacks returns.
`r.in.pdal -e -o input=point_cloud.laz output=point_cloud_return_number type=CELL resolution=1 dimension=returns`
 Majorly we find 5 reurns from LiDAR scanners. Modern RIEGL scanners can have up to 7 returns. PDAL shows 7 return values.

**Comment by marisn** [comment]
Could you, please, clarify what exactly is the issue? Zero based indexing in LAS info output? Or is there a problem when importing a LAS file? If so, could you share an example that fails to import correctly?

We do not interpret return count / numbers and just use plain values as provided by PDAL library.

**Comment by mazingaro** [comment]
> Could you, please, clarify what exactly is the issue? Zero based indexing in LAS info output? Or is there a problem when importing a LAS file? If so, could you share an example that fails to import correctly?
> 
> We do not interpret return count / numbers and just use plain values as provided by PDAL library.

So, The issue is that when you want to check (-p flag, not import )your point cloud (header) with r.in.pdal, you get the back the number of returns from 0 onward. As you can see in the firs post, the first entry of the returns is:
`Point count by return[0]: 11930597`
This is the information for the first return, not the zeroth return. If a user wants to check the number of fourth returns, it will probably focus on reading `Point count by return[4]: 80761`, which in reality shows the number of fifth returns. The PDAL library returns JSON outputs, which  means, that this is parsed? 
I am appending a part of pdal info, which doesnt show any return of category 
`pdal info --all 'point_cloud.laz'
```

      {
        "average": 1.326737844,
        "count": 22632487,
        "maximum": 7,
        "minimum": 1,
        "name": "ReturnNumber",
        "position": 4,
        "stddev": 0.6448665976,
        "variance": 0.4158529287
      }
```

**Comment by mazingaro** [comment]
Hi @rdzur, yes: the maps are correct. As mentioned above: the produced map is correct but it lacks returns. So it is just a report issue. When creating raster maps, lasgrid from LAStools also cuts the values. It is a historical problem which could mean that there were not algorithms updates for such things from point record version changes from LAS 1.4 v6 onward:

1.  *The Return Number is the pulse return number for a given output pulse. A given output laser pulse can have many returns, and they must be marked in sequence of return. The first return will have a Return Number of one, the second a Return Number of two, and so on **up to fifteen returns**. This is for the LAS 1.4 V6. [Page 27](https://www.asprs.org/wp-content/uploads/2019/03/LAS_1_4_r14.pdf).
2. *The Return Number is the pulse return number for a given output pulse. A given output laser pulse
can have many returns, and they must be marked in sequence of return. The first return will have
a Return Number of one, the second a Return Number of two, and so on **up to five returns**. The
Return Number must be between 1 and the Number of Returns, inclusive.* This is for the LAS 1.4 V0. [Page 17](https://www.asprs.org/wp-content/uploads/2019/03/LAS_1_4_r14.pdf).

PDAL recognises 7 return numbers in my data, which is correct.

**Comment by rdzur** [comment]
Hi @mazingaro, if you reduce your raster resolution, to say 0.33, can you get all seven return values represented in your output return_number raster?  

In testing with the clovis.laz file, for example, I modified the r.in.pdal command resolution to 1 ftUS `r.in.pdal -e -o -n input=clovis.laz output=clovis_return_number type=CELL resolution=1 dimension=returns --overwrite` 

After making this modification, the output return number raster represented all 6 returns from the input point cloud with `r.info -r map=clovis_return_number` providing min=1 and max=6.  This change, however, does result in a map with sparse data interspersed with nodata values given the point cloud density versus raster resolution.  If you need to approximate a more visually continuous map albeit with interpolated return number counts which may not work for your application, you could also run r.fill.stats on the return raster, e.g. `r.fill.stats -k --overwrite input=clovis_return_number output=clovis_return_number_1ftUS_fill distance=4 mode=mode power=2.0 cells=8`

**Comment by marisn** [comment]
>  1. _The Return Number is the pulse return number for a given output pulse. A given output laser pulse can have many returns, and they must be marked in sequence of return. The first return will have a Return Number of one, the second a Return Number of two, and so on **up to fifteen returns**._ This is for the LAS 1.4 V6. [Page 27](https://www.asprs.org/wp-content/uploads/2019/03/LAS_1_4_r14.pdf).

OK, I see now. In the code is a simple iterator and it is 0-based. It will be an easy change to print out n+1.

@rdzur MacOS issue is unrelated to this bug report. Please check that GRASS has been compiled with the PDAL library in use (and all of their dependencies are recompiled to correct versions too).

**Comment by neteler** [comment]
@mazingaro The second part above "Return numbers have a range from 1 - 5 instead of the full range." should go into a new issue.

**Comment by marisn** [comment]
> @mazingaro The second part above "Return numbers have a range from 1 - 5 instead of the full range." should go into a new issue.

I'm not certain if this is a bug (or do we want to tackle this). Looking at the PDAL code, it assumes for LAS files with version being >1.4 to always follow 15 return definition. As GRASS just reads the data provided by PDAL, doing otherwise would require to implement some kind of logic to what to display if there are no 15 returns in the data. Not worth it.

**Comment by mazingaro** [comment]
@rdzur for getting a whole, smooth map it would be maybe better to get more return maps (different resolutions) and patch them? But anyway, the information where there is no returns is also important when inspecting.

@rdzur ,@neteler and @marisn I agree that the second part should be another issue. There we can continue this talk and if we find it not worthy also close it soon.
