### ISSUE TITLE
[Bug] wxGUI digitizer: Python TypeError in wxpython/mapwin/buffered.py

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#391]
I digitized some areas in longlat, closed the digitizer, then after looking at some other layers switched again to the digitizer, trying to continue editing the same vector map.

This error appeared:

```
Traceback (most recent call last):
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-
linux-gnu/gui/wxpython/mapwin/buffered.py", line 1377, in
MouseActions

self.OnDragging(event)
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-
linux-gnu/gui/wxpython/mapwin/buffered.py", line 1486, in
OnDragging

self.digit.GetDisplay().GetSelected() > 0)):
TypeError
:
'>' not supported between instances of 'list' and 'int'
```

I cannot exactly say how to reproduce but it probably is a Python2 / 3 issue.

**Comment by petrasovaa** [comment]
If you can, please test it, but it should be ok to merge.
