### ISSUE TITLE
[Feat] Ensure compatibility with NumPy 2.0

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass#4058]
**Is your feature request related to a problem? Please describe.**
NumPy 2.0 will be incompatible with applications build against NumPy 1.x. While downwards compatibility should be fine.
It would be nice to ensure compatibility with NumPy 2.0. There is actually a `ruff`action for that (see migration below).

Here is more information on migration to Numpy 2.0:

https://numpy.org/doc/stable/release/2.0.0-notes.html
https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#numpy-2-migration-guide

**Comment by ninsbl** [comment]
The docker image `osgeo/grass-gis:main-ubuntu` already ships NumPy 2.0...

So what needs to be done is probably just checking ruff rule _[NPY201](https://docs.astral.sh/ruff/rules/numpy2-deprecation/)...

I just tested that rule locally with:
`ruff check --preview --select NPY201`

Since it did not return any required change, we may assume Numpy 2.0 is already supported? Can you confirm @echoix that I used and interpreted ruff correctly?

**Comment by echoix** [comment]
Probably, do a PR that removes the ignored line. Probably the line that had this problem has been changed/removed since I made the list.

**Comment by ninsbl** [comment]
_NPY_ is already in the _select_ list in pyproject.toml and _NPY201_ is included with ruff 0.5.2. _NPY001_ and _NPY002_ need to be addressed to be fully NumPy 2.0 compatible, but here only a few files are affected... Will try to add a PR...
