### ISSUE TITLE
[Bug] grass-devel docs point to grass84, grass85 isn't available

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#4099]
## Describe the bug

GRASS docs from the main (active development branch) doesn't seem to be available online. The latest version published is grass84. grass-devel redirects to grass84, grass-stable redirects to grass83.

## To reproduce

- https://grass.osgeo.org/grass-stable/manuals/g.download.location.html => https://grass.osgeo.org/grass83/manuals/g.download.location.html
- https://grass.osgeo.org/grass-devel/manuals/g.download.location.html => https://grass.osgeo.org/grass84/manuals/g.download.location.html
- https://grass.osgeo.org/grass85/manuals/g.download.location.html => doesn't exist

## Expected behavior

grass-devel points to the current development branch, with the latest changes in the manual pages being available to see. In my interpretation, grass-devel doesn't mean the next unreleased version (if ever a branched off version lags before being released), but really the main branch.

## Screenshots

![image](https://github.com/user-attachments/assets/c0345a1e-252f-473c-8edb-cf368dc6245a)

## Additional context

Small additional remark: Unsurprisingly, the "Edit this page on GitHub" link on the bottom of the 404 leads to another 404, "https://github.com/OSGeo/grass-website/tree/master/content//.md". That's only my QA curiosity that thought there might be an issue there too, and there was. It could be a "won't fix" and I wouldn't really mind.
![image](https://github.com/user-attachments/assets/ed235bbf-cf41-4bad-bc29-e3b2732c2935)

**Comment by neteler** [comment]
> The latest version published is grass84

Not yet. We are still at RC1 only (see [grass-dev](https://lists.osgeo.org/pipermail/grass-dev/2024-July/096313.html))

Once 8.4.0 final is out we can shift all around. So this issue may remain open till then.

Re G85:  indeed, this seems to require a fix.

**Comment by neteler** [comment]
> https://grass.osgeo.org/grass85/manuals/g.download.location.html => doesn't exist

And this will then be done by incrementing the versions defined in 

https://github.com/OSGeo/grass-addons/tree/grass8/utils/cronjobs_osgeo_lxd/
- cron_grass_new_current_build_binaries.sh
- cron_grass_new_current_src_snapshot.sh
- cron_grass_old_current_build_binaries.sh
- cron_grass_old_current_src_snapshot.sh
- cron_grass_preview_build_binaries.sh
- cron_grass_preview_src_snapshot.sh

**Comment by neteler** [comment]
@echoix please check the URLs again, now it should be solved by https://github.com/OSGeo/grass-addons/pull/1147 and https://github.com/OSGeo/grass-addons/pull/1148
