### ISSUE TITLE
[Bug] GUI: all tools are inaccessible from the GUI - main menu, tool tree or console not working

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass#4124]
## Describe the bug
Trying to open any tool dialog with double click from the Tool tree pane yields the following error in the console:

```
Traceback (most recent call last):
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/treeview.py", line 67, in
<lambda>

lambda evt: self._emitSignal(evt.GetItem(),
self.selectionChanged),


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/treeview.py", line 197, in
_emitSignal

signal.emit(node=node, **kwargs)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/signal.py", line 232,
in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/dispatcher.py", line
344, in send

response = robustapply.robustApply(


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/robustapply.py", line
61, in robustApply

return receiver(*arguments, **named)


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/menu.py", line 345, in
OnItemSelected

self.showNotification.emit(message=label)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/signal.py", line 232,
in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/etc/python/grass/pydispatch/dispatcher.py", line
344, in send

response = robustapply.robustApply(


^
^
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/main_window/frame.py", line 324, in
SetStatusText

self.statusbar.SetStatusText(*args)
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-
linux-gnu/gui/wxpython/lmgr/statusbar.py", line 67, in
SetStatusText

self.GetWidget().SetStatusText(*args)
TypeError
:
StatusBar.SetStatusText(): not enough arguments
```

## To reproduce

1. Go to Tools pane in the GUI
2. Double click on any tool, eg. Vector > Topology Maintenance > v.build
3. See error in the Console pane

## System description

```                                                                    
GRASS version: 8.5.0dev                                                         
Code revision: e56c7cddd7                                                       
Build date: 2024-07-30                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.7.1                                                                     
PROJ: 9.2.1                                                                     
GEOS: 3.12.0                                                                    
SQLite: 3.42.0                                                                  
Python: 3.11.6                                                                  
wxPython: 4.2.1                                                                 
Platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.38                          
```

**Comment by nilason** [comment]
This looks familiar, I thought it was my setup.

**Comment by echoix** [comment]
That's kinda weird... my two hypotheses for what could have changed something are after the commit you mentionned (e56c7cddd7), or the commit that reverted to the previous behavior (the e56c7cddd7 commit)

Just to make sure there isn't a mismatch, does `git rev-parse HEAD` give you the same as what the grass libs were compiled with?

Otherwise, we might need to do a git bisect to understand what is happening.

**Comment by dhdeangelis** [comment]
I can also confirm this.

```
File
"/usr/local/grass85/gui/wxpython/main_window/frame.py", line
324, in SetStatusText

self.statusbar.SetStatusText(*args)
  File "/usr/local/grass85/gui/wxpython/lmgr/statusbar.py",
line 67, in SetStatusText

self.GetWidget().SetStatusText(*args)
TypeError
:
StatusBar.SetStatusText(): not enough arguments
```

```
System Info                                                                     
GRASS version: 8.5.0dev                                                         
Code revision: exported                                                         
Build date: 2024-07-31                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.9.1                                                                     
PROJ: 9.4.1                                                                     
GEOS: 3.12.2                                                                    
SQLite: 3.46.0                                                                  
Python: 3.11.9                                                                  
wxPython: 4.2.1                                                                 
```

**Comment by neteler** [comment]
Also confirmed on Fedora 39 with Python 3.12.4, using the current `main` version, locally compiled from scratch.

**Comment by dhdeangelis** [comment]
> @dhdeangelis From where did you get the code? (To know what revision it is from). I can only know that it is "exported", our fallback when the git commit info wasn't available when building

@echoix I got and compiled the latest main on 31 July, I believe it was after the previous GUI bug was solved ( #4091 ). I guess the commit might be https://github.com/OSGeo/grass/commit/e56c7cddd7a23b612cd491592c4ac355ca1bac61

**Comment by echoix** [comment]
> Also confirmed on Fedora 39 with Python 3.12.4, using the current `main` version, locally compiled from scratch.

@neteler so that means it includes c88fc0f73cb1d3f9266b5469831a1d6822b3130e?

**Comment by neteler** [comment]
I used whatever was in `main` 15 min ago

**Comment by echoix** [comment]
Can someone check before e56c7cddd7a23b612cd491592c4ac355ca1bac61?

The commit fdf087c9fecf7c5ba30a268457587281acf3954b is before 1f6fa6c62e7d53f6daa980098735f73f9e3e16b8 that touched GUI files.


Otherwise, this is a commit way back a lot of changes that has chances to be a "good" commit for git bisect 9e87f51dd7efaae0d4f45ab6238ca7f1ecfe41bf, can someone confirm it works?


Is there a reproduction without opening GUI?

**Comment by echoix** [comment]
> I used whatever was in `main` 15 min ago

So 9cebe70d7893d987c8a5aa3f05099d0688800422

**Comment by dhdeangelis** [comment]
> Can someone check before [e56c7cd](https://github.com/OSGeo/grass/commit/e56c7cddd7a23b612cd491592c4ac355ca1bac61)?

If I understand correctly, just before this commit the GUI was broken.


> Is there a reproduction without opening GUI?

It fails too:```


> r.stats
Traceback (most recent call last):
  File "/usr/local/grass85/gui/wxpython/gui_core/forms.py", line 3254, in OnInit
    self.mf = TaskFrame(
              ^^^^^^^^^^
  File "/usr/local/grass85/gui/wxpython/gui_core/forms.py", line 567, in __init__
    self.goutput.showNotification.connect(self.SetStatusText)
  File "/usr/local/grass85/etc/python/grass/pydispatch/signal.py", line 153, in connect
    dispatcher.connect(receiver=handler, signal=self, weak=weak)
  File "/usr/local/grass85/etc/python/grass/pydispatch/dispatcher.py", line 143, in connect
    receiver = saferef.safeRef(receiver, onDelete=_removeReceiver)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/grass85/etc/python/grass/pydispatch/saferef.py", line 26, in safeRef
    assert hasattr(target, im_func), (
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: safeRef target <built-in method SetStatusText of TaskFrame object at 0x7f23a615cb80> has __self__, but no __func__, don't know how to create reference
OnInit returned false, exiting...
```

**Comment by dhdeangelis** [comment]
Question: when one downloads the latest main from the repository, is there a simple way of seeing which was the latest commit integrated in that precise code package?

**Comment by echoix** [comment]
Do you download code or use git?

```shell
git clone https://github.com/OSGeo/grass.git
cd grass
git rev-parse HEAD
make libsclean distclean clean
./configure
make -j $(nproc)
sudo make install
```

If current version is bad,
```shell
git bisect start
git bisect bad
```

use `git checkout <the commit sha>`, like  `git checkout 9e87f51dd7efaae0d4f45ab6238ca7f1ecfe41bf` and test if it is good. If so, use on the checked-out state
```
git bisect good
```
to mark it good or not.

Git bisect will then find a next commit to test, you clean and test again, and enter either `git bisect good` or `git bisect bad` until it spits out the offending commit.

At the end, use `git bisect reset` to end.

**Comment by nilason** [comment]
https://github.com/OSGeo/grass/commit/0cc7cbf610e889075b8f465eecb0f319737b7456 is the culprit.

**Comment by echoix** [comment]
Should we start by reverting that commit (+ adding an exclusion back in ruff with this issue), and try to understand it later?
