### ISSUE TITLE
r.in.pdal fails with LAS files without projection

### ISSUE THREAD

**Issue by CarlosGrohmann** [OSGeo/grass#4157]
## Describe the bug
I'm using GRASS 8.4 from ubuntugis-unstable. When trying to import a lidar dataset I got this error:
```
terminate called after throwing an instance of
'pdal::pdal_error'
  what():  readers.las: Global encoding WKT flag not set for
point format 6 - 10.
```
Searching for the error, I found mentions that this can be avoided by using `readers.las.nosrs=true` but there is no way to add it this option to r.in.pdal.

One field to add extra options to the pdal pipeline could fix this. 

## System description
- Operating System: Linux, Pop!OS (jammy)
- GRASS GIS version: 8.4.0RC1 (from ubuntugis-unstable)

  g.version -rge
  version=8.4.0RC1
  date=2024
  revision=3a099f17bd
  build_date=2024-06-19
  build_platform=x86_64-pc-linux-gnu
  build_off_t_size=8
  libgis_revision=3a099f17bd
  libgis_date=2024-06-11T14:29:08+00:00
  proj=9.3.1
  gdal=3.8.4
  geos=
  sqlite=3.37.2

## external links
https://github.com/PDAL/PDAL/issues/3803
https://gis.stackexchange.com/questions/413191/python-pdal-error-reading-format-1-4-las-file-readers-las-error-global-enco

**Comment by marisn** [comment]
Could you, please, provide a small file with test data?

**Comment by CarlosGrohmann** [comment]
Sure, here it is: https://www.dropbox.com/scl/fi/pa6baxi237tqq0o9nu6ou/example.las.zip?rlkey=macixpzd9czt4dgriperrj45b&dl=0
