### ISSUE TITLE
[Bug] error feast with gcc-9.3 and python-3.8.2

### ISSUE THREAD

**Issue by dirteat** [OSGeo/grass#435]
hi there,
cannot compile grass version 7.8.2, 3 errors show up. Any help welcome.

1)grass-7.8.2/lib/python/ctypes
A lot of ---->
Error: /usr/include/sys/stat.h:235: Syntax error at '__buf'
Error: /usr/include/sys/stat.h:259: Syntax error at '__file'
Error: /usr/include/sys/stat.h:260: Syntax error at '__buf'
Status: Processing description list.
Warning: Member "def" of Struct "Option" has been renamed to "_def" because it has the same name as a Python keyword.
Status: Writing to OBJ.x86_64-mageia-linux-gnu/raster.py.
Status: Wrapping complete.
free(): invalid pointer
make[1]: *** [Makefile:102: OBJ.x86_64-mageia-linux-gnu/raster.py] Aborted (core dumped)
make[1]: *** Deleting file 'OBJ.x86_64-mageia-linux-gnu/raster.py'
make[1]: Leaving directory '/root/repos/grass/BUILD/grass-7.8.2/lib/python/ctypes'
make: *** [Makefile:81: default] Error 2

2)grass-7.8.2/display/d.linegraph

Traceback (most recent call last):
  File "/root/repos/grass/BUILD/grass-7.8.2/dist.x86_64-mageia-linux-gnu/tools/g.html2man.py", line 45, in main
    p.feed(line)
  File "/usr/lib64/python3.8/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib64/python3.8/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/lib64/python3.8/html/parser.py", line 412, in parse_endtag
    self.handle_endtag(tagname)
  File "/root/repos/grass/BUILD/grass-7.8.2/dist.x86_64-mageia-linux-gnu/tools/ghtml.py", line 231, in handle_endtag
    if self.pop() == tag:
  File "/root/repos/grass/BUILD/grass-7.8.2/dist.x86_64-mageia-linux-gnu/tools/ghtml.py", line 185, in pop
    self.excluded = self.excluded_stack.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/repos/grass/BUILD/grass-7.8.2/dist.x86_64-mageia-linux-gnu/tools/g.html2man.py", line 78, in <module>
    main()
  File "/root/repos/grass/BUILD/grass-7.8.2/dist.x86_64-mageia-linux-gnu/tools/g.html2man.py", line 49, in main
    (infile, err.lineno, err.offset, err.msg))
AttributeError: 'IndexError' object has no attribute 'lineno'
make: *** [../../include/Make/Html.make:11: /root/repos/grass/BUILD/grass-7.8.2/dist.x86_64-mageia-linux-gnu/docs/man/man1/d.linegraph.1] Error 1

3) Same error in grass-7.8.2/man

**Comment by neteler** [comment]
The validation of d.linegraph.html is successful, see:

http://validator.w3.org/check?uri=https%3A%2F%2Fgrass.osgeo.org%2Fgrass78%2Fmanuals%2Fd.linegraph.html&charset=%28detect+automatically%29&doctype=Inline&group=0

Probably Python-3.8.2 still has ctypes bug(s) as the version before?

**Comment by NikosAlexandris** [comment]
Same here:
```
Errors in:
/osgeo/grass/lib/python/ctypes
/osgeo/grass/display/d.linegraph
/osgeo/grass/man
```
with Python 3.8.2 and gcc 9.2.0

**Comment by neteler** [comment]
> Same here:
> 
> ```
> Errors in:
> /osgeo/grass/lib/python/ctypes
> /osgeo/grass/display/d.linegraph
> /osgeo/grass/man
> ```
> 
> with Python 3.8.2 and gcc 9.2.0

See https://github.com/OSGeo/grass/issues/392#issuecomment-626390418

**Comment by marisn** [comment]
Ahh. Upgrading to Ubuntu 20.04 and got this issue in its all beauty :(
Only strange thing – it also fails with Python 3.9 from deadsnakes ppa 
python3 --version
Python 3.9.0rc1
gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

6f86e05693db776e4edde4dd4c1bcb3505c7c736
```
vector/v.out.ogr$ make
VERSION_NUMBER=7.9.dev grass-master/dist.x86_64-pc-linux-gnu/tools/g.html2man.py "grass-master/dist.x86_64-pc-linux-gnu/docs/html/v.out.ogr.html" "dist.x86_64-pc-linux-gnu/docs/man/man1/v.out.ogr.1"
Traceback (most recent call last):
  File "grass-master/dist.x86_64-pc-linux-gnu/tools/g.html2man.py", line 45, in main
    p.feed(line)
  File "/usr/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.9/html/parser.py", line 170, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python3.9/html/parser.py", line 344, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "grass-master/dist.x86_64-pc-linux-gnu/tools/ghtml.py", line 208, in handle_starttag
    while not self.is_allowed(tag):
  File "grass-master/dist.x86_64-pc-linux-gnu/tools/ghtml.py", line 204, in is_allowed
    return tag not in self.excluded and tag in allowed[self.top()]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "grass-master/dist.x86_64-pc-linux-gnu/tools/g.html2man.py", line 78, in <module>
    main()
  File "grass-master/dist.x86_64-pc-linux-gnu/tools/g.html2man.py", line 49, in main
    (infile, err.lineno, err.offset, err.msg))
AttributeError: 'KeyError' object has no attribute 'lineno'
```
```
Error: /usr/include/x86_64-linux-gnu/sys/stat.h:235: Syntax error at '__buf'
Error: /usr/include/x86_64-linux-gnu/sys/stat.h:259: Syntax error at '__file'
Error: /usr/include/x86_64-linux-gnu/sys/stat.h:260: Syntax error at '__buf'
Status: Processing description list.
Status: Writing to OBJ.x86_64-pc-linux-gnu/display.py.
Status: Wrapping complete.
double free or corruption (out)
Aborted (core dumped)
make[1]: *** [Makefile:107: OBJ.x86_64-pc-linux-gnu/display.py] Error 134
make[1]: Leaving directory 'grass-master/lib/python/ctypes'
```

**Comment by marisn** [comment]
Successfully compiled on Gentoo system with Python 3.9.0b5 and gcc (Gentoo 10.2.0 p1) 10.2.0. Thus whatever goes wrong, it is down to gcc 9.3 and python 3.8 on Ubuntu.

**Comment by marisn** [comment]
I managed to track down cause of problems on my system – some parts were using proj6 while others proj7. Reinstalling proj and all its dependencies fixed the issue. As I had identical backtraces to original report, closing this bug as not a GRASS bug.

Output of this command should list only a single libproj.so version. If it reports more than one, expect things breaking in unexpected ways.
`ldd PATH_TO_GRASS_INSTALL/lib/libgrass_gproj.so | grep proj`
If only one version of libproj.so is present in your system and you still see this error, reopen the issue with extra info.

**Comment by pesekon2** [comment]
I have also bumped into that. Maris's solution worked for me too (mess in `libproj` versions). Added that into [common compilation during problems](https://grasswiki.osgeo.org/wiki/Compile_and_Install#Common_problems_and_solutions).

**Comment by veroandreo** [comment]
> I have also bumped into that. Maris's solution worked for me too (mess in `libproj` versions). Added that into [common compilation during problems](https://grasswiki.osgeo.org/wiki/Compile_and_Install#Common_problems_and_solutions).

Common compilation during problems ? 🤪🤭😇

**Comment by pesekon2** [comment]
> > I have also bumped into that. Maris's solution worked for me too (mess in `libproj` versions). Added that into [common compilation during problems](https://grasswiki.osgeo.org/wiki/Compile_and_Install#Common_problems_and_solutions).
> 
> Common compilation during problems ? zany_facehand_over_mouthinnocent

Oh yes, I hate it when I expect problems but everything compiles instead. :smiley:   
Thanks, fixed that into "common compilation problems".
