### ISSUE TITLE
[Feat] GRASS GIS 8.4 not compiled with PDAL in Windows

### ISSUE THREAD

**Issue by mazingaro** [OSGeo/grass#4424]
As @dnewcomb mentioned in [this](https://github.com/OSGeo/grass/issues/3099) thread, GRASS GIS 8.3 was not compiled with PDAL in Windows:

> .in.pdal is not compiled for the Windows standalone installer for 8.3.0. The option is greyed out. r.in.pdal is great, on Linux ( on my home computer :-))

The same is with GRASS GIS 8.4 installed via OSGEO4W. It was installed with PDAL (Advanced Install) and PDAL can be run in the GRASS console.
r.in.pdal is still greyed out

**Comment by mazingaro** [comment]
@hellik Thank you for the clarification. 

If I understand correctly, Windows users will have to rely on r.in.lidar moving forward. Since r.in.lidar only supports libLAS up to ASPRS LAS version 1.2 (quite obsolete) and doesn't support importing and managing attributes like number of returns, scan angle, or RGBNir data, this could compromise GRASS GIS's strong reputation in lidar processing. Many researchers are attracted to GRASS GIS for its advanced lidar capabilities, and these limitations on Windows might deter them. But yes, this is another topic.

Cheers

**Comment by wenzeslaus** [comment]
One of the goals of the CMake-based build (which is in works) is to compile GRASS GIS in a way which works with PDAL. There is also [r.in.pdal](https://grass.osgeo.org/grass84/manuals/addons/r.in.pdal.html) as a temporary solution applicable in some cases.

**Comment by mazingaro** [comment]
@wenzeslaus, glad to hear it!
Yes, I tried this addon with the same version of GRASS in Windows and as It has issues with the GUI (I was testing it for students) , It works only for Z and I saw [here ](https://github.com/OSGeo/grass-addons/commit/78b14afbd9054672268b5878a3f0ba0678844938) it will be deprecated, I didn't go for opening issues.

**Comment by wenzeslaus** [comment]
> I saw [here](https://github.com/OSGeo/grass-addons/commit/78b14afbd9054672268b5878a3f0ba0678844938) that it will be deprecated, so I didn't open any issues.

Yes, the CMake updates will eventually make it not useful even for Windows. You could still fix it if you need to use it, but if you can work around it, it may not be worth it. I was curious what's wrong with the GUI since I clearly worked on it and tested that: The fix for the GUI would be trivial (just change the [standard option type](https://grass.osgeo.org/grass84/manuals/parser_standard_options.html) from R_INPUT to some file) and the command line and Python API work. Hard to say what other surprises are there.

**Comment by nilason** [comment]
There is a [mingw-w64-pdal](https://packages.msys2.org/base/mingw-w64-pdal) package which would work I guess, but it could probably end up conflicting with the `OSGeo4W` provided PDAL (which is currently not compatible with GRASS).

**Comment by marisn** [comment]
This bug should be filled against OSGEO4W as they are packaging PDAL incompatible with GRASS.
