### ISSUE TITLE
[Bug] ZSTD might require pthreads — configure failure

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass#448]
ZSTD library can be compiled with or without pthreads support. If it is compiled with pthreads, it needs them to be specified for proper linking. Unfortunately I do not have autotools-fu to create a PR.

1. Compile ZSTD with pthreads support
2. Attempt to configure GRASS
3. Observe error: “Unable to locate zstd library“

**Expected behavior**
GRASS configure phase picks up ZSTD library requirement of -lpthread

**System description (please complete the following information):**

- Operating System: Gentoo Linux ~AMD64
- GRASS GIS version: current master 79c069dae1273981ce8a7a82570c7d1582dff8e2

**Additional context**
```
configure:5535: checking whether to use zstd
configure:5551: checking for location of zstd includes
configure:5576: checking for zstd.h
configure:5584: gcc -E   conftest.c >/dev/null 2>conftest.out
configure:5618: checking for location of zstd library
configure:5643: checking for ZSTD_compress in -lzstd
configure:5660: gcc -o conftest -g -O2     -Wl,--export-dynamic conftest.c -lzstd   1>&5
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib64/libzstd.so: undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib64/libzstd.so: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
configure: failed program was:
#line 5649 "configure"
#include "confdefs.h"
/* Override any gcc2 internal prototype to avoid an error.  */
/* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
char ZSTD_compress();

int main() {
ZSTD_compress()
; return 0; }
```

**Comment by metzm** [comment]
We could use `pkg-config --libs libzstd` in configure to get additional libs needed to use zstd. What does `pkg-config --libs libzstd` report in your case?

**Comment by marisn** [comment]
Turns out this is just a bad timing. There is a bug in zstd: https://github.com/facebook/zstd/issues/2045
We can safely assume it will be solved soon and (hopefully) all distros will pick up the fixed version.
The issue has been solved in Gentoo already (and thus I'm fine already): https://bugs.gentoo.org/713940
