### ISSUE TITLE
[Bug] The init needs to fall back to C locale in Nix environment

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#4503]
## Describe the bug

Running `./app/bin/grass` in Nix shell build from our dev environment reports issues with locale.

## To reproduce

Follow the Nix setup and then:

```
./app/bin/grass --tmp-project XY --exec g.region -p
```

The same command (including `./app/bin/grass`) runs for me without any warnings outside of Nix shell.

## Expected behavior

Run without locale warnings or document better what to do.

## Screenshots

```
> ./app/bin/grass --tmp-project XY --exec g.region -p
System locale is not usable (LC_ALL variable not defined). Most likely it indicates misconfigured environment.
Reported error message: unsupported locale setting
Default locale settings are missing. GRASS running with C locale.
Default locale settings are missing. GRASS running with C locale.
```

There are the two same messages because the same message is used at two different places.

## System description

- main (GRASS GIS 8.5.0dev 573d54ae4a)
- Our Nix environment
- Pop!_OS 22.04 LTS (Ubuntu 22.04 jammy)

**Comment by marisn** [comment]
Could this be related to:
https://github.com/NixOS/nix/issues/4829

@imincik thoughts?

**Comment by imincik** [comment]
Can you try this patch

```diff
git --no-pager diff
diff --git a/flake.nix b/flake.nix
index 51174e1da7..a105607417 100644
--- a/flake.nix
+++ b/flake.nix
@@ -34,6 +34,8 @@
                 pytest
               ];

+            LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
+
             shellHook = ''
               function dev-help {
                 echo -e "\nWelcome to a GRASS development environment !"
```

**Comment by wenzeslaus** [comment]
That works for me. I no longer get the warning. Can you please do a PR and describe the change?
