### ISSUE TITLE
[Bug] cannot import name 'UNCHECKED' from 'ctypes' 

### ISSUE THREAD

**Issue by dhdeangelis** [OSGeo/grass#4580]
## Describe the bug
Upon start the following message is shown on the GUI console:
```
3D view mode not available                                                      
Reason: cannot import name 'UNCHECKED' from 'ctypes' (/usr/lib64/python3.11/ctypes/__init__.py)

```
## To reproduce
1. Start GRASS
2. Check the console

## Expected behavior
Error should not occur

## System description
```
> inxi -S
System:
  Host: localhost.localdomain Kernel: 6.11.3-2-default arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: openSUSE Tumbleweed 20241022

```
```
System Info                                                                     
GRASS version: 8.5.0dev                                                         
Code revision: 3d7b331ba8                                                       
Build date: 2024-10-24                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.9.2                                                                     
PROJ: 9.5.0                                                                     
GEOS: 3.13.0                                                                    
SQLite: 3.46.0                                                                  
Python: 3.11.10                                                                 
wxPython: 4.2.2                                                                 
Platform: Linux-6.11.3-2-default-x86_64-with-glibc2.40                          
```

**Comment by dhdeangelis** [comment]
Closing, as I see it is the same as https://github.com/OSGeo/grass/issues/4552

**Comment by wenzeslaus** [comment]
Are you using Nix? #4552 is really filled "against" the Nix configuration because that should be configured so that GRASS GIS works. You may have an local issue.

**Comment by dhdeangelis** [comment]
No, I am not using NIX. Do not understand exactly whats happens here. This issue is new, I compile the main branch every week at minimum and did not have this a few days ago. I use a rolling OS and it changes all the time so maybe a change there.

**Comment by dhdeangelis** [comment]
I now really wonder if this is an unintended consequence of #4567 

I compiled the main branch a few days ago and this problem was not present. "UNCHECKED" is now explicitly imported here but may be it happens before it is defined?

**Comment by dhdeangelis** [comment]
> Do you want to try on your updated system with the commit before [a4786e1](https://github.com/OSGeo/grass/commit/a4786e1272e741865c2c42371056c718e8388ea3) or a commit from last week when you think it was working?

I will gladly do this but I am not entirely sure how to tell git to revert to that specific commit. Any hint?

**Comment by echoix** [comment]
> I will gladly do this but I am not entirely sure how to tell git to revert to that specific commit. Any hint?

The parent commit is 15134e14f181c9c042a74486132cba52ea8d90e6, so :

```
git checkout 15134e14f181c9c042a74486132cba52ea8d90e6
```

And you will see a message saying you are in a detached head.


You can change the hash for another one, or a branch name or tag name afterwards. As when recompiling, make sure you clean the compiled files before.

**Comment by dhdeangelis** [comment]
I can now confirm that this error message is not present in a build using the main branch up to commit https://github.com/OSGeo/grass/commit/15134e14f181c9c042a74486132cba52ea8d90e6

**Comment by echoix** [comment]
> I can now confirm that this error message is not present in a build using the main branch up to commit https://github.com/OSGeo/grass/commit/15134e14f181c9c042a74486132cba52ea8d90e6

Can you check using something specifically in nviz using that "working" commit? In a4786e1272e741865c2c42371056c718e8388ea3, some star imports were explicitly listed, so I suspect that actually using it would fail, you just don't see it yet. I don't know exactly how to trigger it, but the goal would be to make it use the UNCHECKED from its code.

@arohanajit do you have an idea how to trigger the code path for it?

**Comment by dhdeangelis** [comment]
> Can you check using something specifically in nviz using that "working" commit? In [a4786e1](https://github.com/OSGeo/grass/commit/a4786e1272e741865c2c42371056c718e8388ea3), some star imports were explicitly listed, so I suspect that actually using it would fail at your commit, you just don't see it yet. I don't know exactly how to trigger it, but the goal would be to make it use the UNCHECKED from its code.

I do not clearly see how to check that "UNCHECKED" is being used or not. In any case, NVIZ works. See an example showing West Antarctica and the Antarctic Peninsula:

![test](https://github.com/user-attachments/assets/8189a319-02da-4f4d-b225-35f5e7a1401e)

**Comment by dhdeangelis** [comment]
"UNCHECKED" is defined in:

https://github.com/OSGeo/grass/blob/b6514ca8afc5b82a080f3b694a49a8684ff4defc/python/libgrass_interface_generator/ctypesgen/printer_python/preamble.py#L387-L391

I wonder if this definition is loaded before calling it in wxnviz
