### ISSUE TITLE
[Bug] g.gui.iclass: missing removed matplotlib function

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#461]
**Describe the bug**

The scatter plot functionality of `g.gui.iclass` is disabled for matplotlib 3.1.0+.

**To Reproduce**

Starting `g.gui.iclass` triggers an error alert:

```
Error

Scatter plot functionality is disabled.

Reason: Unable to import packages needed for scatter plot.
The Scatterplot Tool needs the "matplotlib" (python-matplotlib) package to be 
installed. cannot import name 'dist_point_to_segment' from 'matplotlib.mlab' 
(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/mlab.py)
```

**System description (please complete the following information):**

g.version -rge
version=7.9.dev
date=2020
revision=aa0d48c15
build_date=2020-03-26
build_platform=x86_64-apple-darwin18.7.0
build_off_t_size=8
libgis_revision=
libgis_date=
WARNING: GRASS GIS libgis version and date number not available
proj=6.3.1
gdal=3.0.3
geos=3.8.0
sqlite=3.31.1

Official Python release:
Python=3.7.7
wxPython=4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5
matplotlib=3.2.1

**Additional context**
`matplotlib.mlab.dist_point_to_segment()` was removed with [matplotlib 3.1.0](https://matplotlib.org/3.1.0/api/api_changes.html#matplotlib-mlab-removals)
The use of `matplotlib.mlab.dist_point_to_segment()` at https://github.com/OSGeo/grass/blob/9ce853b27582cedcdee591b1df1f2abd1a9f4d29/gui/wxpython/iscatt/plots.py#L850

need to be replaced. Using numpy can be an alternative, see e.g. https://stackoverflow.com/questions/39840030/distance-between-point-and-a-line-from-two-points/39840218.

**Comment by petrasovaa** [comment]
Alternatively, use matplotlib code:
https://matplotlib.org/3.0.0/_modules/matplotlib/mlab.html#dist_point_to_segment
Not sure how the licensing would work.
