### ISSUE TITLE
[Feat] Set NDWI color table for NDWI output of i.vi

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass#4652]
**Is your feature request related to a problem? Please describe.**

While GRASS has a NDWI color table, the module i.vi set a greyscale color table for the Normal Difference Water Index (NDWI). This is inconsistent with other outputs. For example, i.vi sets the Normal Difference Vegetation Index (NDVI) color table for the NDVI output raster.

**Describe the solution you'd like**
i.vi should set the NDWI color table for the NDWI output raster.

**Comment by neteler** [comment]
A few lines next to this will do:

https://github.com/OSGeo/grass/blob/039183d9be2c1baf6e63fc07f6554fe6c2a06276/imagery/i.vi/main.c#L590
