### ISSUE TITLE
[Bug] wxGUI digitizer: background vector map with @mapset kills wxGUI

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#467]
**Describe the bug**

Selecting in the additional tools for digitizing a vector background with `@mapset` ...

![vdigit_kill](https://user-images.githubusercontent.com/1295172/77960089-fa3c1c80-72d7-11ea-9dee-6499b67559c3.png)

...the wxGUI is killed and the vector map destroyed. :(

Message in the terminal:
`Illegal filename <ne_10m_admin_0_countries@PERMANENT>. <@> not allowed.`

This is "funny" because the map selection dialog naturally adds the `@mapset` part.

**System description (please complete the following information):**

```
Linux Fedora 32

GRASS 7.8.3dev (latlong_wgs84):~ > g.version -rge
version=7.8.3dev
date=2020
revision=42388e55e
build_date=2020-03-15
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=
libgis_date=
WARNING: GRASS GIS libgis version and date number not available
proj=5.2.0
gdal=2.3.2
geos=3.7.1
sqlite=3.30.0
```

**Comment by petrasovaa** [comment]
Please test.

**Comment by neteler** [comment]
I have locally backported it to G78 and the GUI no longer crashes (the copy-from-background-vector map doesn't do anything but that's a different issue).

So: thanks for this fix!

**Comment by petrasovaa** [comment]
Well, I was wondering about that, because I was not sure what it is supposed to do, but according to manual, it uses the background map to snap to those features and that seemed to work.
