### ISSUE TITLE
[Bug] histogram tool broken in GRASS 8.5

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#4824]
## Describe the bug
I just compiled GRASS 8.5 today (9 Dec 2024). I tried to use the histogram tool in the GUI (not d.histogram) and it raises an error
```
Traceback (most recent call last):
  File "/Applications/GRASS-8.5.app/Contents/Resources/gui/wxpython/mapdisp/frame.py",
line 1288, in OnHistogramPyPlot

win = HistogramPlotFrame(parent=self, giface=self._giface, 
rasterList=raster)
```

## System description
MacOS 14.6.1
Apple ARM processor

## Additional context
I just compiled with Nicklas Larsson's fix for a layer tree problem (#4306) that involved downgrading wxWidgets a bit. But I'm skeptical that this is the cause.

**Comment by nilason** [comment]
The complete error message is:
```
Traceback (most recent call last):
  File "/dev/grass/dist.aarch64-apple-
darwin23.6.0/gui/wxpython/lmgr/layertree.py", line 1130, in
OnHistogram

win = HistogramPlotFrame(

  File "/dev/grass/dist.aarch64-apple-
darwin23.6.0/gui/wxpython/wxplot/histogram.py", line 44, in
__init__

BasePlotFrame.__init__(self, parent, giface=giface,
size=size, **kwargs)
  File "/dev/grass/dist.aarch64-apple-
darwin23.6.0/gui/wxpython/wxplot/base.py", line 113, in
__init__

self._createColorDict()
  File "/dev/grass/dist.aarch64-apple-
darwin23.6.0/gui/wxpython/wxplot/base.py", line 120, in
_createColorDict

for clr in gs.named_colors.keys():

AttributeError
:
module 'grass.script' has no attribute 'named_colors'
```

**Comment by nilason** [comment]
Please test #4825.

**Comment by cmbarton** [comment]
> The complete error message is:
> 
> ```
> Traceback (most recent call last):
>   File "/dev/grass/dist.aarch64-apple-
> darwin23.6.0/gui/wxpython/lmgr/layertree.py", line 1130, in
> OnHistogram
> 
> win = HistogramPlotFrame(
> 
>   File "/dev/grass/dist.aarch64-apple-
> darwin23.6.0/gui/wxpython/wxplot/histogram.py", line 44, in
> __init__
> 
> BasePlotFrame.__init__(self, parent, giface=giface,
> size=size, **kwargs)
>   File "/dev/grass/dist.aarch64-apple-
> darwin23.6.0/gui/wxpython/wxplot/base.py", line 113, in
> __init__
> 
> self._createColorDict()
>   File "/dev/grass/dist.aarch64-apple-
> darwin23.6.0/gui/wxpython/wxplot/base.py", line 120, in
> _createColorDict
> 
> for clr in gs.named_colors.keys():
> 
> AttributeError
> :
> module 'grass.script' has no attribute 'named_colors'
> ```

Thanks for completing. My console shows up errors with odd, long gaps in the text so that I sometimes miss some things. Other times they are duplicated.

**Comment by nilason** [comment]
> Thanks for completing. My console shows up errors with odd, long gaps in the text so that I sometimes miss some things. Other times they are duplicated.

It was the same for me, should be filed as an issue in itself.
