### ISSUE TITLE
Appropriate input/output range for i.atcorr WorldView2 usage

### ISSUE THREAD

**Issue by byasseepm** [OSGeo/grass#483]
Can anyone speak to the appropriate **range/datatype of WorldView2 rasters when using the i.atcorr** module?

I.atcorr requires the input raster be converted to at-sensor-radiance first, which I have done according to [DigitalGlobe documention][1]. DG suggests all transformations be done in FLOAT32 datatype; however, i.atcorr requires a specified input/output range that is **positive**.

Now, I could convert from DN's (UINT16) to radiance (FLOAT32) and then re-scale to positive values (?), but I am not sure if this would leave me with the WorldView2 range that i.atcorr is seeking... For example, Sentinel 2 L1C are also encoded as UINT16 with 15 significant bits. However, documentation states that the correct i.atcorr Sentinel range is 1-10000; 10000 being a specified QUANTIFICATION_VALUE by Sentinel.

Is there a WorldView 2 equivalent to this quantification value? Even when using the new images converted to radiance? Is there an alternative range specific to WV2? And either way, what would the appropriate output/rescale value be for using i.atcorr with WV2?

Any insight would be greatly appreciated!

*WV2 is encoded in UINT16 with an 11-bit dynamic range

  [1]: https://dg-cms-uploads-production.s3.amazonaws.com/uploads/document/file/209/ABSRADCAL_FLEET_2016v0_Rel20170606.pdf

**Comment by ninsbl** [comment]
You may get more response on the grass-user mailinglist:
https://lists.osgeo.org/mailman/listinfo/grass-user

**Comment by ninsbl** [comment]
Discussion continued on the user mailing list:
https://lists.osgeo.org/pipermail/grass-user/2020-April/081411.html
Feel free to reopen if needed (e.g. if technical issues pop up).
