### ISSUE TITLE
[Bug] Error when registering strds: Unable to read band reference file

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#505]
Registering maps into temporal dataset gives the message:
```
ERROR: Unable to read band reference file for raster map <prec_1@anna>
```
Although the actual registration works in the end, this message should not be labeled as error and it probably should not show up at all. I don't know if there is a way to determine when this information would be meaningful for the user (when the band ref file actually is supposed to be used).

**To Reproduce**

e.g. t.register manual example, the full output:

```
GRASS 7.9.dev (nc_spm_08_grass7):~/dev/grass/grass/lib/python/temporal > t.register -i type=raster input=precip_abs \
>     maps=prec_1,prec_2,prec_3,prec_4,prec_5,prec_6 \
>     start="2001-01-01" increment="1 months"
Gathering map information...
ERROR: Unable to read band reference file for raster map <prec_1@anna>
ERROR: Unable to read band reference file for raster map <prec_2@anna>
ERROR: Unable to read band reference file for raster map <prec_3@anna>
ERROR: Unable to read band reference file for raster map <prec_4@anna>
ERROR: Unable to read band reference file for raster map <prec_5@anna>
ERROR: Unable to read band reference file for raster map <prec_6@anna>
 100%
Registering maps in the temporal database...
Registering maps in the space time dataset...
Updating space time dataset...
 100%
```

**System description:**

- Operating System: all
- GRASS GIS version: master

Perhaps related to #318.

**Comment by veroandreo** [comment]
Fully agree with the blocker label. This breaks the very basis of the temporal modules. 

@landam is it mandatory to set band references? IMHO, it shouldn't be. We do not register imagery bands only.

**Comment by wenzeslaus** [comment]
I'm getting many of these (one for each raster map).

I suggest to revert a83af32aac39f94b9fba7fb0691dd52325a1990c, 61b8d40fd24adad84d29f0c861777d4892f767df, 04da30d46c479416e9cda5ae4591d464abdcc343 and whatever else is needed.

**Comment by wenzeslaus** [comment]
See also #1342.

**Comment by neteler** [comment]
How old is your temporal database? Was it created in a recent G79 installation?

If not: did you already run  `t.upgrade` ([addon](https://grass.osgeo.org/grass7/manuals/addons/t.upgrade.html))?

I suggest to not revert changes since it will break the [openEO](https://openeo.org/) GRASS-driver.

**Comment by wenzeslaus** [comment]
> How old is your temporal database? Was it created in a recent G79 installation?

This is in the `tgis/sqlite.db` file of a newly created mapset (with recent v7.9):

key | value
-- | --
tgis_version | 2
tgis_db_version | 3
creation_time | 2021-02-15 11:51:09.432618

Seems like something which should be in the error message together with the `t.upgrade` suggestion if applicable.

> I suggest to not revert changes since it will break the [openEO](https://openeo.org/) GRASS-driver.

This is an important use case. However, this issue is almost a year old (Apr 13, 2020) with little activity.

**Comment by landam** [comment]
OK, I will take a look at this issue.

**Comment by wenzeslaus** [comment]
> How old is your temporal database? Was it created in a recent G79 installation?

I get the same errors with newly created XY location.

**Comment by veroandreo** [comment]
> How old is your temporal database? Was it created in a recent G79 installation?

This happens when registering maps in newly created STRDS whose easter maps do not have band reference, e.g., ndvi, lst, chlor, etc.

Not all raster maps that we register need to have a band reference, hence t.register should not issue an error when a band reference is not provided.

**Comment by marisn** [comment]
> Not all raster maps that we register need to have a band reference, hence t.register should not issue an error when a band reference is not provided.

Yes, band reference should not be mandatory. Still any map could have a band reference. I'm trying to find time to finish my work on this (see #1272)

**Comment by neteler** [comment]
@marisn does the (draft) PR #1272 already address the `ERROR: Unable to read band reference file for raster map
<mapname@mapset>` issue of `t.register`? I finally ran into the same problem :-)

**Comment by wenzeslaus** [comment]
Since there is also plenty of failing temporal tests because of band references on standard sample data (#1342), we may want to revert this for 8.0.0 release and start over in master branch later on once release 8.0 is branched out. The revert should be still possible even with the Black changes in place, something like reverting the Black changes, reverting the band changes, and reapplying the Black should do the trick.

List of commits to revert: a83af32aac39f94b9fba7fb0691dd52325a1990c, 61b8d40fd24adad84d29f0c861777d4892f767df, 04da30d46c479416e9cda5ae4591d464abdcc343 and newly found 77984e04f8da5335b54ed7c9cb1ee103334cac3c.

When I was reading the commit messages and PR from the above list, it turned out that Grassy the Hungry Cow also works with temporal objects. 

```
 _________________________________________
/ I got some cud, but that grass          \
\ complained about a band reference file. /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
_\|/__\|/__\|/_ ||     ||  _\|/__\|/_
```

**Comment by marisn** [comment]
@neteler no, I haven't been looking specially into t.register part of band support. If it does, then by a side effect.

@wenzeslaus no objections form my side. Bands are a must in G8, but I am struggling to find free time to work on GRASS to finish reshaping them. :(

**Comment by veroandreo** [comment]
> Since there is also plenty of failing temporal tests because of band references on standard sample data (#1342), we may want to revert this for 8.0.0 release and start over in master branch later on once release 8.0 is branched out. The revert should be still possible even with the Black changes in place, something like reverting the Black changes, reverting the band changes, and reapplying the Black should do the trick.
> 
> List of commits to revert: [a83af32](https://github.com/OSGeo/grass/commit/a83af32aac39f94b9fba7fb0691dd52325a1990c), [61b8d40](https://github.com/OSGeo/grass/commit/61b8d40fd24adad84d29f0c861777d4892f767df), [04da30d](https://github.com/OSGeo/grass/commit/04da30d46c479416e9cda5ae4591d464abdcc343) and newly found [77984e0](https://github.com/OSGeo/grass/commit/77984e04f8da5335b54ed7c9cb1ee103334cac3c).

I'm not sure about this... what will happen then with those time series that we updated to version 3 to be able to use them within grass-dev? Isn't there a "simpler" way to remove the error from t.register when maps do not have band reference? Sorry if this is a silly question

**Comment by neteler** [comment]
> What I tried:

(... see [above](https://github.com/OSGeo/grass/issues/505#issuecomment-787457531))

Update:
I re-ran with updated versions and the `t.register` error no longer occurs. The `i.band` step also not needed any more since the updated `i.landsat.import` properly generated the CSV table with band name column.

**Comment by wenzeslaus** [comment]
> I'm not sure about this... what will happen then with those time series that we updated to version 3 to be able to use them within grass-dev?

It is in master branch, so breaking things in this way is expected behavior. I guess one can rewrite `t.upgrade` to reverse operation if really needed.

> Isn't there a "simpler" way to remove the error from t.register when maps do not have band reference?

If it is a trivial and not fixed till now, one more reason to remove that completely. Moreover, it is not just this but also #1342 and basically also #63, #306, #504.

**Comment by wenzeslaus** [comment]
> I re-ran with updated versions and the `t.register` error no longer occurs. The `i.band` step also not needed any more since the updated `i.landsat.import` properly generated the CSV table with band name column.

Note that this is different case, the case in this issue is when you _don't_ use band references.

**Comment by veroandreo** [comment]
> > I'm not sure about this... what will happen then with those time series that we updated to version 3 to be able to use them within grass-dev?
> 
> It is in master branch, so breaking things in this way is expected behavior. I guess one can rewrite `t.upgrade` to reverse operation if really needed.
> 
> > Isn't there a "simpler" way to remove the error from t.register when maps do not have band reference?
> 
> If it is a trivial and not fixed till now, one more reason to remove that completely. Moreover, it is not just this but also #1342 and basically also #63, #306, #504.

Honestly, I'm not keen in removing the feature, though of course we should not release GRASS 8.0.0. with these error messages. I'd really like to know @landam's opinion here

**Comment by metzm** [comment]
Band references are (should not be) required with `t.register`, and it must be possible to provide custom band names such as "mask", "ndvi", "prec", "temperature", etc. Therefore I recommend to simply remove the bogus error message in https://github.com/OSGeo/grass/blob/master/python/grass/temporal/space_time_datasets.py#L363

**Comment by neteler** [comment]
Let's see if the problem persists, till confirmed let's keep this issue open.

**Comment by landam** [comment]
@neteler Can we close?

**Comment by neteler** [comment]
If @petrasovaa agrees, yes

**Comment by petrasovaa** [comment]
Thanks!
