### ISSUE TITLE
[Bug] Startup screen starts and then freezes on CentOS

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#521]
**Describe the bug**

Startup screen is only gray and frozen after GRASS GIS starts on CentOS when using `ssh -X`. The application can be closed (system asks for Force quit), then GRASS command line (grass.py) gives traceback after Ctrl+C (GUI was killed, so that's fine).

**To Reproduce**
Start GRASS with gui, e.g. `grass79 --gui`.

**Expected behavior**
User should see startup screen.

**System description (please complete the following information):**

- Operating System: CentOS Linux release 7.7.1908 (Core)
- master (7.9, cdb718184e)
- Python 3.7
- wxPython 4.0.4

```
>>> import wx
>>> wx.__version__
'4.0.4'
>>> wx.version()
4.0.4 gtk2 (phoenix) wxWidgets 3.0.5
''
```

**Additional context**
Using `git bisect` I determined it is caused by 7ddde01a (Startup screen: Move warning messages to automatically wrapped text widget) from #490 (Use correct (widget) with for word wrapping).

Based on [blame](https://github.com/OSGeo/grass/blame/d121f7f3fed0808d73a46c0ae95443cbf7535b29/gui/wxpython/gis_set.py), the `StaticText` and `Wrap()` calls replaced `StaticWrapText` in 104d3d4992 (use...StaticText instead of StaticTextWrap...since it causes emitting events continually on wxPython 3).

**Comment by wenzeslaus** [comment]
`StaticWrapText` is used on other places and does not cause issues there.

Deleting `~/.grass7/rc` allows the window to show. This shows in message about what's wrong; "GRASS needs a directory..." in this case (that's the `self.lmessage`). Picking a directory which has locations and thus removing the need for the message, causes the window to freeze (gray out) again. It seem that when the message is empty the `StaticWrapText` freezes the GUI.

**Comment by marisn** [comment]
Strange. Works just fine on my system. Still there is a slight difference in wxpython version: `4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.4` My bet would be on gtk3 vs gtk2 part as that's the most prominent difference. Any chatter in console by chance?

**Comment by wenzeslaus** [comment]
There is no startup screen anymore so closing as resolved.
