### ISSUE TITLE
[Bug] Startup messages on Ubuntu 20.04 with GRASS .7.8.2

### ISSUE THREAD

**Issue by dnewcomb** [OSGeo/grass#522]
**Describe the bug**
On starting GRASS GIS from the command line on Ubuntu 20.04 beta, the following messages appear:
Gdk-Message: 22:16:07.216: Window 0x24af2b0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 22:16:07.216: Window 0x24af2b0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 22:16:07.216: Window 0x24af2b0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 22:16:07.216: Window 0x24af2b0 is a temporary window without parent, application will not be able to position it on screen.

Upon selecting a location and mapset and pressing Start Grass session,
dk-Message: 22:23:17.469: Window 0x1fee2b0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 22:23:17.469: Window 0x1fee2b0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 22:23:17.469: Window 0x1fee2b0 is a temporary window without parent, application will not be able to position it on screen.

**To Reproduce**
1. Open Terminal window.
2. Type grass78.
3. press enter key
4. Select ( or create) Location and mapset.
5. Click on Start Grass session button.

**Expected behavior**
GRASS starting without messages

**Screenshots**

**System description (please complete the following information):**

- Operating System: Ubuntu 20.04 (beta)
- GRASS GIS version 7.8.2 ( bundled with Ubuntu 20.04) , also occurs with 7.8 release branch and master (4/14/2020)

**Additional context**
I realize testing on a beta version of an operating system is a bit chancy, but thought this might be worth bringing up.

**Comment by dnewcomb** [comment]
Sorry , forgot this info.
g.version -rge
version=7.8.2
date=2019
revision=exported
build_date=2020-03-24
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=00000
libgis_date="?"
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1

**Comment by dnewcomb** [comment]
[packages_installed.txt](https://github.com/OSGeo/grass/files/4490674/packages_installed.txt)

**Comment by petrasovaa** [comment]
The time.clock() issue has been fixed in #244 and merged to 7.8 couple months ago, so I assume it's happening only in 7.8.2 in packages. So might be good idea to remove it from the ticket.

**Comment by dnewcomb** [comment]
Thank you! I edited the original bug report to reflect the updates changes in 7.8 release and master

**Comment by dnewcomb** [comment]
7.8.3 release fixes this issue.  Closing the ticket.
