### ISSUE TITLE
[Feat] Make better use of GitHub labels when reporting on issues

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#526]
**Is your feature request related to a problem? Please describe.**

It would be advantageous to make better use of labels when reporting an issue.

At present the templates do not create automatic labels for e.g. bug or enhancement, but instead add extra clutter (= [Feat] or [Bug]) to the issue title, which is not even easily filterable.

For an issue reporter that have no writing permission to the repository, there is no possibility to add or alter label. This leaves the task of labelling to an admin or will not be done at all.

**Describe the solution you'd like**

Add automatic labelling to the templates, presently "Bug report" and "Feature request". And consider further templates: e.g. "Bug report"+"GUI" etc.

**Comment by neteler** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> It would be advantageous to make better use of labels when reporting an issue.
> 
> At present the templates do not create automatic labels for e.g. bug or enhancement, but instead add extra clutter (= [Feat] or [Bug]) to the issue title, which is not even easily filterable.

Do you have any pointer how to add these labels automatically? I am happy to modify it.

> For an issue reporter that have no writing permission to the repository, there is no possibility to add or alter label. This leaves the task of labelling to an admin or will not be done at all.

Agreed - this is quite annoying.

> **Describe the solution you'd like**
> 
> Add automatic labelling to the templates, presently "Bug report" and "Feature request". 

Please let me know how to do that and I'll modify it.

> And consider further templates: e.g. "Bug report"+"GUI" etc.

Would that not be too confusing then? Too many choices on the "issues" landing page?

**Comment by nilason** [comment]
#527 resolves the existing templates.

If the community is interesting in adding further templates is a matter of discussion .
I'd would say they should at least be limited in number and very distinct.

**Comment by neteler** [comment]
What is the status here?

**Comment by echoix** [comment]
@nilason Do you think the original complaint of the issue templates not having labels still present?
The two templates in the .github/ISSUE_TEMPLATE folder assign `bug` and `enhancement` to their respective templates.

If this was enough, we should close this 8.4.0 issue
