### ISSUE TITLE
[Bug] v.db.addtable complains about existing cat-column when creating a new table

### ISSUE THREAD

**Issue by jradinger** [OSGeo/grass#567]
**Describe the bug**
Adding a new table (using` v.db.addtable`) to a vector map that is NOT connected to any table raises an error that a **cat** column already exists. As a recommendation, one should use the `--overwrite` flag which works indeed (However, the overwrite flag is not available via the GUI).
 This might just got broken recently, as it was working some weeks ago when tested the last time.

**To Reproduce**
```
# based on the NC dataset
g.copy vector=streams@PERMANENT,stream_test
v.db.droptable -f map=stream_test
v.db.addtable map=stream_test columns="length DOUBLE"
```

**Expected behavior**
Adding a new first table to a vector map should not raise an error that a **cat** column already exist and it should not need an overwrite flag to work?!. I mean if there is no table (before creating it) there is no cat column, or am I wrong? The specified columns (e.g. 'length' in the example) should be created in addition to the cat column.

**System description:**
GRASS version: 7.9.dev                                                          
Code revision: ca9031088                                                        
Build date: 2020-04-27                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 2.4.2                                                                     
PROJ: 6.2.1                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.5                                                                   
wxPython: 4.0.6                                                                 
Platform: Linux-5.3.0-46-generic-x86_64-with-Ubuntu-19.10-eoan

**Comment by jradinger** [comment]
It might be related to the recent changes in `v.to.db` of introducing the overwrite-flag #487??

**Comment by HuidaeCho** [comment]
You're right. Please try  #571.
