### ISSUE TITLE
[Feat] Allow translating an entire layer's X,Y

### ISSUE THREAD

**Issue by jidanni** [OSGeo/grass#581]
None of
- i.rectify
- m.transform
- r.import
- r.in.bin
- r.in.gdal
- r.in.wms
- v.rectify
- wxGUI.GCP_Manager
- etc.

have support for a [simple XY offsets](https://sourceforge.net/p/viking/discussion/general/thread/cfcf7c8c0f/).
E.g., we are importing via WMTS and the whole layer simply needs to be
moved 2.1 meters north and 1.3 meters east. No need to bother with
control points, just allow the user to via a command, and also via the
mouse, to grab the whole (raster) layer and translate it in two dimensions.

**Comment by neteler** [comment]
For this purpose there is `r.region`, did you try that?

**Comment by jidanni** [comment]
I don't know. First, these two
```
EXAMPLES
       Assign absolute coordinates to map:
       r.region map=mymap n=220750 s=220000 w=638300 e=639000
       Shift map (using offset, here by 100 map units in two directions):
       r.region map=mymap n=n+100 e=e+100 w=w+100 s=s+100
```
need to be separated by a blank line.

Then the second one needs more explanation, else it seems like a tug of war, pulling the whole map east 100 units, then back west 100 units, etc.

And also please add an example of how to pull the whole map north one meter and east two meters,
e.g., to align some cadastral or photo layer.
