### ISSUE TITLE
wxGUI error on EPEL7

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#589]
Compiling the new 7.8.3 on EPEL7 shows this error:

```
Compiling /builddir/build/BUILDROOT/grass-7.8.3-1.el7.x86_64/usr/lib64/grass78/gui/wxpython/vnet/dialogs.py ...
  File "/usr/lib64/grass78/gui/wxpython/vnet/dialogs.py", line 1382
    setts = {**self.colorsSetts, **self.sizeSetts}
              ^
SyntaxError: invalid syntax
```

(see at bottom of https://download.copr.fedorainfracloud.org/results/neteler/grass78/epel-7-x86_64/01367560-grass/build.log.gz)

Code:

https://github.com/OSGeo/grass/blob/eecbe060c4dea7e50debdb14d20212815afeb2e2/gui/wxpython/vnet/dialogs.py#L1382

git blame suggests this change 5e17ebc13e8d943ab2592540145da91adc31cca0:

Python version used here: `python3 x86_64  3.6.8-13.el7`

**Comment by petrasovaa** [comment]
This syntax should work since Python 3.5:
https://docs.python.org/3.5/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations

So I wonder if it's using the right Python?

**Comment by neteler** [comment]
> So I wonder if it's using the right Python?

I think so:

```
...
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/vnet_data.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/vnet_utils.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/__init__.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/dialogs.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/toolbars.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/vnet_core.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/vnet/widgets.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/web_services/cap_interface.py
python3 -t -m py_compile /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/web_services/__init__.py
...
```

**Comment by petrasovaa** [comment]
What about this line just above the syntax error:

    + /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1

That may refer to Python 2, no?

**Comment by petrasovaa** [comment]
Also, I can see 
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
```
So it's Python 3.7 or 3.6 as you mentioned before? It shouldn't matter, but still.

**Comment by neteler** [comment]
> What about this line just above the syntax error:
> 
> ```
> + /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
> ```
> 
> That may refer to Python 2, no?

Looks like that!
I am trying to add more EPEL related python3 macros and recompile. Will report...

**Comment by neteler** [comment]
Hurray, solved by adding these macros to the GRASS GIS SPEC file:

```
...
 %if 0%{?rhel} >= 7
 %define __python %{__python3}
%global python3_version_nodots 36
%global main_python3 1
 %endif

# Note that the bcond macros are named for the CLI option they create.
# "%%bcond_without" means "ENABLE by default and create a --without option"
%bcond_without python3
```

Fedora + EPEL 7 RPMS of G 7.8.3 now available at (I'll also update the official package):
https://copr.fedorainfracloud.org/coprs/neteler/grass78/build/1369114/

Thanks for spotting the problem, @petrasovaa !
