### ISSUE TITLE
[Feat] Adding coverity scan support to GH Actions?

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#605]
We have a (sleepy) coverity scan (static code analysis, esp. of C oce) project here:
https://scan.coverity.com/projects/1038

It appears that GH Actions support that, would it be feasible to add a connection also for that?

**Comment by wenzeslaus** [comment]
Added by #3514 and subsequent PRs. Thanks to everyone involved, especially @jadenabrams100 and @nilason!
