### ISSUE TITLE
[Bug] GRASS 7.8.2 on Pop! OS 20.04 results in almost 100% CPU usage due to /usr/lib/grass78/gui/wxpython/wxgui.py

### ISSUE THREAD

**Issue by benhur07b** [OSGeo/grass#612]
**Describe the bug**
Running GRASS 7.8.2 on Pop! OS 20.04 results in almost 100% CPU usage due to /usr/lib/grass78/gui/wxpython/wxgui.py.

Similarly (although I'm not sure if they're related), the following message is displayed in the command line: (wxgui.py:53191): __Gtk-CRITICAL **: 21:28:38.188: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton__.

The Map Display canvas doesn't resize (Thinking if I should add this as a separate bug report).

The bug feels somehow similar to: 
https://bugzilla.redhat.com/show_bug.cgi?id=1440434
https://bugzilla.redhat.com/show_bug.cgi?id=1364580.

Any help would be appreciated. Thanks!

**To Reproduce**
1. Run GRASS (*or* run grass in terminal)
2. Start GRASS Session
3. Check status using htop
4. See "python3 /usr/lib/grass78/gui/wxpython/wxgui.py" having CPU% at almost 100% consistently
5. A message is shown in the GRASS terminal & the Map Display canvas doesn't resize when the window size is changed.

**Expected behavior**
For the CPU load not to be ~100% all the time and for the Map Display canvas to resize.

**Screenshots**
CPU% at ~100%:
![Screenshot from 2020-05-11 21-36-52](https://user-images.githubusercontent.com/22940966/81567921-970dd180-93cf-11ea-88c5-64ea8b76b3bf.png)

Gtk-CRITICAL:
![Screenshot from 2020-05-11 21-19-12](https://user-images.githubusercontent.com/22940966/81568039-ccb2ba80-93cf-11ea-86f0-8bde1e222e41.png)

Map Display canvas not resizing to fill whole window:
![Screenshot from 2020-05-11 21-39-37](https://user-images.githubusercontent.com/22940966/81568387-45197b80-93d0-11ea-8dad-b11b36bf2ed6.png)

**System description (please complete the following information):**

- Operating System: Pop! OS 20.04 (Ubuntu 20.04)
- GRASS GIS version: 7.8.2 (from OS repository, haven't tried 7.8.3 from ubuntugis-unstable PPA yet)
- details about further software components
g.version -rge
version=7.8.2
date=2019
revision=exported
build_date=2020-03-24
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=00000
libgis_date="?"
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1

**Additional context**
This occurs whether window-tiling (available in Pop!) is enabled or disabled.

**Comment by petrasovaa** [comment]
What is the version of wx? Also try turning on debug mode:

    g.gisenv set=wx_DEBUG=1

see if there are any tracebacks during resizing.

**Comment by benhur07b** [comment]
@petrasovaa Thank you for the advice about debug mode. Looks like it's related to the deprecated time.clock() module in Python 3.8.

Traceback (most recent call last):
  File "/usr/lib/grass78/gui/wxpython/mapwin/buffered.py", line 651, in OnIdle
    if self.resize and self.resize + 0.2 < time.clock():
AttributeError: module 'time' has no attribute 'clock' 

I changed time.clock() to time.process_time() [time.perf_counter() also works] and the CPU load isn't 100% anymore + the Map Display canvas now resizes. 

The **(wxgui.py:6289): Gtk-CRITICAL **: 03:15:24.908: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar** warning still appears though.
 
By the way, the wxpython version is on my machine is 4.0.7.

All the best,
Ben Hur

**Comment by neteler** [comment]
> @petrasovaa Thank you for the advice about debug mode. Looks like it's related to the deprecated time.clock() module in Python 3.8.

This has been fixed in https://github.com/OSGeo/grass/releases/tag/7.8.3
Please upgrade...

**Comment by benhur07b** [comment]
@neteler Just upgraded to 7.8.3 and the issue is indeed gone. Good thing the ubuntugis-unstable released the version for focal earlier. Thanks!

**Comment by petrasovaa** [comment]
I suggest to close this and feel free to open the gtk one. But it's difficult to address these, see the comment in wxWidgets/Phoenix#1529
