### ISSUE TITLE
[Bug] g.extension: download from gitlab repositories does not work

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass#623]
**Describe the bug**
Extensions in gitlab repositories are not found by and thus cannot be installed with g.extension.

**To Reproduce**
```grass ./grassdata/nc_spm_08_grass7/user1 --exec g.extension operation=add extension=r.example.plus url=https://gitlab.com/vpetras/r.example.plus```

Results in:
`ERROR: Extension <r.example.plus> not found

**Expected behavior**
Download and install the extension.

**System description (please complete the following information):**

- Ubuntu 18.04
- GRASS GIS 7.9dev (though earlier versions are likely affected too)

**Additional context**
Seems to be caused by urllib and gitlab API as well as bug in URL Construction:
Actual download link is:
`https://gitlab.com/vpetras/r.example.plus/-/archive/master/r.example.plus-master.zip`
It works with wget and Python requests (but not urllib in Python (2?))

Could be fixed by using requests and different default URL suffix (that requires repo name be entered though)...

**Comment by ninsbl** [comment]
Sorry for the blunder in the title.

**Comment by lucadelu** [comment]
@ninsbl is still valid?

**Comment by ninsbl** [comment]
Fixed in #683
