### ISSUE TITLE
[Bug] wxGUI Data import Python error

### ISSUE THREAD

**Issue by 61300** [OSGeo/grass#648]
Hello, 
When I export DEM data to GRASS GIS software, I get the error 'if not self.add.IsChecked () or returncode! = 0: RuntimeError: wrapped C / C ++ object of type CheckBox has been deleted'.

To Reproduce
File>İmport raster data>Simplifed raster import with reprojection> Source İmport > Data import > Error

Screenshots
![Ekran Alıntısı1](https://user-images.githubusercontent.com/65587189/82291666-13954700-99b2-11ea-8377-06f84879733e.PNG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/65587189/82291680-1b54eb80-99b2-11ea-9e7b-cbb632bb6774.PNG)

 Operating System: Windows 10 Pro unlicensed, 320 Gb Hdd; 8 Gb Ram
Grass Gıs version 7.8 

What is the cause?
Anybody suggest a solution? Thank You!

**Comment by neteler** [comment]
Which precise GRASS GIS version do you use? Is it the latest 7.8.3?

**Comment by 61300** [comment]
Yes

**Comment by petrasovaa** [comment]
The error shouldn't really matter for the import, the raster should be imported just fine. You probably closed the import dialog before the import was finished. We should still fix the error, but it's not affecting anything important I think.

**Comment by 61300** [comment]
Thanks Petrasovaa
The problem was solved when closing the import dialog window after loading the data.
                              Thanks for everything.
