### ISSUE TITLE
[Bug] Version parse is broken for some python-wxPython versions

### ISSUE THREAD

**Issue by ggardet** [OSGeo/grass#649]
**Describe the bug**
Version parse is broken for some python-wxPython versions.
Parsing version `4.1.0` is fine, but `4.0.7.post2` is not.

**To Reproduce**
Try to use a `*post*` version of wxPython 

**Expected behavior**
It should parse properly all released versions.

**Screenshots**
N/A

**System description (please complete the following information):**

- Operating System: openSUSE Tumbleweed
- GRASS GIS version 7.8.2

**Additional context**
See: https://github.com/wxWidgets/Phoenix/blob/e8d8294fbbd0003ea718f1b4f9379f2dd0d4ad08/buildtools/version.py#L29

**Comment by petrasovaa** [comment]
This has been fixed already some time ago, please use newer 7.8.3.
