### ISSUE TITLE
[Feat] Create grassdata automatically on the first GUI startup

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#682]
When GRASS GIS first starts, many or even most users, especially beginners want to just create a `grassdata` directory in the default path for their platform. GRASS should just do that automatically.

## Details

After starting GRASS GIS _with GUI_, the GUI now searches for existing grassdata (e.g., dac6d4add511cb47d3329d2c06fdb441b75822f4 and #644 with #664). If nothing is found, GRASS GIS (GUI) should automatically create directory named `grassdata` as a subdirectory of a platfrom-dependent directory. This platfrom-dependent directory would be:

* `$HOME` (`os.path.expanduser('~')`) on Linux and the like,
* User's `Documents` on Windows (see dac6d4add511cb47d3329d2c06fdb441b75822f4 for code trying to identify that dir),
* One of the above on macOS - **macOS users**, please share your ideas.

## Fallback

The directory should be created and tested whether it is writable (well, that's probably the same thing).

If that fails, it should use a temporary directory (`/tmp/...` etc.) as a fallback. This is actually the case for a free account on rollApp which we want to have in the [Try GRASS GIS online section](https://staging.grass.osgeo.org/learn/tryonline/) on the new website.

As for the temporary directory fallback, given the processes of GUI and/or startup and `grass.py`, using `tempfile.gettempdir()/grassdata_{user_name}` (e.g.,  `/tmp/grassdata_smith`) - similarly to what `create_tmp()` in `lib/init/grass.py` does - seems like the best shot. The fact that it would not be deleted (because the GUI process won't delete it and the `grass.py` does not know about it) combined with the fixed name is actually (possibly?) a nice feature (although irrelevant to rollApp): the user has a chance to go back to the data before (before the machine is turned off).

If even that fails, GRASS should not fail, but simply let the user make that choice which is the current behavior.

## Context

The creation of the grassdata directory on Windows in Documents is already happening during installation. This should bring this behavior to all platforms and it should make it independent on the installer.

This is also a necessary step if we decide to provide user with some basic data to start with (the provided location will need to be placed somewhere).

**Comment by nilason** [comment]
> One of the above on macOS - macOS users, please share your ideas.

I'd prefer `os.path.expanduser('~')` ($HOME) for mac. As the grassdata directory is not meant to poke around in manually, `~/Documents/` should be avoided.

**Comment by cmbarton** [comment]
Another option would be in ~/Library/GRASS. This is where extensions now go by default. It is accessible but not a place where people might 'poke around' by accident. The more 'normal' Apple path would be ~/Library/Application Support/GRASS. But that folder does not seem to be recognized by GRASS anymore.

**Comment by nilason** [comment]
> Another option would be in ~/Library/GRASS. This is where extensions now go by default. It is accessible but not a place where people might 'poke around' by accident. The more 'normal' Apple path would be ~/Library/Application Support/GRASS. But that folder does not seem to be recognized by GRASS anymore.

Installing as GRASS.app bundle will put stuff in ~/Library/GRASS (I guess), but as CLI it goes to ~/.grass7. I'm hesitant hiding it too well as it may grow in size (in particual a potential problem on SSD start-up drives).

**Comment by wenzeslaus** [comment]
> The more 'normal' Apple path would be ~/Library/Application Support/GRASS. But that folder does not seem to be recognized by GRASS anymore.

@cmbarton What do you mean by _not recognized anymore_? Recognized as what? When?

**Comment by cmbarton** [comment]
It’s doesn’t seem to be in the path so I can’t launch modules in it from the command line. 

Michael Barton

...Sent from my iPad

**Comment by wenzeslaus** [comment]
> It’s doesn’t seem to be in the path so I can’t launch modules in it from the command line.

If you think that's something which should work, please open an new issue for it.

**Comment by nilason** [comment]
Re: `~/Library/Application Support/GRASS`
I haven't looked into this at any depth, but there is a note in `macosx/app/build_gui_user_menu.sh` regarding problem with spaces in path for addons. I don't know if this is still the case or if there could be a workaround/solution. That would ideally be the place for addons etc., but not for `grassdata`.
