### ISSUE TITLE
i.sentinel on Docker image

### ISSUE THREAD

**Issue by BatuhanKavlak** [OSGeo/grass#696]
I think i.sentinel extension, python packages sentinelsat and pandas should be added to the Dockerfile. I haven't worked for here before and couldn't be sure where to put them. Even i.sentinel extension could be optional, sentinelsat and pandas back-end is required to run the extension.

**Comment by neteler** [comment]
It would not be that difficult but to which of the many docker flavors do you refer to?
See for a version matrix:

https://github.com/OSGeo/grass/blob/master/docker/README.md

**Comment by BatuhanKavlak** [comment]
@neteler I'm using now Ubuntu 18.04 | stable-ubuntu (mundialis/grass-py3-pdal:stable-ubuntu); however, I couldn't see the sentinelsat pandas package on the latest version source code, as well.

At least, python packages could be added.
sth like:
RUN pip3 --no-cache-dir install sentinelsat pandas

My steps in the container were:

pip3 install sentinelsat pandas
grass grassdata/sentinelLocation/firstmap
g.extension extension=i.sentinel

i.sentinel.download is working in this case. I'm trying to solve i.sentinel.import issues.

**Comment by BatuhanKavlak** [comment]
Getting error below when using i.sentinel.import:
```
i.sentinel.import -p input=S2A_MSIL2A_20200424T084601_N0214_R107_T35SND_20200424T113826.SAFE
ERROR: Nothing found to import. Please check input and pattern_file
       options.
```
I'm trying to import data from a volume. It successfully downloads but cannot import whether it's a ```.zip``` file or ```.SAFE``` file.

**Comment by neteler** [comment]
You may want to consider to switch to Ubuntu19 | stable-ubuntu19 ([mundialis/grass-py3-pdal:stable-ubuntu19](https://hub.docker.com/r/mundialis/grass-py3-pdal/builds)), in order to have fresher libs.

FWIW: In actinia, we use a simple way to install addons by looping over a CSV file:

- list of addons and their sources: https://github.com/mundialis/actinia_core/blob/master/docker/grass_addons_list.csv
- loop over list: https://github.com/mundialis/actinia_core/blob/master/docker/actinia-core/Dockerfile#L73

Feel free to open a pull request on the Dockerfile of interest to you.

**Comment by neteler** [comment]
> Getting error below when using i.sentinel.import:
...
> I'm trying to import data from a volume. It successfully downloads but cannot import whether it's a `.zip` file or `.SAFE` file.

Silly question: Do you actually mount the volume into the container?

**Comment by BatuhanKavlak** [comment]
@neteler Thanks for the help. I'll try to build a desktop and if works pull a request.

For the volume issue: yes, I mounted the volume, and succesfully download a ```.zip``` file to there from the docker image as below:
```
GRASS 7.8.4dev (sentinelLocation):/data/GRASSDATA > i.sentinel.download settings=credentials.txt producttype=S2MSI2A start=2020-04-23 end=2020-04-25 cloud=3 limit=1 output=s2_L2A_ap24_19/
1 Sentinel product(s) found
Downloading data into <s2_L2A_ap24_19/>...
7ecd0c9f-cd3b-4d7a-aa32-f78e4776364b ->
s2_L2A_ap24_19/S2A_MSIL2A_20200424T084601_N0214_R107_T35SND_20200424T113826.SAFE

```  

```/data ``` is where my volume is mounted. I think there is an issue on i.sentinel.import which I couldn't understand. (most probably an error when finding ```.jp2``` files in the directory.

I'll try to understand and feedback.

**Comment by BatuhanKavlak** [comment]
@neteler It just works when I input the mainfolder:

```
GRASS 7.8.4dev (sentinelLocation):/data/GRASSDATA > i.sentinel.import input=s2_L2A_ap24_19
Reading
<s2_L2A_ap24_19/S2A_MSIL2A_20200424T084601_N0214_R107_T35SND_20200424T113826.zip>...
Processing <T35SND_20200424T084601_B02_10m>...

```
It is shown above in the manual: https://grass.osgeo.org/grass78/manuals/addons/i.sentinel.import.html

In GRASS Wiki it is shown differently:
https://grasswiki.osgeo.org/wiki/SENTINEL

**Comment by veroandreo** [comment]
> @neteler It just works when I input the mainfolder:
> 
> ```
> GRASS 7.8.4dev (sentinelLocation):/data/GRASSDATA > i.sentinel.import input=s2_L2A_ap24_19
> Reading
> <s2_L2A_ap24_19/S2A_MSIL2A_20200424T084601_N0214_R107_T35SND_20200424T113826.zip>...
> Processing <T35SND_20200424T084601_B02_10m>...
> ```
> 
> It is shown above in the manual: https://grass.osgeo.org/grass78/manuals/addons/i.sentinel.import.html
> 
> In GRASS Wiki it is shown differently:
> https://grasswiki.osgeo.org/wiki/SENTINEL

@BatuhanKavlak The wiki was written quite some time ago and i.sentinel* modules have changed meanwhile. Please feel free to edit the wiki accordingly or provide text/code chunks and instructions on where to insert them. Contributions are highly appreciated and welcome :)

**Comment by BatuhanKavlak** [comment]
@veroandreo Thanks a lot. I'm quite new to Grass, recently watched your videos :). I'll definitely try to contribute as I learn.

**Comment by lucadelu** [comment]
Closing, reopen if needed

**Comment by wenzeslaus** [comment]
> FWIW: In actinia, we use a simple way to install addons by looping over a CSV file:
> 
>     * list of addons and their sources: https://github.com/mundialis/actinia_core/blob/master/docker/grass_addons_list.csv
> 
>     * loop over list: https://github.com/mundialis/actinia_core/blob/master/docker/actinia-core/Dockerfile#L73

BTW, _install multiple modules from a file_ is a functionality worth having in the core.
