### ISSUE TITLE
t.register: Python 2 leftover

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#701]
This issue is similar to https://github.com/OSGeo/grass-addons/issues/201

This code part might need an update to Python 3:
https://github.com/OSGeo/grass/blob/5fa5d69f568ccf2d8551bc4f7858dd7f26f2cfaa/temporal/t.register/t.register.py#L150

since the StandardError class was removed in Python 3, according to
https://portingguide.readthedocs.io/en/latest/exceptions.html#the-removed-standarderror

**Comment by landam** [comment]
The code is designed to work in both Python 2/3, see 

https://github.com/OSGeo/grass/blob/5fa5d69f568ccf2d8551bc4f7858dd7f26f2cfaa/temporal/t.register/t.register.py#L146

**Comment by neteler** [comment]
I see! thanks

**Comment by landam** [comment]
From https://docs.python.org/2/library/exceptions.html#exceptions.Exception it seems that `Exception` should work in both Python2/3.
