### ISSUE TITLE
[Feat] wxGUI loc wizard: Improve new location's CRS method selection page

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#706]
The page "Choose method for creating a new location" in location wizard could be improved, specifically I suggest changes in text:

 **Select Coordinate Reference System (CRS)**

- [ ]  Select CRS from a list by EPSG or description
- [ ] Read CRS from a georeferenced data file
- [ ] Create a generic cartesian coordinate system (XY)

Advanced (alternative/additional?) methods:
- [ ] Specify CRS using WKT string
- [ ] Specify CRS using PROJ.4 string
- [ ] Define custom CRS

The WKT and PROJ4 could be one page, just with a selection of format. The WKT would be using pasted text (the same way as the proj4 string) instead of file, I think that's more practical for users.

The titles of the pages would need to be then updated as well.

Any feedback?

**Comment by petrasovaa** [comment]
@landam, @mlennert, @wenzeslaus please provide feedback.

**Comment by mlennert** [comment]
Sounds good to me.

**Comment by landam** [comment]
Sounds also good to me
