### ISSUE TITLE
[Bug] Use of deprecated sbrk

### ISSUE THREAD

**Issue by lbartoletti** [OSGeo/grass#712]
**Describe the bug**
sbrk is an old function deprecated and removed from grass many times, but there is a leftover in r.terraflow (https://github.com/OSGeo/grass/blob/master/raster/r.terraflow/stats.cpp#L130 and https://github.com/OSGeo/grass/blob/master/raster/r.terraflow/stats.cpp#L154)

**To Reproduce**

**Expected behavior**
Remove sbrk in favor of mmap?

**Screenshots**

**System description (please complete the following information):**

- Operating System: FreeBSD aarch64/riscv64 and MacOS
- GRASS GIS version All

**Additional context**

**Comment by nilason** [comment]
Taking a bit closer look into this, `sbrk` is used in two methods for the sole purpose of printing the amount of "Free Memory" to the stat file, e.g. `r.terraflow stats=stats.txt [...]`.

On my machine (Intel x86 Mac), `getrlimit()` returns with a `rlimit.rlim_cur == RLIM_INFINITY` and therefore bails out with `-1` without even using the results from `sbrk`. See below:

```sh
head stats.txt 
Free Memory=-1
[0.0] Wed Jan 27 10:31:51 2021
Command Line: 
r.terraflow elevation=elev_srtm_30m@PERMANENT filled=filled_rast stats=string.txt 
input elevation grid: elev_srtm_30m
output (filled_rast) elevations grid: filled_rast
[0.0] MFD flow direction
[0.0] D8CUT=999999986991104.000000
[0.0] Memory size: 300.00M (314572800) bytes
region size = 219.73K (225000) elts (450 rows x 500 cols)
```

The question is, is this information relevant on today's machines (or are there any platforms where the "Free Memory" is accurately printed)?

**Comment by nilason** [comment]
@neteler May I ask you to test if the output of "Free Memory" is anything but "-1" and, if so, does it seem accurate given your machine's resources?

I did the above little test: `r.terraflow elevation=elev_srtm_30m@PERMANENT filled=filled_rast stats=stats.txt` on `nc_spm_08`, but any elev data would of course do.

**Comment by neteler** [comment]
```
uname -a
Linux oboe 5.9.9-200.fc33.x86_64 #1 SMP Thu Nov 19 21:25:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

gcc -v
...
gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC) 


# freshly compiled right now
GRASS nc_spm_08_grass7/user1:~ >
g.region raster=elev_srtm_30m -p ; r.terraflow elevation=elev_srtm_30m@PERMANENT filled=filled_rast stats=stats.txt

free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       8.7Gi       4.5Gi       848Mi       1.8Gi       5.1Gi
Swap:          11Gi       4.9Gi       6.7Gi


cat stats.txt
Free Memory=-1
[0.0] Thu Feb  4 14:12:45 2021
Command Line: 
r.terraflow elevation=elev_srtm_30m@PERMANENT filled=filled_rast stats=stats.txt 
input elevation grid: elev_srtm_30m
output (flooded) elevations grid: filled_rast
[0.0] MFD flow direction
[0.0] D8CUT=999999986991104.000000
[0.0] Memory size: 5.86G (6291456000) bytes
region size = 219.73K (225000) elts (450 rows x 500 cols)
internal nodata value: -9999
Reading raster map <elev_srtm_30m> to stream </home/mneteler/grassdata/nc_spm_08_grass7/user1/.tmp/oboe/1793733.0/STREAM_baaaaX>.
[0.0] TIME reading raster map: [0.03u (63%) 0.01s (18%) 0.05 80.8%]
...
```

Anything else I shall report?

**Comment by nilason** [comment]
Thanks you!
I see you also get "Free Memory=-1". Probably means [rlimit.rlim_cur == RLIM_INFINITY](https://github.com/OSGeo/grass/blob/master/raster/r.terraflow/stats.cpp#L149)  for you system too.
Confirms my suspicion this "Free Memory" check, is outdated on modern machines. This is as far as I see it not harmful in anyway, but suggests it needs an update or be removed.

> Anything else I shall report?

More than enough for now :-) , thank you!
