### ISSUE TITLE
[Feat] add missing GRASS specific terminal prompt with zsh

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#719]
**Describe the bug**
In contrast to e.g. bash, using zsh shell running GRASS doesn't change the prompt. This makes it very difficult to know first of all if GRASS is running but also which location is opened. 

* __/bin/bash__:
```
computer:~ nila$ grass79
GRASS 7.9.dev (srtm):~ >
```
* __/bin/zsh__:
```
nila@computer ~ % grass79
nila@computer ~ %
```
**Expected behavior**
Zsh should have a prompt which at least indicates if GRASS is running, and possibly also location.

**System description (please complete the following information):**

- Operating System: tested on macOS 10.15 (but the issue is probably independent of OS)
- GRASS 7.9.dev

**Comment by lbartoletti** [comment]
>     * (but the issue is probably independent of OS)

I can confirm :)

**Comment by neteler** [comment]
I suppose a `zstd_startup()` function needs to be added, corresponding to e.g. bash:

https://github.com/OSGeo/grass/blob/c05ef6de3fcaeb73d586b99bcb29c383933e61f5/lib/init/grass.py#L1904

**Comment by nilason** [comment]
> I suppose a `zstd_startup()` function needs to be added, corresponding to e.g. bash:

Yes, that was what I was thinking (but maybe `zsh_startup()` :).
Looking at this again, I come to realise this isn't a bug proper, please re-label this to `enhancement`.

**Comment by nilason** [comment]
Now with zsh it goes through `default_startup()` and it *should* work with following line:

https://github.com/OSGeo/grass/blob/c05ef6de3fcaeb73d586b99bcb29c383933e61f5/lib/init/grass.py#L1987

but the `PS1` will not be set. (Setting `PS1` manually in terminal works fine).

**Comment by nilason** [comment]
The `PS1` will be set, but not for the process (session) launched in the following line:

https://github.com/OSGeo/grass/blob/c05ef6de3fcaeb73d586b99bcb29c383933e61f5/lib/init/grass.py#L1988

seems to me this part of `default_startup()` has little use...

**Comment by neteler** [comment]
Did you try to add and register a new function `zsh_startup()` ?
