### ISSUE TITLE
[Bug] gui: font error with macOS 10.15

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#720]
**Describe the bug**

Running GRASS with macOS 10.15 produces a font related error:

```
nila@computer ~ % grass79
...
Launching <wxpython> GUI in the background, please wait...
nila@computer ~ % 2020-06-19 11:40:27.663 Python[1140:34850] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-06-19 11:40:27.663 Python[1140:34850] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2020-06-19 11:40:27.782 Python[1140:34850] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```

This doesn't happen with macOS 10.14, so it's probably a related to changes to 10.15.

**Screenshots**

The likely culprit marked:

<img width="496" alt="Screenshot" src="https://user-images.githubusercontent.com/14186207/85121998-25bf0b00-b226-11ea-8874-7b383f4ab8cf.png">

**System description (please complete the following information):**

- Operating System: macOS 10.15.5
```
g.version -rge
version=7.9.dev
date=2020
revision=1bc4a8674
build_date=2020-06-18
build_platform=x86_64-apple-darwin19.5.0
build_off_t_size=8
libgis_revision=1bc4a8674
libgis_date=2020-06-18T17:42:21+00:00
proj=6.3.2
gdal=3.1.0
geos=3.8.1
sqlite=3.32.2

Python=3.8.3
wx.version()=4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5
```

**Additional context**
Seems more likely to be an issue for wxPython or wxWidgets, but until that can be confirmed I'll report it here.

**Comment by nilason** [comment]
Running wxdemo confirms this is not a GRASS bug:
<img width="224" alt="Screenshot2" src="https://user-images.githubusercontent.com/14186207/85130921-1e076280-b236-11ea-9a0a-6efb32e9598d.png">

**Comment by petrasovaa** [comment]
Do you want to open it with wxPython and close it here?

**Comment by nilason** [comment]
I did some test with various configurations:

**Working:**
Python 3.7.3 / 4.1.0 osx-cocoa (phoenix) wxWidgets 3.1.4 (GRASS 7.9.dev)
Python 3.6.10  / 4.0.6 osx-cocoa (phoenix) wxWidgets 3.0.5 (GRASS 7.8.3)
Python 3.8.3 / 4.1.0 osx-cocoa (phoenix) wxWidgets 3.1.4 (GRASS 7.9.dev)

**Not working:**
Python 3.8.3 / 4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5 (GRASS 7.9.dev)

The two Python 3.8.3 are different builds. It seems one of them is a naughty one. Can't explain, but definitely not GRASS issue.
