### ISSUE TITLE
[Feat] wxGUI datacatalog: Add multiple GRASS databases

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#741]
Currently, only the current database is in the GUI datacatalog. To make this more useful, user needs to be able to add additional ones.

Changes throughout the tree.py will be needed, starting e.g. with `_initVariables`, `DefineItems`. Next, wherever there is `gisenv()['GISDBASE']` it needs to be checked if it should be replaced by currently selected db instead. But pretty much all methods need to be reviewed if any change is needed there.

As a way to test it, I suggest adding a button to the toolbar that would open a file dialog to add a new db.

For this issue, we don't need to implement any functionality on right click for db, later we would add e.g. add new location, remove from tree.

**Comment by mlennert** [comment]
> For this issue, we don't need to implement any functionality on right click for db, later we would add e.g. add new location, remove from tree.

Should another issue be opened for this or is there already one that I overlooked ? As soon as I tested adding a new database, I was looking for the option to remove it from the tree ?

**Comment by mlennert** [comment]
> > For this issue, we don't need to implement any functionality on right click for db, later we would add e.g. add new location, remove from tree.
> 
> Should another issue be opened for this or is there already one that I overlooked ? As soon as I tested adding a new database, I was looking for the option to remove it from the tree ?

I see #747 addresses the first, but there is nothing for the latter, or ?

**Comment by petrasovaa** [comment]
We will add a new one, it could be addressed together with more general managing of dbs in settings (so that they are remembered next time gui starts).
