### ISSUE TITLE
[Bug] Remove colouring of standard buttons

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#743]
**Describe the bug**
The colouring of standard buttons may render the button text unreadable, depending on OS default behaviour. Presently, some buttons are set with a green colour.

This is a problem starting with wxPython 4.1.0 on Mac. Previously SetForegroundColour() on buttons was silently ignored, but this is no longer the case with 4.1.0.

**Expected behavior**
The look and behaviour of standard buttons should be set by OS (and wxPython). No need to make GRASS any greener.

**Screenshots**
Now with wxPython 4.1.0:
<img width="467" alt="button-bad" src="https://user-images.githubusercontent.com/14186207/85990652-a2a26f80-b9f2-11ea-8a12-1f276530ef25.png">

Previously, and expected:
<img width="467" alt="button-good" src="https://user-images.githubusercontent.com/14186207/85990666-a7ffba00-b9f2-11ea-8dfa-9f4dd6960b24.png">

**System description (please complete the following information):**

- Operating System: macOS
- wxPython 4.1.0

**Additional context**
An alternative to remove the colouring would be to put SetForegroundColour() in a conditional clause depending on OS, but I must say I favour removing – the alternative is a lot of additional code for a questionable cause.  I found this code in 5 places in the repository.

**Comment by petrasovaa** [comment]
While I am in general in favor of  this, I have some concern about the visibility of the 'green' buttons, like Run in forms.py. At least in my case, although it's the default button, you don't see any visual difference from other buttons (except the current green), so it might be more difficult to find which button you actually want to press.

**Comment by nilason** [comment]
Interesting, is the default button never highlighted for you somehow anywhere, e.g `GUI Settings > Save` or `d.rast > OK` buttons?

**Comment by petrasovaa** [comment]
It's not visually distinguished for me, I tried different styles, so I suspect it may be some wxgtk problem. Not sure about Windows.

**Comment by neteler** [comment]
> It's not visually distinguished for me, I tried different styles, so I suspect it may be some wxgtk problem. Not sure about Windows.

Maybe @hellik can help here?

**Comment by nilason** [comment]
Just checked on windows, the green-labeled buttons seems to correspond to where the default button is *not* distinct, which they otherwise are.

The reason for this mixed behaviour is probably as stated in [wxPython wx.Button.SetDefault docs](https://docs.wxpython.org/wx.Button.html?highlight=wx.button#wx.Button.SetDefault): 

> Note Under Windows, only dialog box buttons respond to this function.

**Comment by nilason** [comment]
Is this visually non-distinct behaviour for default buttons an issue on Linux systems in general or just for some flavours?
How about:
* wxdemo > Button
* wxdemo > GenericButtons ("A real button" is a default button)

This disparate behaviour may perhaps be addressed with a wrapper "DefaultButton" class?

**Comment by petrasovaa** [comment]
They look the same for me. I am still in favor of merging #744, these color customizations are in general problematic (also for the dark mode). Perhaps we could address this by changing the position of the buttons to provide a different visual distinction. It mainly concerns the module dialogs I think.

**Comment by nilason** [comment]
> They look the same for me. I am still in favor of merging #744, these color customizations are in general problematic (also for the dark mode). Perhaps we could address this by changing the position of the buttons to provide a different visual distinction. It mainly concerns the module dialogs I think.

I agree, this may be addressed with following changes:

present button layout in module dialogs:
```
|        [Close] [Run] [Copy] [Help]        |
```


proposed layout:
```
| [Help] [Copy] [Close]              [Run]  |
```
