### ISSUE TITLE
[Feat] Add new location action to database node in Data tab

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#747]
The data catalog (data tab) should allow users to create new locations.

The functionality of the _New Location_ button and _Download_ button in the Startup window can be just reused to allow both 1) starting the Location Wizard and creating location that way and 2) downloading and extracting a location.

For starters, the functionality can be added to the context menu of the spatial database (grassdata) node(s) in the data tree.

So, the user should right click on a database node, and see *Create new location* and *Download location* as options in the context menu. Then either Location Wizard or Location Download dialogs appear and do what they do in the startup.

Should this switch into the new location? Let's leave this discussion for another issue.

A question to the community in regard to this issue: How should the context menu items *Create new location* and especially *Download location* be called? *Download sample location*? *Download location template*?

**Comment by veroandreo** [comment]
> A question to the community in regard to this issue: How should the context menu items _Create new location_ and especially _Download location_ be called? _Download sample location_? _Download location template_?

I like _Download sample location_ best

**Comment by wenzeslaus** [comment]
> I like _Download sample location_ best

What about datasets which are more useful than just samples such as the global dataset in #544?

**Comment by veroandreo** [comment]
> > I like _Download sample location_ best
> 
> What about datasets which are more useful than just samples such as the global dataset in #544?

It is still a sample location in my view. We could also say _Download sample dataset_

**Comment by mlennert** [comment]
Download ready-made location ?
Download ready to use location ?
Download pre-defined location ?
Download prebuilt location ?
