### ISSUE TITLE
[Feat] Make Data tab the default in GUI

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#748]
**Is your feature request related to a problem? Please describe.**
Users in various use cases, start GRASS GIS, but the window they receive is blank. They need to go to menu, toolbar or Data tab to see what is in the current mapset in order to decide what is their next step.

**Describe the solution you'd like**
The Data tab should be moved so it is the first tab from the left and it is the default when the GUI opens.

User can then use the Data tab to add data to Layers tab.

**Additional context**
The behavior for opening a workspace is outside of scope for this issue. Let's open another one if needed after this is finished.

**Comment by petrasovaa** [comment]
@mlennert, @landam, @neteler or anyone else, are you fine with this change?

**Comment by veroandreo** [comment]
I like this, yes. In that way the user can see the list of maps in the mapset first thing once starting GRASS

**Comment by neteler** [comment]
It sounds good to me as well

**Comment by landam** [comment]
Hi all, I fully agree with this change. Martin

Dne st 1. 7. 2020 19:38 uživatel Anna Petrasova <notifications@github.com>
napsal:

**Comment by petrasovaa** [comment]
Note: users with a lot of maps might experience delay when loading the data (they should still see the gui though), this will need to be addressed in #749.
