### ISSUE TITLE
[Feat] Add functionality to load only data from the current mapset in the Data tree

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#749]
**Is your feature request related to a problem? Please describe.**
Loading list of raster and vector maps in the data tab can be slow if there is a lot of maps in a mapset, lot of mapsets, or lot of locations in the database. This becomes more of an issue when #741 and #748 are implemented.

**Describe the solution you'd like**
To future-prove the data catalog (data tree/tab), the function which initializes the tree, should have a parameter to load the lists of maps only current for the current mapset.

At this point, this issue is aiming only at extenteding the API. However, we can use it to discuss how the user interface should look like and behave.

**Comment by neteler** [comment]
I tried the current state (revision=a3888a00d) of the updated wxGUI and like the new data tab very much.

Small cosmetical wish (probably it fits here): use a "busy" cursor when loading the list of maps in the various locations, like

```
wx.BusyInfo(message = _("Loading available maps...")
...
wx.BeginBusyCursor()
...
wx.EndBusyCursor()
```

Rationale: on my laptop, with SSD and a number of locations, it takes 5 seconds to load. At time it is just empty and I (initially) wondered what's going on as all remained empty for this time.

**Comment by petrasovaa** [comment]
> Rationale: on my laptop, with SSD and a number of locations, it takes 5 seconds to load. At time it is just empty and I (initially) wondered what's going on as all remained empty for this time.

I was wondering approximately how many maps and locations do you have? I haven't had an issue with the speed, loading is pretty much instantaneous for me, but I likely don't have as many layers as you do. I found calling g.list to be fast, what took time is unfolding a node with thousands of layers.

**Comment by neteler** [comment]
I count on my laptop:
- 80 locations
    - with 235 mapsets:
         - playing around with `find` on `cellhd` I find 4361 raster map entries 
          - and with `*/*/vector/*/head` 735 vector maps

(seems I am more focused on raster :p)

**Comment by petrasovaa** [comment]
Seems the problem is the number of locations, I created 10000 rasters in one mapset and that is not an issue. I do have new laptop though. The loading is parallel on level of locations, but I am not sure how effective that is. Some kind of notification about loading is definitely needed.

**Comment by nilason** [comment]
I have only some 30 locations in my active grassdata dir, but I have noticed a clear loading speed-up with wxPython 4.1.0 compared to with 4.0.7.

**Comment by wenzeslaus** [comment]
Given the testing done so far, the significance of this issue is reduced by #847 which reduces the number of times whole tree is re-rendered and will be further reduced by indicating the loading (issue needed). Once that is in place, this issue can be closed I think.

**Comment by wenzeslaus** [comment]
The loading is indicated now by a busy cursor. Loading time reduced in #847. With #1043 we can close this. It splits the loading into two thus giving more feedback on what is happening.
