### ISSUE TITLE
[Bug] grass --config throws ValueError: '--exec' is not in list

### ISSUE THREAD

**Issue by jebins** [OSGeo/grass#774]
Hi,

**Describe the bug**
`grass --config` throws a Python ValueError.

```
➜  ~ grass --config
x86_64-pc-linux-gnu
./configure  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr/lib --enable-largefile --enable-socket --enable-shared --with-blas --with-bzlib --with-cairo --with-cxx --with-freetype --with-freetype-includes=/usr/include/freetype2 --with-gdal --with-geos --with-lapack --with-motif --with-mysql --with-mysql-includes=/usr/include/mysql --with-netcdf --with-nls --with-odbc --with-openmp --with-pdal --with-postgres --with-postgres-includes=/usr/include/postgresql --with-proj-share=/usr/share/proj --with-python --with-readline --with-sqlite --with-wxwidgets=/usr/bin/wx-config --with-x --with-zstd
gcc
/usr/lib/grass78
Traceback (most recent call last):
  File "/usr/bin/grass", line 2027, in main
    index = sys.argv.index(batch_exec_param)
ValueError: '--exec' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/grass", line 2218, in <module>
    main()
  File "/usr/bin/grass", line 2032, in main
    params = parse_cmdline(sys.argv[1:], default_gui=default_gui)
  File "/usr/bin/grass", line 1953, in parse_cmdline
    print_params()
  File "/usr/bin/grass", line 1864, in print_params
    "%s\n" % val[0].split(':')[1].rstrip('$"\n').strip())
IndexError: list index out of range
```

**To Reproduce**

1. Open a new terminal or a grass GIS console: `grass --text`.
2. type `grass --config`, then enter.

**Expected behavior**
Printing grass config without errors.

**System description (please complete the following information):**
- Operating System: Ubuntu 20.04
- GRASS GIS version: 7.8.2

- details about further software components:
version=7.8.2
date=2019
revision=exported
build_date=2020-03-24
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=00000
libgis_date="?"
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1

**Comment by ninsbl** [comment]
This should be fixed in #405 
Can you update to GRASS 7.8.3?

**Comment by jebins** [comment]
I confirm it’s working with 7.8.3.

**Comment by wenzeslaus** [comment]
For future reference, note that in Python exceptions can be used to control normal flow of the program (as opposed to handling exceptional error states only) thus if you see `During handling of the above exception, another exception occurred` either of the exceptions can point to an error or both, so good idea to include both as you did. In this case, the first one happens to be controlling normal flow of the program and the second one is the actual error. This could be the other way in some other case. I don't know how to tell the difference without examining the code, but I though you still may find this info handy.

Thanks for testing in 7.8.3.

**Comment by jebins** [comment]
Indeed, I thought the first one was the actual error.
Thanks for that explanation, very informative.
