### ISSUE TITLE
[Feat] Allow delete on multiple mapsets in data catalog

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass#791]
The great new management options in the data catalogue make us greedy ;-), and so now that I easily delete a mapset in the catalogue, I immediately stumbled upon the next wish: being able to delete several mapsets at once, i.e. selecting several mapsets and then right-click and be able to delete. Currently, the message on right-click on a multiple selection of mapsets is "No available options". Another option to right-click would be to add a few more buttons (e.g. delete) that could work on either on or several selected mapsets, but I'm not sure we want to increase the number of buttons.

**Comment by petrasovaa** [comment]
This should be possible, basically just loop over all the mapsets. Special check would need to be done for current mapset.
