### ISSUE TITLE
[Bug] v.to.db: overwrite flag for existing columns not available in GUI

### ISSUE THREAD

**Issue by MiKatt** [OSGeo/grass#794]
**Describe the bug**
Since GRASS 7.8 v.to.db creates a new column to populate and needs the overwrite flag when using existing columns.
However, this flag is not available in the GUI. Hence, if the column already exists, the command can only be run from the command line.

**Expected behavior**
The flag should be available under 'Optional'. It should also be included in the Manual under flags as well as in the interface description.

**System description:**
- Operating System: [Linux Mint 19]
- GRASS GIS version [e.g. 7.8.3]

**Additional context**
I am running GRASS from R using rgrass7. To use flags they need to be given in the description of the interface.

**Comment by HuidaeCho** [comment]
Fixed in #807.

**Comment by neteler** [comment]
@MiKatt can this report be closed as been fixed?

**Comment by MiKatt** [comment]
Thanks!
