### ISSUE TITLE
[Feat] Check for gislock and other issues when deleting/renaming/editing mapset and location in catalog

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#801]
Currently we don't have mechanism in data catalog to check for gislock and if mapset belongs to different user, so that we prevent user from actions including deleting or renaming mapset, and editing layers. The same applies to location deleting/renaming, it needs to check whether all mapsets can be edited.

**Comment by wenzeslaus** [comment]
Now depends on #837.
