### ISSUE TITLE
[Bug] Error when launching a module from GUI while adding a layer to layer manager

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#814]
**Describe the bug**
Error message in console when launching r.contour from wxGUI while adding a layer.
```
`Traceback` (most recent call last):
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/lmgr/frame.py", line 937, in OnMenuCmd

GUI(parent=self, giface=self._giface).ParseCommand(cmd)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/gui_core/forms.py", line 2935, in ParseCommand

get_dcmd=get_dcmd, layer=layer)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/gui_core/forms.py", line 550, in __init__

frame=self)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/gui_core/forms.py", line 1463, in __init__

mapList.append(str(layer))
TypeError
:
__str__ returned non-string (type NoneType)`
```

**To Reproduce**
Start adding a raster layer, but don't finish adding it (it still says: Add raster map layer (double click to set properties))
Select a raster module from menu or call a raster module from command console.

**Expected behavior**
Should launch the r.contour GUI 
It does this if launched from the terminal

**System description (please complete the following information):**

- Mac OSX 15.5
- GRASS GIS version 
version=7.8.4dev
date=2020
revision=f7601c4ce
build_date=2020-07-16
build_platform=x86_64-apple-darwin19.5.0
build_off_t_size=8

**Comment by nilason** [comment]
> Start adding a raster layer, but don't finish adding it (it still says: Add raster map layer (double click to set properties))
Select a raster module from menu or call a raster module from command console.

The same goes for start adding a vector layer and calling a vector module.
