### ISSUE TITLE
[Bug] Map display does not keep the position of decorations

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass#815]
The main map display in the GUI does not remember the position of any decoration added. Every time I add a new element, say scale bar, north arrow, raster legend, it moves those added previously to the original positions where they appear; it does not remember where the user moved them. Also, after moving all elements to desired positions, when exporting as png all the elements are shuffled again and the output does not display the decorations where they were placed by the user.

**Steps to reproduce the behavior:**
1. Display elevation map in NC
2. Add north arrow and move it to a different position
3. Add scale bar --> north arrow goes back to default position
4. Move north arrow again and also scale bar
5. Export as png --> all moves back to default positions

**Expected behavior**
That the map decorators remain where the user wants to place them

**Screenshots**

Desired positions:
![image](https://user-images.githubusercontent.com/20075188/87999278-980f5d80-cafa-11ea-9f43-b21323d78f81.png)

Output when exporting to png (and the same appears in the Main Display, so the elements move before saving):
![image](https://user-images.githubusercontent.com/20075188/87999349-cc831980-cafa-11ea-9a00-12f6e114c615.png)

**System description:**
GRASS version: 7.9.dev                                                          
Code revision: 1419b96e0                                                        
Build date: 2020-07-21                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.0.4                                                                     
PROJ: 6.3.2                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.32.3                                                                  
Python: 3.8.3                                                                   
wxPython: 4.0.7                                                                 
Platform: Linux-5.7.8-200.fc32.x86_64-x86_64-with-glibc2.2.5

**Comment by veroandreo** [comment]
Just found out that it happens in 7.8.3 too... Too bad we didn't discover this one earlier, I'll be teaching GRASS in 2 weeks with 7.8.3

**Comment by petrasovaa** [comment]
@veroandreo can you confirm the fix (merged #817) in master? Needs to be backported.

**Comment by veroandreo** [comment]
It now works fine in master again, thanks :) I leave open until backport is done

**Comment by cmbarton** [comment]
I'll check in master when I can get it to compile.

**Comment by petrasovaa** [comment]
Thanks for testing, merged to 78.
