### ISSUE TITLE
[Bug] Python scripts with CRLF end of line are not found in GRASS_ADDON_PATH (Linux)

### ISSUE THREAD

**Issue by jebins** [OSGeo/grass#816]
Hi,

**Describe the bug**
CRLF Python scripts in GRASS_ADDON_PATH are not recognised by GRASS on Linux. `grass --exec script.py` will fail. Even if you can simply save the file with the correct LF end of line, it can be annoying, _e.g._ working with a Windows partition or trying to execute scripts made on Windows.

**To Reproduce**
1. Create two files, the first saved with LF, the second with CRLF.

`test_LF.py`
``` python3
#! /usr/bin/python3
# coding: utf-8

print("This is a LF file")
```

`test_CRLF.py`
``` python3
#! /usr/bin/python3
# coding: utf-8

print("This is a CRLF file")
```
2. Make them executable
```bash
chmod +x test_CRLF.py
chmod +x test_LF.py
```

2. Copy the 2 files in your `GRASS_ADDON_PATH`

3. Run the scripts with grass --exec

`grass --exec test_LF.py`
``` text
Démarrage du SIG GRASS ...
Nettoyage des fichiers temporaires ...
Exécution de <test_LF.py> ...
This is a LF file
Exécution de <test_LF.py> terminée.
Cleaning up default sqlite database ...
Cleaning up temporary files...
```

`grass --exec test_CRLF.py`
``` text
Démarrage du SIG GRASS ...
Nettoyage des fichiers temporaires ...
Exécution de <test_CRLF.py> ...
ERREUR: La commande <test_CRLF.py> a échoué :
[Errno 2] Aucun fichier ou dossier de ce type: 'test_CRLF.py'
Sortie ...
```
_Note:_ This will work if running `grass --exec python3 test_CRLF.py` outside of GRASS_ADDON_PATH.

**Expected behavior**
At least an error message, and maybe automatic conversion from CRLF to LF on Linux using a [unix2dos](https://en.wikipedia.org/wiki/Unix2dos)-like command ?

**System description**
* Operating System: Ubuntu 20.04
* GRASS GIS version: 7.8.3
* Details about further software components:
    version=7.8.3
    date=2020
    revision=exported
    build_date=2020-05-05
    build_platform=x86_64-pc-linux-gnu
    build_off_t_size=8
    libgis_revision=2020-05-05T23:27:51+00:00
    libgis_date=2020-05-05T23:27:51+00:00
    proj=6.3.1
    gdal=3.0.4
    geos=3.8.0
    sqlite=3.31.1

**Comment by neteler** [comment]
@jebins does #816 solve the issue for you?

**Comment by jebins** [comment]
Yes, it works.

**Comment by wenzeslaus** [comment]
Worth noting that what you observe is standard behavior in Bash, Z shell, and likely others:

```
$ # not in GRASS
$ ./test_crlf.py 
bash: ./test_crlf.py: /usr/bin/python3^M: bad interpreter: No such file or directory
```

@neteler @tmszi @jebins Do I understand correctly that you expect `--exec` to behave differently than your shell?
