### ISSUE TITLE
[Bug] error message on wxGUI launch

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#850]
**Describe the bug**
When launching GRASS 7.9 dev, I get the following error messages in the terminal. They do not seem to cause any problems (at least none that I've run into yet). But something is causing them.

GRASS 7.9.dev (nc_spm_08_grass7):~ > The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

**System description (please complete the following information):**

- Operating System: Mac OSX 10.15.5
- GRASS GIS version 
GRASS 7.9.dev (2020)
libgis revision: 229dd3ea7
libgis date: 2020-07-27T18:20:39+00:00

**Comment by nilason** [comment]
I’ve never encountered this. Is this with your newly posted binary?

**Comment by cmbarton** [comment]
Yes.

**Comment by cmbarton** [comment]
Just ran some things again. This seems to occur the first time I add a raster to the display list rather than on launch

**Comment by cmbarton** [comment]
This also generates a separate Python crash window. Seems very weird.

**Comment by nilason** [comment]
I couldn't reproduce this with the same binary (with macOS 10.15.6, though I doubt *that* has any influence).

**Comment by cmbarton** [comment]
Just launched GRASS 7.9 under OS 10.15.6. This DOES happen when wxGUI launches. I can reproduce by quitting the GUI and then launching it again (g.gui) from the terminal. I'm attaching the system crash report for Python. These are hard for me to sort out but it seems that it might be something in the terminal. Perhaps it is the new code to use zsh???
[apple_crash_report.txt](https://github.com/OSGeo/grass/files/5002699/apple_crash_report.txt)

**Comment by nilason** [comment]
Somehow you managed to squeeze in two versions of python in the app bundle. And GRASS_PYTHON is the no go 3.7.6.

```
echo $GRASS_PYTHON                                         
/Applications/GRASS-7.9.app/Contents/Resources/bin/pythonw

/Applications/GRASS-7.9.app/Contents/Resources/python.app/Contents/MacOS/python --version
Python 3.7.6
/Applications/GRASS-7.9.app/Contents/Resources/bin/pythonw --version
Python 3.7.6
/Applications/GRASS-7.9.app/Contents/Resources/bin/python3.7 --version
Python 3.7.8
```
That would explain the crash!

**Comment by cmbarton** [comment]
The miniconda installer puts in Python in 2 different places, which is why I had to use a symlink in Python 3.6. But it never ran 2 versions. I have a guess as to what the problem is though. I'll check and let you know.

**Comment by cmbarton** [comment]
It was more complicated than I thought. It is a similar, but somewhat different bug in the Anaconda/Miniconda installation that caused the dueling Pythons and Python crash. I can fix this with a new symlink for a workaround. 

However, this is not the cause of the 'this_process_has_forked..." error messages. Those still show up even though I have a single version of Python running now: 3.7.8 only

**Comment by nilason** [comment]
If you have python.app in req list you may try pin a version for it.

**Comment by cmbarton** [comment]
Note that I compiled this with Python 3.7.8. I can't yet use higher versions and get all dependencies. But 3.7.8 should be fine. 

There is python.app in a couple places. 

/Applications/GRASS-7.9.app/Contents/Resources/python.app is a true app folder and by default contains a copy of Python 3.7.6 (the default Python version for the miniconda installer). This is located at /Applications/GRASS-7.9.app/Contents/Resources/python.app/Contents/MacOS/python

There is also /Applications/GRASS-7.9.app/Contents/Resources/bin/python.app 
This latter is actually a script that is identical to the /Applications/GRASS-7.9.app/Contents/Resources/pythonw script

Both of these point to /Applications/GRASS-7.9.app/Contents/Resources/python.app, which means that pythonw launched Python 3.7.6, even though GRASS is compiled with /Applications/GRASS-7.9.app/Contents/Resources/bin/python (which is a symlink pointing to python3.7 = Python 3.7.8). 

To fix this, I replaced /Applications/GRASS-7.9.app/Contents/Resources/python.app/Contents/MacOS/python with a symlink pointing to /Applications/GRASS-7.9.app/Contents/Resources/bin/python.

So when pythonw is called now, it launches v. 3.7.8, matching what GRASS expects. This should be generic enough to work with higher versions when I can begin to use them, even if miniconda continues to dump v. 3.7.6 into its python.app.

Since the Python "crash" has no ill effects, except for befuddlement and annoyance, I thought I'd wait to post a new version until after you or others can check on the forked process messages.

**Comment by nilason** [comment]
Is this still an issue?

**Comment by cmbarton** [comment]
Need to check. The serious error has been resolved. Process forked may remain

**Comment by cmbarton** [comment]
This is no longer an issue. Closing
