### ISSUE TITLE
[Feat] Start in a demo/startup location

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#862]
Let's go a step further than just creating a directory for grassdb in the startup during first-time run: After creating this directory, follow with another function to create a simple location with some data.

The location `demolocation` in distribution (`GISBASE`) can be used for that. If it does not exist and thus cannot be copied, the startup should continue as usual.

I think the name should be `startup` or `startup_location`. It is more descriptive than demolocation but still clearly conveying it is not meant for normal use.

**Additional context**
This was discussed on [Next steps in GSoC and beyond video call, July 15, 2020 (notes)](https://trac.osgeo.org/grass/wiki/wxGUIDevelopment/New_Startup#NextstepsinGSoCandbeyondvideocallJuly152020).

**Comment by mlennert** [comment]
I'm afraid that "startup" in the name would be interpreted as being the location you have to choose to start GRASS GIS.

I would prefer demo, or, since you don't like that, what about "default" ? Or "example location" ?

Or just give it a name linked to it's content and projection, e.g. "Worldwide lat-long (datum WGS84)" or something like that ?

**Comment by wenzeslaus** [comment]
> I'm afraid that "startup" in the name would be interpreted as being the location you have to choose to start GRASS GIS.

...which is not necessarily a harmful interpretation. Also, currently, we don't plan much choosing, you should be automatically brought there (to the startup/demo location) or to your last used mapset (if you have that available).

> I would prefer demo, or, since you don't like that, what about "default" ? Or "example location" ?

Hm, "by default, it should start in the last used mapset," so default is not good plus it does not convey the meaning of not being meant for actual use.

Both _demo_ and _example_ show it is not meant for normal use, but since it is supposed to stay around and might be potentially used at any point, I'm reluctant to give it one of these names because they seem like you use it once and then you delete that.

> Or just give it a name linked to it's content and projection, e.g. "Worldwide lat-long (datum WGS84)" or something like that ?

That's an interesting idea. Why to insist on this location being not meant for serious use? Perhaps it can be as useful as any other lat-lon one would be. The messages in the GUI would have to be more general tailored towards lat-lon rather than startup/demo. That's possible, but it could lead to less clear message and less behavior tailored towards a first-time user.

**Comment by neteler** [comment]
> > Or just give it a name linked to it's content and projection, e.g. "Worldwide lat-long (datum WGS84)" or something like that ?
> 
> That's an interesting idea.

I like that idea a lot.

**Comment by wenzeslaus** [comment]
> > > Or just give it a name linked to it's content and projection, e.g. "Worldwide lat-long (datum WGS84)" or something like that ?

Any suggestions for the directory name? I mean something which is basically vector map name compliant which is what we now enforce in the GUI (although not required by GRASS in (most?) contexts).

**Comment by mlennert** [comment]
> > > > Or just give it a name linked to it's content and projection, e.g. "Worldwide lat-long (datum WGS84)" or something like that ?
> 
> Any suggestions for the directory name? I mean something which is basically vector map name compliant which is what we now enforce in the GUI (although not required by GRASS in (most?) contexts).

world_latlong_wgs84 ?
