### ISSUE TITLE
[Bug] grass-session broken after recent update in master 

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#869]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1295172/89097477-7b6b0380-d3df-11ea-98db-c15802034aa9.png)

Checking the build log shows:

```
Step 63/66 : COPY docker/testdata/test_grass_session.py .
---> 9201a22e2070
Step 64/66 : RUN /usr/bin/python3 /scripts/test_grass_session.py
---> Running in 3182ff068bbf
Traceback (most recent call last):
File "/scripts/test_grass_session.py", line 3, in <module>
import grass.script as grass
ModuleNotFoundError: No module named 'grass'
```

Note that this was also reported on grass-user recently:

https://lists.osgeo.org/pipermail/grass-user/2020-July/081663.html

The test is executed here:
https://github.com/OSGeo/grass/blob/b891555dcf314301975fcb9a01b5a75f821e4b98/docker/ubuntu/Dockerfile_ubuntu_latest_pdal#L188

Release_branch_7_8 is not affected. Hence it appears to be a recent change in master, likely this one (before the builts on hub.docker.com went well):

![image](https://user-images.githubusercontent.com/1295172/89098110-eff47100-d3e4-11ea-993c-449b3fe64408.png)

which is "grass.grassdb: New Python subpackage for working with locations..." (0538cf8d9862d0a0d661a244e07abeeb55000fc7).

@wenzeslaus could you please make a test with `grass-session`?

**Comment by neteler** [comment]
Docker images still broken, potential reason: #837 ("New Python subpackage for working with locations and mapsets")

**Comment by wenzeslaus** [comment]
> @wenzeslaus could you please make a test with grass-session?

I don't think GRASS GIS should be testing some third party repos which is what grass-session currently is from point of view of the GRASS project. If we resolve #658 and something like grass-session is part of the source code, then that's of course a completely different situation.

As for the issue itself, I can look at it, but it would be good to have a minimal reproducible example, i.e., something which does not include 500 lines from another repo. `grass79 --config path` which is used in grass-session works for me.

**Comment by neteler** [comment]
> > @wenzeslaus could you please make a test with grass-session?
> 
> I don't think GRASS GIS should be testing some third party repos which is what grass-session currently is from point of view of the GRASS project. If we resolve #658 and something like grass-session is part of the source code, then that's of course a completely different situation.

Maybe that's exactly the way to go? What do you think, @zarch ?

 
> As for the issue itself, I can look at it, but it would be good to have a minimal reproducible example, i.e., something which does not include 500 lines from another repo. `grass79 --config path` which is used in grass-session works for me.

**Comment by wenzeslaus** [comment]
The issue is in the Docker file. The find command (`find /usr/local -type d -name "grass??" | sort | tail -n 1`) picks `/usr/local/grass79/etc/python/grass/grassdb` while, I assume, @mmacata meant to pick `/usr/local/grass79`. The symlink then leads to grass.grassdb code rather than the dist. The Dockerfile then sets GISBASE confusing even the main executable (init script, i.e., `grass.py` which lets itself be influenced by the env var).

I was not able to get/reproduce this issue locally - now for obvious reasons. Also note that the Alpine Docker build works even with master in your screenshot and on GitHub (I can't get to any logs) further confirming that the issue is just in the Ubuntu and Debian Dockerfiles.

The linked issue from grass-user mailing list looks more along the lines of #658 when user expects `grass` package to be available after installing GRASS or, since it is Windows, even going step further and providing pip and/or conda for uniform cross-platform experience (which basically requires #658) and actually work within Anaconda environment.

**Comment by neteler** [comment]
> The issue is in the Docker file. The find command (`find /usr/local -type d -name "grass??" | sort | tail -n 1`) picks `/usr/local/grass79/etc/python/grass/grassdb` while, I assume, @mmacata meant to pick `/usr/local/grass79`. The symlink then leads to grass.grassdb code rather than the dist. The Dockerfile then sets GISBASE confusing even the main executable (init script, i.e., `grass.py` which lets itself be influenced by the env var).

[docker hub logs are only available after login]

Interesting!
The `find` was once invented by me, but as I now understand not very robust against future changes.

Here the log snippet:

```
...
Step 47/66 : ENV GRASS_SKIP_MAPSET_OWNER_CHECK 1
---> Running in 7b4cb51af8ea
Removing intermediate container 7b4cb51af8ea
---> 7595737f49c0
Step 48/66 : RUN ln -sf `find /usr/local/bin -name "grass??" | sort | tail -n 1` /usr/local/bin/grass
---> Running in d15881246fcd
Removing intermediate container d15881246fcd
---> 00d4619c4895
Step 49/66 : RUN ln -sf `find /usr/local -type d -name "grass??" | sort | tail -n 1` /usr/local/grass
---> Running in fbf9773e57c2
Removing intermediate container fbf9773e57c2
---> d03c093e1464
Step 50/66 : RUN grass --tmp-location EPSG:4326 --exec g.version -rge && pdal --version && python3 --version
---> Running in f71f5a19c105
Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
Cleaning up temporary files...
Executing <g.version -rge> ...
version=7.9.dev
date=2020
revision=exported
build_date=2020-08-08
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2020-08-08T05:31:15+00:00
libgis_date=2020-08-07T16:00:00+00:00
proj=4.9.3
...
```

> I was not able to get/reproduce this issue locally - now for obvious reasons. Also note that the Alpine Docker build works even with master in your screenshot and on GitHub (I can't get to any logs) further confirming that the issue is just in the Ubuntu and Debian Dockerfiles.

Yes, exactly.

I'll prepare a PR for the path issue

> The linked issue from grass-user mailing list looks more along the lines of #658 when user expects `grass` package to be available after installing GRASS or, since it is Windows, even going step further and providing pip and/or conda for uniform cross-platform experience (which basically requires #658) and actually work within Anaconda environment.

In general, "grass-sessions" should become part of core GRASS GIS rather than remain separately.

**Comment by wenzeslaus** [comment]
> In general, "grass-sessions" should become part of core GRASS GIS rather than remain separately.

Prerequisite for that is #658.

**Comment by neteler** [comment]
The docker images are generated again. Effectively, this issue is a "works for me" and indeed an error in the Dockerfiles.
Thanks for identifying the real issue, @wenzeslaus!
