### ISSUE TITLE
[Feat] Create mapset in the startup/demo location

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#897]
The startup mechanism for the first-time user should make use the mapset concept because it will both ensure preserving the data in PERMANENT intact and, at the same time, it will show how to use the mapset concept at least in the relation to the PERMANENT mapset.

When the startup/demo location is created/copied, a new mapset should be created there and used for starting, not the PERMANENT.

I don't have a suggestion regarding the name. As for this issue, it will be only one mapset, but eventually there will be more than one, so probably some `name_1`, `name_2`, ... will be needed. However, the question is still the same: What the name should be?

**Describe alternatives you've considered**

* Use PERMANENT for simplicity. (That's the state after #868, but it seems it won't be enough in the future and it does not show the best practice.)
* Skip implementing this and go right away into implementing reuse of an existing mapset if present and creation of a new one if needed. (That would be fine, but this piece is anyway needed and it might be easier to see the steps needed along the way if we have this first.)

**Additional context**

This depends on PR #868 (issue #862).

This was discussed on [Next steps in GSoC and beyond video call, July 15, 2020 (notes)](https://trac.osgeo.org/grass/wiki/wxGUIDevelopment/New_Startup#NextstepsinGSoCandbeyondvideocallJuly152020):

> Always start in some mapset (demo, last, temporary)?
> Start in the last used and use the demolocation as a fallback when locked or deleted. (Create demolocation if needed. _Create a new mapset there_ if needed and/or find the first unlocked mapset.)

**Comment by ninsbl** [comment]
What about the user name? Needs to be checked for valid characters though...

**Comment by mlennert** [comment]
> What about the user name? Needs to be checked for valid characters though...

I think that would be a good choice.

**Comment by wenzeslaus** [comment]
Closed by #868 (8e8a14a0aa8a6639e38d862f663e67c563563124).
