### ISSUE TITLE
[Feat] wxGUI datacatalog: process of creating a new database

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass#929]
**Is your feature request related to a problem? Please describe.**

Creating a new database requires two steps: 1) create the database (which simply creates a new empty folder), and 2) create a location (and optionally an extra mapset). In most cases, I guess users who want to create a new database would also want to create a new location (and mapset).

**Describe the solution you'd like**

After creating a new database, the user is presented with the option to create a new location as well. E.g., a popup with the question if the user wants to continue to create a location. If confirmed, the 'Create new location' menu is opened. This is more akin the old procedure, in which creating a database takes the user through all steps of the process, from database, location and mapset. 

**Describe alternatives you've considered**

After creating a new database, show a message popup with instructions how to continue, e.g., "Database created. To create a location, in the context menu (right click on the name of the newly created database), select 'Create new location' .

**Additional context**

See also issue #928

**Comment by lindakladivova** [comment]
closed by https://github.com/OSGeo/grass/pull/937
