### ISSUE TITLE
[Bug] Don't work the current path. Tested in version 7.4.0

### ISSUE THREAD

**Issue by edarague** [OSGeo/grass#932]
https://github.com/OSGeo/grass/blob/80538be4d6ebde766991ef455b4330fcf5e68e20/scripts/g.extension/g.extension.py#L1105

Don't work:
base_url = http://wingrass.fsv.cvut.cz/grass74/x86_64/addons/grass-7.4.0

The correct path in this case is:
base_url = http://wingrass.fsv.cvut.cz/grass74/x86_64/addons/grass-7.4.svn

**Comment by neteler** [comment]
@landam how to address this issue?

**Comment by edarague** [comment]
I only replaced **version[2]** with **'svn'**, but it is a temporary solution for my case in version 7.4.0 on Windows. I did not know how to solve it for any version, that is why I am reporting the bug.

    base_url = "http://wingrass.fsv.cvut.cz/" \
               "grass%(major)s%(minor)s/%(platform)s/addons/" \
               "grass-%(major)s.%(minor)s.%(patch)s" % \
               {'platform': platform,
                'major': version[0], 'minor': version[1],
                'patch': **version[2]**}

    base_url = "http://wingrass.fsv.cvut.cz/" \
               "grass%(major)s%(minor)s/%(platform)s/addons/" \
               "grass-%(major)s.%(minor)s.%(patch)s" % \
               {'platform': platform,
                'major': version[0], 'minor': version[1],
                'patch': **'svn'**}

**Comment by a-ggghost** [comment]
Similar issue on windows 10 x64 w/ grass 7.8.5
There is no directory on the server called "https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.5/", so I would get a "Cannot open URL:" error. Also downloaded zip file to disk (as B:\r.in.pdal.zip) and tried to point g.extension to it, but it would still attempt to download from base_url anyway.

Shoved "latest" in at the end of the base url to download from https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/ and successfully installed the addon I wanted but, same as @edarague it's just a temporary workaround.

```
base_url = "http://wingrass.fsv.cvut.cz/" \
               "grass%(major)s%(minor)s/%(platform)s/addons/" \
               "latest" % \
               {'platform': platform,
                'major': version[0], 'minor': version[1],
                'patch': version[2]}
```

**Comment by echoix** [comment]
Is this still relevant? It seems stale

**Comment by neteler** [comment]
(@landam and @pesekon2 are managing https://wingrass.fsv.cvut.cz)

**Comment by wenzeslaus** [comment]
Closing. Please open a new issue with a fresh description a if still need.
