### ISSUE TITLE
[Bug] winGRASS-daily-7.9.dev-2aef82628-293: AttributeError: module 'os' has no attribute 'getuid'

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass#951]
**Describe the bug**

starting the winGRASS daily build 2aef82628 in OSGeo4W

![grafik](https://user-images.githubusercontent.com/12000843/91754919-8b3a5b00-ebca-11ea-9555-c9f5de1d5dca.png)

**To Reproduce**

just start winGRASS daily in the OSGeo4W environment

**Expected behavior**

open the new winGRASS master start up

**Comment by mlennert** [comment]
On 31/08/20 20:45, Helmut Kudrnovsky wrote:
> *Describe the bug*
> A clear and concise description of what the bug is.
> 
> starting the winGRASS daily build 2aef826 
> <https://github.com/OSGeo/grass/commit/2aef82628a4f4435afd9f5d90a9636188f39f080> 
> in OSGeo4W

os.getuid is unix specific [1]. So we need to find a workaround for this.



[1] https://docs.python.org/3/library/os.html

**Comment by mlennert** [comment]
On 31/08/20 20:51, mlennert wrote:
> On 31/08/20 20:45, Helmut Kudrnovsky wrote:
>  > *Describe the bug*
>  > A clear and concise description of what the bug is.
>  >
>  > starting the winGRASS daily build 2aef826
>  > 
> <https://github.com/OSGeo/grass/commit/2aef82628a4f4435afd9f5d90a9636188f39f080> 
> 
>  > in OSGeo4W
> 
> os.getuid is unix specific [1]. So we need to find a workaround for this.

Seems to be fixed in #945. Please test.

**Comment by hellik** [comment]
> Seems to be fixed in #945. Please test.

ah thanks!

http://download.osgeo.org/osgeo4w/x86_64/release/grass/grass-daily/?C=M&O=A

```
grass-daily-7.9.dev-2aef82628-291.tar.bz2 | 85M | 2020-Aug-30 18:35
grass-daily-7.9.dev-2aef82628-292.tar.bz2 | 85M | 2020-Aug-30 18:35
grass-daily-7.9.dev-2aef82628-293.tar.bz2 | 85M | 2020-Aug-30 18:35
```

there seems to be some update issue in the daily builds. @landam ?

**Comment by jmckenna** [comment]
I will test tonight with the next build

**Comment by jmckenna** [comment]
verified that the fix is available in "dev-294" build, which is now available.

**Comment by petrasovaa** [comment]
Thanks for testing
