### ISSUE TITLE
[Feat] Increase history size

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#969]
**Is your feature request related to a problem? Please describe.**
Shell history file (e.g. for Bash) now stores only up to 3000.

**Describe the solution you'd like**
I would like the number of entries in the history file to be larger or even unlimited.

Each mapset has its own file which reduces number of command for each mapset, so there is no need for a safety limit and the even in the no limit scenario seems quite safe. It would not be all command ever which might be large, but it would be all command ever (only) in given mapset (and shell).

**Describe alternatives you've considered**
Something like

```
echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> ~/.logs/bash-history-$(date "+%Y-%m-%d").log
```

in `PROMPT_COMMAND` logs everything immediately in a separate file for each day and can work alongside the normal history. However, given that the history is per-mapset, I don't think this is necessary.

**Comment by neteler** [comment]
Yes, I see 3000 lines history limit for `csh`:

https://github.com/OSGeo/grass/blob/ecc150f8de351b0efc986a7e48dd22923026afaa/lib/init/grass.py#L1785

and for `bash` here:

https://github.com/OSGeo/grass/blob/ecc150f8de351b0efc986a7e48dd22923026afaa/lib/init/grass.py#L1841

I'd suggest to set it to unlimited as losing parts of the mapset shell history is a pain.
And the disk space consumption of `mapset/.bash_history` will not be an issue... :-)

**Comment by wenzeslaus** [comment]
@neteler It seems that the concern usually is with history being loaded into memory and occupying memory, rather than disk space, but I still think that separate histories for individual mapsets mitigate this issue. From reviewing #1026 it seems some people argue for setting specific, possibly well-researched, limits and, e.g., zsh does not even allow to set _unlimited_ explicitly (since there is no such thing in theory).
