### ISSUE TITLE
GRASS r.mapcalc cos() appears to be imprecise [Bug] 

### ISSUE THREAD

**Issue by salbeke** [OSGeo/grass#985]
**Describe the bug**
In comparing output between Program R and GRASS, I have the exact same raster dataset (float) of slope in degrees (range of min = 0, max = 0.59). I use the cos() in R and receive a range of min = 0.83, max = 1. 

I perform the same function in GRASS: r.mapcalc expression="xx2 = cos(xx1)" --overwrite
This function results in all values == 1 (or at least VERY close to 1, e.g. 0.99993). This isn't the correct answer. This lack of precision is affecting downstream calculations. 

**Expected behavior**
I expect the returned values to be a range of min = 0.83, max = 1 for my particular set of input values. I believe the same behavior is occurring for sin(), etc. 

**System description (please complete the following information):**

- Operating System: Windows 10
- GRASS GIS version 7.4.1

**Comment by petrasovaa** [comment]
The result is correct, it's just a degree/radian problem. r.mapcalc expects degrees and indeed, cos(0.59 degrees) is 0.99995. cos in R probably expects radians and cos(0.59 rad) is 0.83.

**Comment by neteler** [comment]
@salbeke if you see any need to improve the documentation at
https://grass.osgeo.org/grass78/manuals/r.mapcalc.html#functions
please suggest!
