### ISSUE TITLE
[Bug]r.univar multiple maps

### ISSUE THREAD

**Issue by HunterGleason** [OSGeo/grass#997]
**Describe the bug**
When r.univar is provided multiple map inputs only statistics for one map are produced. 
**To Reproduce**

1. Go to GRASS 7.8.3
2. Click on  r.univar and provide multiple raster inputs to the map parameter to which derive statistics. Provide a zone raster as well. 
3. Compute ...
4. Notice that only statistics for one map raster are printed to stdout.

**Expected behavior**
Expected statistics for both map raster printed to stdout.

**Screenshots**
NA

**System description (please complete the following information):**

- Operating System: Linux: Debian GNU/Linux bullseye/sid
- GRASS GIS version [e.g. 7.8.3]

**Additional context**
Looking to derive univariate statistics from multiple raster (e.g., elevation, LAI) limited by zones (basins)

**Comment by petrasovaa** [comment]
The statistics is computed from all maps, so e.g. if range of map1 is (-100, 100) and map2 (0, 200), reported min would be -100 and max 200.

Feel free to suggest better documentation, currently it states:

> When multiple input maps are given to r.univar, the overall statistics are calculated. This is useful for a time series of the same variable, as well as for the case of a segmented/tiled dataset. Allowing multiple raster maps to be specified saves the user from using a temporary raster map for the result of r.series or r.patch.

**Comment by HunterGleason** [comment]
Thanks Anna, that makes sense, I guess I was a bit confused as to what the overall statistics represented, but it is clear now. Thanks!

________________________________
