### ISSUE TITLE
[Bug] GRASS 7.8-Python under conda env cannot run_command('g.extension', 'a')

### ISSUE THREAD

**Issue by markwang0** [OSGeo/grass#999]
**Describe the bug**
@dhardestylewis
GRASS 7.8-Python under conda env cannot run_command('g.extension', 'a')
Script of interest:
https://github.com/passaH2O/GeoFlood/blob/master/GeoNet/pygeonet_grass_py3.py

**To Reproduce**

```
1. git clone https://github.com/passaH2O/GeoFlood.git
2. cd GeoFlood
3. conda env create -f geofloodenv.yml
4. conda activate geofloodenv
5. Follow instructions at https://github.com/passaH2O/GeoFlood/blob/master/README.md up to Step 3. GRASS GIS
6. Set appropriate grass .bat directory (line 15) and grassdata directory (line 64) in GeoNet/pygeonet_grass_py3.py
7. python GeoNet/pygeonet_grass_py3.py
```

**Expected behavior**
Installed GRASS modules detected, removed, and reinstalled.

**Screenshots**
![geonet grass error](https://user-images.githubusercontent.com/71631906/94590426-a5606b00-0254-11eb-84ac-ea69fbfcbebf.PNG)

**System description (please complete the following information):**

- Operating System: Discovered under Windows, may impact Unix
- GRASS GIS version 7.8.3
```
g.version -rge                                                                  
version=7.8.3
date=2020
revision=8bcecc9a6
build_date=2020-05-05
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=8bcecc9a6
libgis_date=2020-05-05T08:51:50+00:00
proj=6.3.2
gdal=3.0.4
geos=3.8.1
sqlite=3.29.0
```
(Tue Sep 29 13:08:18 2020) Command finished (0 sec) 

**Additional context**
See GRASS 7.8 directory listing 'dirlisting.txt'
[dirlisting.txt](https://github.com/OSGeo/grass/files/5300727/dirlisting.txt)

See python interactive shell history
[grass errors.txt](https://github.com/OSGeo/grass/files/5300731/grass.errors.txt)

**Comment by dhardestylewis** [comment]
The interactive testing was under this Python environment:
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Running the script under the mentioned Conda env should invoke the same Python environment.

Mark, when you have a chance, include the sample data needed to follow these steps.

**Comment by markwang0** [comment]
@dhardestylewis 
The sample data should be pasted into \GeoInputs\GIS\my_project after preparing the GeoNet file structure (using all defaults) as explained here: https://github.com/passaH2O/GeoFlood/blob/master/README.md

Sample data download:
https://utexas.box.com/s/jopa7a2jsnsj3567ilefi6sa1ysrk5oh

**Comment by nilason** [comment]
> The interactive testing was under this Python environment:
> Python 3.7.6 (default, Jan 8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

I don't know if this is the reason for the reported issue: but Python 3.7.6 and 3.8.1 are problematic for GRASS and should be avoided (see e.g. https://trac.osgeo.org/grass/ticket/4018).

**Comment by petrasovaa** [comment]
> > The interactive testing was under this Python environment:
> > Python 3.7.6 (default, Jan 8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
> 
> I don't know if this is the reason for the reported issue: but Python 3.7.6 and 3.8.1 are problematic for GRASS and should be avoided (see e.g. https://trac.osgeo.org/grass/ticket/4018).

While that's true, I don't think that's the problem here, since you don't seem to use any ctypes components. Most likely it's the GRASS setup. Here is a [simpler setup](https://github.com/wenzeslaus/try-grass-in-jupyter/blob/master/notebook.ipynb), and although it's for linux, maybe you can try to adjust that to windows.

**Comment by wenzeslaus** [comment]
Given the return code, can you please post content of PATH and PATHEXT variables before the g.extension call and also check that against where g.extension script is in your GRASS GIS installation (it should be g.extension.py or g.extension.bat or perhaps both)?

**Comment by ninsbl** [comment]
Is this stil an issue in a reasonably recent version of GRASS GIS? Maybe we can close this as "not palnned"?

**Comment by markwang0** [comment]
I am using v8 now and it is not an issue. Thanks and sorry for the late response
